### ISSUE TITLE
请问怎样把x轴放到下面？

### ISSUE THREAD

**Issue by lenglengiOS** [wuxudong/react-native-charts-wrapper#10]
![default](https://cloud.githubusercontent.com/assets/21171262/23839045/2fc9a52c-07d6-11e7-93a4-5c1d2ba0c627.png)

**Comment by wuxudong** [comment]
xaxis.position ......

**Comment by lakeoffaith** [comment]
`xAxis:{
  $set: {
            valueFormatter: ['Q1', 'Q2', 'Q3', 'Q4'],
            position:'BOTTOM'
          }
}`
