### ISSUE TITLE
remove numbers 

### ISSUE THREAD

**Issue by jsina** [wuxudong/react-native-charts-wrapper#100]
Hi there
I wanna know how could I remove number from RadarChart as you can see on the picture I've attached.
[https://drive.google.com/file/d/0B7Gi6iIggewLa3RpLXltbzJEMlU/view?usp=sharing](url)

**Comment by wuxudong** [comment]
Actually, that is labels in yAxis. 
You can add `yAxis={{drawLabels:false}}` in radarChart config

**Comment by wuxudong** [comment]
I found that I didn't implement yAxis config in iOS. I fix this bug in latest version.
