### ISSUE TITLE
autoScaleMinMaxEnabled in `<CombinedChart />`

### ISSUE THREAD

**Issue by uinz** [wuxudong/react-native-charts-wrapper#102]
hi,
I have a CandleChart and BarChart in CombinedChart.

CandleChart.axisDependency = 'RIGHT'
BarChart.axisDependency = 'LEFT'

Is there any way to let `autoScaleMinMaxEnabled` option only works with CandleChart ?

---

我 正在 CombinedChart 中使用 蜡烛图 和 柱状图.

我的蜡烛图是相对 `右边Y轴` 的
我的柱状图图是相对 `左边Y轴` 的

当我设置 了左边Y周的最大最小值后, 右边的自动最大最小就不能用了.

有没有办法可以使用 柱状图依赖的左Y周不自动缩放, 右边的Y轴自动缩放?

**Comment by wuxudong** [comment]
autoScaleMinMaxEnabled is applied to the whole chart.

I don't think it can be set on axis.

Close the issue. Please reopen it if you have any update.

**Comment by uinz** [comment]
情况是这样的, 我将 K 线 和 柱状图(成交量) 信息使用 CombinedChart 组合起来.

由于成交量 的 最大值比 当前价格 要大或者小很多,  如果不指定 yAxis 的范围 图表会相当难看,

比如 成交量范围是 0 ~ 10k  而价格范围是 0 ~ 1k 

所以我的想法是 固定成交量依赖 左侧Y轴, 不需要自动缩放, 价格K线依赖 右侧 自动缩放.


--------

我看了几款使用 swift Chart 做的 app  发现他们是通过2个chart 重叠实现的.

目前版本好像没有提供 触摸滑动相关的事件, 所以没法做两张图表的联动.

不知项目之后是否会考虑增加该特性

谢谢.

**Comment by wuxudong** [comment]
There is a pull request about gesture, but it is only for android. I haven't tested it.

you can make a try.

**Comment by uinz** [comment]
gesture feature is awesome!
