### ISSUE TITLE
BarChart xAxis Text Can we rotate 90 degrees 

### ISSUE THREAD

**Issue by hulusimizrak** [wuxudong/react-native-charts-wrapper#104]
Screen shot: 
https://i.hizliresim.com/bGmAdZ.png

**Comment by rohitforwork** [comment]
How did you manage to rotate the x axis values ?

**Comment by angelos3lex** [comment]
For anyone wondering, the solution is proposed [here](https://github.com/wuxudong/react-native-charts-wrapper/issues/337)
