### ISSUE TITLE
Does not work at all with 0.45.1 React Native

### ISSUE THREAD

**Issue by harisb2012** [wuxudong/react-native-charts-wrapper#106]
Hello,

Came across this library, did setup and it just doesn't work. Does not matter which chart I choose, I get just red line.

https://www.dropbox.com/s/2p1mz8nftvxpclf/Screenshot%202017-08-30%2013.11.43.png?dl=0

**Comment by amerdiglisic** [comment]
You could try to put it into ScrollView instead of View (if you did not already), and check the height and width of the container where chart is being rendered.

I had similar problem.

Hope this will help.

**Comment by harisb2012** [comment]
Thanks @amerdiglisic even though that wasn't a problem. It was somehow weird behavior of node_modules (disappearing .swift files). I deleted it, did npm install again and it was working all good.
