### ISSUE TITLE
How to disable fit (Line Bar)

### ISSUE THREAD

**Issue by albertosgr** [wuxudong/react-native-charts-wrapper#107]
Hi I cant seem to find a solution for disabling the initial chart fit.

I would like to show the chart in some zoom/scale and the user can pan the chart along the xAxis.
I already tried "setAvoidFirstLastClipping" and "setVisibleXRangeMaximum" with no luck.

any suggestions?
thank you

**Comment by wuxudong** [comment]
you can try zoom. 

`zoom={{scaleX: 2, scaleY: 1, xValue:  1, yValue: 1}}`
