### ISSUE TITLE
get custom property from bridge

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#11]
hi, it's not a issue, just some question, feel free to close if need :)

I notice that in swift 2.0 previous project `react-native-ios-charts` define custom property in both [header file](https://github.com/Jpadilla1/react-native-ios-charts/blob/master/RNiOSCharts/RNLineChart.h#L13) and [implement file](https://github.com/Jpadilla1/react-native-ios-charts/blob/master/RNiOSCharts/RNLineChart.m#L14), then get the value from js side [via swift setter](https://github.com/Jpadilla1/react-native-ios-charts/blob/master/RNiOSCharts/RNLineChart.swift#L26), I follow this way and it works well.

Today I upgrade my project to swift 3.0, strangely I notice that setter feature like `setConfig` no longer be called, I don't know how to get custom property value from js side in swift 3.0, and I check your smart project but also have no idea,

how should I get custom property value from js side in swift 3.0?

thanks for your time,

regards.

**Comment by wuxudong** [comment]
Actually, this is my first swift & ios project. 
I spent several days to learn the swift3. and I know nothing about swift2.0

In my project, the procedure is quite similar to react-native-ios-charts.

there is `RCT_EXPORT_VIEW_PROPERTY(drawValueAboveBar, BOOL)` declared in `RNBarChartManagerBridge.m`, and `func setDrawValueAboveBar(_ enabled: Bool) {...}` in RNBarChartView.swift .   the .h is not necessary.

**Comment by L-Jovi** [comment]
@wuxudong  ok, thanks for your suggestion, I try change `func setConfig(config: String!)` to `func setConfig(_ config: String!)` and it works. it's react-native feature while not swift, that's my mistake..
