### ISSUE TITLE
HI, How can I hide Marker?

### ISSUE THREAD

**Issue by uinz** [wuxudong/react-native-charts-wrapper#112]
HI, How can I hide Marker?

I didn't find any way to hide `marker` in [https://github.com/wuxudong/react-native-charts-wrapper/tree/master/lib](https://github.com/wuxudong/react-native-charts-wrapper/tree/master/lib)

**Comment by MarsLuo** [comment]
Hello, @uinz , do you know how to hide a marker when data change ?

**Comment by zmnv** [comment]
I need the same functional
