### ISSUE TITLE
Setting custom fonts

### ISSUE THREAD

**Issue by PiotrDabek** [wuxudong/react-native-charts-wrapper#114]
Is option fontFamily currently working? Other parameters like font size or color work fine however I am not able to change font family.

`legend: {
                enabled: true,
                textSize: 14,
                form: 'SQUARE',
                formSize: 9,
                fontFamily: 'Avenir-Black',
                xEntrySpace: 10,
                yEntrySpace: 5,
                formToTextSpace: 5,
                wordWrapEnabled: true,
                maxSizePercent: 0.5,
            }

<BarChart
                        style={styles.chart}
                        data={this.state.data}
                        xAxis={this.state.xAxis}
                        yAxis={this.state.yAxis}
                        legend={this.state.legend}
                        drawGridBackground={false}
                        chartDescription={{ text: '' }}
                        drawMarkers={false}
                    />`

**Comment by wuxudong** [comment]
```
  fontFamily: PropTypes.string,
  fontStyle: PropTypes.number,
```

is not implemented by android/iOS code. 

I will take a look.

**Comment by wuxudong** [comment]
It is already listed in the [notice](https://github.com/wuxudong/react-native-charts-wrapper#notice)

Pull request is appreciated.
