### ISSUE TITLE
How to limit scale?

### ISSUE THREAD

**Issue by happyjosh** [wuxudong/react-native-charts-wrapper#115]
I want to limit scaleX/Y,like setScaleXMax().

**Comment by rodrigoxavier** [comment]
In your data you can define.
The code below will set 300 as maximum value in the left side of yAxis.

Hope can help you.

`yAxis: {
            $set: {
              left:{
                axisMaximum: 300, axisMinimum: 0
              }
            }`

**Comment by happyjosh** [comment]
@rodrigoxavier I want to limit scale ,not value for axis

**Comment by wuxudong** [comment]
I can only find one setting `scaleMinima` in MpAndroidChart.  

I am not sure if that is you need.

```
    public void setScaleMinima(float scaleX, float scaleY) {
        mViewPortHandler.setMinimumScaleX(scaleX);
        mViewPortHandler.setMinimumScaleY(scaleY);
    }
```

At this moment, these is no config in RNCW can limit scaleX/scaleY.

**Comment by wuxudong** [comment]
Reopen it if necessary.

**Comment by HighSoftWare96** [comment]
I was wondering how to do this too... Is there a way to set a maximum scale for the zoom so the user cannot keep zooming to the infinite?

**Comment by wuxudong** [comment]
visibleRange?

**Comment by ddavydov** [comment]
> visibleRange?

setting visibleRange doesn't prevent from zooming to the infinite unfortunately, is there any other option?
