### ISSUE TITLE
build error "No such module 'Charts'"

### ISSUE THREAD

**Issue by thoitrangphovn** [wuxudong/react-native-charts-wrapper#119]
Hi all, please help me resolve this problem:
![image](https://user-images.githubusercontent.com/15246452/31060997-6deb3e32-a746-11e7-938f-3722edd5c2bf.png)

folder in my project:
![image](https://user-images.githubusercontent.com/15246452/31061021-bb94d260-a746-11e7-9e77-18fdfaa21708.png)

**Comment by jordenchang55** [comment]
Same. I can run ```react-native run-ios``` and see the chart in my app. But It just cannot build from Xcode so that I cannot build release.

**Comment by jordenchang55** [comment]
Well, I found I made mistake. I should open ```.xcworkspace``` instead of ```.xcodeproj```

**Comment by victormer** [comment]
@jordenchang55 that didn't work to me. I get the same error ('No such module 'Charts'').

**Comment by jordenchang55** [comment]
@victormer Did you install the library by Pod or manually? 
My solution is for Pod and it work everything well.

**Comment by lorenzomilesi** [comment]
I was stuck on this problem with XCode 10.3, I think I've tried all the solutions I found on the internet for about 4 days.
It could be weird, but I fixed it by changing the project path: **I simply placed the project 2 or 3 folder outer than before**. It seems that the Swift compiler could not reach that nested folder level.
