### ISSUE TITLE
How to set label font size , label format, description Label

### ISSUE THREAD

**Issue by lenglengiOS** [wuxudong/react-native-charts-wrapper#12]
![c8638a8e-6ec9-4fb7-9606-5de53a904145](https://cloud.githubusercontent.com/assets/21171262/23930978/8fd8e154-096a-11e7-9ab5-b3590ee13f32.png)

**Comment by wuxudong** [comment]
Here are some suggestions:
-  please use english so that more people can find help in your issue.
- use meaningful title.
- for react-native, there are always files contains prototype, it will be useful to find all the configuration properties.

**Comment by wuxudong** [comment]
- currently, the label size and format is not supported. may be added in next version.
- there is a chartDescription

**Comment by lenglengiOS** [comment]
Thank you, I will ask questions in English





------------------ 原始邮件 ------------------
发件人: "wuxudong";<notifications@github.com>;
发送时间: 2017年3月15日(星期三) 中午11:44
收件人: "wuxudong/react-native-charts-wrapper"<react-native-charts-wrapper@noreply.github.com>; 
抄送: "青春"<18708363472@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wuxudong/react-native-charts-wrapper] How to set label font size, label format, description Label (#12)



 
currently, the label size and format is not supported. may be added in next version.
 
there is a chartDescription

**Comment by wuxudong** [comment]
@lenglengiOS  check the latest version. now there is valueTextSize & valueFormatter. 
and the example -> LineChartScreen , TimeSeriesLineChartScreen

**Comment by lenglengiOS** [comment]
ok thank you





------------------ 原始邮件 ------------------
发件人: "wuxudong";<notifications@github.com>;
发送时间: 2017年3月15日(星期三) 下午3:17
收件人: "wuxudong/react-native-charts-wrapper"<react-native-charts-wrapper@noreply.github.com>; 
抄送: "青春"<18708363472@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [wuxudong/react-native-charts-wrapper] How to set label font size, label format, description Label (#12)




@lenglengiOS  check the latest version. now there is valueTextSize & valueFormatter.
 and the example -> LineChartScreen , TimeSeriesLineChartScreen

**Comment by thiswhy** [comment]
国人，好亲切，哥们怎么删除的Description Lable？Q1414770848
