### ISSUE TITLE
How to show separate charts in a single page using ScrollView?

### ISSUE THREAD

**Issue by quoclap** [wuxudong/react-native-charts-wrapper#122]
I have tried showing 2 charts: 1 bar chart and 1 line chart separately in a page. So user can slide in a single page to see 2 charts. I tried using ScrollView tag but it shows nothing. Could you guys provide me some solutions? thanks a lot!

**Comment by quoclap** [comment]
I just do this by wrapping chart in a View tag and add many charts as I want: 
`<ScrollView>
<View><LineChart/></View>
<View><BarChart/></View>
</ScroolView>`

**Comment by viet97** [comment]
barchar just not show in scrollview and idk why
