### ISSUE TITLE
label format forgrid

### ISSUE THREAD

**Issue by LuanNg** [wuxudong/react-native-charts-wrapper#123]
Hi,

Label of auto number in grid, i just want to format the label like the "marker" as picture below (0.###), is it support? if yes could you show me the config for this one?

![image](https://user-images.githubusercontent.com/12404031/31530850-61f3692c-b00d-11e7-995f-a3d8b41fb930.png)

please help me resolve this problem
Thank you

**Comment by wuxudong** [comment]
Axis support valueFormatter too.
