### ISSUE TITLE
If I input 0.654, the line charts will show .654.like the pic...

### ISSUE THREAD

**Issue by lenglengiOS** [wuxudong/react-native-charts-wrapper#13]
![2626](https://cloud.githubusercontent.com/assets/21171262/23939976/3290fb88-099e-11e7-99d8-b00f7fc7becf.png)

**Comment by wuxudong** [comment]
now it support valueFormatter. check java DecimalFormat for the detail. I think it is compatible with [ Unicode Technical Standard #35](http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns)

**Comment by lenglengiOS** [comment]
I got the way

**Comment by lenglengiOS** [comment]
valueFormatter: "0.000",Can Solve the problem
