### ISSUE TITLE
error when install react-native-charts-wrapper on android (react-native Version 0.48)

### ISSUE THREAD

**Issue by fr-quoctv** [wuxudong/react-native-charts-wrapper#130]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-charts-wrapper'.
      > Could not resolve all dependencies for configuration ':react-native-charts-wrapper:_debugPublishCopy'.
         > Could not find com.github.PhilJay:MPAndroidChart:v3.0.2.
           Required by:
               BitStationApp:react-native-charts-wrapper:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.02 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:

**Comment by brunoconterato** [comment]
Maybe you put the maven { url "https://jitpack.io" } in the buildscripts->repositories, like:

(project build.gradle)
```
buildscript {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

If so, put maven in the allprojects->repositories instead of buildscript->repositories, like:

```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

Hope it helps :)

**Comment by wuxudong** [comment]
The example runs without problem. 

Close this issue, reopen it if you have any questions.
