### ISSUE TITLE
piechart bug

### ISSUE THREAD

**Issue by aryankranthi** [wuxudong/react-native-charts-wrapper#131]
hi,
i'm using a pie-chart and its works great..
im getting extra value (0) in entry labe text. how can i remove that one
please help me
![screenshot_1509084724](https://user-images.githubusercontent.com/29574535/32090252-55673d78-baa3-11e7-9dac-c1c251fc4250.png)

**Comment by wuxudong** [comment]
In this picture, 0 is the 'Correct' value.

As a workaround, you can filter entries which value zero out of your data.

**Comment by wuxudong** [comment]
Check the discussion in [MpAndroid](https://github.com/PhilJay/MPAndroidChart/issues/1692)

**Comment by ericklarac** [comment]
@aryankranthi how do you deleted the chart tag, I mean even setting the value to false on drawSliceText the chart is displaying the text as in the following image:

![image](https://user-images.githubusercontent.com/8422946/33773321-1a70df28-dbfd-11e7-8509-99d92ab05b50.png)

Wish you could help me.

**Comment by aryankranthi** [comment]
{value: 21, label: 'Salads'},{value: 40, label: 'Sandwiches'}
instead of   {value: 21'},{value: 40}
remove label from dataset

**Comment by aryankranthi** [comment]
@ericklarac
 {value: 21, label: 'Salads'},{value: 40, label: 'Sandwiches'}
instead of {value: 21'},{value: 40}
remove label from dataset

**Comment by s349856186** [comment]
@aryankranthi how do you set label, if instead of {value: 21},{value: 40}  will no label show on the rihgt ? just deleted the label of chart, how to 
![111](https://user-images.githubusercontent.com/2498958/34407268-7524fed0-ebf8-11e7-9844-94b931f4bb64.png)
do

**Comment by s349856186** [comment]
@wuxudong do you have time to help me？thanks

**Comment by aryankranthi** [comment]
@s349856186 actually that was another module.
i take another view and create that one...

**Comment by wuxudong** [comment]
Do you mean this?

![simulator screen shot - iphone x - 2018-01-06 at 11 53 49](https://user-images.githubusercontent.com/1391101/34636264-76d2c26c-f2d8-11e7-8dee-a8a9f383ac0c.png)


Just set drawEntryLabels={false}

**Comment by wuxudong** [comment]
@ericklarac My bad, drawSliceText is already renamed to drawEntryLabels in underlying native lib.
I forgot to update the example.

**Comment by s349856186** [comment]
@wuxudong Thank you reply.  I had updated to 0.4.1 and set drawEntryLabels={false},but its nothing change, what's wrong with my test?

**Comment by s349856186** [comment]
@wuxudong Thank you reply. I had updated to 0.4.1 and try set drawEntryLabels={false or true},but its exit after run, can't into interface and no error messages,  what's wrong with my test? 
 "react-native": "0.51.0",
"react-native-charts-wrapper": "^0.4.1",

**Comment by s349856186** [comment]
@wuxudong thank you reply

**Comment by s349856186** [comment]
@wuxudong It's wrong when i run ios, what's wrong with my test? can you help me,thanks

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ChartTest.RNPieChartView setDrawEntryLabels:]: unrecognized selector sent to instance 0x7fff19d02fb0'
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by wuxudong** [comment]
Check the latest version,it’s a bug in older version.

**Comment by s349856186** [comment]
@wuxudong 
 "react-native": "0.51.0",
"react-native-charts-wrapper": "^0.4.1",
I had updated to 0.4.1, it's not latest version?

**Comment by wuxudong** [comment]
Check issue #165, drawEntryLabels crash in iOS

**Comment by wuxudong** [comment]
Close inactive issue, reopen it if necessary.

**Comment by MrLich** [comment]
I have faced one problem which named "RNPieChar was not found in the manager", Please help me! :(
