### ISSUE TITLE
removing space between two adjacent bars

### ISSUE THREAD

**Issue by hadar-ayoub** [wuxudong/react-native-charts-wrapper#132]
I'm using this library to display Bars on a combinedChart. it's working perfectly like represented bellow.

![aze](https://user-images.githubusercontent.com/5258992/32190347-701666e4-bda5-11e7-903f-d0209581de47.png)

Now, i want to remove space between two adjacent bars on IOS and Android, any thoughts ? 

Thank you,
Ayoub

**Comment by wuxudong** [comment]
Just set barSpace to 0.

The config of 3 bars in a group:

```
       config: {
          barWidth: 0.2,
          group: {
            fromX: 0,
            groupSpace: 0.4,
            barSpace: 0,
          },
        }

```

In most case,  (barWidth + barSpace) * barCountInAGroup + groupSpace = 1
