### ISSUE TITLE
zero line on linechart.

### ISSUE THREAD

**Issue by hadar-ayoub** [wuxudong/react-native-charts-wrapper#133]
Hello guys, I'm rendering a dynamic lineChart with data coming from backend, it's working almost as expected. I also want to display a zero line  specified on yAxis state, here is a code snippet : 

`                    zeroLine: {
                        enabled: true,
                        lineWidth: 1.5
                    }
`
However, yAxis values are displayed dynamically depending on data fetched from backend. When all bound data are positive values the zero line isn't displayed as shown on the image below : 

![sans titre 2](https://user-images.githubusercontent.com/5258992/32191102-c95cb4f4-bda7-11e7-9619-b534c2d2e7f2.png)
![sans titre](https://user-images.githubusercontent.com/5258992/32191423-f7b03bd6-bda8-11e7-9aa9-c1aad3c2e4b7.png)

Is there a way to display the zero line independently of the drawn chart.

Thanks,

**Comment by wuxudong** [comment]
I think `yAxis: {left:{axisMinimum: -10}}` can help
