### ISSUE TITLE
Creating a half Pie Chart

### ISSUE THREAD

**Issue by danielbm** [wuxudong/react-native-charts-wrapper#134]
Hi!

I set the property `maxAngle={180} `, and the result is this:

![screenshot from 2017-11-01 18-34-17](https://user-images.githubusercontent.com/6644090/32302010-a812ade8-bf47-11e7-8c7a-1e5c1bebbc43.png)

I want to create a Half Pie Chart like this:

<img src="https://user-images.githubusercontent.com/6644090/32302368-7c2a82bc-bf49-11e7-8ff7-222204a35f35.png" width="400">

I tried searching on the code for the reason it has this behavior, which is different from MPAndroidChart, but I could not find anything =/

**Comment by danielbm** [comment]
I solved this by exposing the rotationAngle property.

Here is a fork for anyone interested: https://github.com/danielbm/react-native-charts-wrapper/commit/7d74bdf3b3582716dc5c48cf2403c744ebf4f3cb

**Comment by wuxudong** [comment]
@danielbm , Thanks, this feature make sense, I will add it in latest version.

**Comment by Nehal-29** [comment]
@wuxudong  Do we have this feature in the latest version?

**Comment by gopikasireddy202** [comment]
@wuxudong  how to set height to pie chart having maxAngle={180}.
