### ISSUE TITLE
Import Statement issue

### ISSUE THREAD

**Issue by ashish-at-github** [wuxudong/react-native-charts-wrapper#136]
The import Statemnt `import {PropTypes} from 'react';` does not work since it is changed in the react native library updates.

Now the imports should be replaced in all the charts files in lib folder to 
`import PropTypes from 'prop-types';`

**Comment by voratham** [comment]
you can use from https://github.com/merryjs/react-native-charts
https://github.com/wuxudong/react-native-charts-wrapper/issues/126

**Comment by ashish-at-github** [comment]
Thankyou @voratham

**Comment by wuxudong** [comment]
@voratham Thanks, I will also update this to latest rn.

**Comment by wuxudong** [comment]
It is ready merged. Thanks.
