### ISSUE TITLE
How to disable text value on Bar of StackedBarChart ?

### ISSUE THREAD

**Issue by voratham** [wuxudong/react-native-charts-wrapper#139]
How to disable text value in Bar of StackedBarChart  ?

![screenshot-raw githubusercontent com-2017-11-09-19-05-52-019](https://user-images.githubusercontent.com/30921472/32604706-3166a92a-c581-11e7-82b2-913f1e81063c.png)

**Comment by wuxudong** [comment]
add `drawValues: false` in bar.data.config
