### ISSUE TITLE
drawCircleHole not work

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#14]
I add `drawCircleHole` property like below format to LineChart

```
data={{
  dataSets: [ { config: { drawCircleHole: true, circleHoleColor: processColor('yellow'), }, }, ...]
}}
```

but it seems not work, then I find that bridge config also receive `drawCircleHole` property, why does't make sense?

![image](https://cloud.githubusercontent.com/assets/7262199/23987155/1cf9f1c4-0a63-11e7-9eea-a8e19c4da510.png)

thanks for your time.

**Comment by wuxudong** [comment]
I find there is a circle hole in the [screenshot](https://raw.githubusercontent.com/wuxudong/react-native-charts-wrapper/master/screenshot/android-time-series-line.png). 

can you upload your screenshot?

**Comment by L-Jovi** [comment]
@wuxudong  thanks for your reply, I follow your Example __LineChartScreen.js__ and try to add `drawCircleHole`, and eventually I figure out that `drawCircleHole` will works when `circleRadius` >= 5, 

close this issue, regards.

**Comment by wuxudong** [comment]
in mpandroidchart, default circleRadius is 4,  default circleHoleRadius is 2. and I think there must be some relation inside.
