### ISSUE TITLE
Charts empty

### ISSUE THREAD

**Issue by Bubblex** [wuxudong/react-native-charts-wrapper#141]
Android

Example: BarChartScreen.js

 "react-native": "0.47.2",
"react-native-charts-wrapper": "0.2.10", 

Already `link` and add `maven { url "https://jitpack.io" }`, but has error .

![image](https://user-images.githubusercontent.com/22041769/33058398-7fc1d76e-ceca-11e7-97b3-cbec7226a0d1.png)
![screenshot_1511246741](https://user-images.githubusercontent.com/22041769/33058472-bded1878-ceca-11e7-977d-547b96c46c8d.png)

 按照文档步骤来的，不知问题出在哪里，大神求助

**Comment by wuxudong** [comment]
Try react-native-chart-wrapper 0.3.0.

**Comment by wuxudong** [comment]
0.2.10 may not be compatible with RN0.47+

**Comment by Bubblex** [comment]
I try react-native-chart-wrapper 0.3.0, however still not working.

**Comment by wuxudong** [comment]
What about Examples project?

**Comment by Bubblex** [comment]
https://github.com/Bubblex/official-react-native-demo/tree/map

Branch: map

![screenshot_1511399325](https://user-images.githubusercontent.com/22041769/33155841-f797def4-d02e-11e7-90a7-231ec33fd233.png)


Kline example
