### ISSUE TITLE
Rendering marker

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#142]
Hello. Is it possible to display a marker for one bar only. I.e. i have the following values (combined chart - barDataSet):

[{x: 1, y: 400}, {x: 2, y: 300}, {x: 3, y: 600}]

On the 3rd bar ({x: 3, y: 600}) I should automatically show the marker for it and then disable the markers from showing when I click at the other bar data.

Basically, I only want to show the marker for one bar data and disable the marker from showing when I click on the other bar data. If this is possible, please tell me. 

What I did so far is I tried calling onSelect() props from componentDidMount() but I couldn't make it work.

**Comment by wuxudong** [comment]
No such feature currently.

But it is not difficult to implement it.
In MpAndroidChart,  [highlight](https://github.com/PhilJay/MPAndroidChart/issues/240) can help.
 You are welcome to create pull request.

**Comment by GermanMontejo** [comment]
Could you also give me a tip on how to do this with ios? Like give me an idea on which method to use... Thanks!

**Comment by wuxudong** [comment]
@GermanMontejo  try 0.4.0-alpha.
a lot of new features are introduced.
