### ISSUE TITLE
Chart render too slow with large amount of data

### ISSUE THREAD

**Issue by barbaragomes** [wuxudong/react-native-charts-wrapper#144]
Hi,

I'm trying to render a LineChart with approximately 50k points, but my app hangs forever and do not render the Chart.

Any ideia on how to optimize it?

**Comment by wuxudong** [comment]
<img width="474" alt="screen shot 2017-11-28 at 2 33 00 pm" src="https://user-images.githubusercontent.com/1391101/33305445-1b4ecd9e-d449-11e7-913d-c7977da0a32a.png">

That is 50k points in MPAndroidChart.  very very slowly.  

I don't think it is problem of the lib. You just have to sample your data.

Just like stock data, it doesn't make sense to provide minute data if the duration is 10 years.

**Comment by barbaragomes** [comment]
@wuxudong Thanks for the response.

I'm using my own native implementation of the native ios Charts library that this project uses, and rendering the 50k of data is very fast, but when I try to render using this component, it is really slow.

I will do some further investigation

**Comment by wuxudong** [comment]
Can you provide a screenshot of how it shows using Charts (the underlying iOS lib).

**Comment by rghorbani** [comment]
Have you tried rendering in production mode?
Due to react-native's usage of development libraries this usually happens in this kind of libraries.

**Comment by barbaragomes** [comment]
Yes, I have tried to run it in production mode, but no success.

Here is a 30k sample using Charts:



Barbara Gomes
+1 (650) 713-6092

**Comment by barbaragomes** [comment]
@rghorbani Yes, I did run it in production mode, but no success.

Here is a 30k sample chart using my native implementation of Charts:

![image](https://user-images.githubusercontent.com/13023284/33307608-f5bc65fa-d3cb-11e7-86cc-537218256e8c.png)

**Comment by wuxudong** [comment]
<img width="378" alt="screen shot 2017-11-29 at 8 43 12 am" src="https://user-images.githubusercontent.com/1391101/33352235-f66d3bce-d4e2-11e7-8989-37c529a2468c.png">

I update Examples->LineChartScreen, 

```
this.setState(
      update(this.state, {
        data: {
          $set: {
            dataSets: [{
              values: Array.from(new Array(30000),(val,index)=>index),
              label: 'Company X',
              .......    
```

I tested it in my laptop. For 30k point, it took less than half a second. 
Is there anything else in your app? fetch large data cost a lot? call setState too many times?

**Comment by barbaragomes** [comment]
@wuxudong 

My App records vibration data with a 10ms frequency during 5min, and stores it to a variable.
Once the recording is done, I render the Chart.

So there is no calling setState too many times at this point.

**Comment by wuxudong** [comment]
You may try Examples->line chart with more points, then compare it with yours.

I can not figure out why at this moment.

**Comment by barbaragomes** [comment]
I will do some further investigation. Thanks

**Comment by barbaragomes** [comment]
@wuxudong **UPDATE** I figured out one of the problems. I had a `console.log()` that was logging all the data prior to the graph generation. Removing the log solve the issue for android, but it is still too slow for iOS

**Comment by wuxudong** [comment]
<img width="394" alt="screen shot 2017-11-30 at 8 42 06 am" src="https://user-images.githubusercontent.com/1391101/33407010-6081141e-d5aa-11e7-8dfd-41da2f0e5346.png">

This is iOS simulator, less than 1 second for iOS simulator.

**Comment by wuxudong** [comment]
Any update?

**Comment by wuxudong** [comment]
Close inactive issue, reopen if necessary. I think https://github.com/d3fc/d3fc-sample can help.

**Comment by wuxudong** [comment]
https://github.com/d3fc/d3fc-sample  doest not draw any line in graph?

**Comment by pawan8525** [comment]
@wuxudong  your link not working https://github.com/d3fc/d3fc-sample  .
I would thankful if you can give a better suggestion.

**Comment by wuxudong** [comment]
I don't why d3fc-sample is 404.

but you can still find it at https://www.npmjs.com/package/d3fc-sample

**Comment by nayfusaurus** [comment]
Referencing issue [#277](https://github.com/wuxudong/react-native-charts-wrapper/issues/277)

I tried running the code with this input and the chart lags so bad on my iPhone XR. Not sure why.

`values: Array.from({length: 1024}, () => Math.random() * 40)`

**Comment by kavindadilshan** [comment]
any solutions

**Comment by renishdeveloper** [comment]
+1
