### ISSUE TITLE
Dynamic rendering chart

### ISSUE THREAD

**Issue by lpb006** [wuxudong/react-native-charts-wrapper#145]
i want achieve like this http://blog.csdn.net/zhangphil/article/details/50185115
but i can't let the chart just show certain quantity in x just like above demo

**Comment by wuxudong** [comment]
It seems more properties should be introduced.

In MPAndroidChart, the following api is used to follow latest data

```
        mChart.setVisibleXRangeMaximum(5);  
        mChart.moveViewToX(data.getXValCount() - 5);  
```

Not supported at this moment.  PR is welcome.

It is a useful feature.

**Comment by wuxudong** [comment]
@lpb006 try 0.4.0-apha.
check Example->MovingWindowChartExample.
