### ISSUE TITLE
How to customize the styles in the “marker” and the contents of the display

### ISSUE THREAD

**Issue by XiaYongjie** [wuxudong/react-native-charts-wrapper#146]
the marker is not I want ,how about customize

**Comment by wuxudong** [comment]
you can adjust the color, alpha,  but not the shape. 

You can make a pull request to add more types of  markerView

**Comment by XiaYongjie** [comment]
@wuxudong thanks ,you are great

**Comment by tayloraleach** [comment]
This was closed a long time ago. Is there still no way of adding a custom marker?

**Comment by chellongCoder** [comment]
any updates for custom marker? :(
