### ISSUE TITLE
linechart xaxis's start

### ISSUE THREAD

**Issue by danceyoung** [wuxudong/react-native-charts-wrapper#147]
<img width="758" alt="wx20171201-101908 2x" src="https://user-images.githubusercontent.com/1777025/33465165-2fcd5f94-d681-11e7-8341-f77259ef6350.png">
how make this present?
one line starts drawing at first potin in xaxis,the other line starts drawing at second or third point in xaxis

**Comment by danceyoung** [comment]
i get slove. set value of 'x' in values:[{x:,y: }]

**Comment by taoyife** [comment]
@danceyoung   can you show your code please?  I also had this problem.

**Comment by danceyoung** [comment]
@taoyife 
Just set the different the first point value of xAxis for per line(data:{dataSets:[]}, 
i think this problem should be a data organation problem, because these code is simple,  and most codes are fellow example.

**Comment by danceyoung** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1777025/40225427-92e519aa-5abb-11e8-9589-f58df02a9923.png">
@taoyife

**Comment by taoyife** [comment]
@danceyoung   thanks
