### ISSUE TITLE
PropTypes is not available in react

### ISSUE THREAD

**Issue by tranhuuthinhit** [wuxudong/react-native-charts-wrapper#148]
On the RN version > 45. We don't have PropTypes in react.

**Comment by wuxudong** [comment]
？ check the latest version?

**Comment by lelup** [comment]
npm install --save prop-types
and you need to replace all PropTypes in react with: 
import 'PropTypes' from 'prop-types'

**Comment by wuxudong** [comment]
in the latest v0.3.1 .

It is already fixed. Just update this lib.

**Comment by lelup** [comment]
@wuxudong  i follow step by step in set up on link https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6
but dont show pop up Create Bridging Header,
![screen shot 2017-08-24 at 9 35 11 am](https://user-images.githubusercontent.com/19283388/33652043-83858716-da9a-11e7-8fd8-12b71d747be1.png)
 and my project build all failed. It wasted a day but won't find solution. Can you help me?

**Comment by wuxudong** [comment]
If Xcode doesn't promote 'Create Bridging Header', just do it by yourself. then add it to build setting.

<img width="786" alt="screen shot 2017-12-06 at 4 43 39 pm" src="https://user-images.githubusercontent.com/1391101/33652505-aa89e582-daa4-11e7-9107-b8d4d93a913d.png">

**Comment by lelup** [comment]
@wuxudong (SWIFT_VERSION) is required to be configured, this error appear? 
![screen shot 2017-12-06 at 16 20 16](https://user-images.githubusercontent.com/19283388/33654068-98ecd864-daa1-11e7-9371-b872e5cf9902.png)

**Comment by wuxudong** [comment]
What swift version you are using?
