### ISSUE TITLE
Is there a way to remove the padding on the graphs in IOS?

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#149]
Basically, if I modify the height and width of a chart component, i.e. PieChart, the Pie Chart has a predefined padding on the chart, unlike in Android where the chart occupies all the space. I've tried a lot of things like setting padding on a style to a negative value, or adding a padding property in my PieChart but it still does not work. In android there's no padding in the chart components no matter how big or small the size is. My current way to handle this situation is by setting the margin to a negative value but it becomes ugly on other iphone devices with small screens.

**Comment by abury** [comment]
@GermanMontejo Were you able to resolve this issue?

**Comment by luongs3** [comment]
@abury  did you resolve this issue? Got the same

**Comment by GermanMontejo** [comment]
@abury I was able to fix this issue but I can't remember the things I did, this was a long time ago. I'll look at the source code on Monday when I get to the office. I'm not sure but can you try setting a fixed height, i.e. 250 and a width of null. Then set a padding/margin to whatever value you want.

**Comment by GermanMontejo** [comment]
@abury here's the style I applied for the PieChart for IOS:

```
pieChartIOS: {
    flex: 1,
    height: 200,
    width: null,
    backgroundColor: 'transparent',
    padding: 0
  }
```

Try it.

**Comment by abury** [comment]
Thanks heaps @GermanMontejo! I ended up just setting negative margins, but i'll give this a go.
@luongs3, see it negative margins or the above works for you 👍
