### ISSUE TITLE
how to custom xAxis value appropriatly

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#15]
hi, in my project I want to custom xAxis value, like formatter, and I find that property `valueFormatter` could works in your Example __LineChartScreen.js__ , but when I change the count, it will not sort appropriatly.

![image](https://cloud.githubusercontent.com/assets/7262199/23991556/b3a333ae-0a74-11e7-9615-aab039ac4edb.png)

![image](https://cloud.githubusercontent.com/assets/7262199/23991575/c31ca090-0a74-11e7-9a4f-54f7338134bf.png)

how should I sort them homogeneous?

thanks for your time.

**Comment by wuxudong** [comment]
I think  granularity can help.

Try

        granularityEnabled: true,
        granularity: 1,

**Comment by L-Jovi** [comment]
@wuxudong  thanks,  you awesome :)

**Comment by xuananpham93** [comment]
Hi, 
How do you remove vertical borders in the chart?
