### ISSUE TITLE
setting limitline's textColor is not working 

### ISSUE THREAD

**Issue by danceyoung** [wuxudong/react-native-charts-wrapper#152]
limitLines: _.times(this.state.data.dataSets[0].values.length / 5, (i) => {
              return {
                limit: 5 * (i + 1) + 0.5,
                lineColor: processColor('darkgray'),
                lineWidth: 1,
                label: (i + 1).toString(),
                textColor: processColor('white'),
              };
            })
env:ios, react-native-charts-wrapper'version is 0.3.1

**Comment by danceyoung** [comment]
through looking for source code for iOS,may be setting valueTextColor.

attributes: [NSAttributedStringKey.font: limitLine.valueFont, NSAttributedStringKey.foregroundColor: limitLine.valueTextColor])

this is a little diffrent with MPAndroidChart's source code for java .

**Comment by danceyoung** [comment]
I think that it is a bug.I add code snap
                    if (limitLineConfig["valueTextColor"].int != nil) {
                      limitLine.valueTextColor = RCTConvert.uiColor(limitLineConfig["valueTextColor"].intValue)
                    }
in RNChartViewBase.swift

set valueTextColor is working

**Comment by wuxudong** [comment]
@danceyoung limitline.valueTextColor is not supported in this lib. Can you create a pull request about it? Thank you.

**Comment by danceyoung** [comment]
@wuxudong 
ok.I may be pull a requet
