### ISSUE TITLE
Build fails on iOS - Method does not override any method from its superclass

### ISSUE THREAD

**Issue by nvme978** [wuxudong/react-native-charts-wrapper#153]
React: 16.0.0-alpha.13
RN: 0.46.4
react-native-charts-wrapper: 0.3.1
Xcode: 9.2

iOS build fails with the error "Method does not override any method from its superclass"

See screenshot attached 
<img width="1015" alt="screen shot 2017-12-08 at 2 38 38 pm" src="https://user-images.githubusercontent.com/13456525/33758811-e77a0cc4-dc25-11e7-8027-cbd946a8dab2.png">

**Comment by wuxudong** [comment]
Which method indicate that error?

**Comment by nvme978** [comment]
This one

  override open static func requiresMainQueueSetup() -> Bool {
    return true;
  }

**Comment by wuxudong** [comment]
It is a new method introduced in RN0.47.
It will promote a warning if you don't override it...

**Comment by wuxudong** [comment]
Please update your RN.

**Comment by nvme978** [comment]
Got it. Thanks.

**Comment by SanyasiraoM** [comment]
@wuxudong We are using RN 0.48.4, Facing same issue

**Comment by wuxudong** [comment]
Sorry. that api is for RN 0.49+

**Comment by matr1xprogrammer** [comment]
Is there a version that is compatible with RN < 0.48.x ? I too am having the issue.
To fix I remove the 

`override open static func`

to look like this:

`open static func`

in all files affected.
