### ISSUE TITLE
Cannot build iOS project

### ISSUE THREAD

**Issue by jleed** [wuxudong/react-native-charts-wrapper#155]
Have done everything by readme,

here is my pods file
```
use_frameworks!

target 'gas' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'CxxBridge',
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTAnimation',
    'RCTImage',
    'RCTNetwork',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-blur', path: '../node_modules/react-native-blur'
  pod 'RNVectorIcons', path: '../node_modules/react-native-vector-icons'
  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

app-Bridging-Header.h

```
#import "React/RCTBridge.h"
#import "React/RCTViewManager.h"
#import "React/RCTUIManager.h"
#import "React/UIView+React.h"
#import "React/RCTBridgeModule.h"
#import "React/RCTEventDispatcher.h"
#import "React/RCTEventEmitter.h"

```

using xcode 9.2
Swift Language Versions sets to 3.2

errors:
```

node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift:16:23: Use of undeclared type 'RCTBubblingEventBlock'

node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNHorizontalBarChartManager.swift:8:41: Use of undeclared type 'RCTViewManager'

react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNHorizontalBarChartManager.swift:7:2: Only classes that inherit from NSObject can be declared @objc

node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNHorizontalBarChartManager.swift:9:22: Method does not override any method from its superclass

react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift:48:32: Use of unresolved identifier 'RCTConvert'
...
```

is there something I missing?

**Comment by wuxudong** [comment]
try example first？

**Comment by wuxudong** [comment]
It seems react native is not linked correctly

**Comment by johnbian** [comment]
try example，run ios doesn't work。
**errors**
The following build commands failed:
        CompileSwift normal x86_64 /Volumes/WORK/demo/react-native-charts-wrapper-master/ios/ReactNativeCharts/utils/BridgeUtils.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/Example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by johnbian** [comment]
@wuxudong hi，Is there a requirement for the Xcode version

**Comment by wuxudong** [comment]
I am not sure about it. My Xcode is Version 9.1 (9B55)

**Comment by wuxudong** [comment]
Same to #159

**Comment by sandeepsinghs** [comment]
@wuxudong  I am also not able run example project on IOS. I have tried all the possible way to resolve but unsuccessful.

Getting error for IOS as 

> Invariant Violation: Native component for "RNBarChart" does not exist
> 
> This error is located at:
> in RNBarChart (at BarChart.js:23)
> in BarChart (at App.js:79)
> in RCTView (at View.js:60)
> in View (at App.js:78)
> in RCTView (at View.js:60)
> in View (at App.js:70)
> in App (at renderApplication.js:33)
> in RCTView (at View.js:60)
> in View (at AppContainer.js:102)
> in RCTView (at View.js:60)
> in View (at AppContainer.js:122)
> in AppContainer (at renderApplication.js:32)
> 
> getViewConfig
> requireNativeComponent.js:107:6
> get$1
> ReactNativeRenderer-dev.js:14131:17
> createInstance
> ReactNativeRenderer-dev.js:14295:27
> completeWork
> ReactNativeRenderer-dev.js:10097:14
> completeUnitOfWork
> ReactNativeRenderer-dev.js:12769:10
> performUnitOfWork
> ReactNativeRenderer-dev.js:12941:32
> workLoop
> ReactNativeRenderer-dev.js:12953:43
> renderRoot
> ReactNativeRenderer-dev.js:12996:17
> performWorkOnRoot
> ReactNativeRenderer-dev.js:13632:34
> performWork
> ReactNativeRenderer-dev.js:13545:26
> performSyncWork
> ReactNativeRenderer-dev.js:13506:16
> requestWork
> ReactNativeRenderer-dev.js:13392:6
> scheduleWorkImpl
> ReactNativeRenderer-dev.js:13259:24
> scheduleRootUpdate
> ReactNativeRenderer-dev.js:13930:17
> render
> ReactNativeRenderer-dev.js:14726:35
> renderApplication
> renderApplication.js:49:21
> runApplication
> AppRegistry.js:194:26
> __callFunction
> MessageQueue.js:351:47
> 
> MessageQueue.js:116:26
> __guardSafe
> MessageQueue.js:314:6
> callFunctionReturnFlushedQueue
> MessageQueue.js:115:17

I have able to resolve on Android but not working on IOS.

Please help.
