### ISSUE TITLE
how to label limitLines on the bottom ?

### ISSUE THREAD

**Issue by nguyenhonggiangvietnam** [wuxudong/react-native-charts-wrapper#157]
how to label limitLines on the bottom like this 
![image](https://user-images.githubusercontent.com/34567975/34033509-14b84232-e1ad-11e7-8c1e-83ca525801d0.png)

**Comment by papsti7** [comment]
+1

**Comment by manjuy124** [comment]
@nguyenhonggiangvietnam 
 Did you find any way to do the same?

**Comment by wuxudong** [comment]
What do you mean by `label limitLines`?

Maybe axisMinimum can work for you.
