### ISSUE TITLE
question: 关于单位的问题

### ISSUE THREAD

**Issue by zhmeng** [wuxudong/react-native-charts-wrapper#158]
请问下TimeSeriesLineChartScreen 的 x, y 轴的单位一般怎么给提示呢。 例如： 元，万元，年，月 @ # # @wuxudong  ❓

**Comment by wuxudong** [comment]
check the valueFormatter property in axis config.

something like xAxis={{valueFormatter: '#.## $', position:'BOTTOM'}} will result in 
<img width="467" alt="screen shot 2017-12-18 at 6 33 32 pm" src="https://user-images.githubusercontent.com/1391101/34101838-03745b38-e422-11e7-8fc7-536a525cf4ca.png">

**Comment by zhmeng** [comment]
好的，谢谢
