### ISSUE TITLE
Example cannot run

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#159]
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by wuxudong** [comment]
Maybe the node port is occupied by other program. Check the [discussion](https://github.com/facebook/react-native/issues/7308).

**Comment by s349856186** [comment]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `prop-types` from `/Users/alpha/Desktop/APP/reactnative/react-native-charts-wrapper-master/lib/BarChart.js`: Module does not exist in the module map or in these directories:
  /Users/alpha/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`. (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.250
    RCTCxxBridge.mm:441
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_client_callout
_dispatch_queue_serial_drain
_dispatch_queue_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread3
_pthread_wqthread
start_wqthrea

**Comment by s349856186** [comment]
@wuxudong

**Comment by s349856186** [comment]
@wuxudong  how should i do

**Comment by wuxudong** [comment]
what is your react native version?

**Comment by s349856186** [comment]
"dependencies": {
    "immutability-helper": "2.4.0",
    "lodash": "4.17.4",
    "pod": "^0.9.0",
    "react": "^15.6.2",
    "react-native": "0.50.3",
    "react-native-charts-wrapper": "file:../",
    "react-navigation": "^1.0.0-beta.19"
  },

**Comment by GermanMontejo** [comment]
hi @wuxudong this is also a problem with android. I tried running your Example project and the log gave me this:

native-charts-wrapper\\lib\\BarChart.js`:Module does not exist in the module map or in these directories:

**Comment by guoguoss** [comment]
Delete the node_modules folder: rm -rf node_modules && npm install.  重新运行就好了

**Comment by jackmew** [comment]
Just do npm install 2 times:
1.react-native-charts-wrapper/
2.react-native-charts-wrapper/Example

Open react-native-charts-wrapper/Example/ios/Example.xcworkspace
Run

![screen shot 2018-04-17 at 3 34 11 pm](https://user-images.githubusercontent.com/6193983/38858140-1f257808-4255-11e8-92e1-e394249fd2c1.png)

**Comment by sandeepsinghs** [comment]
I am not able to install this example project on android device. While compiling this project it get struck on **Configuring > 3/3 projects > Resolving dependencies ':app:_debugApk' > Resolving dependencies ':react-native-charts-wrapper:_debugPubli**

please help to resolve.

**Comment by Oraclesports** [comment]
Which is the solution? I am not able to solve it 


error: bundling failed: Error: Unable to resolve module `react` from `/Users/BenedictChin/Downloads/react-native-charts-wrapper-master/lib/BarChart.js`: Module `react` does not exist in the Haste module map

**Comment by CoderGMLee** [comment]
Same problem

**Comment by sandeepsinghs** [comment]
I have solve this problem by adding 
` maven { url "https://jitpack.io" }    // ADD jitpack.io, IT IS USED BY MPAndroidChart` in file android/build.gradle
under 
`allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }    // ADD jitpack.io, IT IS USED BY MPAndroidChart
    }
}`

For IOS I followed this instruction to integrate in our project.
[https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6](url)

**Comment by wuxudong** [comment]
Cocoapods is suggested for iOS, follow https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md
