### ISSUE TITLE
Dificult

### ISSUE THREAD

**Issue by patrickalbani** [wuxudong/react-native-charts-wrapper#16]
I'm new in iOs using and follow the installations steps, and copy the barchart example, but not work form me. The only thing i change was the width and height.

Result:

![image](https://cloud.githubusercontent.com/assets/20818198/24003429/3b47cc3a-0a42-11e7-8b67-be14dce28fe1.png)

**Comment by wuxudong** [comment]
any error log ?

**Comment by wuxudong** [comment]
I guess the bridge header are missing

**Comment by patrickalbani** [comment]
No errors,
My header:

![image](https://cloud.githubusercontent.com/assets/20818198/24006433/853240f2-0a4a-11e7-8401-e221fc8b71ac.png)

**Comment by wuxudong** [comment]
Can you run Examples project successfully?

Have you added bridging header in build settings?

**Comment by wuxudong** [comment]
Can you run examples successfully?

Have you added bridge header in build settings?

Check [step by step tutorial](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/README.md)

**Comment by wuxudong** [comment]
Turn on debug js remotely, and check errors in chrome debug window

**Comment by patrickalbani** [comment]
When i run with debug:

![image](https://cloud.githubusercontent.com/assets/20818198/24055406/a18a3bae-0b1e-11e7-908f-776458be5c40.png)

**Comment by wuxudong** [comment]
Yes, the bridge header is not working, check tutorial and Xcode settings
