### ISSUE TITLE
CandleStickChart: set xAxis lable to show date,Show weird。

### ISSUE THREAD

**Issue by wuyanwuyan** [wuxudong/react-native-charts-wrapper#160]
I want draw CandleStickChart。 I learn from the example and modify the code，attend to show date on the xAxis label。
so，I add “x” value on the dateSet，
![2017-12-26 15 32 59](https://user-images.githubusercontent.com/4576326/34350731-539ead16-ea53-11e7-944f-cb5288a205b8.png)
and，add valueFormatter
![2017-12-26 15 43 04](https://user-images.githubusercontent.com/4576326/34350760-7deccdb4-ea53-11e7-9291-74fc561bea70.png)
finally：the result is weird。
![2017-12-26 15 34 28](https://user-images.githubusercontent.com/4576326/34350794-9e108ba8-ea53-11e7-8a79-28576e59c108.png)

Forgive me for breaking English。
我想画个K线图，于是试着修改源码example里面的CandleStickChart例子，dataSets里面我都加了个x的时间戳，还设置了valueFormatter，但是最后效果很奇怪。

**Comment by uinz** [comment]
我也也到了类似情况, 我的解决方法是

x 先用下标 0 1 2 3 4
```js
data = [
  {x: 0, ts: 1514308190539, ...},
  {x: 1, ts: 1514318190539, ...},
  {x: 2, ts: 1514328190539, ...},
  {x: 3, ts: 1514338190539, ...},
]

// ------------------------

xAxis = {
  valueFormatter: data.map(item => moment(item.ts).formate('MM-DD HH:mm')),
  ...
}
```

**Comment by wuxudong** [comment]
I found many people are drawing k-line chart with this lib， can anyone create a PR for a k-line example? Thank you.
