### ISSUE TITLE
did yAxis support `setShowOnlyMinMax`?

### ISSUE THREAD

**Issue by uinz** [wuxudong/react-native-charts-wrapper#161]
[setShowOnlyMinMax](https://github.com/mskec/react-native-mp-android-chart/blob/master/android/src/main/java/com/github/reactNativeMPAndroidChart/charts/YAxisChartBase.java#L38)

**Comment by wuxudong** [comment]
PR is welcome

**Comment by wuxudong** [comment]
no setShowOnlyMinMax in MpAndroidChart 3
