### ISSUE TITLE
build errors , for example: 'Position' is not a member type of 'Legend'  in BridgeUtils.swift

### ISSUE THREAD

**Issue by whoyoung** [wuxudong/react-native-charts-wrapper#162]
I build my demo failed:
![errors.png](http://upload-images.jianshu.io/upload_images/1396364-5cb8159ddf586a64.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![Position.png](http://upload-images.jianshu.io/upload_images/1396364-604df6a7e4a36e7c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![positionValue.png](http://upload-images.jianshu.io/upload_images/1396364-006063d7a72abef6.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![labels.png](http://upload-images.jianshu.io/upload_images/1396364-5fed29b4df3db912.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
My package.json
```"dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-charts-wrapper": "^0.4.0",
    "react-navigation": "^1.0.0-beta.22"
  }```

Once, I delete these wrong codes, build successful! I don't think the way of delete codes is a good solution.

**Comment by wuxudong** [comment]
What is your Charts version?

**Comment by wuxudong** [comment]
This lib is using Charts v3.0.3, and Legend.Position is removed in v3.0.4.

You can set Charts to v3.0.3, or create a PR to upgrade Charts to v3.0.4

**Comment by whoyoung** [comment]
@wuxudong Using Charts (3.0.4) Using SwiftyJSON (4.0.0)

**Comment by MeKarina** [comment]
both "pod 'Charts', '< 3.0.4'" and "pod 'Charts', '3.0.3'" dont work for me.. the only thing is working is to comment the source error...

**Comment by delkant** [comment]
@MeKarina did you find a solution, this is not working for me either. @whoyoung I have this same error when using '3.0.3' or '< 3.0.4'. Is there anything else I can try? I am using xcode Version 8.3.3 could that be a problem?

**Comment by nthegedus** [comment]
I'm facing the same issue.

Does anyone have any solution?

**Comment by delkant** [comment]
@nthegedus not me. I end up using https://github.com/JesperLekland/react-native-svg-charts
