### ISSUE TITLE
Highlight can't be used in combination with markers

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#164]
Hi @wuxudong! I've tried your latest version and the highlights feature you added is great! I just can't wrap around the notion why using highlights with marker causes our app to crash. I have enabled both in my CombinedChart component and if they are both enabled then my app crashes. Can you help me solve this? Thanks again for creating this awesome library! :)

**Comment by GermanMontejo** [comment]
@wuxudong please see this explanation above ^

**Comment by GermanMontejo** [comment]
This is the stacktrace when the app crashes:

12-27 17:53:18.406 11825 11825 E AndroidRuntime: FATAL EXCEPTION: main
12-27 17:53:18.406 11825 11825 E AndroidRuntime: Process: com.neurobeat, PID: 11825
12-27 17:53:18.406 11825 11825 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
12-27 17:53:18.406 11825 11825 E AndroidRuntime:        at java.util.ArrayList.get(ArrayList.java:413)
12-27 17:53:18.406 11825 11825 E AndroidRuntime:        at com.github.mikephil.charting.data.CombinedData.getEntryForHighlight(CombinedData.java:185)
12-27 17:53:18.406 11825 11825 E AndroidRuntime:        at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:730)
12-27 17:53:18.406 11825 11825 E AndroidRuntime:        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:270)
12-27 17:53:18.406 11825 11825 E AndroidRuntime:        at android.view.View.draw(View.java:17236)

**Comment by GermanMontejo** [comment]
This is the stacktrace when the app crashes:

12-27 17:53:18.406 11825 11825 E AndroidRuntime: FATAL EXCEPTION: main
12-27 17:53:18.406 11825 11825 E AndroidRuntime: Process: -------, PID: 11825
12-27 17:53:18.406 11825 11825 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
12-27 17:53:18.406 11825 11825 E AndroidRuntime: at java.util.ArrayList.get(ArrayList.java:413)
12-27 17:53:18.406 11825 11825 E AndroidRuntime: at com.github.mikephil.charting.data.CombinedData.getEntryForHighlight(CombinedData.java:185)
12-27 17:53:18.406 11825 11825 E AndroidRuntime: at com.github.mikephil.charting.charts.Chart.drawMarkers(Chart.java:730)
12-27 17:53:18.406 11825 11825 E AndroidRuntime: at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:270)
12-27 17:53:18.406 11825 11825 E AndroidRuntime: at android.view.View.draw(View.java:17236)

**Comment by wuxudong** [comment]
Which platform? 
and any log?

**Comment by wuxudong** [comment]
I will take a look, the bug is reproduced.

**Comment by wuxudong** [comment]
The problem is the dataIndex attribute of Highlight.

the default value of dataIndex is -1, and it is useless except for CombindChart(Only CombindChart can have multiple data).

It is a bug. and I will fix it soon. Thank you.

**Comment by GermanMontejo** [comment]
Okay, thank you! :)
