### ISSUE TITLE
drawEntryLabels cause crash ios app

### ISSUE THREAD

**Issue by windydang26** [wuxudong/react-native-charts-wrapper#165]
i cannot set draw label in pie chart. someone same me?
    "react-native": "0.47.2",
    "react-native-charts-wrapper": "^0.2.10",

**Comment by wuxudong** [comment]
sample data or logs?

**Comment by windydang26** [comment]
when i add drawEntryLabels={true} in pie chart config ios crash. but i set self._chart.drawEntryLabelsEnabled = true in ios lib is no issue.
@wuxudong you can check that

**Comment by s349856186** [comment]
@windydang26 how to do no issue?

**Comment by windydang26** [comment]
@s349856186 i don't know. temporary i don't use it.

**Comment by wuxudong** [comment]
you can check the Example, it has drawEntryLabels in PieChartScreen, and it works well.

**Comment by huybq95** [comment]
Hi @wuxudong , i have same issue with pie chart in IOS, when i set drawEntryLabels it throw this error [https://drive.google.com/file/d/1dFxvK2NpLsyEGhrW8q5j1N8vsEjTXD26/view?usp=sharing](url)

**Comment by wuxudong** [comment]
What is the lib version?
and can you find following [code](https://github.com/wuxudong/react-native-charts-wrapper/blob/6265d04ece53c579b6d0427cf9b4c5207b6cded0/ios/ReactNativeCharts/pie/RNPieChartView.swift#L121) in RNPieChartView of local node_modules?


    func setDrawEntryLabels(_ enabled: Bool) {
        chart.drawEntryLabelsEnabled = enabled
    }

**Comment by huybq95** [comment]
I using latest lib version and i can't find func setDrawEntryLabels in RNPieChartView.swift

**Comment by s349856186** [comment]
@wuxudong I can find the code but crash,

**Comment by wuxudong** [comment]
@s349856186  the code exists but still crash?

**Comment by s349856186** [comment]
@wuxudong yes，I upgraded the latest version, and I can find code but crash，do I still need other actions?

**Comment by wuxudong** [comment]
That’s weird. You can clone the repo and run examples to see if it works well. The Example->PieChartScreen also has the drawEntryLabels property.

**Comment by huybq95** [comment]
How can i set .xValuePosition when drawEntryLabels={true} ?

**Comment by wuxudong** [comment]
@huybq95 
> I using latest lib version and i can't find func setDrawEntryLabels in RNPieChartView.swift. Thank you for your help. The problem resolved 👍



I am pretty sure that func setDrawEntryLabels is in the latest RNPieChartView.swift . Why it is disappear?

Are you trying to add more features like xValuePosition?

**Comment by huybq95** [comment]
Sorry for my bad im using old version which have func drawSliceText.
I'm trying to add xValuePosition below:

override func dataSetConfig(_ dataSet: IChartDataSet, config: JSON) {
        let pieDataSet = dataSet as! PieChartDataSet;
            pieDataSet.xValuePosition = .outsideSlice;
            pieDataSet.valueLineWidth = CGFloat(0.5);
            pieDataSet.valueLinePart1Length = CGFloat(1);
            pieDataSet.valueLinePart2Length = CGFloat(1);
      
        ChartDataSetConfigUtils.commonConfig(pieDataSet, config: config);
        
        // PieDataSet only config
        if config["sliceSpace"].number != nil {
            pieDataSet.sliceSpace = CGFloat(config["sliceSpace"].numberValue)
        }
        
        if config["selectionShift"].number != nil {
            pieDataSet.selectionShift = CGFloat(config["selectionShift"].numberValue)
        }    
    }
It work in my case.

**Comment by wuxudong** [comment]
you can create a PR for xValuePosition
