### ISSUE TITLE
iOS Build Error - 'Position' is not a member type of 'Legend'

### ISSUE THREAD

**Issue by c0d3blooded** [wuxudong/react-native-charts-wrapper#168]
I just started getting this error recently (probably after a Pod refresh). It's probably related to the recent commit in the iOS Charts library.

Line 44: BridgeUtils.swift

Possibly related to this recent commit ('Position' enum has been removed from Legend.swift):
https://github.com/danielgindi/Charts/commit/ecdd295b9b1868dd6a13253ebd9263e3c5559413

**Comment by wuxudong** [comment]
same as #162
