### ISSUE TITLE
Highlights not calling a listener

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#169]
Hello @wuxudong I've tried your highlights feature and now it's not crashing. There's one problem though. You were invoking **chart.highlightValues(highlights.toArray(new Highlight[highlights.size()]));** but this method does not call the listener. I needed to call the listener when highlightValues is invoke.

Upon checking the documentation on MPAndroidCharts, I've found out that I can use:

**public void highlightValue(Highlight high, boolean callListener) {}**

So I tweaked your ChartBaseManager's setHighlights() by adding this:

```
if (array.size() == 1) {
            ReadableMap highlightMap = array.getMap(0);

            if (highlightMap.getDouble("x") == -1) {
                return;
            }

            int dataSetIndex = BridgeUtils.validate(highlightMap, ReadableType.Number, "dataSetIndex") ? highlightMap.getInt("dataSetIndex") : 0;
            float y = BridgeUtils.validate(highlightMap, ReadableType.Number, "y") ? (float) highlightMap.getDouble("y") : 0;
            Highlight highlight = null;

            if (BridgeUtils.validate(highlightMap, ReadableType.Number, "stackIndex")) {
                highlight = new Highlight((float) highlightMap.getDouble("x"), dataSetIndex, highlightMap.getInt("stackIndex"));
            } else {
                highlight = new Highlight((float) highlightMap.getDouble("x"), y, dataSetIndex);
            }

            if (BridgeUtils.validate(highlightMap, ReadableType.Number, "dataIndex")) {
                highlight.setDataIndex(highlightMap.getInt("dataIndex"));
            }

            System.out.println("123handle! highlight: " + highlight.toString());

            chart.highlightValue(highlight, true);
}
```

This does not work as intended. Although I've passed the correct arguments to chart.highlightValue(), it does not highlight and invoke the listener of my chart. The reason I need the listener to be invoked is so that the chart's marker will display when the highlightValue() is invoked. Please help me with this issue.

P.S.

I've logged entry.x on handleSelect() and it returns an empty object:

entry.x: {}
entry.y: undefined

**Comment by wuxudong** [comment]
check the combine chart example first. The marker has nothing to do with the listener. Make sure the x, y, dataIndex are correct.

**Comment by GermanMontejo** [comment]
yup, I did use the correct dataIndex (1 in my case because it's a bar data and I'm using it as the first dataset) and my x value was correct as well because my bar was highlighted (the color changed for that bar).

Even though the bar was highlighted, the marker above did not show up. I'm trying to make it appear just like when you're tapping the bar and the marker displays above it.

**Comment by wuxudong** [comment]
you can run my combined chart example first， you will find that marker shows without listener.

**Comment by GermanMontejo** [comment]
okay @wuxudong , I'll do that.

**Comment by wuxudong** [comment]
Y value is also needed..

**Comment by GermanMontejo** [comment]
Deym! It's working! I'm really happy right now. You're awesome! 🍻 here are two beers for you for being an awesome author/developer!
I didn't know the y field would have an impact here. hahaha maybe we should make it a requirement to always supply the y field?

**Comment by wuxudong** [comment]
The configure of highlight in CombinedChart is a little complicated, especially the dataIndex (this is not mentioned in any doc), and y value.
