### ISSUE TITLE
horizontal barchart support?

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#17]
hi, I find that no __Horizontal BarChart__ exist in your __lib__ at js side,

![image](https://cloud.githubusercontent.com/assets/7262199/24034015/81d8e1dc-0b2a-11e7-8734-2ebcea364826.png)

how should I use horizontal barchart?

thanks for your time.

**Comment by wuxudong** [comment]
not support yet. 
or you can fork and PR

**Comment by L-Jovi** [comment]
ok, I'll try to check the project source, the same newer of swift  : (

**Comment by wuxudong** [comment]
@L-Jovi   It is supported in latest version. check it

**Comment by L-Jovi** [comment]
awesome :)

**Comment by sabarishnarain** [comment]
Is this documented? Can someone point to that please?
