### ISSUE TITLE
Config multi color in BarChart?

### ISSUE THREAD

**Issue by xuananpham93** [wuxudong/react-native-charts-wrapper#170]
Hi @wuxudong , How can I configure barchar like the image?

![capture](https://user-images.githubusercontent.com/16789892/34509179-a677582c-f079-11e7-9745-d9e66e2abc6d.PNG)

 I didn't find any way to resolve it...Please help!

**Comment by wuxudong** [comment]
In BarChartScreen.
replace     
`color: processColor('teal'),`
 with     
`colors:[processColor('teal'),processColor('red'),processColor('green'),processColor('black'),processColor('black')]`

**Comment by xuananpham93** [comment]
Thank you, bro. How can I remove iconLabel when label ='' ?
![capture](https://user-images.githubusercontent.com/16789892/34510602-e240328a-f087-11e7-8aea-3dba228ffded.PNG)

**Comment by wuxudong** [comment]
Maybe filter your data.

**Comment by xuananpham93** [comment]
what does that mean? @@
