### ISSUE TITLE
Invariant Violation: Native component for "RNBarChart" does not exist

### ISSUE THREAD

**Issue by nantaya** [wuxudong/react-native-charts-wrapper#172]
`Invariant Violation: Native component for "RNBarChart" does not exist`
`This error is located at:
   in RNBarChart (at BarChart.js:23)`

and this is my package.json

`"dependencies": {
    "immutability-helper": "^2.6.2",
    "lodash": "^4.17.4",
    "moment": "^2.19.2",
    "react": "16.0.0",
    "react-native": "0.50.3",
    "react-native-charts-wrapper": "^0.4.1",
    "react-native-chooser": "^1.7.0",
    "react-native-circular-progress": "^0.1.0",
    "react-native-elements": "^0.18.5",
    "react-native-event-listeners": "^1.0.3",
    "react-native-gesture-handler": "^1.0.0-alpha.35",
    "react-native-image-picker": "^0.26.7",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-maps": "^0.19.0",
    "react-native-modal": "^4.1.1",
    "react-native-modal-datetime-picker": "^4.13.0",
    "react-native-navigation": "^1.1.307",
    "react-native-percentage-circle": "^1.0.6",
    "react-native-radio-buttons": "^1.0.0",
    "react-native-swipeout": "^2.3.3",
    "react-native-tab-view": "^0.0.73",
    "react-native-touch-id": "^3.1.0",
    "react-native-vector-icons": "^4.4.2",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "21.2.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.2.1",
    "react-test-renderer": "16.0.0",
    "redux-immutable-state-invariant": "^2.1.0",
    "redux-logger": "^3.0.6"
  }`

**Comment by wuxudong** [comment]
android or iOS?

**Comment by nantaya** [comment]
@wuxudong  android

**Comment by wuxudong** [comment]
react-native link?

**Comment by nantaya** [comment]
The problem is solved now. Because react-native-navigation create one more getPackage method in MainApplication.java, so what i have to do is add class in another getPackage method manually.

**Comment by rishiankush** [comment]
I am getting this error for IOS. what should I do in case of IOS?

**Comment by rishiankush** [comment]
ok found the solution here: https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6

**Comment by fabioplaka** [comment]
I am getting this error now, anything new for ios?

**Comment by neemssoni** [comment]
@fabioplaka did you find any solution for this?

**Comment by fabioplaka** [comment]
Yes I uninstalled and installed the library again and read the official documentation carefully and it works
