### ISSUE TITLE
Drawing a box around an x value on the chart.

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#173]
Hi @wuxudong ! Is there any way with the current implementation where I can draw a box around an x value on the chart? Kinda something like the image I've attached here...

![selected_num](https://user-images.githubusercontent.com/8085558/34702885-2eeb8b0a-f52b-11e7-8eea-ba636ba9f7a1.png)

**Comment by wuxudong** [comment]
no......
