### ISSUE TITLE
How to hide zero values in bar chart

### ISSUE THREAD

**Issue by herarya** [wuxudong/react-native-charts-wrapper#174]
hi guys @wuxudong 

how to hide zero value on bar chart

<img width="356" alt="screen shot 2018-01-09 at 15 29 41" src="https://user-images.githubusercontent.com/5027291/34711425-f2f8dcb6-f551-11e7-8d46-5fed25b4f0ea.png">

**Comment by wuxudong** [comment]
remove these entry?

**Comment by herarya** [comment]
thanks for replay,
I try to delete object crash and i set value to null, also crash on ios @wuxudong

**Comment by wuxudong** [comment]
may be something like [{x:0, y:1}, {x:3, y:55000}, {x:10,y:57000}].

**Comment by herarya** [comment]
@wuxudong thanks for replay

this my values 
`[{
    "marker":"4806990.5",
    "x" : "03/18",
    "y" : "4806990.5"
},
{
    "marker":"55500",
    "x" : "05/18",
    "y" : "55500"
},
{
    "marker":"57000",
    "x" : "09/18",
    "y" : "57000"
}]`;

still same

**Comment by herarya** [comment]
@wuxudong thanks bro, 
i try change values

![screen shot 2018-01-11 at 08 52 40](https://user-images.githubusercontent.com/5027291/34804785-010985a6-f6ad-11e7-9bf0-12f62654fbba.png)

the date range start 4 jan 2018 - 11 -jan 2018,
my bar only show start 5 Jan 2018 - 8 jan 2018

this my values

`[
    {
        "marker" : "55500",
        "x" : 1,
        "y" : 55500
    },
    {
        "marker" : "20500",
        "x" : 4,
        "y" : 20500
    }
]`


i think need formater
i found https://stackoverflow.com/questions/32940999/how-to-hide-zero-values-in-pie-chart-mpchart-android

but I do not know how to do it

**Comment by wuxudong** [comment]
maybe set axisminimum to 0

**Comment by MarsLuo** [comment]
xAxis: {
            $set: {
              drawAxisLine: false,
            }

have you try this ?

**Comment by herarya** [comment]
hi @wuxudong i set axisMinimum 
still same

my code 
`<BarChart
                    style={styles.chart}
                    data={data}
                    xAxis={xAxis}
                    marker={this.state.marker}
                    yAxis={{
                        left: {
                            drawLabels: true,
                            drawAxisLine: false,
                            drawGridLines: false,
                            zeroLine: {
                                enabled: true,
                                lineWidth: 1.5
                            },
                            axisMinimum: 0
                        },
                        right: {
                            enabled: false
                        }
                    }}
                />`

**Comment by wuxudong** [comment]
data: {
        dataSets: [{
          values: [{x:1,y: 100}, {x:3,y: 105},  {x:7,y: 110}],
          label: 'Bar dataSet',
          config: {
            color: processColor('teal'),
            barSpacePercent: 40,
            barShadowColor: processColor('lightgrey'),
            highlightAlpha: 90,
            highlightColor: processColor('red'),
            axisDependency: 'left',
            
          }
        }]
      },
      highlights: [{x: 3}, {x: 6}],
      xAxis: {
        valueFormatter: ['02/18', '03/18', '04/18', '05/18', '06/18', '07/18', '08/18', '09/18', '10/18'],
        granularityEnabled: true,
        granularity : 1,
        axisMinimum: -1,
        axisMaximum: 10
      },



![simulator screen shot - iphone 6 - 2018-01-16 at 10 36 19](https://user-images.githubusercontent.com/1391101/34969316-3808bb94-faa9-11e7-8502-4eeb0dbf5511.png)

**Comment by herarya** [comment]
@wuxudong thank bro ... cool

**Comment by hpelitebook745G2** [comment]
how about for Pie Chart @wuxudong ?

**Comment by taongocsontam** [comment]
@wuxudong 
how can i hide the value on 2 sides of y axis.
![Screen Shot 2021-07-21 at 10 31 05 AM](https://user-images.githubusercontent.com/49177358/126426291-933fb342-c5b0-4da8-8e60-4124bf87ffb6.png)
