### ISSUE TITLE
Argument exception for candlestick chart

### ISSUE THREAD

**Issue by benoist** [wuxudong/react-native-charts-wrapper#177]
I'm getting an exception on a Samsung Note 4, but not on an nexus.
It says the android.graphics.Paint.Style.FİLL constant can't be found.

Using this as config for the candle stick chart
```javascript
config: {
            highlightColor: processColor('darkgray'),
            drawValues: false,
            shadowColor: processColor(DefaultColors.background),
            shadowWidth: 0.5,
            shadowColorSameAsCandle: false,
            increasingColor: processColor(DefaultColors.success),
            increasingPaintStyle: 'fill',
            decreasingColor: processColor(DefaultColors.danger),
          },
```

Getting this error

```
IllegalArgumentException
No enum constant android.graphics.Paint.Style.FİLL
java.lang.Enum in valueOf at line 254
android.graphics.Paint$Style in valueOf at line 343
com.github.wuxudong.rncharts.data.CandleDataExtract in dataSetConfig at line 67
com.github.wuxudong.rncharts.data.DataExtract in extract at line 40
com.github.wuxudong.rncharts.data.CombinedDataExtract in extract at line 43
com.github.wuxudong.rncharts.data.CombinedDataExtract in extract at line 19
com.github.wuxudong.rncharts.charts.ChartBaseManager in setData at line 388
```

**Comment by wuxudong** [comment]
com.github.wuxudong.rncharts.data.CandleDataExtract in dataSetConfig at line 67 

`candleDataSet.setIncreasingPaintStyle(Paint.Style.valueOf(config.getString("increasingPaintStyle").toUpperCase()));`

fill -> FİLL ? what is the locale?

**Comment by benoist** [comment]
I just asked and it was set to turkish

**Comment by benoist** [comment]
I asked the user to set the language and it has fixed the issue! Is there a way to fix this from the code

**Comment by wuxudong** [comment]
public class Demo {
	    public static void main(String[] args) {
	        Locale trlocale = new Locale("tr", "TR");
	        System.out.println("fill".toUpperCase(trlocale));
	    }
	}
 
will print `FİLL`.

As a temporary workaround, you can change the config: `increasingPaintStyle: 'FILL',`

**Comment by benoist** [comment]
Oh wow, nice catch! Didn't even see it wasn't an I

**Comment by benoist** [comment]
Thank you for the quick fix!
