### ISSUE TITLE
chart package is not working 

### ISSUE THREAD

**Issue by shashikantChetu** [wuxudong/react-native-charts-wrapper#178]
Hi guys,
I have implement this chart functionality but i can't see any graph on my page and also i don't get any issue and error related to package .I have implement line Chart without Update functionality only i want to show graph.

**Comment by wuxudong** [comment]
Check log in chrome console ？

**Comment by shashikantChetu** [comment]
i have some warning in console...
Warning: Native component for "RNBarChart" does not exist
Warning: Native component for "RNHorizontalBarChart" does not exist
Warning: Native component for "RNBubbleChart" does not exist
Warning: Native component for "RNCandleStickChart" does not exist

but I am working on android device .

**Comment by wuxudong** [comment]
The lib is not linked correctly. Run example first, then compare it with yours.

**Comment by shashikantChetu** [comment]
but I have output in` BarChartScreen` to show `selected entry` on page and get to hide with according to chart but don't show chart

**Comment by wuxudong** [comment]
selected entry is a plain text out of chart.
