### ISSUE TITLE
Xcode 8.3.3 issues

### ISSUE THREAD

**Issue by AndrePech** [wuxudong/react-native-charts-wrapper#179]
Thanks for making this wrapper. I am trying to run the Example project on my machine running Xcode 8.3.3 and it does not work:

Error: Value of type 'String' has no member 'first'

I think it is due to my Swift 3.0 version.

Does this library require a Swift version > 3 ?
I am not able to update my swift version unless i Update the Xcode itself...

(Updating my Xcode causes my whole project to break )

**Comment by wuxudong** [comment]
I’m afraid not.

The latest underlying native lib ‘Charts 3.0.4’ requires Xcode 9.0 / Swift 4.0. And currently I am using Charts 3.0.3, swift 3 is necessary.
