### ISSUE TITLE
how to format percentValues of pie chart

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#18]
I find that `usePercentValues` property could compute percent value of pie chart, but how should I format along `%` from result?

thanks a lot,

regards.

**Comment by wuxudong** [comment]
check valueFormatter?

**Comment by L-Jovi** [comment]
@wuxudong do you mean `valueFormatter={'$ %s'}`?

I just find that apply this property in xAxis or yAxis, but PieChart have __no axis__ exist, would you mind provide simple code?

thanks for your patience,

regards.

**Comment by wuxudong** [comment]
it can also applied to data. check the usage of valueFormatter in LineChartScreen.js. 

I haven't test this, but it should work.

**Comment by wuxudong** [comment]
an update may required. the feature is introduced in recent days.

**Comment by L-Jovi** [comment]
thanks for your reply, I update your smart project to latest and follow your example,

and I try that `valueFormatter: "##.0 %"` but notice the value isnot right

![image](https://cloud.githubusercontent.com/assets/7262199/24038878/39dc013e-0b3e-11e7-99dd-efbfa5d2ee45.png)

maybe 15.0 %, 90.0 %  ..etc

**Comment by wuxudong** [comment]
mpandroidchart will translate [10,10,10,10] to [25,25,25,25] when usePercentValues is set. which means every part occupies 25%.

be ware valueFormat use DecimalFormat grammar, so '#.0%' will convert 25 -> 2500%.

as a workaround, replace '#.0%'  with "#.0'%'"

**Comment by L-Jovi** [comment]
well, I understand your mean, mpandroid already compute percent result for me, but if I provide `%`, mpandroid will consider it as command that convert the result to percent,

so two workaround
- provide 0.15 and mpandroid will convert to 15%
- directly append `%`

thanks for your time.
