### ISSUE TITLE
large value formatter

### ISSUE THREAD

**Issue by windydang26** [wuxudong/react-native-charts-wrapper#182]
large value cannot formatter correct.
Ex. 2200 -> 2k so duplicate 2k

**Comment by windydang26** [comment]
@wuxudong you can help me?

**Comment by windydang26** [comment]
![screen shot 2018-01-20 at 8 52 57 am](https://user-images.githubusercontent.com/20814511/35178715-60696dae-fdbf-11e7-908b-540ae02186bc.png)

**Comment by wuxudong** [comment]
what about set granularity to 1000 combined with large value formatter?

**Comment by windydang26** [comment]
ok. thank you! however, need support formatter func to custom formatter is better. thank!

**Comment by wuxudong** [comment]
custom decimal format like "#.000" is supported , but it is little hard to write custom formatter like 'k', 'm'

**Comment by windydang26** [comment]
hi. @wuxudong. user can write largeValueFormatter function to formatter axisValue. So can formatter 2200 -> 2.2k ...
