### ISSUE TITLE
default focus one slice in pie chart

### ISSUE THREAD

**Issue by windydang26** [wuxudong/react-native-charts-wrapper#183]
how i can auto focus in one slice of pie chart in first render?
![screen shot 2018-01-21 at 10 07 13 am](https://user-images.githubusercontent.com/20814511/35190400-1b1f25c0-fe93-11e7-82b9-a8ea101d58cf.png)

**Comment by wuxudong** [comment]
there is a highlight attribute.

**Comment by windydang26** [comment]
thank for response. i used highlight like piechart example but not working. with

**Comment by windydang26** [comment]
highlights: [{ x: 1 }]

**Comment by wuxudong** [comment]
In Examples->PieChartScreen, it works fine.
Check if it is at right place.

**Comment by windydang26** [comment]
this is my component and highlights attribute still not working. 

import React, { Component, PropTypes } from 'react'
import { View, processColor, Text, Dimensions } from 'react-native';
import { PieChart } from 'react-native-charts-wrapper';
import I18n from '../../modules/language';
import style from '../../style';
import { dataStorage } from '../../storage';
import deviceModel from '../../constants/device_model';
const { height, width } = Dimensions.get('window');

class PieChartNew extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      listData: this.props.listData || [],
      legend: {
        enabled: false
      },
      data: {},
      highlights: [{ x: 1 }]
    };
  }

  componentDidMount() {
    this.setState({
      data: {
        dataSets: [{
          values: this.props.listData,
          label: '',
          config: {
            colors: this.props.listColors,
            drawValues: false,
            valueTextSize: style.fontSizeS - 1,
            valueTextColor: processColor('#fff'),
            valueFormatter: '#0.00 %',
            sliceSpace: 3,
            selectionShift: 10
          }
        }]
      },
      highlights: [{ x: 1 }]
    })
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps && nextProps.listData) {
      this.setState({
        listData: nextProps.listData,
        data: {
          dataSets: [{
            values: nextProps.listData,
            label: '',
            config: {
              colors: nextProps.listColors,
              drawValues: false,
              valueTextSize: style.fontSizeS,
              valueTextColor: processColor('#fff'),
              valueFormatter: '#0.00 %',
              sliceSpace: 3,
              selectionShift: 10
            }
          }]
        },
        highlights: [{ x: 1 }]
      })
    }
  }

  handleSelect(event) {
    const obj = event.nativeEvent;
    const code = obj.data ? obj.data.code : '';
    const listData = this.state.listData;
    let index = 0;
    if (code !== '') {
      index = listData.findIndex(x => x.code === code);
    }
    this.props.onFocus && this.props.onFocus(code, index);
  }

  render() {
    return (
      <View style={{ flex: 1, backgroundColor: 'white', justifyContent: 'center', alignItems: 'center' }}>
        <PieChart
          style={{ width: '100%', height: dataStorage.deviceModel === deviceModel.IPHONE_X ? '85%' : '100%', backgroundColor: 'white' }}
          logEnabled={true}
          chartBackgroundColor={processColor('white')}
          chartDescription={{ text: '' }}
          data={this.state.data}
          legend={this.state.legend}
          highlights={this.state.highlights}
          noDataText={'No data chart !'}
          entryLabelColor={processColor('#10a8b2')}
          entryLabelTextSize={12}
          touchEnabled={true}
          drawEntryLabels={true}
          usePercentValues={false}
          centerText={''}
          onSelect={this.handleSelect.bind(this)}
          centerTextRadiusPercent={0}
          holeRadius={0}
          transparentCircleRadius={0}
          rotationEnabled={true}
          maxAngle={360}
        />
      </View>
    );
  }
}

export default PieChartNew;

**Comment by windydang26** [comment]
@wuxudong it work for android but ios not working.

**Comment by wuxudong** [comment]
what is the version? upgrade, clean , rebuild?

**Comment by windydang26** [comment]
i'm using version 0.4.0? i will retry with 0.4.1.

**Comment by s349856186** [comment]
@windydang26 How is your pie style set, How to display the label outside the pie ？

**Comment by s349856186** [comment]
@wuxudong can you help me, How to display the label outside the pie ？

**Comment by windydang26** [comment]
you must edit some thing in native code.
add snippet in dataSetConfig function of PieDataExtract.swift (for ios):
        pieDataSet.xValuePosition = .outsideSlice;
        pieDataSet.valueLineWidth = CGFloat(0.5);
        pieDataSet.valueLinePart1Length = CGFloat(1);
        pieDataSet.valueLinePart2Length = CGFloat(1);

**Comment by windydang26** [comment]
as:
    override func dataSetConfig(_ dataSet: IChartDataSet, config: JSON) {
        let pieDataSet = dataSet as! PieChartDataSet;
        pieDataSet.xValuePosition = .outsideSlice;
        pieDataSet.valueLineWidth = CGFloat(0.5);
        pieDataSet.valueLinePart1Length = CGFloat(1);
        pieDataSet.valueLinePart2Length = CGFloat(1);
        
        ChartDataSetConfigUtils.commonConfig(pieDataSet, config: config);
        
        // PieDataSet only config
        if config["sliceSpace"].number != nil {
            pieDataSet.sliceSpace = CGFloat(config["sliceSpace"].numberValue)
        }
        
        if config["selectionShift"].number != nil {
            pieDataSet.selectionShift = CGFloat(config["selectionShift"].numberValue)
        }
        
    }

**Comment by windydang26** [comment]
and sure that drawEntryLabels={true} in chart config.

**Comment by wuxudong** [comment]
Is the problem in iOS solved?

**Comment by windydang26** [comment]
Yes, @wuxudong . current i don't use highlights autribute. this issue can close.
