### ISSUE TITLE
Multiple Y Axis for multiple Series

### ISSUE THREAD

**Issue by sourceship13** [wuxudong/react-native-charts-wrapper#184]
Hello wuxudong!

I love your library, I was wondering if it was possible to have multiple Y Axis in a Chart. I have a few series some of which have a different Y Axis values then the other series; Is it possible  to have one of the Y Axis on the left or right Side of the chart represent a different number range then on the other chart? 

Thanks in Advance!

**Comment by wuxudong** [comment]
Maybe #175 can help.

**Comment by sourceship13** [comment]
The axisDependency property was exactly what I was looking for. I was able to implement it. 

Thanks for your help and a great library!

**Comment by GowthamGr** [comment]
How to add third yaxis value.
