### ISSUE TITLE
How to draw horizontal line in min and max values in Line chart

### ISSUE THREAD

**Issue by ashanjayasundara** [wuxudong/react-native-charts-wrapper#186]
how can i draw vertical line which highlighting min and max values in line chart data set

**Comment by danceyoung** [comment]
i think you can try to draw limitline

**Comment by ashanjayasundara** [comment]
@danceyoung how can i draw limitline i am new to this

**Comment by danceyoung** [comment]
@ashanjayasundara 
set xAxis or yAxis
eg
        xAxis: {
          //  valueFormatter: '#0.00',
          position: 'BOTTOM',
           textColor: processColor(global.constants.favorite_label_value_color),
          //  labelCount: 5,
          //  labelCountForce: true,
          drawGridLines: false,
          drawLabels: false,
          limitLines: [
{
                    limit: 0,
                    label: this.state.realtimeChartStockXYAxisValues[0][0].xLabel,
                    labelPosition: 'RIGHT_BOTTOM',
  lineColor: processColor('gray'),
  lineWidth: 1,
  valueTextColor: processColor(global.constants.favorite_label_value_color),
  valueFont: 9,

}
]
        },

**Comment by platonish** [comment]
@danceyoung is it possible to have dashed limit lines, similar to the grid lines? Here's what I've tried so far:
```javascript
limitLines: [
  {
  	limit: 300, 
  	lineColor: processColor('white'), 
  	label:'300', 
  	valueTextColor: processColor('white'), 
  	labelPosition:'LEFT_TOP', 
  	lineDashLengths: [1, 2]
  }
]
```

**Comment by danceyoung** [comment]
@platonish 
I think the dashline code likes this 
  dashedLine: {
    lineLength: 8,
    spaceLength: 8
  }
but it's different between in iOS and Android

**Comment by platonish** [comment]
@danceyoung thanks for the reply; I tried  using both `dashedLine` as well as `lineDashLengths` properties, neither of them seem to work

**Comment by wuxudong** [comment]
<img width="556" alt="screen shot 2018-07-26 at 12 43 15 pm" src="https://user-images.githubusercontent.com/1391101/43242097-844ffa80-90d1-11e8-8545-5c92ed9c38ed.png">

Check the properties in lib.

          yAxis: {
            $set: {
              left: {
                valueFormatter: '$ #',
                limitLines: [{
                  limit: 112.4,
                  lineColor: processColor('red'),
                  lineDashPhase: 2,
                  lineDashLengths: [10,20]
                }, {
                  limit: 89.47,
                  lineColor: processColor('red'),
                  lineDashPhase: 2,
                  lineDashLengths: [10,20]
                }]
              },
              right: {
                enabled: false
              },

            }
          }

**Comment by platonish** [comment]
@wuxudong the `lineDashLengths` property only works on iOS; it's simply a solid line on android. Please take a look at the [snippet](https://github.com/wuxudong/react-native-charts-wrapper/issues/186#issuecomment-406773398) I wrote above. I also tried with `[10, 20]` as values, still no luck.

**Comment by wuxudong** [comment]
<img width="585" alt="screen shot 2018-07-27 at 8 41 20 pm" src="https://user-images.githubusercontent.com/1391101/43321135-85fd9a1a-91dd-11e8-9d1e-6b2295825f55.png">

this is my android simulator. Check code in example->CandleStickChart in v0.4.4 branch
