### ISSUE TITLE
click event in barchart

### ISSUE THREAD

**Issue by danceyoung** [wuxudong/react-native-charts-wrapper#187]
without zoomming out the barchart,whether stopping highlight event when touching,only supporting tap event

**Comment by wuxudong** [comment]
I don't get your meaning? do you mean you need onSelect event, but disable highlight?

**Comment by danceyoung** [comment]
now it will trigger the event onSelect when touch the barchart.I expect it only triggers the event onSelect when single tap ,not touching

**Comment by wuxudong** [comment]
no such config...

**Comment by danceyoung** [comment]
I've been finding a teamporary solution to the problem in this topic
set barchart's highlightPerDragEnabled = false and zoom={{scaleX:1.1,scaleY:1.1,xValue:,yValue:,}}

do not trigger the onSelect event when touching drag,but trigger the onSelect event when single tapping a bar

**Comment by wuxudong** [comment]
It may be useful to expose highlightPerDragEnabled/highlightPerDragEnabled attributes.

**Comment by tsiory** [comment]
Hey @danceyoung ! where to put theses configs ? And what is the values for xValue and yValue. Thanks!
