### ISSUE TITLE
Bar Chart not showing

### ISSUE THREAD

**Issue by lanzosuarez** [wuxudong/react-native-charts-wrapper#188]
I just used the example code state in ZeroLineChart example, but it's not apperaing, same thing with the Barchart example

"react": "16.0.0-alpha.12",
 "react-native": "0.45",
 "react-native-charts-wrapper": "^0.4.1",

**Comment by wuxudong** [comment]
Any error log?

**Comment by lanzosuarez** [comment]
Its alright now. Thank you :)
