### ISSUE TITLE
valueFormatter is no effect in android, however iOS is ok

### ISSUE THREAD

**Issue by lenglengiOS** [wuxudong/react-native-charts-wrapper#19]

**Comment by lakeoffaith** [comment]
he forget the android

**Comment by lenglengiOS** [comment]
but I see Android has code for valueFormatter

**Comment by lenglengiOS** [comment]
http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns

thanks for wuxudong,This problem is solved, the valueFormatter i set is wrong
