### ISSUE TITLE
transparentCircle position

### ISSUE THREAD

**Issue by daxiangaikafei** [wuxudong/react-native-charts-wrapper#194]
Dear wuxudong:
        the piechart contain a transparentCircleRadius and transparentCircleColor propertity，can you tell me if the transparentCircle can show bellow the piechart rather than the front of the piechart
![image](https://user-images.githubusercontent.com/16950367/35607673-4946acb6-0690-11e8-9572-87143fba69b5.png)

**Comment by daxiangaikafei** [comment]
this is my code:
<PieChart
                    style={{ flex: 0.5, marginTop: 26, }}
                    styledCenterText={{ text: '12 合计', color: processColor('#666'), size: 20 }}
                    holeColor={processColor('#f5fbff')}
                    holeRadius={33}
                    centerTextRadiusPercent={40}
                    chartDescription={this.state.description}
                    data={this.state.data}
                    transparentCircleRadius={(width / 4) - 23}
                    // transparentCircleColor={processColor('#ff0000')}
                    // transparentCircleRadius={40}
                    transparentCircleColor={processColor('#ff0000')}
                    maxAngle={360}
                    entryLabelColor={processColor('#fff')}
                    entryLabelTextSize={13}
                    drawEntryLabels={true}
                    // rotationEnabled={false}
                    // rotationAngle={0}
                    legend={this.state.legend}
                    animation={{ durationX: 1000 }}
                />

**Comment by wuxudong** [comment]
I can't find relative settings in MpAndroidChart.
