### ISSUE TITLE
chart is not work with android

### ISSUE THREAD

**Issue by shashikantChetu** [wuxudong/react-native-charts-wrapper#197]
line chart ,bar chart anyone chart is  not working on android can you provide some suggestion which on is dependencies require and other thing.

**Comment by wuxudong** [comment]
Details are need.

**Comment by shashikantChetu** [comment]
I have install and integrate  react-native-charts-wrapper package to 3 times but front end show only blank space and show text 'selected entry ' and don't show any warning and error why it is not working .  i am only integrate your package and bar chart on my project  no integrate any other dependencies .

**Comment by wuxudong** [comment]
Run Examples first, then compare it with yours.

Check  log in chrome inspector.

**Comment by shashikantChetu** [comment]
I am not running on chrome to our project on PC I am running on mobile with make dev build.

**Comment by wuxudong** [comment]
open dev setting in mobile and turn on debug  then check log in browser?

**Comment by shashikantChetu** [comment]
Yaa sure I have found some Warning ...

Warning: Native component for "RNBarChart" does not exist
Warning: Native component for "RNHorizontalBarChart" does not exist
Warning: Native component for "RNBubbleChart" does not exist
Warning: Native component for "RNCandleStickChart" does not exist
Warning: Native component for "RNLineChart" does not exist
Warning: Native component for "RNPieChart" does not exist
Warning: Native component for "RNRadarChart" does not exist
Warning: Native component for "RNScatterChart" does not exist
Warning: Native component for "RNCombinedChart" does not exist

**Comment by wuxudong** [comment]
Check your MainApplication->getPackages, 
sometime other lib may overwrite this function.
