### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#2]
hi, thanks for your help that merging ios and and project.

I also get many swift 3.0 compile error by following setup staging, how about your setup environment, maybe I did something wrong.

thanks for your time.

PS: I notice Charts project remove previous swift 3.0 support branch and some inner maintainer fork the new repo [here](https://github.com/liuxuan30/Charts/tree/Swift-3.0), have you follow it in your test case?

**Comment by wuxudong** [comment]
Maybe you can create a new project, then follow this project's guide to test Example .
If there is errors, can you give me a screenshot or logs. 
thx.

What is previous swift 3.0 support? I am not quite sure, Do you mean your project is written in swift2?

**Comment by L-Jovi** [comment]
thanks for your reply, I notice the essential issue that you specify the react-native version >= 0.40 while I use 0.37 now.

my project depends many 3rd node modules over 40+, ..colleague will be mad if I decide to upgrade to latest react-native, maybe it's not a good way.

is any require prerequisite about your strict version limitation, if possible, would you mind support >=0.37?

if some breaking change remain painful effect, I'll consider other way maybe.

finally thanks for your smart project and patience.

**Comment by wuxudong** [comment]
I am not quite sure about that. Generally it doesn't matters, I will make some test, and remove restriction if everything works fine. 

or maybe you can update the version limitation locally, and test it.

**Comment by L-Jovi** [comment]
@wuxudong  thanks, I'll try it.
close this issue, it's not your project inner error.

**Comment by wuxudong** [comment]
@L-Jovi limitations are removed, check the latest version for new features.

**Comment by L-Jovi** [comment]
@wuxudong  thanks for your working :)
