### ISSUE TITLE
CocoaPods install ?

### ISSUE THREAD

**Issue by matpaul** [wuxudong/react-native-charts-wrapper#20]

**Comment by wuxudong** [comment]
I don't understand....

Do you mean package the iOS part to an CocoaPods component?

**Comment by matpaul** [comment]
Yep as option - for example react-native-vector-icons you can do it manually, use link or cocoa pods

**Comment by wuxudong** [comment]
I do agree.

The main problem is I am new to iOS, and I failed to compile it successfully.

the detail is [here](https://github.com/wuxudong/react-native-charts-wrapper#need-for-help)

that will be great if you can help.

**Comment by wuxudong** [comment]
cocoapods is introduced.
