### ISSUE TITLE
marker displaying content make me confused

### ISSUE THREAD

**Issue by jichangshuai** [wuxudong/react-native-charts-wrapper#200]
When the value is over 1000 such as 1000.11,that is , one thousand point eleven, but display made me confused and it just like 1.00011. is there something wrong, bro?

![772630176007256498](https://user-images.githubusercontent.com/20329081/35663761-de7f1628-0759-11e8-9a7d-28dcd8e9ed14.jpg)

**Comment by wuxudong** [comment]
You can use marker:"1000.11" in data to avoid auto formatting.

**Comment by jichangshuai** [comment]
Thank you, bro. got it.
