### ISSUE TITLE
axisMaximum Barchart Android

### ISSUE THREAD

**Issue by huybq95** [wuxudong/react-native-charts-wrapper#201]
Hi @wuxudong i have issue when using axisMaximum, it work on IOS but in Android if i set axisMaximum=20000 it will be show like this:

Android:
![image](https://user-images.githubusercontent.com/26105254/35665817-3c241116-075a-11e8-92dd-4fe46c719d75.png)

IOS: 
![image](https://user-images.githubusercontent.com/26105254/35665930-a35122c0-075a-11e8-8f5e-884672de9b61.png)

**Comment by wuxudong** [comment]
axisMaximum has nothing to do with the grid line.
you can introduce granularity to set the gap width between grid lines.
