### ISSUE TITLE
Cant not run in Xcode 9, because 9 not suppport Swift 2.x.

### ISSUE THREAD

**Issue by jaggerwang** [wuxudong/react-native-charts-wrapper#202]
It is need to install Xcode 8 to migrate code to Swift 3. Is there any plan to support Xcode 9 directly?

![image](https://user-images.githubusercontent.com/1255011/35721192-e125471c-082b-11e8-8de6-699e2e836797.png)

**Comment by wuxudong** [comment]
Just update your code to swift 3, you can do it manually without Xcode 8.x.

**Comment by jaggerwang** [comment]
The code is belong to npm package 'react-native-charts-wrapper', not mine. My question is can 'react-native-charts-wrapper' support Xcode 9 directly.

**Comment by wuxudong** [comment]
...... It do support Xcode 9. The lib is using swift 3,

I think the warning is generated because some of your code is using swift 2.

**Comment by jaggerwang** [comment]
The project can build and run in Xcode 9 before integrating "react-native-charts-wrapper", but got error when open the new xcworkspace after doing this. There is no swift code in the project self.

Here is the package.json file.
```
{
  "name": "gtgjdp",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean",
    "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build/ModuleCache/* && rm -rf node_modules/ && npm cache clean && npm i",
    "format": "standard",
    "format:fix": "standard --fix"
  },
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.0.0",
    "axios": "^0.16.2",
    "compare-versions": "^3.0.1",
    "geolib": "^2.0.22",
    "path": "^0.12.7",
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.3",
    "react-native-animatable": "^1.2.2",
    "react-native-charts-wrapper": "^0.4.1",
    "react-native-code-push": "^2.1.0-beta",
    "react-native-vector-icons": "^4.2.0",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.1",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.8.1",
    "redux-thunk": "^2.1.0",
    "url": "^0.11.0",
    "validate.js": "^0.11.1"
  },
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "standard": "^10.0.2"
  },
  "standard": {
    "ignore": [
      "android",
      "ios",
      "res"
    ],
    "parser": "babel-eslint",
    "globals": []
  }
}

```

**Comment by wuxudong** [comment]
Maybe check your project config.
I suggest that you can run examples first, if it works well, then compare it with yours.

**Comment by jaggerwang** [comment]
After re install and link, there is no complain, but still got compile error.
