### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by windydang26** [wuxudong/react-native-charts-wrapper#203]
@wuxudong can you add new attribute to config color for label and expand line of pie chart, and user can custom marker ?
Ex:
entryLabelColor: PropTypes.arrayOf(PropTypes.number), // current single color.
entryLineColor: PropTypes.arrayOf(PropTypes.number)
![screen shot 2018-02-05 at 8 55 28 am](https://user-images.githubusercontent.com/20814511/35785512-6848cda8-0a53-11e8-8070-4d1a72bf2811.png)
Thank!

**Comment by wuxudong** [comment]
Unfortunately,  MpAndroidChart doesn't support it.
