### ISSUE TITLE
Detect gesture when swipe pie chart ?

### ISSUE THREAD

**Issue by hihihahahehe** [wuxudong/react-native-charts-wrapper#205]
Hi @wuxudong , i got problem when using with react-native-scrollable-tab-view. How can i detect when swipe pie chart to disable change tab ?

**Comment by wuxudong** [comment]
Do you mean that you want to rotate pie chart, but app switch to another tab when you swipe?

**Comment by huybq95** [comment]
Yes, any solution for that ?

**Comment by hihihahahehe** [comment]
Yes, any solution for that ?

**Comment by wuxudong** [comment]
No...

**Comment by far1s** [comment]
You can pass `locked` prop to `ScrollableTabView`, which disables the swipe ability. Either you disable it completely when your chart is displayed or you do it when the chart is being dragged.
