### ISSUE TITLE
Spacing between xAxis and label

### ISSUE THREAD

**Issue by thuctl** [wuxudong/react-native-charts-wrapper#206]
I facing a problem when the label is close to xAxis. Have any attribute to resolve this, such as margin...?
thanks for the support!

![img](https://user-images.githubusercontent.com/29792418/35798039-324bd11e-0a94-11e8-9158-ad80328290b6.jpg)

**Comment by wuxudong** [comment]
there is 

    xEntrySpace: PropTypes.number,
    yEntrySpace: PropTypes.number,
    formToTextSpace: PropTypes.number,

in chart config. 

According to doc in MpAndroidChart, 

    /**
     * the space between the legend entries on a horizontal axis, default 6f
     */
    private float mXEntrySpace = 6f;

    /**
     * the space between the legend entries on a vertical axis, default 5f
     */
    private float mYEntrySpace = 0f;

    /**
     * the space between the legend entries on a vertical axis, default 2f
     * private float mYEntrySpace = 2f; /** the space between the form and the
     * actual label/text
     */
    private float mFormToTextSpace = 5f;

**Comment by thucld** [comment]
@wuxudong, I tried to use this, but no effect
`data: {
                dataSets: [{
                    values: dataTmp,
                    label: Constant.title_temperature,
                    config: {
                        lineWidth: 1,
                        drawCircles: false,
                        drawFilled: false,
                        drawLabels: false,
                        drawValues: false,
                        color: processColor('blue'),
                        fillColor: processColor('blue'),
                        xEntrySpace: 10,
                        yEntrySpace: 10,
                    }
                }],
},`

**Comment by thucld** [comment]
@wuxudong, I tried to use this, but no effect
data: {
       dataSets: [{
               values: dataTmp,
               label: Constant.title_temperature,
               config: {
                      lineWidth: 1,
                       drawCircles: false,
                      drawFilled: false,
                      drawLabels: false,
                      drawValues: false,
                      color: processColor('blue'),
                      fillColor: processColor('blue'),
                      xEntrySpace: 10,
                      yEntrySpace: 10,
               }
       }],
},
and use: <LineChart data={data} ... />

**Comment by thucld** [comment]
@wuxudong, I tried to use this, but no effect
```javascript
data: {
       dataSets: [{
               values: dataTmp,
               label: Constant.title_temperature,
               config: {
                      lineWidth: 1,
                       drawCircles: false,
                      drawFilled: false,
                      drawLabels: false,
                      drawValues: false,
                      color: processColor('blue'),
                      fillColor: processColor('blue'),
                      xEntrySpace: 10,
                      yEntrySpace: 10,
               }
       }],
},
```
and use: `<LineChart data={data} ... />`

**Comment by wuxudong** [comment]
These attributes is not for dataSets, they belongs to `legend`. 

Please check the source code for details.

**Comment by thucld** [comment]
yep, I also tried to follow this source but it did not work:
[https://github.com/mskec/react-native-mp-android-chart-example/blob/master/app/LineChartScreen.js](url)

**Comment by wuxudong** [comment]
this.state = {
      data: {},
      legend: {
        enabled: true,
        textColor: processColor('blue'),
        textSize: 12,
        position: 'BELOW_CHART_LEFT',
        form: 'SQUARE',
        formSize: 14,
        xEntrySpace: 10,
        yEntrySpace: 5,
        formToTextSpace: 5,
        wordWrapEnabled: true,
        maxSizePercent: 0.5,
        custom: {
          colors: [processColor('red'), processColor('blue'), processColor('green')],
          labels: ['Company X', 'Company Y', 'Company Dashed']
        }
      }
    }


![simulator screen shot - iphone 6 - 2018-02-07 at 23 41 36](https://user-images.githubusercontent.com/1391101/35925397-86e34ff4-0c60-11e8-92bd-41b638267466.png)



and         `formSize: 24`, notice the square is much bigger.

![simulator screen shot - iphone 6 - 2018-02-07 at 23 45 27](https://user-images.githubusercontent.com/1391101/35925577-0f6463ae-0c61-11e8-8755-e371127d8a2a.png)


and `yEntrySpace: 25`, the distance between lines is bigger.

![simulator screen shot - iphone 6 - 2018-02-07 at 23 47 02](https://user-images.githubusercontent.com/1391101/35925668-51f886aa-0c61-11e8-84dd-b678cc42f843.png)


and `formToTextSpace: 35`, legend text move to right.

![simulator screen shot - iphone 6 - 2018-02-07 at 23 48 38](https://user-images.githubusercontent.com/1391101/35925777-8babf7c4-0c61-11e8-9e15-e36bb91cf52a.png)


and I will dig a little deeper how to use xEntrySpace

**Comment by wuxudong** [comment]
I think you can set `wordWrapEnabled: false` to make them in one line first.

There is some problem about calculatedLabelBreakPoints in iOS. It seems initial frame is always 0,0 - 0,0

**Comment by wuxudong** [comment]
extraOffsets={{"bottom":100}} can do the work for you.

<img width="563" alt="screen shot 2018-07-26 at 3 14 45 pm" src="https://user-images.githubusercontent.com/1391101/43247246-b5101fdc-90e6-11e8-8c19-ec4552dbb12f.png">
