### ISSUE TITLE
rotationEnabled support

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#21]
thanks wuxudong, this issue is for coming soon feature.

> rotationEnabled should be added to pie and radar

**Comment by wuxudong** [comment]
@L-Jovi I publish a new version.  rotationEnabled is added.

because lack of java8 default implementation and swift protocol extension. the configure code is duplicated in pie and radar....

but at least, it works now

**Comment by L-Jovi** [comment]
thanks for your reply, I'll follow your latest release :)
