### ISSUE TITLE
How to avoid displaying the lable when the value is 0

### ISSUE THREAD

**Issue by ugendrang** [wuxudong/react-native-charts-wrapper#211]
[{"key":"01","value":0},{"key":"02","value":80},{"key":"03","value":30},{"key":"04","value":0},{"key":"05","value":0},{"key":"06","value":0},{"key":"07","value":0},{"key":"08","value":0},{"key":"09","value":0},{"key":"10","value":0},{"key":"11","value":0},{"key":"12","value":0},{"key":"13","value":0},{"key":"14","value":50}...]

**BarChart**: How to avoid displaying the lable in X-axis when the value is 0.0 or 0.
**LineChart**: How to start Y-axis from 0. Observed there is a space between X-axis and starting index of Y-axis.
**PieChart**: How to avoid displaying key and value label when the value is 0.0 or 0

![image](https://user-images.githubusercontent.com/20017649/35905963-eaebf37c-0c0e-11e8-9349-fb02ddaa77ce.png)

**Comment by wuxudong** [comment]
same to #174

**Comment by ugendrang** [comment]
Thank you @wuxudong.

[#174](https://github.com/wuxudong/react-native-charts-wrapper/issues/174) resolves barchart issue.

Can you please help me to resolve the issue in PieChart.
```
var data = [{"value":90,"label":"01"},{"value":80,"label":"02"},{"value":30,"label":"03"},{"value":0,"label":"04"},{"value":0,"label":"05"}...}]

let pieData = {
  legend: {
    enabled: false,
  },
  data: {
    dataSets: [{
      values: data,
      label: 'Pie dataset',
      config: {
        //colors: [processColor('#C0FF8C'), processColor('#FFF78C'), processColor('#FFD08C'), processColor('#8CEAFF'), processColor('#FF8C9D')],
        valueTextSize: 15,
        valueTextColor: processColor('green'),
        sliceSpace: 5,
        selectionShift: 15
      }
    }],
  },
  description: {
    text: '',
  },
};
```

**Comment by ugendrang** [comment]
I have updated values as shown below, (ie not included 0 values in the data[]) and it works perfect.

`var data = [{"value":90,"label":"01"},{"value":80,"label":"02"},{"value":30,"label":"03"},{"value":0,"label":"04"},{"value":0,"label":"05"}...}]`

to 

`var data = [{"value":90,"label":"01"},{"value":80,"label":"02"},{"value":30,"label":"03"}...}]`

**Comment by lucaingold** [comment]
Hey, how did you solved the linechart-issue with the filled space below 0 in y-axis? Thank you

**Comment by ugendrang** [comment]
No, i haven't resolved yet.  

@wuxudong  , can you please help us to resolve it?

**Comment by wuxudong** [comment]
@Summys why don't you set yAxis axisMinimum to 0.
