### ISSUE TITLE
How to keep the label in the same line?

### ISSUE THREAD

**Issue by jichangshuai** [wuxudong/react-native-charts-wrapper#213]
## **The first is i want, but when data value become larger, it ocupies two lines. How to set it to the same line, bro?**
![1111](https://user-images.githubusercontent.com/20329081/35910927-3a9dd43e-0c33-11e8-91eb-57dacba05968.jpg)

The following is the two-line case:
![2222](https://user-images.githubusercontent.com/20329081/35911169-0487bc7e-0c34-11e8-829f-608444186336.jpg)

**Comment by wuxudong** [comment]
Try bigger xEntrySpace, check #206

**Comment by jichangshuai** [comment]
I've tried #206, but it does not work yet, bro. Is there anything else to affect that?
The following code is my legend:
`legend: {
                                enabled: true,
                                textSize: 14,
                                form: 'SQUARE',
                                formSize: 14,
                                xEntrySpace: 10,
                                yEntrySpace: 5,
                                formToTextSpace: 5,
                                wordWrapEnabled: true,
                                maxSizePercent: 0.5
                            },`

**Comment by jichangshuai** [comment]
It works, bro. Thanks!
