### ISSUE TITLE
How to know which props can be given, the wiki link for MpAndroidChart isn't realy helpfull.

### ISSUE THREAD

**Issue by phantom1299** [wuxudong/react-native-charts-wrapper#214]
Hi there, first of all, great library!

I couldn't figure out how to customize the charts with props other than with those in the examples. I would realy help to create a documentation for this library if I would know how to get the info for that.

**Comment by wuxudong** [comment]
Just take a look at js code in lib.

There are ifaces describe everything.

    const legendIface = {
      enabled: PropTypes.bool,

      textColor: PropTypes.number,
      textSize: PropTypes.number,
      fontFamily: PropTypes.string,
      fontStyle: PropTypes.number,

      wordWrapEnabled: PropTypes.bool,
      maxSizePercent: PropTypes.number,

      position: PropTypes.string,
      form: PropTypes.string,
      formSize: PropTypes.number,
      xEntrySpace: PropTypes.number,
      yEntrySpace: PropTypes.number,
      formToTextSpace: PropTypes.number,

      custom: PropTypes.shape({
        colors: PropTypes.arrayOf(PropTypes.number),
        labels: PropTypes.arrayOf(PropTypes.string)
      })
    };

**Comment by phantom1299** [comment]
Oh, thanks. I didnt saw these. I know most of them are self explanatory but I think a documentation would be still usefull. It gives a better developer experience^^. I'll try to create a documentation with this, will let you know when I'm done :)
