### ISSUE TITLE
How set XAxis position and how hide XAxis line and grid line ?

### ISSUE THREAD

**Issue by NickWarrior** [wuxudong/react-native-charts-wrapper#216]

**Comment by danceyoung** [comment]
@NickWarrior refer [issues](https://github.com/wuxudong/react-native-charts-wrapper/issues/88)

**Comment by jichangshuai** [comment]
The following code can help you set XAis position 'bottom'
`xAxis: {
        valueFormatter: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
        granularityEnabled: true,
        granularity: 1,
        axisMaximum: 13,
        axisMinimum: 1,
        centerAxisLabels: true,
        position: 'BOTTOM'
    }`

**Comment by jichangshuai** [comment]
![background](https://user-images.githubusercontent.com/20329081/36087738-d29cf290-100e-11e8-8bcb-51a5d8a4a636.png)

Try to set  the property **drawGridBackground = false**
