### ISSUE TITLE
LineChart style

### ISSUE THREAD

**Issue by Deno028** [wuxudong/react-native-charts-wrapper#22]
1. How to config LeftAxis and Right Axis?
2. How to style text color for xAxis, LeftAxis, RightAxis and points value?

Thanks!

**Comment by wuxudong** [comment]
-  for bar and line chart.

        yAxis: PropTypes.shape({
         left: PropTypes.shape(yAxisIface),
         right: PropTypes.shape(yAxisIface)
        }),


- there is several color config. like

	export const axisIface = {
	  // what is drawn

	  // style
	  textColor: PropTypes.number,
	  textSize: PropTypes.number,

**Comment by Deno028** [comment]
Solved! Thank you so much!

**Comment by Deno028** [comment]
Hi @wuxudong  I got another questions. 

1. How to style for point value label on the chart?
2. How to set value for "Description Label" on LineChart?

As the image below : 

<img width="139" alt="screen shot 2017-03-23 at 15 15 05" src="https://cloud.githubusercontent.com/assets/4360556/24238238/30866096-0fdc-11e7-8805-9615f52f8c61.png">


Thanks!
