### ISSUE TITLE
How to disable Candlestick chart candle point detail  

### ISSUE THREAD

**Issue by ashanjayasundara** [wuxudong/react-native-charts-wrapper#221]
![image](https://user-images.githubusercontent.com/16848987/36674085-100e1808-1b2b-11e8-941f-2ab2791d7bf4.png)
how can i disable text values on the candle

**Comment by wuxudong** [comment]
I think [drawValues](https://github.com/wuxudong/react-native-charts-wrapper/blob/1be07048e730e70f67a9bc73299bacda0512b7f4/lib/ChartDataSetConfig.js#L13) is what you are looking for.
