### ISSUE TITLE
Candlestick graph data point not showing

### ISSUE THREAD

**Issue by ashanjayasundara** [wuxudong/react-native-charts-wrapper#222]
Candle does not drawing when  open and close prices are same 
![image](https://user-images.githubusercontent.com/16848987/36774107-b54ed14c-1c82-11e8-929f-8c3c6d068ef3.png)

**Comment by wuxudong** [comment]
The iOS works fine, but in android, it is just invisible. It seems there are some problem about default neutral color in MpAndroidChart.

As a workaround, you can set a custom neutral color to fix it . 
Just like 

	config: {
	            highlightColor: processColor('darkgray'),
	            shadowColor: processColor('black'),
	            shadowWidth: 1,
	            shadowColorSameAsCandle: true,
	            neutralColor: processColor('pink'),
	            increasingColor: processColor('#71BD6A'),
	            increasingPaintStyle: 'fill',
	            decreasingColor: processColor('#D14B5A')
	          },


then it works well.

<img width="564" alt="screen shot 2018-03-02 at 12 40 47 pm" src="https://user-images.githubusercontent.com/1391101/36883712-4145722e-1e17-11e8-8d94-9600c8acd775.png">

**Comment by Bhargav0528** [comment]
Can you share the code for Candle Stick Chart
