### ISSUE TITLE
How to Custom Marker And Get Rid of Column Values ?

### ISSUE THREAD

**Issue by HelenChenVIP** [wuxudong/react-native-charts-wrapper#227]
I would like to ask you:

1. How to modify the Marker display form, as shown in the figure, I want to show it in this form?

2. How to remove the display value of each column?
![y r jivtb49q pskoi lgm](https://user-images.githubusercontent.com/19185883/37077582-877af40a-2216-11e8-8b41-06487ad1f6c2.png)
Thanks All

**Comment by HelenChenVIP** [comment]
3.And the first column doesn't show???? 
@wuxudong

**Comment by wuxudong** [comment]
Check js under lib, most of the attributes are self-explained, and the wiki of MpAndroidChart if necessary.

**Comment by HelenChenVIP** [comment]
@wuxudong 
I'm sorry. I really didn't solve it.
I have checked the BarChart document, but I haven't tried to solve it.
![1520411819 1](https://user-images.githubusercontent.com/19185883/37081952-11c721e2-2226-11e8-9857-b0ac0f2b5cb2.jpg)
Can you give me some advice? thank you！

**Comment by wuxudong** [comment]
Check barData -> drawValues

**Comment by HelenChenVIP** [comment]
@wuxudong hello, I am so sorry! I can not find the correct attribute to solve the problem . Can you tell me exactly how to set it to get rid of the value above each post?
Thanks

**Comment by wuxudong** [comment]
in Example/app/GroupBarChartScreen.js, your can find `drawValues : false` in config

**Comment by HelenChenVIP** [comment]
Your method has been solved. Thank you very much.
