### ISSUE TITLE
(Android) RN 0.54 Exception "local reference table overflow (max=512)"

### ISSUE THREAD

**Issue by kyle-ssg** [wuxudong/react-native-charts-wrapper#229]
Getting the above error using React Native Version 0.54 when rendering over 512 points on a LineChart.

I can confirm that this does not happen on react-native 0.53.0

**Comment by wuxudong** [comment]
It is react-native related. 

It crash at `if (ReadableType.Map.equals(values.getType(index))) ` in LineDataExtract.createEntry

     @Override
        Entry createEntry(ReadableArray values, int index) {
            float x = index;

            Entry entry;
            if (ReadableType.Map.equals(values.getType(index))) {
                ReadableMap map = values.getMap(index);
                if (map.hasKey("x")) {
                    x = (float) map.getDouble("x");
                }
                entry = new Entry(x, (float) map.getDouble("y"), ConversionUtil.toMap(map));
            } else if (ReadableType.Number.equals(values.getType(index))) {
                entry = new Entry(x, (float) values.getDouble(index));
            } else {
                throw new IllegalArgumentException("Unexpected entry type: " + values.getType(index));
            }

            return entry;
        }


ReadableNativeArray.getType is totally different between 0.53.0  and 0.54.0 .

here is 0.53.0 , it only care the type at the index.

ReadableNativeArray.java
 
     public native ReadableType getType(int index);

ReadableNativeArray.cpp 

    local_ref<ReadableType> ReadableNativeArray::getType(jint index) {
      return ReadableType::getType(array_.at(index).type());
    }

ReadableType.cpp

    local_ref<ReadableType> ReadableType::getType(folly::dynamic::Type type) {
      switch (type) {
        case folly::dynamic::Type::NULLT: {
          static alias_ref<ReadableType> val = getTypeField("Null");
          return make_local(val);
        }
        case folly::dynamic::Type::BOOL: {
          static alias_ref<ReadableType> val = getTypeField("Boolean");
          return make_local(val);
        }
        case folly::dynamic::Type::DOUBLE:
        case folly::dynamic::Type::INT64: {
          static alias_ref<ReadableType> val = getTypeField("Number");
          return make_local(val);
        }
        case folly::dynamic::Type::STRING: {
          static alias_ref<ReadableType> val = getTypeField("String");
          return make_local(val);
        }
        case folly::dynamic::Type::OBJECT: {
          static alias_ref<ReadableType> val = getTypeField("Map");
          return make_local(val);
        }
        case folly::dynamic::Type::ARRAY: {
          static alias_ref<ReadableType> val = getTypeField("Array");
          return make_local(val);
        }
        default:
          throwNewJavaException(exceptions::gUnexpectedNativeTypeExceptionClass, "Unknown type");
      }
    }



but in 0.54.0

ReadableNativeArray.java

    @Override
    public ReadableType getType(int index) {
      if (mUseNativeAccessor) {
        jniPassCounter++;
        return getTypeNative(index);
      }
      return getLocalTypeArray()[index];
    }


    private ReadableType[] getLocalTypeArray() {
      // Fast, non-blocking check for the common case
      if (mLocalTypeArray != null) {
        return mLocalTypeArray;
      }
      synchronized (this) {
        // Make sure no concurrent call already updated
        if (mLocalTypeArray == null) {
          jniPassCounter++;
          Object[] tempArray = Assertions.assertNotNull(importTypeArray());
          mLocalTypeArray = Arrays.copyOf(tempArray, tempArray.length, ReadableType[].class);
        }
      }
      return mLocalTypeArray;
    }


ReadableNativeArray.cpp

	local_ref<JArrayClass<jobject>> ReadableNativeArray::importTypeArray() {
	  jint size = array_.size();
	  auto jarray = JArrayClass<jobject>::newArray(size);
	  for (jint i = 0; i < size; i++) {
	    jarray->setElement(i, ReadableNativeArray::getType(i).release());
	  }
	  return jarray;

It will get the type of every element then return the type at index, but it crash.....


I will post a issue there.

**Comment by zhangshenjie** [comment]
In my project. I use this code to avoid this crash.

`ReadableNativeArray.setUseNativeAccessor(true);`
`ReadableNativeMap.setUseNativeAccessor(true);`

**Comment by hugows** [comment]
@zhangshenjie I'm using RN 0.55.3 and adding those two lines to MainApplication.java's onCreate method makes the app crash when starting up. (instead of crashing when rendering the chart..)

**Comment by hugows** [comment]
Those lines stopped crashing the app when I also pasted this there:

`SoLoader.init(this, /* native exopackage */ false); // ???`

**Comment by yavorski** [comment]
`BubbleChart` crash application on Android with 512 points.
Only changed this line in examples `BubbleChartScreen.js` (line 48)

`values: this._randomYValues(20, size)` 
to this: 
`values: this._randomYValues(20, 512)`

**Comment by HsuWeiYu666** [comment]
Do I import something?
It say
cannot find symbol
    ReadableNativeMap.setUseNativeAccessor(true);
    ^

**Comment by JoseVf** [comment]
@HsuWeiYu666 Try to add
`import com.facebook.react.bridge.ReadableNativeArray;`
`import com.facebook.react.bridge.ReadableNativeMap;`
on top of your `MainApplication.java`

**Comment by ammoradi** [comment]
@wuxudong please update `installation_guide/README.MD` aacording to @JoseVf 's amendment.

**Comment by ashrystein** [comment]
react-native 0.63.4

import com.facebook.react.bridge.ReadableNativeArray;
import com.facebook.react.bridge.ReadableNativeMap;

cannot find symbol
ReadableNativeMap.setUseNativeAccessor(true);
                                  ^
Any help ?
