### ISSUE TITLE
LineChart 'highlightColor' property don't work in iOS?

### ISSUE THREAD

**Issue by Au12th0psav** [wuxudong/react-native-charts-wrapper#23]
I see the swift code 'highlightColor' is number, but you get it string in ChartDataSetConfigUtils.swift;
like: 
<img width="683" alt="error" src="https://cloud.githubusercontent.com/assets/10460843/24235114/a5064ab8-0fd6-11e7-8bbd-5af93896197e.png">
so i change it, work is ok.

And are you plan config LineChart LeftAxis and Right Axis? Thank you for your time.

**Comment by wuxudong** [comment]
- Thank you for this bug.

- LineChart support Left and right Axis. check

      yAxis: PropTypes.shape({
      left: PropTypes.shape(yAxisIface),
      right: PropTypes.shape(yAxisIface)
    }),

**Comment by Au12th0psav** [comment]
As you say, i config left and right Axis, but work so bad，LineChart dataSet 'axisDependency' always left type.
i suggest you add LineRadarChartDataSet left/right enum.
so
<img width="553" alt="error" src="https://cloud.githubusercontent.com/assets/10460843/24237606/f9fdfe34-0fe1-11e7-852e-2a50a1de374e.png">
you can set up the axisDependency in ChartDataSetConfigUtils.swift commonLineRadarConfig(...) method, and i try it:
<img width="385" alt="try" src="https://cloud.githubusercontent.com/assets/10460843/24237781/a34231c2-0fe2-11e7-8c1d-f0fc905ef354.png">
is ok，just a little advice. i hope you can try it.

**Comment by wuxudong** [comment]
I get what you mean.

	yAxis: PropTypes.shape({
	left: PropTypes.shape(yAxisIface),
	right: PropTypes.shape(yAxisIface)

is used to config how left and right yAxis looks like.


and your `axisDependency` is which axis this DataSet should be plotted against.  They are different attribute. and not supported at this moment. 

I will add this attribute in next version.

**Comment by Au12th0psav** [comment]
thanks

**Comment by wuxudong** [comment]
the new version is published.
