### ISSUE TITLE
How to remove the text on the top of the candle

### ISSUE THREAD

**Issue by quocson1** [wuxudong/react-native-charts-wrapper#232]
How to remove the text on the top of the candle

![candle](https://user-images.githubusercontent.com/29052846/37250744-779a5d7e-2535-11e8-97dd-059ecf57a81f.png)

**Comment by wuxudong** [comment]
drawValues

**Comment by quocson1** [comment]
how to drawValues it

**Comment by quocson1** [comment]
drawValues: PropTypes.bool,  do with it ,
