### ISSUE TITLE
PieDataSet method

### ISSUE THREAD

**Issue by 7449** [wuxudong/react-native-charts-wrapper#233]
pieDataSet.setValueLinePart1Length(0.2f);
        pieDataSet.setValueLinePart2Length(0.6f);
        pieDataSet.setXValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);
        pieDataSet.setYValuePosition(PieDataSet.ValuePosition.OUTSIDE_SLICE);

这几个方法在源码里面没有看见,是没有添加还是我没有找到？

**Comment by wuxudong** [comment]
They will be added in 0.4.4
