### ISSUE TITLE
xAxis axisMaximum should reach to a thousand value but only show 60 at a time.

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#234]
Hi @wuxudong . Is it possible for the line chart to possibly reach an axisMaximum of 1000 but only show 60 points at a time? I tried setting axisMaximum to 60 for a simple test, and my array has 120 elements. The last 60 records are not shown and I can't scroll to the rightmost part because it locks the graph at the axisMaximum. My array can reach thousands of values so it's not a good option to just set the axisMaximum to 1000+ because the lines would look really compressed.

**Comment by GermanMontejo** [comment]
something like this:
setVisibleXRangeMaximum

**Comment by GermanMontejo** [comment]
ahh there's visible range.

**Comment by GermanMontejo** [comment]
I tried doing this:

visibleRange: {
          $set: {
            x: {
              min: 0,
              max: 30
            }
          }
        }

the graph does not show any data. :(

**Comment by GermanMontejo** [comment]
The app freezes when I add visibleRange in my LineChart component.

**Comment by GermanMontejo** [comment]
hi @wuxudong . I've also tried the example app and modified the LineChart example to use:

<LineChart
            style={styles.chart}
            data={this.state.data}
            chartDescription={{text: ''}}
            legend={this.state.legend}
            marker={this.state.marker}
            xAxis={this.state.xAxis}
            drawGridBackground={false}
            borderColor={processColor('teal')}
            borderWidth={1}
            drawBorders={true}
            // visibleRange={{
            //   x: {
            //     min: 0,
            //     max: 30
            //   }
            // }
            // }
            touchEnabled={true}
            dragEnabled={true}
            scaleEnabled={true}
            scaleXEnabled={true}
            scaleYEnabled={true}
            pinchZoom={true}
            doubleTapToZoomEnabled={true}

            dragDecelerationEnabled={true}
            dragDecelerationFrictionCoef={0.99}

            keepPositionOnRotation={false}
            onSelect={this.handleSelect.bind(this)}
            onChange={(event) => console.log(event.nativeEvent)}
          />

Note I've commented visibleRange because the app hangs (freezes) if I don't comment it out.

**Comment by GermanMontejo** [comment]
hi @wuxudong I found this github issue from the mpandroidchart repository. I think it's related to what I'm encountering:

https://github.com/PhilJay/MPAndroidChart/issues/2506

**Comment by ionush** [comment]
@GermanMontejo did you find a fix for this issue?

**Comment by wuxudong** [comment]
@GermanMontejo , maybe Example->MovingWindowChartScreen is what you are looking for. 
It move the chart at a fixed speed.

**Comment by GermanMontejo** [comment]
hi @wuxudong It's okay. I've already implemented a working example of a moving LineChart :D.
It works so I won't touch it again :D.
