### ISSUE TITLE
Swift version does not support

### ISSUE THREAD

**Issue by wjh0309** [wuxudong/react-native-charts-wrapper#235]
When I import the ReactNativeCharts folder, the run shows that the swift version is not supported.
My version of Xcode is 9.2.

The error is as follows:
Showing Recent Errors Only The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

**Comment by rghorbani** [comment]
Update the swift build version to 3.0
In your project -> Build Settings -> search for swift

more information on how to automate this is available at [here](https://github.com/wuxudong/react-native-charts-wrapper#3-add-charts-and-swiftyjson)

**Comment by prashen** [comment]
I have updated to 3.3 but it's now showing swift compile error.
