### ISSUE TITLE
Reset linechart values

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#238]
How can I reset the line chart?
On a button press, I'd like all the plotted points on the line chart to disappear and when I pass a new dataset, it should render the new data.
But it doesn't work. even if I pass a new dataset, the point being plotted is still at 60 (this was the last plotted point on the line chart). It's like the new dataset is just being appended.

This is how I added a dataset to my linechart component:

`data={this.state.lineChartData}`

This is how I'm updating the dataset.
I tried removing the update() function but this doesn't work because it does not render the dataset on the line chart. I just noticed that the other graphs don't use it. I was thinking maybe it was reusing the existing state and just appending the new dataset we are passing. Please help me @wuxudong.
```
this.setState(
      update(this.state, {
        lineChartData: this.getLineChartData(dataset)
      })
    );
```

**Comment by Oraclesports** [comment]
you solved this?

**Comment by GermanMontejo** [comment]
Yes. I reset the linechartData and used a moveViewToX function.

**Comment by GermanMontejo** [comment]
Yeah, do change the state of the data by clearing the array that you're passing to it. Then call the chart's moveViewToX function and supply a zero value so thex-coordinate would move back to zero. Then update the state of the data by setting it with an array with the new values (x & y coordinates). Tell me if you don't understand this so I can show you a source code later.

**Comment by Oraclesports** [comment]
Ok fix the first part. Can I see the code on function moveViewToX? I have not really touched java yet. But I will if I have to

**Comment by Oraclesports** [comment]
Nvm. I got it already! Thanks :)

**Comment by wuxudong** [comment]
You can find a similar example in example->MovingWindowChartScreen
