### ISSUE TITLE
Listen onChange to change the zoom

### ISSUE THREAD

**Issue by huanglaoju** [wuxudong/react-native-charts-wrapper#243]
I have two charts. I monitor the onChange of the first chart to change the zoom of the second chart to avoid setState?

**Comment by wuxudong** [comment]
I don't get what you mean.
Can you explain in detail?

**Comment by huanglaoju** [comment]
在一个界面中我有两个K线图，当我滑动/放大/缩小第一个K线图的时候，怎样才能让第二个K线图流畅的滑动/放大/缩小？我有试过setState来改变第二个K线图的zoom,但这样太卡了。

**Comment by wuxudong** [comment]
Any solution?
