### ISSUE TITLE
Customizing values shown on the top of each column of a bar chart 

### ISSUE THREAD

**Issue by vRhythms** [wuxudong/react-native-charts-wrapper#244]
Is there a way to customize values shown on the top of each column of a bar or stacked bar chart? I know that these values can be shown/hidden with drawValues option. But I couldn't find a way to format them. 

As circled in the attached screen shot, I have 2 objectives
1. Format the number in thousands, millions etc. e.g. instead of 12500 show 12.5K
2. For stacked bar show the aggregate of all the stacks for that column. e.g. if I have 2 stacks of values 4400 and 1100, I would like to show 5.5K on the top of the column. 

Please let me know if this is possible.

![stackedbarchart](https://user-images.githubusercontent.com/38032141/38237481-f409a3ee-3744-11e8-9da8-d1a964233475.PNG)

**Comment by GermanMontejo** [comment]
Hi @vRhythms. I know how to do this in android but not in ios. 
If you want a quick fix I can help you.
You have to modify this function:
`public void refreshContent(Entry e, Highlight highlight) {`

in the **RNRectangleMarkerView.java** file. Inside that function block, there's a `text` variable that gets passed to `tvContent.setText(text);`. Do the formatting you want in that `text` variable.

**Comment by wuxudong** [comment]
1. Format the number in thousands, millions etc. e.g. instead of 12500 show 12.5K

You can try `valueFormatter: "largeValue"`

2. For stacked bar show the aggregate of all the stacks for that column. e.g. if I have 2 stacks of values 4400 and 1100, I would like to show 5.5K on the top of the column.

I can't find relative settings in MpAndroidChart, let me know if there is one.

**Comment by wuxudong** [comment]
I find there is a  StackedValueFormatter in MpAndroidChart. 

 StackedValueFormatter
     
     A formatter specifically for stacked BarChart that allows to specify whether the all stack values
     or just the top value should be drawn.
 

But it doesn't support formating the number in thousands, millions etc. e.g. instead of 12500 show 12.5K
