### ISSUE TITLE
Show only the last value on the top

### ISSUE THREAD

**Issue by GerardCasadevall** [wuxudong/react-native-charts-wrapper#245]
Hi,

Is it possible show only the last value on the top? Now show all values.

![captura](https://user-images.githubusercontent.com/13941090/38359968-aa798538-38c9-11e8-9476-0474157fc472.PNG)

How can I remove the description from PieChart (Description Label)? I've tried description={{ enabled: false }} but not working.

`componentDidMount() {
	this.setState(
		update(this.state, {
			data: {
				$set: {
					dataSets: [
						{
							values: [
								{ y: 80 },
								{ y: 75 },
								{ y: 15 },
								{ y: 30 },
								{ y: 45 },
								{ y: 55 },
								{ y: 60 },
								{ y: 55 },
								{ y: 65 },
								{ y: 30 },
								{ y: 15 },
								{ y: 17 },
								{ y: 19 },
								{ y: 25 },
								{ y: 22 },
								{ y: 27 },
								{ y: 23 },
								{ y: 25 },
								{ y: 35 },
								{ y: 42 },
								{ y: 45 },
								{ y: 47 },
								{ y: 55 },
								{ y: 65 },
								{ y: 75 },
								{ y: 85 },
								{ y: 80 }
							],
							label: '',
							config: {
								color: processColor('white'),
								drawFilled: false,
								fillColor: processColor('white'),
								textColor: processColor('white'),
								fillAlpha: 50,
								valueTextSize: 10,
								drawCircles: false,
								startAtZero: false,
								drawGridLines: false
							}
						}
					]
				}
			},
			xAxis: {
				$set: {
					valueFormatter: [
						'1',
						'2',
						'3',
						'4',
						'5',
						'6',
						'7',
						'8',
						'9',
						'10',
						'11',
						'12',
						'13',
						'14',
						'15',
						'16',
						'17',
						'18',
						'19',
						'20',
						'21',
						'22',
						'23',
						'24',
						'25',
						'26',
						'27',
						'28'
					],
					position: 'BOTTOM',
					drawGridLines: false,
					spaceBetweenLabels: 0,
					labelRotationAngle: -30.0,
					textColor: processColor('white'),
					axisLineColor: processColor('darkgray'),
					axisLineWidth: 1
				}
			},
			yAxis: {
				$set: {
					left: {
						drawGridLines: false,
						textColor: processColor('white'),
						axisLineColor: processColor('darkgray'),
						axisLineWidth: 1
					},
					right: {
						enabled: false
					}
				}
			}
		})
	);
}`

`                        <LineChart
                            style={{ flex: 1 }}
                            data={this.state.data}
                            xAxis={this.state.xAxis}
                            yAxis={this.state.yAxis}
                            drawGridBackground={false}
                            scaleEnabled={false}
                            legend={{ enabled: false }}
                            description={{ enabled: false }}
                        />`

regards,
Gerard.

**Comment by wuxudong** [comment]
I don't know how to only display the last value.

For the second question, rename description -> chartDescription.

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

I've rename the description for chartDescription but it still not working

`<LineChart
                            style={{ flex: 1, margin: 15 }}
                            data={this.state.data}
                            xAxis={this.state.xAxis}
                            yAxis={this.state.yAxis}
                            drawGridBackground={false}
                            scaleEnabled={false}
                            legend={{ enabled: false }}
                            chartDescription={{ enabled: false }}
                            marker={{
                                enabled: true,
                                markerColor: processColor('#66000000'),
                                textSize: 10
                            }}
                            highlights={this.state.highlights}
                        />`

**Comment by wuxudong** [comment]
It is a little bit to left because there is no enough spaces to be positioned at center, you can extend x axis max a little bit to put the marker at center.

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

The values of x axis is TimeSpan, It's possible put string (TimeSpan) in axisMaximum ? There is any other solution ? 

xAxis: {
	$set: {
		valueFormatter: [
			'09:30',
			'10:00',
			'10:30',
			'11:00',
			'11:30',
			'12:30',
			'13:00',
			'13:30',
			'14:00',
			'14:30',
			'15:00',
			'15:30',
			'16:00',
			'16:30',
			'17:00',
			'17:30',
			'18:00',
			'18:30',
			'19:00',
			'19:30',
			'20:00',
			'20:30',
			'21:00',
			'21:30',
			'22:00',
			'22:30',
			'23:00',
			'23:30'
		],
...

regards,
Gerard.

**Comment by wuxudong** [comment]
The TimeSpan is just the formatted value, the actual x value is still the number, so you can set  axisMaximum  to (data.length + n）.

I think the best solution is to change data valueFormatter to : 

	valueFormatter: PropTypes.oneOfType([
	  PropTypes.oneOf(['largeValue', 'percent', 'date']),
	  PropTypes.string,
	  PropTypes.arrayOf(PropTypes.string)
	]),

check #248 

This feature make sense, but I am a little busy recently. PR is welcome.

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

axisMaximum =  data.length + n, It works well , thx!

I have another doubt, I am trying to position the description of the graph in the top in the center:

`chartDescription={{
        text: 'Toque para gráfico avanzado',
        textColor: processColor('#FFF'),
        textSize: 10,
        positionX: 700,
        positionY: 50
}}`

positionX and positionY what number are it referring to? I not understand what position it refers to, if the size of the screen, the number of data of the graph... How can I put the description of the graph in the top in the center for all the screens?

![captura](https://user-images.githubusercontent.com/13941090/39134793-c335e204-4717-11e8-9829-1774e0f9c8a0.PNG)

regards,
Gerard.

**Comment by wuxudong** [comment]
That is the code in mpAndroidChart:

	protected void drawDescription(Canvas c) {

        // check if description should be drawn
        if (mDescription != null && mDescription.isEnabled()) {

            MPPointF position = mDescription.getPosition();

            mDescPaint.setTypeface(mDescription.getTypeface());
            mDescPaint.setTextSize(mDescription.getTextSize());
            mDescPaint.setColor(mDescription.getTextColor());
            mDescPaint.setTextAlign(mDescription.getTextAlign());

            float x, y;

            // if no position specified, draw on default position
            if (position == null) {
                x = getWidth() - mViewPortHandler.offsetRight() - mDescription.getXOffset();
                y = getHeight() - mViewPortHandler.offsetBottom() - mDescription.getYOffset();
            } else {
                x = position.x;
                y = position.y;
            }

            c.drawText(mDescription.getText(), x, y, mDescPaint);
        }
    }

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

I'm trying to position the description in the center of the screen but there is no way. I take the width of the screen and divide it by two, then I assign the value to positionX but it does not work:

var { height, width } = Dimensions.get('window');
this.setState({ xPositionDescription: width / 2 });

chartDescription={{
	text: 'Toque para gráfico avanzado',
	textColor: processColor('#FFF'),
	textSize: 10,
	positionX: this.state.xPositionDescription,
	positionY: 50
}}

![captura](https://user-images.githubusercontent.com/13941090/39365995-fe57dae0-4a32-11e8-9be8-2178f5d17340.PNG)

Any suggestions? The positionX refers to another measure?

regards,
Gerard.

**Comment by GerardCasadevall** [comment]
I've solved it! I used an <Text> in absolute position instead of the description of the graph.

**Comment by otikindriyana** [comment]
> I've hidden all values and I've put one highlight value (the last value). Can the marker be positioned on top of the last point? Right now, it's a bit to the left. Is it possible show the highlight value as the normal values?
> 
> ![captura](https://user-images.githubusercontent.com/13941090/38371199-21329972-38ec-11e8-9364-2325c83754df.PNG)
> 
> regards,
> Gerard.

how to hide all value and show last data bro?
