### ISSUE TITLE
How to set value for specific point of line chart

### ISSUE THREAD

**Issue by kenvandemar** [wuxudong/react-native-charts-wrapper#248]
I'm trying to set Max and Min value for my line chart like this but haven't found the solution. Please help!
<img width="441" alt="screen shot 2018-04-08 at 10 18 34 pm" src="https://user-images.githubusercontent.com/8335788/38469191-d9cd8a06-3b7a-11e8-891e-3ba4ed175267.png">

**Comment by wuxudong** [comment]
It is not supported yet.

but I think it is ok to implement it.

the valueFormatter in data is : 

    valueFormatter: PropTypes.oneOfType([
      PropTypes.oneOf(['largeValue', 'percent', 'date']),
      PropTypes.string
    ]),


and you can extend it to 

    valueFormatter: PropTypes.oneOfType([
      PropTypes.oneOf(['largeValue', 'percent', 'date']),
      PropTypes.string,
      PropTypes.arrayOf(PropTypes.string)
    ]),

PR is welcome

**Comment by wuxudong** [comment]
0.4.4 will support this feature.

**Comment by wuxudong** [comment]
valueFormatter: ["","min","","max"],
