### ISSUE TITLE
Gesture support

### ISSUE THREAD

**Issue by ozanorhan** [wuxudong/react-native-charts-wrapper#25]
Hi, 
Are planning to support more gesture callbacks like scale or doubletap?

**Comment by wuxudong** [comment]
scale is already supported. you can use two fingers to zoom in/out.

there is no plan to implement OnChartGestureListener because it is a little difficult to expose MotionEvent to js, it is too fundamental.

Can you describe in more detail what gestures you need most, and their usage?

**Comment by ozanorhan** [comment]
Imagine you have 2+ charts on a screen, when you zoom in on one of them i want to zoom other ones with them.

**Comment by MumblesNZ** [comment]
+1 for this feature, my use case is reload the data at a finer resolution when the user zooms in, and also load more historical data when the user pans left right.  For our purposes we can have 100,000's datapoints which is too heavy to query all at once.

**Comment by hbenkhay** [comment]
I have the same issue as well , I have to display more than 200,000 so I need to reload data after scrolling , I tried to concatenate multiple Chart using a simple scrollView , but I am not able to delete the margin between two charts , any suggestions please ?

**Comment by hbenkhay** [comment]
@ozanorhan , did you fix that , I am trying to do the same

**Comment by wuxudong** [comment]
@ozanorhan @hbenkhay 
try 0.4.0-alpha Examples->MultipleChartExample
A lot of new features are introduced.

**Comment by hugows** [comment]
@hbenkhay Did you ever manage to implement the "load more data on zoom" thing? I must do the same and have no idea..

**Comment by devonhuangcodes** [comment]
+1 for the "load more data on zoom" feature

**Comment by wuxudong** [comment]
you can check Example->StockExample.  In that example, it load more data when the user pans left right.

**Comment by devonhuangcodes** [comment]
For that example I see nativeEvent.action == 'chartTranslated'. Would the nativeEvent.action property also support zooming-in/zooming-out gestures for the charts? Is there like a nativeEvent.action == ‘chartZoomedIn’?
