### ISSUE TITLE
Marker and Line padding

### ISSUE THREAD

**Issue by kenvandemar** [wuxudong/react-native-charts-wrapper#250]
I do not know why the marker and line chart space is too close like this? How to make space between them?
<img width="79" alt="screen shot 2018-04-09 at 2 58 48 pm" src="https://user-images.githubusercontent.com/8335788/38486224-8f498e26-3c06-11e8-897e-17de5d255c97.png">

**Comment by wuxudong** [comment]
no config for it. But you can change the source code, or create a PR.

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.
