### ISSUE TITLE
yAxis Lines properties not working. 

### ISSUE THREAD

**Issue by mufaawan** [wuxudong/react-native-charts-wrapper#251]
I tried to hide these highlighted lines with these properties. 
       xAxis: {
          $set: {
            drawAxisLine: false,
            drawGridLines: false,
            position: 'BOTTOM',
          },
        },
        yAxis: {
          $set: {
            enabled: true,
            drawAxisLine: false,
            drawGridLines: false,
            position: 'LEFT',
            right: {
              enabled: false,
            },
          },
        },

output looks like this.
![bug_current](https://user-images.githubusercontent.com/17979287/38554798-632d282a-3cdd-11e8-8e08-7ee587971164.PNG)

I want output like this.

![bug_expected](https://user-images.githubusercontent.com/17979287/38554812-728e9b82-3cdd-11e8-8b89-e254cacebe66.png)

**Comment by viotti** [comment]
@mufaawan did you try setting left and right properties?

    yAxis: {
      $set: {
        left: {
          enabled: true,
          drawAxisLine: false,
          drawGridLines: false
        },
        right: {
          enabled: false
        }
      }
    }
