### ISSUE TITLE
ios build failed CompileSwift normal x86_64

### ISSUE THREAD

**Issue by nopedev** [wuxudong/react-native-charts-wrapper#252]
HI. thank you for great library.
Ios build failed  but have no clue at all what`s wrong.

### My environment
RN: 0.54.4
react-native-charts-wrapper: 0.4.3

in `podfile.lock`
Chart: 3.1.1
SwiftyJSON: 4.0.0

using xcode simulstor.
xcode Swift Language Version is `4.1`.
xcode version is `9.3`
iOS Deployment Target is `8.0`

### Error Message
```
** BUILD FAILED **


The following commands produced analyzer issues:

	Analyze Base/RCTModuleMethod.mm normal x86_64
(1 command with analyzer issues)

The following build commands failed:
	CompileSwift normal x86_64 /Users/batflip03/DEV/GIT/izib/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

```

Would you help me?

**Comment by wuxudong** [comment]
Simulator?

**Comment by nopedev** [comment]
@wuxudong  Yes, using xcode(9.3) Simulator. iOS Deployment Target is `8.0`

**Comment by nopedev** [comment]
It was resolved by adding 
```
#import "React/RCTFont.h"
```
to header.h file

**Comment by prateeksuraj** [comment]
CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/scatter/ScatterDataExtract.swift
	CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/scatter/RNScatterChartView.swift
	CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/radar/RNRadarChartManager.swift
	CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartViewBase.swift
	CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartView.swift
	CompileSwift normal x86_64 /Users/prateeksuraj/Documents/zunSolarApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/utils/BridgeUtils.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(7 failures)

Tried , but not able to solve. Any Help? xcode 9

**Comment by titancat** [comment]
@nopedev Where's the header.h file?

**Comment by angelos3lex** [comment]
@titancat its the bridging-header file. I face the following error after updating today during build:

```
The following build commands failed:
CompileSwift normal x86_64 /Users/username/myApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/pie/RNPieChartView.swift
CompileSwift normal x86_64 /Users/username/myApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/BalloonMarker.swift
CompileSwift normal x86_64 /Users/username/myApp/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
```

**Comment by titancat** [comment]
@angelos3lex Thanks

**Comment by Donhv** [comment]
The following build commands failed:
        CompileSwift normal x86_64 /Users/hoo/Desktop/traderapp-mobile/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift
        CompileSwift normal x86_64 /Users/hoo/Desktop/traderapp-mobile/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNBarLineChartBaseManager.swift
        CompileSwift normal x86_64 /Users/hoo/Desktop/traderapp-mobile/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/utils/ChartDataSetConfigUtils.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)
my error.
