### ISSUE TITLE
Spacing between yAxis and value label

### ISSUE THREAD

**Issue by RoarRain** [wuxudong/react-native-charts-wrapper#253]
How to change padding between yAxis and value label.
![test](https://user-images.githubusercontent.com/10494442/38593983-bac0f078-3d76-11e8-8d50-7d3cb96b26df.png)

thx!

**Comment by alexhuiculescu** [comment]
Add a value formatter for the y axes that transforms the values like this: (v) => v+"  "

**Comment by Taylor123** [comment]
@wuxudong  @alexhuiculescu is there any way to change style without using the valueFormatter string?

I'd like to have the Y axis labels to be overlayed on top of the graph so the graph can take up the entire width of the screen.

**Comment by thiennguyenminh1a** [comment]
> how to remove space from first value in pie chart
> 
> ![capture](https://user-images.githubusercontent.com/3347527/44997465-2c867a80-afcc-11e8-9584-9bfd03a27a4c.PNG)

Set the maxAngle props to 360, the default props on the example is 350 so is will have 10 spacing px.

**Comment by Boriow** [comment]
Any idea how to fix axis labels being clipped - 
![screen shot 2019-02-01 at 17 54 28](https://user-images.githubusercontent.com/18168502/52133690-80b08c00-264a-11e9-8412-4fd2f0c1066b.png)
![screen shot 2019-02-01 at 17 54 41](https://user-images.githubusercontent.com/18168502/52133695-83ab7c80-264a-11e9-821a-54558a6942b5.png)

**Comment by Abhipsha** [comment]
Set the maxAngle to 369 . The spacing will be removed

**Comment by Abhipsha** [comment]
Remove the maxAngle props by default it takes it as 360. The space will be removed

**Comment by alz10** [comment]
@RoarRain any solution to this?
