### ISSUE TITLE
The '\n' / breakLine int valueFormat of xAxis not working in android

### ISSUE THREAD

**Issue by mrcluc** [wuxudong/react-native-charts-wrapper#256]
Hello, have one StackBar on my application and the xAxis contains two texts separated
for breaking line. I used this: 

valueFormatter: data.days.map((value,index) => 
      value.substring(8,10)  + '\n'  + _renderMouth(parseInt(value.substring(5,7))) ),

In IOs the result is : 

01
Jan

In Android is:

01 Jan

How use breaking line correctly?

**Comment by wuxudong** [comment]
It seems MpAndroidChart doesn't support this. Check [this issue](https://github.com/PhilJay/MPAndroidChart/issues/1617)
