### ISSUE TITLE
Bar chart not working inside scrollview

### ISSUE THREAD

**Issue by rishiankush** [wuxudong/react-native-charts-wrapper#258]
I simply run the bar chart example(BarChartScreen.js) as provided. it was working fine
But when I placed this component in my other component that uses scrollview it did not work. It works only in a View because the width is fixed may be.

I want to run it inside a scrollview only. How can I implement this

**Comment by benjaminbillet** [comment]
Hi, 
I have the exact same problem, how did you manage to solve it?

**Comment by wublack** [comment]
@rishiankush hi,how did you solve it?

**Comment by youngcao2015** [comment]
@rishiankush hi,how did you solve it?

**Comment by wublack** [comment]
给一个固定高度

**Comment by jacruzca** [comment]
I solved it setting this in the ScrollView:

`contentContainerStyle={{flex: 1}}`

**Comment by Skillnter** [comment]
> I solved it setting this in the ScrollView:
> 
> `contentContainerStyle={{flex: 1}}`

not working.. any solution for this till now??

**Comment by viet97** [comment]
> I solved it setting this in the ScrollView:
> 
> `contentContainerStyle={{flex: 1}}`

it shouldnt work as expected. this style make all view show in 1 screen window and cannot scroll
