### ISSUE TITLE
Manipulate data of pie chart

### ISSUE THREAD

**Issue by aelallam** [wuxudong/react-native-charts-wrapper#259]
in `this.state` the data is set as: 
```
      data: {
        dataSets: [{
          values: [
            { value: 0, label: 'Healthy' },
            { value: 0, label: 'Unhealthy' }],
          label: '',
          config: {
            colors: [processColor('#00e500'), processColor('#ff3232')],
            valueTextSize: 18,
            valueTextColor: processColor('white'),
            sliceSpace: 2,
            selectionShift: 13
          }
        }],
      },
```

I would like to change the values by calling `this.setState` however what is the path to values?
I tried `this.setState({ data.dataSet[0].values: [ value:...]}) `but its does not work. Any suggestions?

**Comment by wuxudong** [comment]
...... I don't think your can work with react.

try Object.assign or es6 spread operator.
