### ISSUE TITLE
ios LineChart description设置无效

### ISSUE THREAD

**Issue by hzlgit** [wuxudong/react-native-charts-wrapper#26]

**Comment by wuxudong** [comment]
description is reserved for iOS, use chartDescription instead.

**Comment by Thyiad** [comment]
not only ios, in source code it defined as  chartDescription:

text: PropTypes.string,
  textColor: PropTypes.number,
  textSize: PropTypes.number,

  positionX: PropTypes.number,
  positionY: PropTypes.number,

  fontFamily: PropTypes.string,
  fontStyle: PropTypes.number

**Comment by lequangtuananh** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md#chartbase-props-plus-props-listed-below
