### ISSUE TITLE
Issues on Radar Charts

### ISSUE THREAD

**Issue by Nexengineer** [wuxudong/react-native-charts-wrapper#261]
Hi, 

I have few issues 
1) First I am not able to change X-axis and Y-axis width and color.
2) when Ever the Text on X-axis label is big Radar Chart shrinks and there is lot of padding around text.
Please help me on this.
Warm Regards

**Comment by wuxudong** [comment]
any pic?

**Comment by Nexengineer** [comment]
Hi,
Image 1
<img width="521" alt="with large text" src="https://user-images.githubusercontent.com/16309506/39062611-b65774b4-44e5-11e8-8318-a3e1290ee67b.png">
<img width="525" alt="with small text" src="https://user-images.githubusercontent.com/16309506/39062613-b71d08d2-44e5-11e8-9f50-248bcfaf9c75.png">

 is with small text and Image 2 is with big text

**Comment by wuxudong** [comment]
Sorry, I don't know at this moment. I will make a try later.

**Comment by podvipodvert** [comment]
@Nexengineer have you find a solution in style axis and web axis?

**Comment by Nexengineer** [comment]
well i Used D3charts instead of this library

**Comment by wuxudong** [comment]
Add some new settings of radar chart in 0.4.4, like 

    webLineWidth: PropTypes.number,
    webLineWidthInner: PropTypes.number,
    webAlpha: PropTypes.number,
    webColor: PropTypes.number,
    webColorInner: PropTypes.number,

but it seems there are no settings about padding.

**Comment by mMarcos208** [comment]
@Nexengineer do you solved this issue?

I have the same issue.

**Comment by jasonwr** [comment]
@wuxudong this isn't resolved. Should be a fairly easy fix. Is this project being maintained? I don't have bandwidth right now to work on this but might in a month.

**Comment by LaGregance** [comment]
I have the same issue, any solution ?
