### ISSUE TITLE
能否绘制间断的折线图？Can I render an  incontinuity linechart with this plugin?

### ISSUE THREAD

**Issue by SDLapp** [wuxudong/react-native-charts-wrapper#262]
能否绘制间断的折线图？Can I render an  incontinuity linechart with this plugin?

**Comment by wuxudong** [comment]
Check these properties in line data:

     dashedLine: PropTypes.shape({
        lineLength: PropTypes.number.isRequired,
        spaceLength: PropTypes.number.isRequired,
        phase: PropTypes.number,
      })
