### ISSUE TITLE
how to add colorGradient in line chart above limitLine

### ISSUE THREAD

**Issue by MohithHasan** [wuxudong/react-native-charts-wrapper#264]
![ss](https://user-images.githubusercontent.com/34531234/38984220-ee9122d4-43e7-11e8-985b-0a87a5f3a5de.PNG)

**Comment by wuxudong** [comment]
I am afraid it is not supported by mpAndroidChart & Charts.
You can check this feature there, let me know the result.

**Comment by wuxudong** [comment]
Reopen it if necessary.
