### ISSUE TITLE
Change Font color and Size

### ISSUE THREAD

**Issue by burhanahmed92** [wuxudong/react-native-charts-wrapper#266]
![screenshot_61](https://user-images.githubusercontent.com/1272261/38976967-4cb8faba-43cc-11e8-93ee-36545b32b05b.png)

I want to change font size and color of a pointed text in above image.

I tried like
 
fontSize:30,
textSize: 30

But not working

**Comment by wuxudong** [comment]
![simulator screen shot - iphone x - 2018-04-21 at 00 11 37](https://user-images.githubusercontent.com/1391101/39062025-d1a45fb2-44f8-11e8-876f-ede99373af29.png)


    this.state = {
      legend: {
        enabled: true,
        textSize: 14,
        form: 'SQUARE',
        formSize: 14,
        xEntrySpace: 10,
        yEntrySpace: 5,
        formToTextSpace: 5,
        wordWrapEnabled: true,
        maxSizePercent: 0.5
      },
      data: {
        dataSets: [{
          values: [{y: 100}, {y: 105}, {y: 102}, {y: 110}, {y: 114}, {y: 109}, {y: 105}, {y: 99}, {y: 95}],
          label: 'Bar dataSet',
          config: {
            color: processColor('teal'),
            barSpacePercent: 40,
            barShadowColor: processColor('lightgrey'),
            highlightAlpha: 90,
            highlightColor: processColor('red'),
            valueTextSize: 20,
            valueTextColor: processColor('red')
          }
        }],
      },
      highlights: [{x: 3}, {x: 6}],
      xAxis: {
        valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        granularityEnabled: true,
        granularity : 1,
        textSize: 30,
        textColor: processColor('green'),

      }
    };

Please check the properties under lib/ before making an issue

**Comment by ikimpau** [comment]
hi, is changing text color for yAxis possible? because I can't change it.

**Comment by christopher-18** [comment]
@wuxudong  Is there any way to set different colors to the highlighted text present in the screenshot?
