### ISSUE TITLE
How to adjust LimitLine label position 

### ISSUE THREAD

**Issue by MohithHasan** [wuxudong/react-native-charts-wrapper#268]
=======Expected Ouput:========

![ss](https://user-images.githubusercontent.com/34531234/38985226-9b9fcd5c-43ea-11e8-8c16-7c21b5e38b1b.PNG)

=======My output:========

![screen shot 2018-04-19 at 4 33 35 pm](https://user-images.githubusercontent.com/34531234/38986724-11bbd5a4-43ef-11e8-8a0e-abf56f42b132.png)

**Comment by MohithHasan** [comment]
my output:
![screen shot 2018-04-19 at 4 03 57 pm](https://user-images.githubusercontent.com/34531234/38985351-ee62047e-43ea-11e8-84ca-9feb13c49543.png)

**Comment by wuxudong** [comment]
All limitLine related properties are listed here:

     limitLines: PropTypes.arrayOf(
      PropTypes.shape({
        limit: PropTypes.number.isRequired,
        label: PropTypes.string,
        lineColor: PropTypes.number,
        lineWidth: PropTypes.number,
        valueTextColor: PropTypes.number,
        valueFont: PropTypes.number,
        labelPosition: PropTypes.string, // RIGHT_BOTTOM,  LEFT_BOTTOM, RIGHT_TOP,  LEFT_TOP 
        lineDashPhase: PropTypes.number,
        lineDashLengths: PropTypes.arrayOf(PropTypes.number)
      })
    ),
    drawLimitLinesBehindData: PropTypes.bool,

**Comment by MohithHasan** [comment]
Sir , i want that '53' aligned with yAxis value markers. using labelPosition:LEFT_BOTTOM is not helping me.Can you help me?? please....

**Comment by alexhuiculescu** [comment]
Doesn't seem possible only using the props.
As a hard way, you could show de limit line without the label, and compute the position of the label yourself, then draw it

**Comment by wuxudong** [comment]
Reopen it if necessary.

**Comment by trung1008** [comment]
i want this

**Comment by DhavalKakadiya** [comment]
I also want this.

**Comment by rezareact** [comment]
> I also want this.
