### ISSUE TITLE
Error whhile updating property 'data' of a view managed by:RNLineChart

### ISSUE THREAD

**Issue by HelenChenVIP** [wuxudong/react-native-charts-wrapper#269]
I met a problem: I get in the interface to the data updated after the line chart, always get wrong, I'm componentWillReceiveProps (nextProps) {} in the logic of processing. From the results error is the data value is null when the print but I see componentWillReceiveProps of valueFormatter are numerical values. Thank you very much for your help.
`//import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet,processColor,Dimensions,TouchableOpacity } from 'react-native';
import {LineChart} from 'react-native-charts-wrapper';
import update from 'immutability-helper';
import { createAction,ShowToast,NavigationActions} from '../../utils'; 
import { connect } from 'react-redux';
const SCREEN_WIDTH=Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;
/**
 * 站点详情 图表
 * Helenchen
 * @class PointDetailsChart
 * @extends {Component}
 */
@connect(({app})=>({zxData:app.zxData}))
class PointDetailsChart extends Component {
    constructor() {
        super();
        this.state = {
          data: {},
          xAxis:{},
          yAxis:{}
        };
      }
   
    componentWillReceiveProps(nextProps) {
     
      if (nextProps.zxData !== this.props.zxData) {
        let values=[];
        let valueFormatter=[];
        let axisMaximum=nextProps.zxData.length;
        nextProps.zxData.map((item,key)=>{
        values.push({y:item.YValue});
        valueFormatter.push(item.XValue);
        })
        debugger;
        this.setState(
          update(this.state, {
            data: {
              $set: {
                dataSets: [{
                  'values': values,
                  label: 'LineChart',
                  config: {
                    lineWidth: 0.5,
                    drawCircles: false,
                    highlightColor: processColor('red'),
                    color: processColor('red'),
                    drawFilled: true,
                    fillColor: processColor('red'),
                    fillAlpha: 60,
                    valueTextSize: 15,
                    valueFormatter: "##.000",
                  }
                }],
              }
            },
            xAxis: {
              $set: {
                fontFamily:"HelveticaNeue-Medium",
                fontWeight:"bold",
                fontStyle:"italic",
                'valueFormatter': valueFormatter,
                position: 'BOTTOM' ,
                drawGridLines: false
              }
            },
            yAxis: {
              $set: {
                left: {
                  drawLabels: true,
                  drawAxisLine: true,
                  drawGridLines: false,
                  drawValueAboveBar:false,
                  zeroLine: {
                    enabled: true,
                    lineWidth: 1
                  }
                },
                right: {
                  enabled: false
                }
              }
            },
          })
        );   
      }
    }
    handleSelect(event) {
      let entry = event.nativeEvent
      if (entry == null) {
        this.setState({...this.state, selectedEntry: null})
      } else {
        this.setState({...this.state, selectedEntry: JSON.stringify(entry)})
      }
  
      console.log(event.nativeEvent)
    }
    render() {
        let dgimn=this.props.pointDetailsShow.dgimn;
        return (
          <View style={{width:SCREEN_WIDTH,height:SCREEN_HEIGHT/2}}>
            <LineChart
            style={{width:SCREEN_WIDTH,height:SCREEN_HEIGHT/4}}
            data={this.state.data}
            chartDescription={{text: ''}}
            legend={this.state.legend}
            marker={this.state.marker}
            xAxis={this.state.xAxis}
            drawGridBackground={false}
            borderColor={processColor('teal')}
            borderWidth={1}
            drawBorders={true}
            touchEnabled={true}
            dragEnabled={true}
            scaleEnabled={true}
            scaleXEnabled={true}
            scaleYEnabled={true}
            pinchZoom={true}
            doubleTapToZoomEnabled={true}
            dragDecelerationEnabled={true}
            dragDecelerationFrictionCoef={0.99}
            keepPositionOnRotation={false}
            onSelect={this.handleSelect.bind(this)}
            onChange={(event) => console.log(event.nativeEvent)}
          />
         
          </View>
        );
    }
}

// define your styles
const styles = StyleSheet.create({
   
});

//make this component available to the app
export default PointDetailsChart;
`
![3](https://user-images.githubusercontent.com/19185883/39029650-7f382312-448f-11e8-9340-29fe119b47f1.jpg)
@wuxudong

**Comment by HelenChenVIP** [comment]
This problem is sometimes encountered sometimes, do not know the problem is where?

**Comment by wuxudong** [comment]
I have no idea, but I suggest to check your data,.

**Comment by HelenChenVIP** [comment]
You are right, My data have a null data, so......
