### ISSUE TITLE
android "error while updating property 'data' of view managed by: RNLineChart"

### ISSUE THREAD

**Issue by hzlgit** [wuxudong/react-native-charts-wrapper#27]
rn version "0.41.2"

**Comment by wuxudong** [comment]
more details required.

**Comment by hzlgit** [comment]
![wechatimg3](https://cloud.githubusercontent.com/assets/20529057/24540829/7517c8c0-1627-11e7-9933-3de7d262184c.jpeg)

**Comment by wuxudong** [comment]
...... I mean your config, your code, and your analysis

**Comment by hzlgit** [comment]
和demo一模一样，ios运行正常

**Comment by wuxudong** [comment]
Can you run the demo successfully?

**Comment by wuxudong** [comment]
reopen it if you still have problem

**Comment by abcde1499** [comment]
Same here.
![screenshot_1491815513](https://cloud.githubusercontent.com/assets/3325816/24890075/522870ae-1ea0-11e7-8c04-a3da77bf2c9d.png)

And I've tried the Example project on android it's also failed
![screenshot_1491877146](https://cloud.githubusercontent.com/assets/3325816/24890086/6642d6d8-1ea0-11e7-99a6-b2529270929e.png)

**Comment by wuxudong** [comment]
any error log in chrome debug window?

**Comment by HasanElfalt** [comment]
No error log in chrome debug window @wuxudong

**Comment by HasanElfalt** [comment]
In my case the problem was with `fillGradient` at config when I remove it works on my android emulator
