### ISSUE TITLE
Error unresolved identifier RCTFont

### ISSUE THREAD

**Issue by juniorneo2** [wuxudong/react-native-charts-wrapper#272]
Hi, I updated the version to 3.1.1 and stopped working, can anyone help me? These 3 errors are occurring

$ app / node_modules / react-native-charts-wrapper / ios / ReactNativeCharts / RNChartViewBase.swift: 256: 30: Use of unresolved identifier 'RCTFont'

$ app / node_modules / react-native-charts-wrapper / ios / ReactNativeCharts / RNChartViewBase.swift: 260: 30: Use of unresolved identifier 'RCTFont'

$ app / react-native-charts-wrapper / ios / ReactNativeCharts / RNChartViewBase.swift: 264:30: Use of unresolved identifier 'RCTFont'

[Link Image](https://drive.google.com/file/d/1EDC6USGNfg4jzMySd3F1sTjFuDTqMyTU/view?usp=sharing)

Thank you!

**Comment by wuxudong** [comment]
When you add the files XCode should prompt you to create a bridging header if you haven't done so already, or you can create empty swift file to trigger xcode prompt. Create the bridging header and import the RCTViewManager.h. It should look something like this.

	#import "React/RCTBridge.h"
	#import "React/RCTViewManager.h"
	#import "React/RCTUIManager.h"
	#import "React/UIView+React.h"
	#import "React/RCTBridgeModule.h"
	#import "React/RCTEventDispatcher.h"
	#import "React/RCTEventEmitter.h"
	#import "React/RCTFont.h"

**Comment by juniorneo2** [comment]
Thank you! Now this error has occurred and I have no idea what it is (Ambiguos resolution)

[Link Image
](https://drive.google.com/file/d/1xJN8J_9A4ZFVjkymAbAs2B8M1a15tkAM/view?usp=sharing)

**Comment by wuxudong** [comment]
I have no idea, but you can make a try to start from a new project, then copy the existing source files.

**Comment by juniorneo2** [comment]
I'll try, thank you, the stranger who only upgraded the library, react native is very good but some very strange errors occur

**Comment by KevinOfNeu** [comment]
```
#ifndef XXX_Bridging_Header_h
#define XXX_Bridging_Header_h
#import "React/RCTBridge.h"
#import "React/RCTViewManager.h"
#import "React/RCTUIManager.h"
#import "React/UIView+React.h"
#import "React/RCTBridgeModule.h"
#import "React/RCTEventDispatcher.h"
#import "React/RCTEventEmitter.h"
#import "React/RctFont.h"

#endif /* XXX_Bridging_Header_h */
```

@juniorneo2

**Comment by juniorneo2** [comment]
@KevinOfNeu the same error occurred again.

[Link](https://drive.google.com/file/d/1dMokBL0HoioCHaFVaySx6aJ3_1CLyNOI/view?usp=sharing)

**Comment by KevinOfNeu** [comment]
@juniorneo2  this error is nothing about the issue title 'Error unresolved identifier RCTFont #272
', there is something else wrong, read the error log carefully

**Comment by juniorneo2** [comment]
@KevinOfNeu and @wuxudong it worked, I had to create a new project and set it all up again, thanks and sorry, can close the topic

**Comment by KevinOfNeu** [comment]
@juniorneo2 congratulations

**Comment by GodVampire** [comment]
when I repetition this problem.
because of I read this [guide](https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6)
missing  #import "React/RctFont.h"
So you can fix it, so as not to let others have the same error   @wuxudong   
Thanks to the open source

**Comment by leo-tavares** [comment]
hello @juniorneo2  https://github.com/wuxudong/react-native-charts-wrapper/issues/272#issuecomment-383794455
try add this in your podfile 

` pod 'React', :path => '../node_modules/react-native' `
` pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga' `

and then do 
> cd ios
> rm -rf Pods
> pod install

**Comment by chudaotrucnhan** [comment]
In my case, downgrade to react-native-chart-wrapper version 0.4.3

**Comment by jonmnoj** [comment]
I have been having this issue with react native 0.61.1, I am using firebase so cannot enable use_frameworks so have opted for the manual setup with SwiftyJSON and Charts install via cocoapod.
I have the bridging header setup as [wuxudong](https://github.com/wuxudong/react-native-charts-wrapper/issues/272#issuecomment-383793155) has listed but it just will not find the RCTFont file it appears.
I've tried reinstalling the pod, node modules and clearing the build folder all to no effect.

**Comment by wuxudong** [comment]
@jonmnoj 

I found it is a silly bug. I forgot to add `#import "React/RCTFont.h"` in RNCharts-Bridging-Header.h

I publish a new version and update installation_tutorial, now it can be used as a static lib without `use_frameworks!`.

Give it a try.

**Comment by jonmnoj** [comment]
@wuxudong 

That was it, thanks for your help. 
I had never really noticed the RNCharts bridging header in among the other files so never thought to check it, always assumed I must have done something wrong with linking my app's bridging header.

**Comment by wuxudong** [comment]
If you install this lib manually, you are supposed to add your own bridge file, and the original RNCharts-Bridging-Header.h will be ignored.

```
Add Bridge File
When you add the files XCode should prompt you to create a bridging header if you haven't done so already, or you can create empty swift file to trigger xcode prompt. Create the bridging header and import the RCTViewManager.h. It should look something like this.

 #import "React/RCTBridge.h"
 #import "React/RCTViewManager.h"
 #import "React/RCTUIManager.h"
 #import "React/UIView+React.h"
 #import "React/RCTBridgeModule.h"
 #import "React/RCTEventDispatcher.h"
 #import "React/RCTEventEmitter.h"
 #import "React/RCTFont.h"


```

**Comment by jonmnoj** [comment]
Ah I see, I am still quite new to the iOS side of things. It may have been something else then?

As I have had my own App-Bridging-Header.h file in the RNCharts directory with the setup as you have listed previously when it was giving me this error message so I thought that change you made with 0.5.7 to the RNCharts-Bridging-Header.h fixed it, though when creating my own xcode did not bring the popup asking me if I wanted to create a bridging header file I just had to specify the filename with the .h extension in the filename input to create it.

Either way it works anyway so I'm happy, thanks again.
