### ISSUE TITLE
Cannot build in IOS

### ISSUE THREAD

**Issue by HouLinguo** [wuxudong/react-native-charts-wrapper#273]
Xcode 9.3 
swift 3.3
Chart 3.0.3
The code is as follows ：
override open static func requiresMainQueueSetup()->Bool{
  return true
}
it has a error:
Method does not override any method from its superclass

I dont know how to solve the problem.Thanks

**Comment by wuxudong** [comment]
upgrade rn version

**Comment by HouLinguo** [comment]
rn version:0.42.3
I delete the word “override ” then build success。
but have a new problem dyld: Library not loaded .......... Reason: image not fonud

**Comment by HouLinguo** [comment]
1. Drag the pods.xcodeproj in Libraries Folder
2. General -> Embedded Binaries -> Remove the Chart framework 
3. General -> Embedded Binaries + --> ChartFramework.
4. General -> LinkedFrameworks -> Add ChartFrameWork  
5. Build Phase--> Click on + --> Copy File 'Destination' select FrameWork->Add Chart.FrameWork in it.
6. Clean & Build.
