### ISSUE TITLE
How to set barSpace in HorizontalBarChart

### ISSUE THREAD

**Issue by HouLinguo** [wuxudong/react-native-charts-wrapper#275]
I want to align text and charts.

Code:
```js
bardata: {
	dataSets: [{
		values: [4, 3, 5, 2, 10],
		label: '',
		config: {
			drawValues: false,
			colors: common.deepCopy(this.proColors).reverse(),
		}
	}],
	config: {
		barWidth: 0.7,
	}
},
<HorizontalBarChart
	style={styles.chart}
	data={this.state.bardata}
	xAxis={this.state.xAxis}
	yAxis={this.state.yAxis}
	chartDescription={{ text: '' }}
	legend={{ enabled: false }}
/>
```

![570365ce3a4fe48f335eb30e4e409cb](https://user-images.githubusercontent.com/22906873/39391311-dacf1c18-4ad3-11e8-8af0-d3ec981afb4f.png)
thx!

**Comment by wuxudong** [comment]
I can't reproduce your problem in Example project.

But I think  `granularityEnabled`  `granularity`  can help.


      xAxis: {
        valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        position: 'BOTTOM',
        granularityEnabled: true,
        granularity: 1,
        labelCount: 10,
      },

Reopen it if necessary.
