### ISSUE TITLE
Line chart performance issue on iOS

### ISSUE THREAD

**Issue by ddavydov** [wuxudong/react-native-charts-wrapper#277]
I have a line chart with ~10000 points with timestamps on xAxis and yAxis values from 0 to 5000. Rendering of the chart and zoom in/out on real device is pretty slow.

![iphone 6 - 11 3 2018-05-01 15-43-02](https://user-images.githubusercontent.com/511782/39473224-68e313f4-4d56-11e8-97b4-02cf9013eecc.png)

Here is configuration that I use

```
<LineChart
        style={styles.chart}
        data={{
          dataSets: [{
            values: this.props.data,
            label: '',
            config: {
              lineWidth: 1,
              drawValues: true,
              drawCircles: false,
              highlightColor: processColor('blue'),
              color: processColor('blue'),
              drawFilled: true,
              fillColor: processColor('blue'),
              fillAlpha: 60,
              highlightEnabled: false
            }
          }]
        }}
        chartDescription={{ text: '' }}
        legend={{ enabled: false }}
        marker={{ enabled: false }}
        drawGridBackground={false}

        borderWidth={0}
        drawBorders={false}

        touchEnabled
        dragEnabled
        scaleEnabled
        scaleXEnabled
        scaleYEnabled
        pinchZoom={false}
        doubleTapToZoomEnabled={false}
        dragDecelerationEnabled
        autoScaleMinMaxEnabled
        dragDecelerationFrictionCoef={0.99}
        yAxis={{
          left: {
            axisMaximum: 5000,
            axisMinimum: 0,
            granularity: 50,
            granularityEnabled: true,
            textColor: processColor('white')
          },
          right: {
            enabled: false
          }
        }}

        keepPositionOnRotation={false}

        xAxis={{
          textColor: processColor('white'),
          position: 'BOTTOM',
          granularityEnabled: true,
          granularity: 60 * 60 * 1000,
          valueFormatter: 'date',
          valueFormatterPattern: 'E'
        }}

        onSelect={this.handleSelect}
        onChange={(e) => {
          e.persist();
          this.handleChange(e);
        }}
      />
    );
  }
}
```

I noticed that charts with the same amount of points but lower yAxis.axisMaximum performs better, also setting greater granularity helps but not much.

Are there any workarounds to improve performance for such cases?

**Comment by wuxudong** [comment]
I made a little test by modifying the Example->LineChartScreen.

1. 

    dataSets: [{
      values: Array.from(new Array(10000),(val,index)=>index + Math.ceil(Math.random() * 0)),
      label: 'Company X',
      config: {
        lineWidth: 2,
        drawCircles: false,
        highlightColor: processColor('red'),
        color: processColor('red'),
        drawFilled: true,
        fillColor: processColor('red'),
        fillAlpha: 60,
        valueTextSize: 15,
        valueFormatter: "##.000",
        dashedLine: {
          lineLength: 20,
          spaceLength: 20
        }
      }
    }]


It works fine, the UI frame rate in iOS simulator is around 60.


2. 

      values: Array.from(new Array(10000),(val,index)=>index + Math.ceil(Math.random() * 10)),

UI frame rate decrease to 40-50 when dragging/zooming, still acceptable.

3.  

     values: Array.from(new Array(10000),(val,index)=>index + Math.ceil(Math.random() * 1000)),

the UI frame rate drop to 5-10 when dragging, quite laggy.

4.

   I think the best solution is sampling.

5. 

   I guess you are using unix millisecond as x.  actually there are some problems in android. check discussion #192 #160  and #193 .

**Comment by ddavydov** [comment]
Thanks! Using sampling solved the problem, https://github.com/d3fc/d3fc-sample

**Comment by ezranbayantemur** [comment]
> Thanks! Using sampling solved the problem, https://github.com/d3fc/d3fc-sample

Hello, I have a performance issue too. The link that you shared looks like gone. What did you do for sampling? Can you share it?

**Comment by wuxudong** [comment]
It is now merged to d3fc/d3fc

**Comment by ezranbayantemur** [comment]
> It is now merged to d3fc/d3fc

Is there any way to sample data automatically? Like any option?
I mean, we can set limit (like 1000) and if we currently showing 1000 or more data it will automatically sample them.

**Comment by wuxudong** [comment]
No easy way.

Maybe you can combine your own javascript code to recalculate data when user zoom in/out , then use setDataAndLockIndex to replace data.

**Comment by ezranbayantemur** [comment]
Okay I will try.
One question, is there any option to get currently showed data count?

**Comment by ezranbayantemur** [comment]
> No easy way.
> 
> Maybe you can combine your own javascript code to recalculate data when user zoom in/out , then use setDataAndLockIndex to replace data.

By the way setDataAndLockIndex can be use on iOS?

**Comment by wuxudong** [comment]
setDataAndLockIndex can be used in both android and iOS, but there are some restrictions in android that is already mentioned in README.
