### ISSUE TITLE
using visibleRange

### ISSUE THREAD

**Issue by ionush** [wuxudong/react-native-charts-wrapper#278]
Using the BarChartScreen from Example folder:

added visibleRange in state:
```


    this.state = {
      visibleRange: {
        x: { min: 6, max: 5 }
      },
```
Added visibleRange in props:
 ```     
  render() {
    return (
      <View style={{ flex: 1 }}>
        <View style={{ height: 80 }}>
          <Text> selected entry</Text>
          <Text> {this.state.selectedEntry}</Text>
        </View>

        <View style={styles.container}>
          <BarChart
            style={styles.chart}
            data={this.state.data}
            xAxis={this.state.xAxis}
            animation={{ durationX: 2000 }}
            legend={this.state.legend}
            gridBackgroundColor={processColor('#ffffff')}
            drawBarShadow={false}
            visibleRange={this.state.visibleRange}
            drawValueAboveBar={true}
            drawHighlightArrow={true}
            onSelect={this.handleSelect.bind(this)}
            highlights={this.state.highlights}
            onChange={event => console.log(event.nativeEvent)}
          />
        </View>
      </View>
    );
  }
}
```
The bar should show 6 bars on render with a maximum zoom to 5 bars.  But I still get this:
![peek 2018-05-02 14-17](https://user-images.githubusercontent.com/26359601/39508080-9e458b86-4e13-11e8-9b0f-bd0470cde9e8.gif)

Can you please tell me why it's not working?

感谢啊

**Comment by wuxudong** [comment]
That is what I get using your code.  What is the version? try the latest one?


![simulator screen shot - iphone 6 - 2018-05-02 at 14 50 04](https://user-images.githubusercontent.com/1391101/39509308-5ba6f490-4e18-11e8-9b58-73b8f608c902.png)

**Comment by ionush** [comment]
using version 0.4.3, just recloned the whole github repo and ran from a different location, npm i in the Example folder, still the same issue.

I'm using android. Tested on both android emulator and real android device.

**Comment by ionush** [comment]
@wuxudong any advice?

**Comment by wuxudong** [comment]
The reason why it doesn't work is visibleRange depend on data.

But there is no grantee that setData will be called before setVisibleRange.

**Comment by nimo007** [comment]
hi guys,  v0.4.5, 'visibleRange' test on Android device don't work when update data in componentDidMount.
```
componentDidMount() {
        this.setState({data: {
                dataSets: [{
                    values: [{y: 100}, {y: 105}, {y: 102}, {y: 110},  {y: 114}, {y: 109}, {y: 105}, {y: 99}, {y: 95}],
                    label: '',
                    config: {
                        color: processColor('teal'),
                        barShadowColor: processColor('lightgrey'),
                        highlightAlpha: 90,
                        highlightColor: processColor('red'),
                    }
                }],

                config: {
                    barWidth: 0.7,
                }
            },
            highlights: [{x: 3}, {x: 6}],
            xAxis: {
                valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
                granularityEnabled: true,
                granularity : 1,
            }
        })
}
```

**Comment by wuxudong** [comment]
you have to setVisibleRange after setData, setVisibleRange won't work if data is empty.
