### ISSUE TITLE
Swift compile error

### ISSUE THREAD

**Issue by richfisher** [wuxudong/react-native-charts-wrapper#28]
ReactNativeCharts/utils/BridgeUtils.swift:24:26: Extraneous argument label 'string:' in call

https://github.com/wuxudong/react-native-charts-wrapper/blob/master/ios/ReactNativeCharts/utils/BridgeUtils.swift#L24

Fix-it Delete "string: "

**Comment by wuxudong** [comment]
In my SwiftyJSON
         
          /**
	     Create a JSON from JSON string
	    - parameter string: Normal json string like '{"a":"b"}'

	    - returns: The created JSON
	    */
	    public static func parse(string:String) -> JSON {
	        return string.data(using: String.Encoding.utf8).flatMap({JSON(data: $0)}) ?? JSON(NSNull())
	    }

string: is necessary. 

Maybe their api change in latest version.

what is your SwiftyJSON version?

**Comment by wuxudong** [comment]
It is weird.

	target 'Example' do
	  pod 'SwiftyJSON', git: 'https://github.com/IBM-Swift/SwiftyJSON.git'
	  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
	end

will lead to 

	Analyzing dependencies
	Pre-downloading: `Charts` from `https://github.com/danielgindi/Charts.git`
	Pre-downloading: `SwiftyJSON` from `https://github.com/IBM-Swift/SwiftyJSON.git`
	Downloading dependencies
	Installing Charts (3.0.1)
	Installing SwiftyJSON (2.3.2)

it is compatible to the code.



and  

	target 'Example' do
	  pod 'SwiftyJSON'
	  pod 'Charts'
	end

will lead to 

	Analyzing dependencies
	Downloading dependencies
	Installing Charts (3.0.1)
	Installing SwiftyJSON (3.1.4)

which is not compatible with the code.

It is a good practice to use fixed version.

	target 'Example' do
	  pod 'SwiftyJSON', '3.1.4'
	  pod 'Charts', '3.0.1'
	end

**Comment by wuxudong** [comment]
fixed. use SwiftyJSON 3.1.4
