### ISSUE TITLE
How to change value color on linechart?

### ISSUE THREAD

**Issue by antofa** [wuxudong/react-native-charts-wrapper#280]
Hi. I can't find how to change value color on linechart. Any solution?

https://i.gyazo.com/6307ba7850ff88ba94f9d606c5bc48e3.png

**Comment by wuxudong** [comment]
const chartDataSetConfig = {
	  common: {
	    color: PropTypes.number,
	    colors: PropTypes.arrayOf(PropTypes.number),
	    highlightEnabled:PropTypes.bool,
	    drawValues: PropTypes.bool,
	    valueTextSize:PropTypes.number,
	    valueTextColor:PropTypes.number,
	    visible:PropTypes.bool,
	    valueFormatter: PropTypes.oneOfType([
	      PropTypes.oneOf(['largeValue', 'percent', 'date']),
	      PropTypes.string
	    ]),
	    valueFormatterPattern: PropTypes.string,
	    axisDependency:PropTypes.string
	  },
