### ISSUE TITLE
Customize Bar Charts

### ISSUE THREAD

**Issue by hungdev** [wuxudong/react-native-charts-wrapper#281]
With 2 columns, I want its horizontal smaller like image. And the first column will be higher than the default. How to do it?
thanks
![chart](https://user-images.githubusercontent.com/12009276/39620112-468659d2-4fb4-11e8-98d6-5a3ff72e41a5.PNG)

**Comment by wuxudong** [comment]
Check bar data config:

	 config: PropTypes.shape({
	    barWidth: PropTypes.number,
	    group:  PropTypes.shape({
	      fromX:PropTypes.number.isRequired,
	      groupSpace:PropTypes.number.isRequired,
	      barSpace: PropTypes.number.isRequired
	    })
	  })
