### ISSUE TITLE
Violation error : Native component "RNLineChart doesn't exists'

### ISSUE THREAD

**Issue by jejesh26** [wuxudong/react-native-charts-wrapper#282]
#Dear,

trying to run basic example  from [(https://github.com/gregkyt/rnchartsexample)].

1 - Have create root folder with `react-native init myapp`
2- cd myapp then `react-native build-android`
3- then add react-native-charts-wrapper by using `yarn add  react-native-charts-wrapper`
4- then do the link as requested: `react-native link react-native-charts-wrapper`
5- check that all dependencies are correct 
6- the try run the code hereafter and the  error showed up on my android emulator

**Invariant violation : Native component for "RNLineChart" doesn't exist
error is located iat :
RNLineChart in linechart.js line 23**

Did I miss a step ?

thks

[EDIT]:
I found the solution, but seems weird to me, need to add one step in the installtion process

1- adding the library with yarn doesnt works
2- should use `npm install react-native-charts-wrapper --save`
3- **BUT here, you need to run** `npm install`
without this step, can not link the library to react-native

4- then can link  `react-native link react-native-charts-wrapper`
5- add Add Maven Repository
6- then run `create-native run-android`

Without step3, can not link, so nothing is working

Rgds

**Comment by wuxudong** [comment]
I have no idea about this, yarn work fine for me.

**Comment by KakitLee** [comment]
I have the same problem. Not sure why

**Comment by leo-tavares** [comment]
I have the same problem and... i resolve the question with this comands

In android directory of your project, code this -> `gradlew.bat clean --info`  

rebuild your app with `react-native run-android`
