### ISSUE TITLE
legend position not work

### ISSUE THREAD

**Issue by jiangdb** [wuxudong/react-native-charts-wrapper#283]
Legend position has no effect, if we try to set BELOW_CHART_CENTER, it still keep in the left

**Comment by wuxudong** [comment]
In new mpAndroidChart api, position is replaced by horizontalAlignment, verticalAlignment, orientation, drawInside, direction.

**Comment by tsiory** [comment]
@wuxudong How to make the PieChart in the left and the legend to the right (react-native-charts-wrapper v0.5.7)? Thanks

**Comment by tsiory** [comment]
@wuxudong This is my code but no success ...
<img width="479" alt="Capture d’écran 2020-07-19 à 17 18 08" src="https://user-images.githubusercontent.com/32092421/87876938-e7af3580-c9e3-11ea-8735-106a2735148a.png">
