### ISSUE TITLE
CMD + D and CMD + R not working

### ISSUE THREAD

**Issue by sozkahya** [wuxudong/react-native-charts-wrapper#285]
CMD + D and CMD + R do not work after adding the library. In the example CMD + D and CMD + R do not work. Help.

**Comment by wuxudong** [comment]
Reopen it if necessary.

**Comment by hosseinsalemi** [comment]
It doesn't work for me too.

**Comment by wuxudong** [comment]
Maybe this can help
`if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo.`

Check it in https://github.com/wuxudong/react-native-charts-wrapper/tree/master/installation_guide

**Comment by hosseinsalemi** [comment]
manual setup is ok :-)
