### ISSUE TITLE
Not Working on IOS

### ISSUE THREAD

**Issue by Nevtep** [wuxudong/react-native-charts-wrapper#29]
The Pod install command for swiftyjson fails.

I tried manual install, I get errors saying:
2017-04-03 00:29:22.117 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNBarChart" does not exist
2017-04-03 00:29:22.117 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNHorizontalBarChart" does not exist
2017-04-03 00:29:22.117 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNBubbleChart" does not exist
2017-04-03 00:29:22.118 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNCandleStickChart" does not exist
2017-04-03 00:29:22.118 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNLineChart" does not exist
2017-04-03 00:29:22.119 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNPieChart" does not exist
2017-04-03 00:29:22.119 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNRadarChart" does not exist
2017-04-03 00:29:22.119 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNScatterChart" does not exist
2017-04-03 00:29:22.119 [warn][tid:com.facebook.react.JavaScript] Warning: Native component for "RNCombinedChart" does not exist

Trying to get it fixed for several hours, I tried the example for beginners step by step and couldn't get it to work either. can you advise?

**Comment by Nevtep** [comment]
Ok Managed to make it work, this is what I actually had to do:

Create a Podfile like this

`use_frameworks!

target 'KrakenExchange' do
  pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end`

Otherwise SwiftyJSON 3.1.4 reference is not found. That configured the dependencies properly.

Then, to include the files to the project is not just "Add files to AppName" you have to create a Group named ReactNativeCharts, and add groups for each folder, the add files to the specific groups, if the folders inside the ReactNativeCharts have blue icons it won't work.

Hope this makes sense, thanks for the awesome library. 
Cheers!

**Comment by ludovic-coder** [comment]
Same issue using git versions of SwiftyJSON and Charts. I did all steps from https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/README.md

React Native 0.43

**Comment by wuxudong** [comment]
@ludovic-coder  can you paste pod verbose log?  I wonder which repository it is searching.

**Comment by ludovic-coder** [comment]
The verbose
  
  pod install --verbose                                     ✓  1921  12:40:27
      Preparing
        - Running pre install hooks

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-myProject`: (``)

    Finding Podfile changes
      - Charts
      - SwiftyJSON

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      - Charts
      - SwiftyJSON

    Downloading dependencies

    -> Using Charts (3.0.2)

    -> Using SwiftyJSON (3.1.4)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Adding source files to Pods project
      - Adding frameworks to Pods project
      - Adding libraries to Pods project
      - Adding resources to Pods project
      - Linking headers
      - Installing targets
        - Installing target `Charts` iOS 8.0
          - Generating Info.plist file at `Pods/Target Support Files/Charts/Info.plist`
          - Generating module map file at `Pods/Target Support Files/Charts/Charts.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Charts/Charts-umbrella.h`
        - Installing target `SwiftyJSON` iOS 8.0
          - Generating Info.plist file at `Pods/Target Support Files/SwiftyJSON/Info.plist`
          - Generating module map file at `Pods/Target Support Files/SwiftyJSON/SwiftyJSON.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/SwiftyJSON/SwiftyJSON-umbrella.h`
        - Installing target `Pods-myProject` iOS 8.0
          - Generating Info.plist file at `Pods/Target Support Files/Pods-myProject/Info.plist`
          - Generating module map file at `Pods/Target Support Files/Pods-myProject/Pods-myProject.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Pods-myProject/Pods-myProject-umbrella.h`
      - Running post install hooks
        - Podfile
      - Writing Xcode project file to `Pods/Pods.xcodeproj`
        - Generating deterministic UUIDs
      - Writing Lockfile in `Podfile.lock`
      - Writing Manifest in `Pods/Manifest.lock`

    Integrating client project

    Integrating target `Pods-myProject` (`myProject.xcodeproj` project)
      - Running post install hooks
        - cocoapods-stats from `/Users/ljamet/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

    Sending stats
          - Charts, 3.0.2
          - SwiftyJSON, 3.1.4

**Comment by wuxudong** [comment]
@ludovic-coder Thanks, I found it is because I upgrade Charts to v3.0.2 which hasn't been published to Pod. 
I will revert it back to v3.0.1 in Examples

**Comment by wuxudong** [comment]
`pod 'Charts', :tag => 'v3.0.2', :git => 'https://github.com/danielgindi/Charts.git'`

**Comment by ludovic-coder** [comment]
@wuxudong Perfect, thanks!

**Comment by ludovic-coder** [comment]
Same issue after upgrading to 0.44

**Comment by wuxudong** [comment]
what is the error ? swiftjson 3.1.4 not found?

**Comment by wuxudong** [comment]
Make sure you have  react@16.0.0-alpha.6 installed as log indicated:

`react-native@0.44.0 requires a peer of react@16.0.0-alpha.6 but none was installed.`
