### ISSUE TITLE
My pie chart dosen't show zero value area.

### ISSUE THREAD

**Issue by reepias** [wuxudong/react-native-charts-wrapper#290]
My pie chart dosen't show zero value area.

How to display zero value area on pie chart?
![pie zero](https://user-images.githubusercontent.com/35448088/40216067-7ac59cf0-5a8e-11e8-8135-6017bb551b47.png)

**Comment by NamPrik** [comment]
![screen shot 2561-05-18 at 11 23 45](https://user-images.githubusercontent.com/35448088/40216124-d309a30c-5a8e-11e8-8b9a-de3e252cb620.png)

**Comment by wuxudong** [comment]
I think zero value area should take no space.

Reopen it if necessary.
