### ISSUE TITLE
Not installing on android device

### ISSUE THREAD

**Issue by sandeepsinghs** [wuxudong/react-native-charts-wrapper#292]
I am not able to install react-native-charts-wrapper example project on android device. While compiling this project it get struck on Configuring > 3/3 projects > Resolving dependencies ':app:_debugApk' > Resolving dependencies ':react-native-charts-wrapper:_debugPubli

please help to resolve.

Thank you.

**Comment by wuxudong** [comment]
Maybe it takes long time to download something.

Reopen it if necessary.

**Comment by sandeepsinghs** [comment]
Thank you @wuxudong;

It is resolved by adding 
`  maven { url "https://jitpack.io" }    // used for MPAndroidChart`

in  android/build.gradle
