### ISSUE TITLE
PieChart: How to display labels and values at the edges

### ISSUE THREAD

**Issue by awadesmoline** [wuxudong/react-native-charts-wrapper#295]
Hi,
Is it possible to display the labels on the pieChart on the edges? like this:
<img width="303" alt="screen shot 2018-05-22 at 5 03 00 pm" src="https://user-images.githubusercontent.com/25609312/40374977-3abf018a-5de2-11e8-88bc-96bfbac22742.png">

**Comment by wuxudong** [comment]
I think these can help.

            xValuePosition: "OUTSIDE_SLICE",
            yValuePosition: "OUTSIDE_SLICE",
