### ISSUE TITLE
how to set zoom to 50% and lock it there ?

### ISSUE THREAD

**Issue by shayvidas2018** [wuxudong/react-native-charts-wrapper#296]
my question is after i use the app, for display
how do i set the zoom to 25 or 50 % . ?

**Comment by wuxudong** [comment]
you can use zoom property , and set pinchZoom/doubleTapToZoomEnabled/scaleEnabled false to lock it.



    zoom: PropTypes.shape({
      scaleX: PropTypes.number.isRequired,
      scaleY: PropTypes.number.isRequired,
      xValue: PropTypes.number.isRequired,
      yValue: PropTypes.number.isRequired,
      axisDependency: PropTypes.oneOf(['LEFT', 'RIGHT'])
    })
