### ISSUE TITLE
你好 我能设置饼图的位置吗

### ISSUE THREAD

**Issue by YinRenjie1993** [wuxudong/react-native-charts-wrapper#297]
如果图例过长的hu话就会遮挡饼图了

![image](https://user-images.githubusercontent.com/11569655/40435931-5af7fbd4-5ee4-11e8-8527-234d9f934bec.png)

**Comment by wuxudong** [comment]
It works fine in examples.

    legend: {
        enabled: true,
        textSize: 15,
        form: 'CIRCLE',
        // position: 'RIGHT_OF_CHART',

        horizontalAlignment: "RIGHT",
        verticalAlignment: "CENTER",
        orientation: "VERTICAL",
        wordWrapEnabled: true
      },

![simulator screen shot - iphone 8 plus - 2018-07-27 at 06 35 28](https://user-images.githubusercontent.com/1391101/43292366-7f10ae02-9167-11e8-8b65-f454640325e5.png)

I am not sure if it is caused by your special legend settings. 


Reopen it if necessary.
