### ISSUE TITLE
Customize BarChart

### ISSUE THREAD

**Issue by nthegedus** [wuxudong/react-native-charts-wrapper#298]
I'm trying to customize my BarChart to some like this:

![captura de tela 2018-05-23 as 14 46 33](https://user-images.githubusercontent.com/1063383/40441726-455cef74-5e98-11e8-93e4-65b69edbb00f.png)

Does is it possible? I couldn't find any solutions to make xAxis like the printscreen, and round the corners.

**Comment by wuxudong** [comment]
* Check #110 for the round corners.
* no settings for xAxis to make it look like this, but you can highlight several entries in the settings.

Reopen it if necessary.

**Comment by zxy198717** [comment]
@wuxudong seems native has supported it.

**Comment by Eramirez06** [comment]
does this have any support?
