### ISSUE TITLE
Change decimal separator

### ISSUE THREAD

**Issue by GerardCasadevall** [wuxudong/react-native-charts-wrapper#299]
I have a LineChart in one mobile with locale = ES, but i want display decimal values with the separator for dot '.' 

![captura](https://user-images.githubusercontent.com/13941090/40476894-7544489c-5f45-11e8-9a49-0b7c0c02d31b.PNG)

Can I set a specific configuration in the chart ? For example, Locale = US ?
I need that the decimal separator to always be '.'

regards,
Gerard.

**Comment by wuxudong** [comment]
you can manually set valueFormatter regardless of  Locale.

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

I have it put in '.', In yAxis I put the valueFormatter: '#0.0' but don't work well

regards,
Gerard.

**Comment by wuxudong** [comment]
yAxis has left and right.

    yAxis: PropTypes.shape({
      left: PropTypes.shape(yAxisIface),
      right: PropTypes.shape(yAxisIface)
    }),

**Comment by GerardCasadevall** [comment]
Hi wuxudong,

Yes,  yAxis right is disable.

>                             
yAxis={{
                                left: {
                                    valueFormatter: '#0.0',
                                    drawGridLines: true,
                                    textColor: processColor('white'),
                                    axisLineColor: processColor('white'),
                                    axisLineWidth: 1,
                                    gridColor: processColor('grey'),
                                    gridDashedLine: {
                                        lineLength: 1,
                                        spaceLength: 2
                                    },
                                    granularityEnabled: true,
                                    granularity: this.state.Salto,
                                    axisMaximum: this.state.MaxG,
                                    axisMinimum: this.state.MinG
                                },
                                right: { enabled: false }
                            }}

regards,
Gerard.

**Comment by wuxudong** [comment]
DecimalFormat is still locale related.

As a temporary workaround, you can format it as string at js side, then set it to marker.

**Comment by s349856186** [comment]
@GerardCasadevall 
I also get the same problem. Did you solve this problem? How to solve it?

**Comment by GerardCasadevall** [comment]
I didn't solve this problem, the library get the DecimalFormat from the mobile locale.

**Comment by wuxudong** [comment]
As a temporary workaround, you can format it as string at js side, then set it to marker.
