### ISSUE TITLE
There is a blank area in the pie chart

### ISSUE THREAD

**Issue by roselind** [wuxudong/react-native-charts-wrapper#3]
There is a section of the pie chart in the example that is blank.
eg：
![07988832-638e-44d8-8227-0c185971ae4a](https://cloud.githubusercontent.com/assets/9067932/23603637/e9b5d136-0290-11e7-83a9-062c45ec8995.png)

**Comment by wuxudong** [comment]
there is     maxAngle={350}  in the config.

you can set to 360 if you like

**Comment by roselind** [comment]
So that is what it is., thank you

**Comment by L-Jovi** [comment]
@wuxudong  hi, I try `rotationEnabled={false}` but not work for pieChart, how should I implement this property?

thanks for your time.

**Comment by wuxudong** [comment]
you can add an issue for this feature.
