### ISSUE TITLE
android "error while updating property 'data' of view managed by: RNBarChart"

### ISSUE THREAD

**Issue by patrickalbani** [wuxudong/react-native-charts-wrapper#30]
BarChart:
![image](https://cloud.githubusercontent.com/assets/20818198/24674905/9892f28c-1953-11e7-9352-d91dbfa337ae.png)

PieChart with same data:

![image](https://cloud.githubusercontent.com/assets/20818198/24674982/de837dde-1953-11e7-8bf0-541c7350b409.png)

**Comment by wuxudong** [comment]
can you run example successfully?

And can you paste your package.json?

**Comment by wuxudong** [comment]
And log in chrome debug windows?

**Comment by patrickalbani** [comment]
Solved, my mistake

**Comment by patrickalbani** [comment]
How to make to the chart always show the zeroline?

![image](https://cloud.githubusercontent.com/assets/20818198/24709728/4a1b344a-19f1-11e7-8dab-b6d567ca33df.png)

**Comment by wuxudong** [comment]
maybe zerolinechart in examples can help

**Comment by patrickalbani** [comment]
Dont help.

=/

**Comment by patrickalbani** [comment]
Solved.

in the yAxis:{
axisMinValue: 0
axisMinimum: 0,
}

in the chart  scaleEnabled={false}

Solved all my problems.

thanks for the awesome library and support.

=D

**Comment by wuxudong** [comment]
axisMinValue Is deprecated, use axisMinimum instead

**Comment by abcde1499** [comment]
@patrickalbani 
I'm having the same issue now, how did you solve it?
It's all good in iOS, but in Android, it shows "Error while updating property 'data' of a view managed by: RNLineChart"

Thank you

**Comment by wuxudong** [comment]
@abcde1499  error in Examples ? or in your own project?

**Comment by abcde1499** [comment]
@wuxudong In my own project

**Comment by wuxudong** [comment]
I suggest you run Examples first, if it success, then compare it with your own project.

pay attention to settings.gradle, build.gradle, xxApplication.java

**Comment by abcde1499** [comment]
The Example also went wrong as below:
![screenshot_1491877146](https://cloud.githubusercontent.com/assets/3325816/24891609/8ab047e0-1ea9-11e7-9d7f-2cacd0a297b3.png)

But I think this is not the same issue...

**Comment by abcde1499** [comment]
@wuxudong 
Just found the problem.
Since I don't need the 'legend' part below, so I didn't specify the 'label' in dataSets:
`dataSets:
              [
                {
                  values: lineValue,
                  config: lineChartConfig
                }
              ]`

After I fill in the label value, it's working:
`dataSets:
              [
                {
                  values: lineValue,
                  label: 'Whatever',
                  config: lineChartConfig
                }
              ]`

But in iOS, it's OK to not specify the 'lable' value.

Thank you for your great work anyway!

**Comment by SpadeKingW** [comment]
how do you solver the first problem?

**Comment by RCTnativeapp** [comment]
I have added label value..but still getting error in android.Can anyone help please

**Comment by wuxudong** [comment]
more details needed.

**Comment by RCTnativeapp** [comment]
Hi,

I am getting this error..Any clue please.

It comes only with Android.I have added key label,still getting the error.

Any clue please.

Thanks

**Comment by RCTnativeapp** [comment]
![ac71179e-9af5-43e9-9d9a-5c2ffe17a7cb](https://user-images.githubusercontent.com/36904072/36867365-bfcc79ea-1d49-11e8-8cd5-7b7d3fea03bd.jpeg)

**Comment by RCTnativeapp** [comment]
It comes only in Android. I have specified label value as label: 'Whatever', still I get it. any clue please.

**Comment by wuxudong** [comment]
Can you run example successfully? Just run it and compare it with yours.

and where did you add the label property？

**Comment by yhyfms** [comment]
我也出现了相同的问题

**Comment by yhyfms** [comment]
I show the same question

**Comment by goleador0322** [comment]
+ 100000000

**Comment by matantech** [comment]
Don't know if it's still relevant, any ways, i just discovers Android can't handle in case it contains objects.
Found some simple solution:

`dataSets: [{
                    values: Platform.OS != 'ios' ?  this.props.barData.map( ele => {
                        return ele.y
                    }) : this.props.barData,
                        label: 'Daily Cut',
                    config: {
                        colors: [processColor('#0069b2')],
                        drawValues: false,


                    },
                }],`

hope it helps!

**Comment by mMarcos208** [comment]
I have the same issue.
