### ISSUE TITLE
Could not resolve com.github.PhilJay:MPAndroidChart:v3.0.2

### ISSUE THREAD

**Issue by uttampawar** [wuxudong/react-native-charts-wrapper#300]
Hi,
I'm working on Android project where I'm trying to add MPAndroidChart as follows,

At project level build.gradle file I've two repositories,
allprojects {
    repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
    }
}
'Sync' at this point works okay. After that I added following line to the app/build.gradle file as,

dependencies {
     ...
     ...
     ...
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'
}

With this change, I started getting 'Could not resolve' error. What am I missing? Any help is appreciated.

**Comment by aditijadon28** [comment]
Add
maven { url "https://jitpack.io" }
to your build.gradle main

**Comment by aditijadon28** [comment]
Add
maven { url "https://jitpack.io" } under repositories under all projects under build.gradle of your App.
Rememer the main build.gradle under Gradle not under app
