### ISSUE TITLE
Maximum values for scale

### ISSUE THREAD

**Issue by benjaminbillet** [wuxudong/react-native-charts-wrapper#301]
Hi,
I would like to set a maximum/minimum scale on a bar chart (i.e., set boundaries to the pinch zoom), is there a way to do it? I didn't see any related parameter in the library code.

**Comment by ionush** [comment]
check visibleRange. Although as referenced in #278 , it seems like it doesn't work on Android, only iOS

**Comment by wuxudong** [comment]
VisibleRange will be fixed in 0.4.4.
