### ISSUE TITLE
how to make the table legend be in the same row like you have in the example ?

### ISSUE THREAD

**Issue by shayvidas2018** [wuxudong/react-native-charts-wrapper#303]
i have a table that i'm doing and the legend is in line after line
and in all your designs the legend is one next to another
is there a parameter i can add to make it happen like in you ?
also is there any way to lock the graph from the user zooming in and out, and where do i add it ?

![webp net-resizeimage 1](https://user-images.githubusercontent.com/38243924/40657163-77f1299e-634f-11e8-9bd5-b150da36ccd3.jpg)

thnx

**Comment by wuxudong** [comment]
wordWrapEnabled:true can help.

    scaleEnabled: PropTypes.bool,
    scaleXEnabled: PropTypes.bool,
    scaleYEnabled: PropTypes.bool,
    dragEnabled: PropTypes.bool,
    pinchZoom: PropTypes.bool,
    doubleTapToZoomEnabled: PropTypes.bool,
