### ISSUE TITLE
iOS not show marker

### ISSUE THREAD

**Issue by GerardCasadevall** [wuxudong/react-native-charts-wrapper#304]
Hi,

In iOS the LineChart not show the marker value. I always pass an array with the last position of the value xAxis (highlights = [{ x: bars.length - 1 }]), in android it show well but in iOs not show.

iPhone X
<img width="587" alt="iphonex" src="https://user-images.githubusercontent.com/13941090/40711572-d60d6b26-63fb-11e8-9d92-05b51292f677.png">

iPhone 8
<img width="559" alt="iphone8" src="https://user-images.githubusercontent.com/13941090/40711573-d6324798-63fb-11e8-96be-7085613f8a24.png">

Android
![android](https://user-images.githubusercontent.com/13941090/40711574-d64d63c0-63fb-11e8-98e2-f0be99e1c1e1.PNG)

My code:

<LineChart
	style={{ flex: 1, marginBottom: '1%' }}
	data={{
		dataSets: [
			{
				values: this.state.dataBars, // [{ x: 0, y: 158.0 } ...]
				label: '',
				config: {
					color: processColor('white'),
					drawFilled: false,
					fillColor: processColor('white'),
					textColor: processColor('white'),
					fillAlpha: 50,
					valueTextSize: 10,
					drawCircles: false,
					startAtZero: false,
					drawGridLines: false,
					drawValues: false,
					highlightEnabled: true,
					highlightColor: processColor(
						'#66000000'
					),
					valueFormatter: this.state
						.priceFormat
				}
			}
		]
	}}
	xAxis={{
		valueFormatter: this.state.labelxAxis, // ['00:05', ...]
		position: 'BOTTOM',
		drawGridLines: true,
		spaceBetweenLabels: 0,
		textColor: processColor('white'),
		axisLineColor: processColor('white'),
		axisLineWidth: 1,
		gridColor: processColor('grey'),
		axisMaximum: this.state.axisxMax,
		gridDashedLine: {
			lineLength: 1,
			spaceLength: 2
		}
	}}
	yAxis={{
		left: {
			valueFormatter: this.state.priceFormat,
			drawGridLines: true,
			textColor: processColor('white'),
			axisLineColor: processColor('white'),
			axisLineWidth: 1,
			gridColor: processColor('grey'),
			gridDashedLine: {
				lineLength: 1,
				spaceLength: 2
			},
			granularityEnabled: true,
			granularity: this.state.Salto,
			axisMaximum: this.state.MaxG,
			axisMinimum: this.state.MinG
		},
		right: { enabled: false }
	}}
	drawGridBackground={false}
	chartDescription={{ text: '' }}
	scaleEnabled={false}
	legend={{ enabled: false }}
	marker={{
		enabled: true,
		markerColor: processColor(
			'rgba(255, 255, 255,0.2)'
		),
		textSize: 10,
		textColor: processColor(
			this.state.highlightColor
		),
		digits: this.state.digits
	}}
	highlights={this.state.highlight} // [{ x: bars.length - 1 }]
	touchEnabled={false}
/>

**Comment by herarya** [comment]
+1 same, after update

**Comment by wuxudong** [comment]
In example -> LineChart

if I add highlights={[{x:3}]} to LineChart. It looks like this:

![simulator screen shot - iphone 8 plus - 2018-07-27 at 07 03 09](https://user-images.githubusercontent.com/1391101/43293136-483b4bb8-916b-11e8-95fb-5447c3a14d7f.png)

the position is not correct.

As a workaround, highlights={[{x:3, y:135}]} will display as expected.
