### ISSUE TITLE
support custom valueFormat callBack

### ISSUE THREAD

**Issue by tututututututu** [wuxudong/react-native-charts-wrapper#306]
PieChart 目前只支持数值类型的显示在 图标上,不能加 %.  可以加一个valueFormat回调来自定义显示内容

**Comment by wuxudong** [comment]
valueFormatter is supported on all charts.

you can use valueFormatter: "#.#'%'",   usePercentValues={true}

![simulator screen shot - iphone 8 plus - 2018-07-27 at 08 05 16](https://user-images.githubusercontent.com/1391101/43294875-0b607854-9174-11e8-898e-2d2427bf3554.png)
