### ISSUE TITLE
No working on IOS device

### ISSUE THREAD

**Issue by sandeepsinghs** [wuxudong/react-native-charts-wrapper#307]
I have tried all the possibility with the given steps in docs,example and previous issues asked on this lib, but it is not working on IOS devices.

Getting error as 
**"Invariant Violation: Native component for "RNPieChart" does not exist"** 
Same error is coming for **other graph** also.

The same error was coming for android but able to resolve and it is working on android device.

Please help.

**Comment by Wamae** [comment]
How? may I ask

**Comment by sandeepsinghs** [comment]
Thank you @Wamae  for reply.

I have follow steps as per the docs of this lib for integrating in project. 

Getting error as
"Invariant Violation: Native component for "RNPieChart" does not exist"
Same error is coming for other graph also.

The same error came for Android but I am able to resolved but not able to resolve for IOS.

I navigate this object and found code as

`var RNPieChart = requireNativeComponent('RNPieChart', PieChart, {
  nativeOnly: {onSelect: true, onChange: true}
});`

I research on this but not understand the error.

Please help.

**Comment by sandeepsinghs** [comment]
I am able to resole the issues of IOS. I followed this tutorials steps to setups lib for IOS using Xcode Ide and it is working 
[(https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6)]

Thank you.

**Comment by iamsee** [comment]
@sandeepsinghs the second url of evenote can't open now

**Comment by sandeepsinghs** [comment]
Please refer the first URL 
[https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6](url)
