### ISSUE TITLE
how to remove decimal on percent value formatter ?

### ISSUE THREAD

**Issue by ramazord** [wuxudong/react-native-charts-wrapper#310]
![image](https://user-images.githubusercontent.com/19430442/41029959-5c4a5180-69a7-11e8-9fbe-7998769c4c28.png)

how to remove .0 at percent value format ? 
here's my code

> mountChart(dateList) {
        const { color_statusbar } = this.props
        this.setState(
            update(this.state, {
                data: {
                    $set: {
                        dataSets: this.getDataSets()
                    }
                },
                xAxis: {
                    $set: {
                        drawGridLines: false,
                        fontFamily: "odudosoft_regular",
                        valueFormatter: dateList
                    }
                },
                yAxis: {
                    $set: {
                        left: {
                            valueFormatter: 'percent',
                        },
                        right: {
                            enabled: true,
                            drawLabels: false,
                            drawAxisLine: true,
                            drawGridLines: false,
                        }
                    }
                }
            })
        );
    }

**Comment by wuxudong** [comment]
DecimalFormat valueFormatter is more flexible.

if your yAxis value is 0.3, and you want to display it as 30%, not 30.0%,  you can use valueFormatter: "#%"

**Comment by correadevuk** [comment]
just add `valueFormatter: "#.#'%'"` to yAxis object
