### ISSUE TITLE
axis dependency iOS issue again

### ISSUE THREAD

**Issue by ionush** [wuxudong/react-native-charts-wrapper#311]
I have a bug in iOS where the axis dependency issue is a problem again. Android works fine
I have already seen #224 , but I understand that the newest version 0.4.3 has charts version 3.1.1.
On IOS if i only use axisDependency:"RIGHT" i get:

![image](https://user-images.githubusercontent.com/26359601/41036298-28803142-69c2-11e8-9ea5-f434e1d4b585.png)

But if i add a left axisDependency i get:

![image](https://user-images.githubusercontent.com/26359601/41036247-0511acd6-69c2-11e8-9c7c-bb1f591d95dc.png)

I thought this issue was solved?

**Comment by wuxudong** [comment]
I copied your code, and this is the result, looks fine.

![simulator screen shot - iphone 6 - 2018-08-16 at 09 31 39](https://user-images.githubusercontent.com/1391101/44181943-405e5f80-a137-11e8-940b-a9fe9ce58b68.png)

**Comment by wuxudong** [comment]
Can you provide a sample data and config, @ionush

**Comment by iqysf** [comment]
![image](https://user-images.githubusercontent.com/13929730/45148826-bddb3400-b1fa-11e8-8d66-4a45ad738928.png)
same problem.
