### ISSUE TITLE
Unable to update pieChar value with redux

### ISSUE THREAD

**Issue by AnthonyNTK** [wuxudong/react-native-charts-wrapper#312]
ENV:
```
react-native: 0.54
react-native-charts-wrapper: 0.4.3
redux: 3.7.2
react-redux: 5.0.7
firebase: 4.10.1
```

I am fetching data from Firebase and using Redux for state management. However, i am not able to update the data of my pieChart. I have checked that there is no log in Chrome console.

Here is my code:

```
class StatisticScreenComponent extends Component {

  constructor(props) {
    super(props)

    this.state = {
      legend: {
        enabled: true,
        textSize: 10,
        form: 'CIRCLE',
        position: 'RIGHT_OF_CHART',
        wordWrapEnabled: true
      },
      highlights: [{x:2}],
      description: {
        text: 'This is the overall distribution of your messaging type',
        textSize: 15,
        textColor: processColor('darkgray'),
      }
    }

    this.setData = () => {
      this.setState(
        update(
          this.state, {
            data: {
              $set: {
                dataSets: [
                  {value: this.props.publicCount.file + this.props.privateCount.file, label: 'File Transfer'},
                  {value: this.props.publicCount.text + this.props.privateCount.text, label: 'Photo Upload'},
                  {value: this.props.publicCount.photo + this.props.privateCount.photo, label: 'Text Sent'},
                  {value: this.props.publicCount.location + this.props.privateCount.location, label: 'Location Sharing'},
                  {value: 2, label: 'Byte Transfered'}
                ],
                label: 'Pie dataset',
                config: {
                  colors: [
                    processColor('#C0FF8C'),
                    processColor('#FFF78C'),
                    processColor('#FFD08C'),
                    processColor('#8CEAFF'),
                    processColor('#FF8C9D')
                  ],
                  valueTextSize: 14,
                  valueTextColor: processColor('green'),
                  sliceSpace: 5,
                  selectionShift: 13
                }
              }
            }
          }
        )
      )
    }
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>{JSON.stringify(this.props.publicCount)}</Text>
        <PieChart
          style={styles.chart}
          chartBackgroundColor={processColor('lightgray')}
          data={this.state.data}

          entryLabelColor={processColor('black')}

          rotationEnabled={true}
          rotationAngle={45}
          usePercentValues={false}
          styledCenterText={{text:'Rotate Me', color: processColor('pink'), size: 20}}
          centerTextRadiusPercent={100}
          holeRadius={40}
          holeColor={processColor('#f0f0f0')}
          transparentCircleRadius={45}
          transparentCircleColor={processColor('#f0f0f088')}
          maxAngle={350} />

        <Button
          style={{width:30, height:20}}
          title="Press Me"
          onPress={this.setData}/>
      </View>
    )
  }
}
```

You can see that data fetched from firebase can be correctly received but it just can be "inserted" into the chart. I am not sure about the cause but I believe that it related to problem of async request.

I suspect that pieChart is initialized before the props arrived(which can be confirmed that if i `alert(JSON.stringify(this.props.publicCount))` in `componentDidMount()`), and my initalState of publicCount in Redux store is null. Therefore, it catch null exception and give me those redbox. Any idea to solve this kind of problem with async request to update data in chart?

FYI:
Since this View is also under a navigation, when can exit the view and enter again, the PieChart is rendered as expected which is also another hint on async problem

![screenshot_20180608-221513](https://user-images.githubusercontent.com/26246071/41163012-1bf34ff0-6b6a-11e8-8d71-f28dd6c38d3b.png)
![screenshot_20180608-221520](https://user-images.githubusercontent.com/26246071/41163013-1c265cce-6b6a-11e8-95ba-753eae7cd698.png)

**Comment by wuxudong** [comment]
It seems the data you provide is null? try debug it and print some log.

Reopen it if necessary.

**Comment by AnthonyNTK** [comment]
@wuxudong as I mentioned before, my redux dispatch and firebase data could be successfully fetched and displayed as shown on the first image. I eventually use `setInterval` to continuously update the pie chart and clear the `timer` after some count (like after 2s or 3s). I don't know what is the real cause but I suspect that the `<PieChart>` fail to receive new props/state. If you would like to investigate more, I can help to reproduce the test case for you.
