### ISSUE TITLE
Legend support clicks?

### ISSUE THREAD

**Issue by allyju** [wuxudong/react-native-charts-wrapper#313]
<img width="142" alt="image" src="https://user-images.githubusercontent.com/10126204/41188345-5c0d7564-6bee-11e8-9b43-d061d746a0d2.png">
I hope I can click on each of them to select each block on Pie.

**Comment by wuxudong** [comment]
It won't be fixed according to [this](https://github.com/PhilJay/MPAndroidChart/issues/4012)
