### ISSUE TITLE
yAxis gridColor not taking effect

### ISSUE THREAD

**Issue by mashwinprdxn** [wuxudong/react-native-charts-wrapper#315]
Hi, I used the following JSX for a ScatterChart:
```javascript
<ScatterChart
  style={styles.chart}
  data={this.state.data}
  legend={this.state.legend}
  marker={this.state.marker}
  onSelect={this.handleSelect.bind(this)}
  chartDescription={{ text: '' }}
  touchEnabled={false}
  xAxis={{ axisLineColor: processColor('white'), gridColor: processColor('white') }}
  yAxis={{ axisLineColor: processColor('white'), gridColor: processColor('white') }}
  onChange={(event) => console.log(event.nativeEvent)}
/>
```
but the yAxis grid color doesn't seem to use the specified color:
![screenshot-2018-06-11_19 14 20 485](https://user-images.githubusercontent.com/39124207/41235429-6c92e4a4-6dac-11e8-9fcc-b11b69389a6f.png)

What am I doing wrong here? Any help would be appreciated!

**Comment by podvipodvert** [comment]
Did you find a solution?

**Comment by platonish** [comment]
you need to mention `gridColor` inside the `left` or `right` property like this:
```javascript
<ScatterChart
  yAxis={{
    right: {
      gridLineWidth: 1,
      gridColor: processColor('white')
      ...
    }
  }}
/>
```

**Comment by podvipodvert** [comment]
and about RadarChart?

**Comment by wuxudong** [comment]
Web color of RadarChart is supported in v0.4.4。
