### ISSUE TITLE
How to set the label position

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#316]
![image](https://user-images.githubusercontent.com/2498958/41578909-2b4d858c-73c7-11e8-9639-8571f71bb0d9.png)

how to set Horizontal one line display？Has anyone helped?

**Comment by wuxudong** [comment]
These can help.

    horizontalAlignment: PropTypes.string, // LEFT, CENTER, RIGHT
    verticalAlignment: PropTypes.string, // TOP, CENTER, BOTTOM
    orientation: PropTypes.string, // HORIZONTAL, VERTICAL
    drawInside: PropTypes.bool,
    direction: PropTypes.string, // LEFT_TO_RIGHT, RIGHT_TO_LEFT

    wordWrapEnabled: PropTypes.bool,
