### ISSUE TITLE
LineChart disorder

### ISSUE THREAD

**Issue by Thyiad** [wuxudong/react-native-charts-wrapper#32]
Hey, first of all, thanks for an awesome component!

I have a problem regarding using it with a LineChart: 

> let lineData={
            dataSets:[ {
                    values: [67, 25, 76, 82, 81, 79],
                    // ...
                }],
        };

 let linexAxis = {
            valueFormatter: [
                '2016-11',
                '2016-12',
                '2017-01',
                '2017-02',
                '2017-03',
                '2017-04',
            ],
        };

I found when data set more than 4 length, the render is something wrong...

[lineError.png](http://www.thyiad.win/img/lineError.png)

图片死活传不上，只好先放到临时网站上了。。

**Comment by wuxudong** [comment]
duplicated with #15 , check the solution there

**Comment by Thyiad** [comment]
Thank you !

> 只是我用ngrock转发映射的测试站点，方便app，微信调试用
