### ISSUE TITLE
How to create a market depth chart?

### ISSUE THREAD

**Issue by longpq18** [wuxudong/react-native-charts-wrapper#320]
![workspace 1_010](https://user-images.githubusercontent.com/15885041/41948922-472e0a2e-79e9-11e8-8ccd-ab3d4aa3bd47.png)

**Comment by ZSH-HSZ** [comment]
y轴怎么设置让数字显示在右侧的呢？

**Comment by wuxudong** [comment]
Can you provide a market depth chart example pic?

**Comment by longpq18** [comment]
You can see exemple here: https://bitcoincharts.com/markets/bitstampUSD_depth.html

**Comment by wuxudong** [comment]
I think it is a common bar/line chart with two series of data?  The line chart already support fillGradient.
