### ISSUE TITLE
Remove highlights

### ISSUE THREAD

**Issue by FRizzonelli** [wuxudong/react-native-charts-wrapper#322]
Hi @wuxudong, great porting and thank you for all the work! (I've already used MPAndroidChart in some native apps and it's amazing).

I'm unable to remove highlight from my LineChart, currently I've made a button which basically calls setState and set highlights to empty array (tried with null/undefined too but I received an error).

Working on Android, still to try on iOS. Any idea? Is this implemented on the RN side? Currently I'm looking at ChartBaseManager to make it work but I've no clue on what's wrong :(

EDIT: To clarify, what I'm trying is to have dragEnabled, show the current selected value with proper highlight, then onTouchEnd I want to deselect the value and remove the highlight

**Comment by wuxudong** [comment]
1. setState({highlights:[]}) multiple time has no effect because no change occurred.
2. A new function is introduced in v0.4.4, you can use `this.refs.chart.highlights([])`  to clear all highlights.

**Comment by Taylor123** [comment]
@wuxudong is there any plans to add a prop that can take a handler which is called when the drag ends?

Would love the functionality to change state on drag, but then reset `onTouchEnd`

**Comment by Taylor123** [comment]
For the time being, i was able to get the desired behavior by setting one of the surrounding views to the Responder with `onStartShouldSetResponder` and then set a handler function within the same view using `onResponderRelease={hanlderFunc}`

Example:
```
<View onStartShouldSetResponder={() => true} onResponderRelease={this.handleChartDragEnd}>
  <Chart />
</View>
```

**Comment by wuxudong** [comment]
Or you can try latest version?

**Comment by jocoders** [comment]
Refs works not properly. Every time get the error of ref's null

**Comment by zoomerland** [comment]
> 2\. this.refs.chart.highlights([])

Did anyone solve this? 
Have this.refs.chart.highlights([]) at v0.4.4 but i got error highlights is not function too
