### ISSUE TITLE
安卓和ios显示的y轴数值不一样

### ISSUE THREAD

**Issue by liuliu66666** [wuxudong/react-native-charts-wrapper#325]
我设定了y轴的区间为0～100
`const yAxisConfig = {
  textSize: 10,
  axisMinimum: 0,
  axisMaximum: 100,
}`

安卓显示正常，ios则是扩大了100倍显示为10000%

**Comment by rcj60560** [comment]
@liuliu66666  请教一个问题啊 看到回复我一下

**Comment by wuxudong** [comment]
10000% = 100
