### ISSUE TITLE
Scroll zoomed chart to the end

### ISSUE THREAD

**Issue by etartakovsky** [wuxudong/react-native-charts-wrapper#33]
@wuxudong thanks for the library!

I'm making a financial app that's using candlestick chart to show prices.

I need my chart to zoom my chart to show only latest X values out of hundreds available. I managed to do that with `zoom` prop.

Also, I need my chart to show the latest available value at the right side of the chart. By default it starts with the first value and the left side. Is there a way to do that?

**Comment by wuxudong** [comment]
There are `xValue` and `yValue` in  zoom prop which indicate zoom center. 

	    zoom: PropTypes.shape({
	      scaleX: PropTypes.number.isRequired,
	      scaleY: PropTypes.number.isRequired,
	      xValue: PropTypes.number.isRequired,
	      yValue: PropTypes.number.isRequired,
	      axisDependency: PropTypes.oneOf(['LEFT', 'RIGHT'])
	    }),

**Comment by wuxudong** [comment]
I found it only work in android, not in iOS, I will take a look why

**Comment by etartakovsky** [comment]
Thank you, please keep me updated

**Comment by santiment-admin** [comment]
Update:

I was able to draw combined chart with candlesticks scrolled almost to the end, but not quite: 
http://take.ms/m7ZvI

Notice that the chart focuses zoom on a candle several candles before the last one.

There are 180 candles drawn, I hardcoded higher xValue on purpose. Here are my zoom parameters
```
zoom={{scaleX: 2, scaleY: 1, xValue: -9999, yValue: 1, axisDependency: 'RIGHT'}}
```

How can I make a chart go full way to the end? :)

**Comment by etartakovsky** [comment]
Update:

I was able to draw combined chart with candlesticks scrolled almost to the end, but not quite: 
http://take.ms/m7ZvI

Notice that the chart focuses zoom on a candle several candles before the last one.

There are 180 candles drawn, I hardcoded higher xValue on purpose. Here are my zoom parameters
```
zoom={{scaleX: 2, scaleY: 1, xValue: -9999, yValue: 1, axisDependency: 'RIGHT'}}
```

How can I make a chart go full way to the end? :)

**Comment by etartakovsky** [comment]
Another update: I just launched the same chart on Android and noticed that it's scrolled to the beginning of the chart.

Apparently, it happens because Android and iOS expect different `xValue`s. For iOS it should be negative to scroll to the end, for Android it should be positive:
```
iOS
zoom={{scaleX: 2, scaleY: 1, xValue: -9999, yValue: 1, axisDependency: 'RIGHT'}}

Android
zoom={{scaleX: 4, scaleY: 1, xValue: 9999, yValue: 1, axisDependency: 'RIGHT'}}
```

**Comment by wuxudong** [comment]
I am not sure if iOS expects a negative value. 

The purpose of Charts is providing an iOS equivalent to android MpAndroidChart, It doesn't make sense to make API difference.

I have to write a native example to test Charts, I will do it in weekend.

**Comment by kyle-ssg** [comment]
Is there any update on this ? I'm doing the same suggestion as above

```
                        xValue: Platform.OS == 'ios' ? -Number.MAX_SAFE_INTEGER : Number.MAX_SAFE_INTEGER,
```

on iOS this scrolls just short of to the end by around 200px

**Comment by kyle-ssg** [comment]
Update on this, found out that this only happens on initial props, after that setting xValue to 9999 works the same as android: e.g.

```
   componentDidMount() {
        _.defer(()=>{
            this.setState({ xValue: Platform.OS == 'ios' ? 9999 : 9999 })
        });
    }
```

**Comment by wuxudong** [comment]
Yes, it works, thanks. I will update it in examples.

**Comment by kyle-ssg** [comment]
No problem, this is still a bit of an underlying issue as doing this will cause the chart to flicker
