### ISSUE TITLE
how to show all labels in the xAxis?

### ISSUE THREAD

**Issue by abreudiego94** [wuxudong/react-native-charts-wrapper#331]
how to show all labels in the xAxis ? 
![img-20180718-wa0029](https://user-images.githubusercontent.com/14917271/42909509-cff258ec-8aba-11e8-9710-e6ff5bff86dd.jpg)

**Comment by wuxudong** [comment]
xAxis: {
        valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        granularityEnabled: true,
        granularity : 1,
      }
