### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nayfusaurus** [wuxudong/react-native-charts-wrapper#333]
Hello, I have a problem rendering the line chart with multiple points.

![photo6237672590319659072](https://user-images.githubusercontent.com/35911760/42988054-d48a14ca-8c2d-11e8-9423-afdd5269beab.jpg)
![photo6237672590319659070](https://user-images.githubusercontent.com/35911760/42988063-dbb52082-8c2d-11e8-9eac-c28692fd4231.jpg)

Currently i am loading 3 datasets into the state with 1024points of X,Y,Z values each onto the graph,
dataset1:{x values, y values, z values}
dataset2: ..... 
dataset3: .....
and using a button to trigger between the different datasets. So following the live chart updating in the example, i can switch the datasets accordingly. But sometimes it randomly crashes and shows the maximum call stack size error and i am not sure why. Any help will be appreciated. Thank you

My dependencies
"react": "16.3.1",
"react-native": "0.55.4",
"react-native-easy-grid": "^0.1.17",
"react-native-charts-wrapper": "^0.4.3",

**Comment by wuxudong** [comment]
It is weird, are there any recursive calls?

**Comment by wuxudong** [comment]
Close inactive issue, reopen it if necessary.
