### ISSUE TITLE
prevent deselect hightlighting per tap

### ISSUE THREAD

**Issue by Qvatra** [wuxudong/react-native-charts-wrapper#336]
I need to prevent deselect hightlighting per tap for LineChart.

in docs for MPAndroidChart: https://github.com/PhilJay/MPAndroidChart/wiki/Highlighting
there is a possibility to set setHighlightPerTapEnabled to false.

is it possible in your wrapper?

i was trying to set it for LineChart as prop highlightPerTapEnabled={false} but it doesnt work

**Comment by makoy21** [comment]
How about touchEnabled={false}?

**Comment by Qvatra** [comment]
@makoy21  I still need interaction with the chart. I can use dragging but it stops working when I set  touchEnabled={false}

**Comment by makoy21** [comment]
@Qvatra try highlightEnabled={false}

**Comment by Qvatra** [comment]
@makoy21 the problem is that i need highlight to be on my chart.

**Comment by wuxudong** [comment]
highlightPerTapEnabled, highlightPerDragEnabled is introduced in v0.4.4

you can use it like this:

            highlightPerTapEnabled={false}
            highlightPerDragEnabled={false}
            highlights={[{x:3, y:135}]}


these settings will always fix the highlights.
