### ISSUE TITLE
How i can make label like this in StackedBarChart

### ISSUE THREAD

**Issue by WoodsterId** [wuxudong/react-native-charts-wrapper#337]
Halo, thank you for awesome library, but i have one problem..
how i can make label like this in StackedBarChart : 

![badb4a85-eefa-48a4-902f-340ffc33d4f4](https://user-images.githubusercontent.com/32380621/43126657-7e5be290-8f57-11e8-9305-c71c05e62d8e.jpg)

thank you.

**Comment by makoy21** [comment]
try to use `labelRotationAngle={{45}}`

check it here: [https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md#xaksis](url)

**Comment by WoodsterId** [comment]
halo @makoy21 thank you for reply, it's work but 

![screenshot_1532505594](https://user-images.githubusercontent.com/32380621/43187408-81cbebea-901b-11e8-8a51-13cc47942f08.png)

how do i fix this ?

**Comment by wuxudong** [comment]
You can use  `position: "BOTTOM"` in  xAxis to put the label at bottom.
