### ISSUE TITLE
Dynamic load data it's possible with onChange event ? 

### ISSUE THREAD

**Issue by aleksbgs** [wuxudong/react-native-charts-wrapper#342]
Dynamic load data it's possible with onChange event ?  for example swiping left

**Comment by wuxudong** [comment]
You can load more data in onChange. 

I guess you want to implement a moving window,  it is possible , but a little complicate, let me know if you made it.

**Comment by Lastin** [comment]
The problem I am facing here is to keep the track of the right position to show on chart.
For example, then 30 new data points are fetched and appended to the beginning of the previous data, I want the chart to stay at the exactly same point, instead it always jumps to the beginning of the data.

Can you give me some tips on how to get around that?

**Comment by wuxudong** [comment]
refer to [this](https://github.com/PhilJay/MPAndroidChart/issues/3262)

**Comment by Lastin** [comment]
Those side-effects are to be expected when doing all async stuff. I will try to implement the way you say.

**Comment by wuxudong** [comment]
A new function is introduced: setDataAndLockIndex
