### ISSUE TITLE
Static chart in multiple chart

### ISSUE THREAD

**Issue by Oraclesports** [wuxudong/react-native-charts-wrapper#345]
Hi @wuxudong 
Is it possible to make the bottom chart static to the X values of the top chart?
Thus, while i scroll the top chart, the bottom chart moves as well as it is being **stacked together** with top chart.
Unlike the given example in multiplechart, where the bottom chart follows the topchart.
@GermanMontejo

**Comment by wuxudong** [comment]
CombinedChart?

**Comment by Oraclesports** [comment]
I don't mean that way. For example, having a MACD indicator chart stacked below the stock chart. I'm looking for it to move together instead of the current sync function in multiple chart.
Would it be possible? Or do I need to code it based on gestures in AndroidMPChart?

**Comment by GermanMontejo** [comment]
@Oraclesports I don't understand what you mean... I also haven't tried using a MultipleChart but @wuxudong 's MultipleChartScreen.js is just a demonstration of two linechart whose change callback has been synchronized. If I understand it correctly, you want the bottom chart to follow the top chart when the top chart is being dragged? So maybe you can do something similar, wherein you create a syncToChart() but this time your bottom chart is onChange will pass its event and in the syncToChart() function you need to update the xAxis' xValue with the event's xValue.

**Comment by GermanMontejo** [comment]
or you can also pass the xValue that you get from the event and use that xValue for the chart's moveViewToX() function.

**Comment by wuxudong** [comment]
MultipleChartScreen.js is an approach, but the performance is poor in android. It is caused by the nature of react native.  The synchronization of multiple chart is similar to animation in some ways, and the performance of  react native animation is poor (unless use native-driver).

**Comment by Oraclesports** [comment]
Thank you for the replies. Will the use of moveViewToX() cause the animation?
I do not want the animation. I think i'll work natively

**Comment by RPeast** [comment]
May I ask if your problem has been solved? I am looking for the way of chart linkage

**Comment by wuxudong** [comment]
check group & syncX & syncY
