### ISSUE TITLE
How to reset zoom properties.

### ISSUE THREAD

**Issue by yuehue** [wuxudong/react-native-charts-wrapper#348]
Hi,

How can I reset chart back to its original state after user pinch and zoom the chart ?  Did try update zoom properties back to {scaleX: 1, scaleY: 1, xValue: 0, yValue: 0} but didn't do the trick.

**Comment by wuxudong** [comment]
fitScreen/moveViewTo can be used.

**Comment by yuehue** [comment]
Just got a chance to try your advice. fitScreen() is working good on Android. But got error on iOS with message : 

> fitScreen is not a recognized Objective-C method.' was thrown while invoking dispatchViewManagerCommand on target UIManager with params ...

I'm currently work with chart-wrapper v 0.4.2. and Charts v 3.0.3

Do I need to update version or anything ?

Thanks.

**Comment by wuxudong** [comment]
I am not sure, I think you can try the latest version.

**Comment by yuehue** [comment]
Try the latest version but problem still persisted :(

Is there any example that use this fitScreen/moveViewTo ?

**Comment by wuxudong** [comment]
Try the master branch.

**Comment by manjuy124** [comment]
@wuxudong 
Right now doubleTap is working to zoom in the chart. But how do we use double tap to zoom out as well. My requirement is when we double tap for the first time, it should get zoom in. When we double tap for the second time, it should get zoom out(reset).

 Is that possible?
