### ISSUE TITLE
Unable to edit EntryLabel on Pie Chat

### ISSUE THREAD

**Issue by JCDJulian** [wuxudong/react-native-charts-wrapper#35]
The fields entryLabelColor and entryLabelTextSize do not appear to do anything on the pie chart. Setting them as

```
entryLabelColor={processColor('black')}
entryLabelTextSize={1}
```

simply returns the same white font. Same results no matter how I edit them.

This also occurs in the example application. All other functionality is as expected in my installation.

**Comment by JCDJulian** [comment]
Update: Similar issue with updating the description. It's just defaulting to "Description Label" even when I change it.

**Comment by JCDJulian** [comment]
Running debugger on native code.

Looks like `setChartDescription` is not being called (or at least not triggering breakpoint), although the other setters are. setEntryLabelColor and setEntryLabelTextSize ARE being called, but the results are not displaying on the chart, strangely.

**Comment by wuxudong** [comment]
@JCDJulian  I mentioned entryLabelColor &  entryLabelTextSize [here](https://github.com/wuxudong/react-native-charts-wrapper#notice) ,  currently it can only work in android.

you should use `chartDescription`. not `description`

**Comment by wuxudong** [comment]
I find this problem is related to Charts.

Charts render pie chart using dataSet's entryLabelColor & entryLabelTextSize. it will always ignore the settings in root chart. It looks like a bug.

**Comment by wuxudong** [comment]
check latest version. now pie's entryLabelColor& entryLabelTextSize  support iOS

**Comment by windydang26** [comment]
@wuxudong when i set drawEntryLabels for pie chart, ios crash.
