### ISSUE TITLE
Only show highlight on drag and only show marker on initial load

### ISSUE THREAD

**Issue by Taylor123** [wuxudong/react-native-charts-wrapper#354]
I would like to only show the highlight indicator lines when a user is dragging and changing the selected data point, but would like to have the highlights removed once that gesture ends. I would also like there to be markers to highlight certain data points (max and min on LineChart), but don't want other markers to appear `onSelect`.

Is there any way to handle this scenario?

```
react-native-charts-wrapper: 0.4.3
"react-native": "0.55.3"
```

**Comment by wuxudong** [comment]
It is easy to add more callback like dragging/dragEnd, but I think it is hard to control only certain data points can be highlighted.

**Comment by Taylor123** [comment]
Do you have an example of how to add a dargEnd callback or plans to add a prop for it?

Also, i can see how it would be difficult to only highlight certain data points. But maybe it would be easier to have the highlight and makers off, but initialize the chart with some markers that are persisted on certain data points.

**Comment by wuxudong** [comment]
There is a direct function : highlights

Maybe you can combine this.refs.chart.highlights(config) with onResponderRelease/onResponderGrant.

**Comment by Taylor123** [comment]
@wuxudong it turns out that this design was suboptimal as the View would become the Responder and cause there to be a poor drag experience on android. Haven't had a chance to dive into both native libraries yet, but for some reason the experience was fine on iOS and not android.

For the time being, I'm just going to use the drag functionality out of the box and not clear the selected data on drag end. I think this issue can be closed out for now until it becomes a more requested feature.
