### ISSUE TITLE
Candles go beyond the screen.

### ISSUE THREAD

**Issue by rocktea** [wuxudong/react-native-charts-wrapper#355]
```
      zoom={{
        scaleX: 0,
        scaleY: 0,
        xValue: 9999,
        yValue: 1,
        axisDependency: "RIGHT"
      }}
```
How to compress the vertical axis to fit candles?
![1231231231](https://user-images.githubusercontent.com/8441897/44000647-a8bb9f56-9e2c-11e8-86ed-61d3c61e9a63.png)

**Comment by wuxudong** [comment]
Just remove the zoom property? It will default fit screen.

**Comment by rocktea** [comment]
Thanks for the reply! Unfortunately, this did not fix the problem :(

**Comment by wuxudong** [comment]
Can you provide the  data and config?

**Comment by rocktea** [comment]
I found the cause! But I don't know what's wrong.

```
              yAxis={{
                left: {
                  enabled: false
                },
                right: {
                  enabled: true
                }
              }}
```
If I do `yAxis={{ }}` - everything's going to be fine.

**Comment by wuxudong** [comment]
Maybe your data is depend on left yAxis by default, try specify axisDependency in your data.

**Comment by rocktea** [comment]
Yes! Thank you very much, it solved the problem!
