### ISSUE TITLE
`CombinedChart` has no propType for native prop `RNCombinedChart.extraOffsets` of native type `Map`

### ISSUE THREAD

**Issue by DiptiVShinde** [wuxudong/react-native-charts-wrapper#356]
I am getting this error when i run Example in android emulator. 
**Error: `CombinedChart` has no propType for native prop `RNCombinedChart.extraOffsets` of native type `Map`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.**
This error comes even when i click on other few charts. Please help as I am stuck here since few hours.
I have attached the screenshot for the error.
![ss](https://user-images.githubusercontent.com/26712224/44026671-6c36ae8c-9f11-11e8-85f0-25020fdc2bd6.png)

**Comment by wuxudong** [comment]
Which version?

**Comment by DiptiVShinde** [comment]
react-native version is 0.55.0.
node version is 8.11.3

package.json is as following

`{
  "name": "Example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "dependencies": {
    "immutability-helper": "^2.7.1",
    "lodash": "^4.17.10",
    "npm": "^6.3.0",
    "react": "16.1.1",
    "react-native": "0.55.0",
    "react-native-charts-wrapper": "^0.4.3",
    "react-navigation": "^1.5.12"
  },
  "devDependencies": {
    "babel-jest": "21.0.2",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.1.0",
    "react-test-renderer": "15.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by wuxudong** [comment]
It works in my example, try the latest version.

```
 <CombinedChart
            data={this.state.data}
            xAxis={this.state.xAxis}
            onSelect={this.handleSelect.bind(this)}
            onChange={(event) => console.log(event.nativeEvent)}
            marker={this.state.marker}
            highlights={this.state.highlights}
            extraOffsets={{left:100, right:1, top: 1, bottom: 1}}
            style={styles.container}/>
```

<img width="562" alt="screen shot 2018-08-17 at 4 12 43 pm" src="https://user-images.githubusercontent.com/1391101/44255361-67e92100-a238-11e8-8caf-4ba86814b38e.png">

**Comment by DiptiVShinde** [comment]
Thanks a lot! @wuxudong
