### ISSUE TITLE
Area Chart Or Stacked Line Chart

### ISSUE THREAD

**Issue by GowthamGr** [wuxudong/react-native-charts-wrapper#357]
Hi @wuxudong ,
            I have to use Area chart or stacked line chart in my application.Can you please help me to solve .

**Comment by wuxudong** [comment]
It seems a little more work is needed even using native mpandroidchart.  [stackoverflow](https://stackoverflow.com/questions/43342597/android-fill-the-color-between-two-lines-using-mpandroidchart/43452404#43452404)

or you can sum your y value by yourself to make a stacked line chart.

Following chart is based on example->LineChartGradientScreen. 



![simulator screen shot - iphone 6 - 2018-08-14 at 15 25 07](https://user-images.githubusercontent.com/1391101/44077554-a83ca8ee-9fd6-11e8-877d-eb73e4852d54.png)
