### ISSUE TITLE
GroupBarChart rendering issue

### ISSUE THREAD

**Issue by darshan-raj** [wuxudong/react-native-charts-wrapper#358]
The xAxis and the bars are not aligned together. The graph is not scrollable to the right after the end of the x-axis labels are reached.
The config is same as the one in the GroupBarChart example. Am I missing out something here?

![screen shot 2018-08-13 at 9 21 52 pm](https://user-images.githubusercontent.com/1267110/44043239-f5a875b4-9f3f-11e8-902d-5ed7b3ee4631.png)

**Comment by darshan-raj** [comment]
I found a solution. This [issue comment](https://github.com/PhilJay/MPAndroidChart/issues/3154#issuecomment-316998974) in MPAndroidChart helped me.

**Comment by wasim-abuzaher** [comment]
Would you mind posting your solution in JS? Having the same problem
