### ISSUE TITLE
Gradient on IOS not working

### ISSUE THREAD

**Issue by mareapp** [wuxudong/react-native-charts-wrapper#359]
LineChart ,version 0.4.4, fillGradient dont work, always show same blue color like from example (tested on simulator)?

**Comment by wuxudong** [comment]
It looks fine in my simulator?

![simulator screen shot - iphone 6 - 2018-08-14 at 18 44 09](https://user-images.githubusercontent.com/1391101/44087323-107e16c0-9ff2-11e8-91a9-15cb4e42774f.png)

**Comment by mareapp** [comment]
Please tell me your version of swift ,maybe i am something miss during the manual linking

**Comment by wuxudong** [comment]
the v0.4.4 now support cocoapods, you can clean then run example again.

**Comment by mareapp** [comment]
Ok thanks ,i will try

**Comment by mareapp** [comment]
v0.4.4 ,installed by cocoapods, gradient work perfectly on IOS ,thanks man for support
