### ISSUE TITLE
How to set decimal places to 0?

### ISSUE THREAD

**Issue by ywongweb** [wuxudong/react-native-charts-wrapper#36]
First of all big thanks for this awesome lib!

Does anyone know how to set decimal places to 0 so a value of `0` doesn't show up as `.0`?

![image](https://cloud.githubusercontent.com/assets/1422851/25237130/b502eefa-25e1-11e7-95eb-edc65f4d2e48.png)

**Comment by wuxudong** [comment]
Use null instead?

**Comment by ywongweb** [comment]
Setting the `y` value to null seem to cause the chart to not display those columns altogether. 

Note in the screenshot below, the x axis now starts at `day 2` instead of `day 1` because the value of day 1 is **null**, and every day after `day 6` is not displayed because they have a `null` y value.
![image](https://cloud.githubusercontent.com/assets/1422851/25276297/6a4806a6-2691-11e7-8045-e2bfb94d28ee.png)

Is there a way to make the charts to show columns when the value is `{y: 0}` ? 
Or
Show whole numbers like 0, 15, 23 without the decimal place in the screenshots?

**Comment by wuxudong** [comment]
Maybe valueFormatter ,axisMininum , axisMaximum can help

**Comment by ywongweb** [comment]
Where can I find out more about these API? Do you have a link to a doc or repo?

Thanks @wuxudong !

**Comment by wuxudong** [comment]
You can check line chart examples.
 
You can find most of API usage in examples.

**Comment by ywongweb** [comment]
Got it working using `valueFormatter: '#'`. 

Thanks again @wuxudong !
