### ISSUE TITLE
How to use time?

### ISSUE THREAD

**Issue by jmceara** [wuxudong/react-native-charts-wrapper#362]
Hi.
How can I use time in line chart? I'm trying, but chart expect integer or double values.....and I need something like "00:26.3", both in values as in axis label.

Tks!

**Comment by wuxudong** [comment]
Both values and  axis support valueFormatter.

**Comment by jmceara** [comment]
But how do I use? I could not find docummentation for this module :( probabily my mistake.
In the examples I just found valueFormatter with fixed values......that I need is to apply an function to convert my numbers to time before display. Is it possible?

**Comment by wuxudong** [comment]
valueFormatter can accept array, so you can use js to format your timestamps to string array.

**Comment by KakitLee** [comment]
@wuxudong I use unix timestamp to draw the line, and want to show MM-DD format on the xAxis,  I tried to pass in a string array to xAxis.valueForamtter, but then the values on xAxis are all gone. Any idea why?

Regards,

**Comment by wuxudong** [comment]
Can you paste your data and config here?

**Comment by angelos3lex** [comment]
Check solution [here](https://github.com/wuxudong/react-native-charts-wrapper/pull/108), helped me a lot!

**Comment by christopher-18** [comment]
@wuxudong @angelos3lex can you guys suggest something for this https://github.com/wuxudong/react-native-charts-wrapper/issues/908

**Comment by KakitLee** [comment]
> @wuxudong @angelos3lex can you guys suggest something for this #908
> 
> @KakitLee What worked for you? Facing same issue

Hi @christopher-18 I forgot how exactly I fixed the issue but this is something I found in my code previously 

```js
 xAxis: {
        enabled: true,
        fontFamily:"HelveticaNeue-Medium",
        fontWeight:"bold",
        textColor: processColor('white'),
        fontStyle:"italic",
        fontSize: 12,
        drawGridLines: false,
        drawAxisLine: true,
        position:'BOTTOM',
        granularityEnabled: true,
        granularity: 1,
        centerAxisLabels: true,
        axisLineColor: processColor('white'),
        axisLineWidth: 1,
        valueFormatter: 'date',
        valueFormatterPattern: 'dd MMM'
      },
```

**Comment by christopher-18** [comment]
> > @wuxudong @angelos3lex can you guys suggest something for this #908
> > @KakitLee What worked for you? Facing same issue
> 
> Hi @christopher-18 I forgot how exactly I fixed the issue but this is something I found in my code previously
> 
> ```js
>  xAxis: {
>         enabled: true,
>         fontFamily:"HelveticaNeue-Medium",
>         fontWeight:"bold",
>         textColor: processColor('white'),
>         fontStyle:"italic",
>         fontSize: 12,
>         drawGridLines: false,
>         drawAxisLine: true,
>         position:'BOTTOM',
>         granularityEnabled: true,
>         granularity: 1,
>         centerAxisLabels: true,
>         axisLineColor: processColor('white'),
>         axisLineWidth: 1,
>         valueFormatter: 'date',
>         valueFormatterPattern: 'dd MMM'
>       },
> ```

@KakitLee I tried, above but it is returning incorrect values. 
Here's the sample code - 
I get the result in utc so i convert the same to unix timestamp 

Result - 2022-10-11T23:59:59.999

Post conversion - 
```
 const recordingDate = moment(readings?.result)?.format('DD MMM YYYY');
 const recordingDateInTimeStamp = moment(recordingDate)?.unix();
```
 
 // 1665513000
 // value = {x:1665513000, y: 23 }
 
 on doing above - it returns 20th Jan 
 
 I tried this as well 
```
  const xAxisFormat = value.map((val: any) => {
      let date = moment.unix(val?.x)?.format('MMM DD');
      return date;
    });
```
    
    and set it like this -   (but this doesn't show any values on axis)
     ```
      valueFormatter: xAxisFormat,
      valueFormatterPattern: 'dd MMM',
```
Might be some conversion issue, but logs are fine.
