### ISSUE TITLE
Show all markers in HorizontalBarchart

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [wuxudong/react-native-charts-wrapper#364]
Hi is there any way to show all the marker at the same time in HorizontalBarchart?
Here is the code I have been using: 
```
<HorizontalBarChart
                            style={{ flex: 1 }}
                            data={this.state.progressData}
                            xAxis={this.state.progressXAxis}
                            yAxis={this.state.yAxis}
                            marker={{
                                enabled: true,
                                markerColor: processColor('transparent'),
                                textSize: 10,
                                textColor: processColor("black")
                            }}
                            chartDescription={{ text: '' }}
                            legend={this.state.progressLegend}
                            doubleTapToZoomEnabled={false}
                            drawBarShadow={true}
                            pinchZoom={false}

                        />
```
Currently I'm able to show marker only when I tried to click on the bars. But I need to show all the markers every time.

**Comment by wuxudong** [comment]
Why use marker in this case?  I think using value will be better.

**Comment by jeffreyrajanofficial** [comment]
<img width="172" alt="screen shot 2018-08-18 at 7 07 22 pm" src="https://user-images.githubusercontent.com/16349497/44299801-2c268800-a31a-11e8-8d60-7492d9e6f473.png">
I'm trying to achieve the above bar chart, if I use **value** then it will goes inside the bar but I need it on the top like above image. I'm able to achieve it with the marker that's why I'm asking how to show all the marker value

**Comment by jeffreyrajanofficial** [comment]
@wuxudong any help/suggestion on this?

**Comment by wuxudong** [comment]
you can try it in Example->HorizationtalBarChartScreen

```
            highlightPerTapEnabled={false}
            highlightPerDragEnabled={false}            
            highlights={[{x:0},{x:1},{x:2},{x:2},{x:3},{x:4},{x:5},{x:6},{x:7},{x:8}]}
```


but the result is ugly.

![simulator screen shot - iphone 6 - 2018-08-20 at 14 43 22](https://user-images.githubusercontent.com/1391101/44324194-6cefdf80-a487-11e8-92da-1137349d24c6.png)

**Comment by jeffreyrajanofficial** [comment]
Thanks @wuxudong it's working. I agree it looks ugly but in my scenario I have given highlight color as transparent, so it looks better
