### ISSUE TITLE
use of unresolved identifier after upgrading to 0.4.4

### ISSUE THREAD

**Issue by Taylor123** [wuxudong/react-native-charts-wrapper#365]
I'm in an existing project that currently uses `react-native-charts-wrapper: 0.4.3`, and I'm trying to upgrade it to `0.4.4`. Is upgrading the npm package not enough?

When compiling iOS, i receive the following errors:
```
node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift:262:23: use of unresolved identifier 'FontUtils'
node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift:443:31: use of unresolved identifier 'HighlightUtils'
node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/utils/ChartDataSetConfigUtils.swift:65:38: use of unresolved identifier 'IndexValueFormatter'
```

**Comment by wuxudong** [comment]
0.4.4 has moved to cocoapods. 

please follow https://github.com/wuxudong/react-native-charts-wrapper/tree/master/installation_guide to upgrade.

**Comment by andrejcesen** [comment]
Even when transitioning to cocoapods, the problem persists. @Taylor123 Have you managed to make it working?

**Comment by dg92** [comment]
@andrejcesen  any success?

**Comment by andrejcesen** [comment]
@dg92 Nope... still using a version prior to 0.4.4.

**Comment by wuxudong** [comment]
IndexValueFormatter and others are new files added in 0.4.4

if you are upgrading from 0.4.3 and not using cocoapods, you have to do this again.
`create a group under your project top level and add files under directory node_modules/react-native-charts-wrapper/ios/ReactNativeCharts`
