### ISSUE TITLE
Stacked Line Chart

### ISSUE THREAD

**Issue by GowthamGr** [wuxudong/react-native-charts-wrapper#368]
Hi @wuxudong ,
          How to make stacked line chart using this module.Can you please guide me.

**Comment by wuxudong** [comment]
Do you mean chart like #359 ?

**Comment by GowthamGr** [comment]
Yes..How to add values in linear gradient chart

**Comment by GowthamGr** [comment]
Ok @wuxudong  Thanks a lot.I too confirmed that there is no stacked type line chart.
