### ISSUE TITLE
How to clear space between xAxis and bottom label?

### ISSUE THREAD

**Issue by rotationba** [wuxudong/react-native-charts-wrapper#369]
Is any way to reduce or clear the space between xAxis and bottom labels? I didn't found any way from docs. Anyone can help me? Thanks

<img width="252" alt="screen shot 2018-08-23 at 12 48 14 am" src="https://user-images.githubusercontent.com/21239590/44480930-b0f10900-a66e-11e8-88ab-9c779a0dd063.png">

**Comment by wuxudong** [comment]
add yOffset to xAxis.

**Comment by bunnypavan** [comment]
Use Zoom prop and provide scaleX value, For example: { scaleX: 3, scaleY: 1, xValue: -9999, yValue: 1, axisDependency: 'RIGHT' }
