### ISSUE TITLE
LineChart (cubic lines) 

### ISSUE THREAD

**Issue by berkaybeyaz1** [wuxudong/react-native-charts-wrapper#37]
Hello,
How can i draw cubic lines chart with LineChart component or any component ?

**Comment by berkaybeyaz1** [comment]
![68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f63756269636c696e6563686172742e706e67](https://cloud.githubusercontent.com/assets/7584428/25302878/e2336420-2750-11e7-9254-d8caa836b226.png)
I found this https://github.com/danielgindi/Charts inside

**Comment by wuxudong** [comment]
Check 

mode: "CUBIC_BEZIER",

You can find it in LiveUpdateLineExample
