### ISSUE TITLE
Render images instead of circles for data points in LineChart

### ISSUE THREAD

**Issue by angelos3lex** [wuxudong/react-native-charts-wrapper#371]
As i can see in MPAndroidChart library [here](https://github.com/PhilJay/MPAndroidChart/issues/2769), there is an option to insert an image for points instead of circle. 
I searched here but didn't find any option like this, and marker also accepts string values, not icons-images. Is there any way to achieve that?

**Comment by wuxudong** [comment]
Currently, there is no workaround.

PR is welcome.
