### ISSUE TITLE
super.didSetProps cause crashes on iOS

### ISSUE THREAD

**Issue by phuhk** [wuxudong/react-native-charts-wrapper#374]
Hi all, i need your help. I'm use RN 0.50.4, and use lastest version of this lib 0.44 (I'm using BarChart). I facing crash issue on iOS.

This line: super.didSetProps(changedProps) on RNBarLineChartViewBase.swift cause crash, I just remove it then it work well, I don't know real issue of this. Am I wrong in something?

Thanks.

**Comment by wuxudong** [comment]
The examples work fine.
Try latest RN?

**Comment by SunflowerGJ** [comment]
I meet the same error ,and remove it like you because our app used 0.46 and can't update to the latest easily. It works well too. I'll follow the issue for real issue. 🙈

**Comment by AsaYao** [comment]
I meet the same error too , my react native is 0.49.5. what's version will not be crashed. 
Please help.

**Comment by phuhk** [comment]
@AsaYao: 0.56 will not be crashed

**Comment by AsaYao** [comment]
@phuhk  ok, thanks, but i worry about my project upgrade that will meet more bug.o(╥﹏╥)o

but now ,i think it will be the important.
