### ISSUE TITLE
求问react-native-charts-wrapper和react-native-echarts的区别

### ISSUE THREAD

**Issue by SemiraChen** [wuxudong/react-native-charts-wrapper#376]
求问react-native-charts-wrapper和react-native-echarts的区别
一个是基于Web端封装的，一个是基于MPAndroid封装的。
但是不知道该选用哪个比较好。

**Comment by wuxudong** [comment]
In my opinion: 

If you only need simple chart, then those svg based is best choice. 
They are easy to integrate, and platform independent.

If your chart is complicated, you can try native or web based.
