### ISSUE TITLE
Setting background color for value label in bar chart

### ISSUE THREAD

**Issue by manjuy124** [wuxudong/react-native-charts-wrapper#378]
Thanks for providing such a wonderful library. I am trying to set background color for value label in bar chart. But I didn't any available props to set the BG color. Can you please help me with the same?

Here is  the requirement
<img width="135" alt="screen shot 2018-08-29 at 3 40 35 pm" src="https://user-images.githubusercontent.com/29254928/44781560-5b52ba00-aba2-11e8-9802-952288d737dc.png">
.

**Comment by manjuy124** [comment]
ok

**Comment by prpgan** [comment]
Hi @wuxudong, Is there is any chance that, the above requirement is added in the next releases of this library. I have the same issue (not able to give background color to the value above bar)
