### ISSUE TITLE
How to set Value Text Color For Barchart

### ISSUE THREAD

**Issue by vinhhrv** [wuxudong/react-native-charts-wrapper#38]
data: {
        dataSets: [{
          values: [{y: 23}, {y: 105}, {y: 102}, {y: 110}, {y: 114}, {y: 109}, {y: 105}, {y: 99}, {y: 95}],
          config: {
            colors:[processColor('#d3d3d3')],
            valueTextSize: 13,
            **valueTextColor: processColor('green'), // not working**
            valueFormatter: "##",
            barSpacePercent: 40,
            barShadowColor: processColor('lightgrey'),
            highlightAlpha: 90,
            highlightColor: processColor('red'),
          }
        }],
      },

Thank you

**Comment by wuxudong** [comment]
check latest version. support valueTextColor now.
