### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by CoderGMLee** [wuxudong/react-native-charts-wrapper#380]
按照https://github.com/wuxudong/react-native-charts-wrapper/tree/master/Example 步骤一步步操作下来，提示build failed  是我哪里操作有问题吗

** BUILD FAILED **

The following build commands failed:

	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/BarDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/BridgeUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/candlestick/CandleDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/ChartDataSetConfigUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/FontUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/line/LineDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/pie/PieDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartManager.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartView.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartViewBase.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/RNBarLineChartBaseManager.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/RNBarLineChartViewBase.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(13 failures)

**Comment by wuxudong** [comment]
Where is error log?

**Comment by CoderGMLee** [comment]
** BUILD FAILED **


The following build commands failed:

	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/BarDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/BridgeUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/candlestick/CandleDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/ChartDataSetConfigUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/utils/FontUtils.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/line/LineDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/pie/PieDataExtract.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartManager.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartView.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/bar/RNBarChartViewBase.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/RNBarLineChartBaseManager.swift
	CompileSwift normal x86_64 /Users/lgm/Desktop/demos/react-native-charts-wrapper/ios/ReactNativeCharts/RNBarLineChartViewBase.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(13 failures)

Installing build/Build/Products/Debug-iphonesimulator/Example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
this is total log

**Comment by wuxudong** [comment]
There is a common problem of react native that is boost is not correctly compiled in Mac.

Check  the content under  ~/.rncache  .

Try re-download them or download them manually.

**Comment by CoderGMLee** [comment]
tks
