### ISSUE TITLE
Charts are Empty on ios

### ISSUE THREAD

**Issue by droidpree** [wuxudong/react-native-charts-wrapper#383]
Hello everyone.
I am trying to generate the graphics in IOS and they appear blank. They are working perfectly fine on Android. They charts stopped working with the versions 0.4.3

We were using an older version of graph library and recently updated to this version after which the library is not working on ios. I read that the latest version of the library requires swift 4.1 so is there any migration needs to be done when moving from older version to new version?

I have also tried using an older version of the graph library: 0.3.0 but it is not working. I have tried steps mentioned in the issue [#51](https://github.com/wuxudong/react-native-charts-wrapper/issues/51) but still no luck. Any kind of help/guidance will be really appreciated. Let me know if you need any more details from my side

Below are details about Xcode and React Native version 
Infos: Xcode Version 9.4.1
RN 0.48.4

![screen shot 2018-09-03 at 10 48 37 am](https://user-images.githubusercontent.com/33113940/44968912-2ced2a00-af68-11e8-8a28-59af13d5182c.png)

**Comment by wuxudong** [comment]
Why not try 0.4.4?

It supports cocoapods.
