### ISSUE TITLE
Pie chart spaceing issue

### ISSUE THREAD

**Issue by sarry173** [wuxudong/react-native-charts-wrapper#384]
how to remove sapce from pie chart fist value.

![capture](https://user-images.githubusercontent.com/3347527/44997522-a0c11e00-afcc-11e8-8806-24d08404bb6c.PNG)

**Comment by wuxudong** [comment]
remove `maxAngle={350}` ?

**Comment by Jarchisamira** [comment]
maxAngle={360}
