### ISSUE TITLE
More value Can't be loaded in LineChart.

### ISSUE THREAD

**Issue by GowthamGr** [wuxudong/react-native-charts-wrapper#387]
Hi @wuxudong 
             Can you please help me. I cant able to load more than 500 data in yAxis.I cant able to make time series chart using this line chart.

**Comment by wuxudong** [comment]
Please describe it in detail.Screenshot is preferred.

**Comment by wuxudong** [comment]
Android?

**Comment by GowthamGr** [comment]
Yes.

**Comment by wuxudong** [comment]
Please read [README](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md#4--additional-setting) carefully.
