### ISSUE TITLE
Build Failed:  Could not find method implementation()

### ISSUE THREAD

**Issue by abolinhas** [wuxudong/react-native-charts-wrapper#388]
Hi,
I'm getting this error when try build the project
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\DEV\react\Artica\node_modules\react-native-charts-wrapper\android\build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':react-native-charts-wrapper'.
> Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by wuxudong** [comment]
check https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md

**Comment by abolinhas** [comment]
Quick fix.
Inside node_modules\react-native-charts-wrapper\android\build.gradle
Replace
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.facebook.react:react-native:0.20.+'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
}
with
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.facebook.react:react-native:0.20.+'
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.3'
}
