### ISSUE TITLE
paging feature for charts?

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#392]
Hi @wuxudong . I was wondering if there's a paging feature on the charts because I haven't see this feature in this library. I manually tried to do a paging feature by using the onChange props but it's messy. Right now I'm detecting if the event.nativeEvent.left has already reached the page start and page end but it's not ideal because the function i get to invoke gets called a lot of times when I drag the graph. If there is a feature where I can set pages for the charts, please teach me how to do it.

**Comment by wuxudong** [comment]
related discussion #342

**Comment by GermanMontejo** [comment]
I've also used the moveViewToX function. I'll show you a snippet tomorrow as to how I did it. I used the onChange props but like I said it's messy and sometimes my code moves two pages especially if I try to scroll left and right fast. I'll try your snippet as well tomorrow when I get to the office. Thanks for replying. :)

**Comment by wuxudong** [comment]
Currently, moveViewToX and setState both leads to 
>sometimes my code moves two pages especially if I try to scroll left and right fast

No perfect solution at this moment.

**Comment by GermanMontejo** [comment]
Yeah, I was pulling my hair with that too. There's a problem with moveViewToX in that even if I specify it to, let's say, 600, it goes to 0, especially if I'm scrolling fastly to the left. I was thinking of adding a delay so that it would minimize the chances of moving to the wrong x coordinate.

**Comment by Lastin** [comment]
I figured most reliable way is to override function `setData` in `BarLineChartBaseManager`, so that it calls `chart.centerViewTo(x, y, axis)` after calling `super.setData`
Alternatively adding timeout delay (trashy solution) between updating the data for your chart, and actually calling the moveViewToX

**Comment by wuxudong** [comment]
What do you mean by

> Alternatively adding timeout delay (trashy solution) between updating the data for your chart, and actually calling the moveViewToX

Can you provide code snippet about it ?

It looks something like https://github.com/expo/react-native-infinite-scroll-view will be useful.
I will try to  add an example of it.

**Comment by wuxudong** [comment]
Your code can work, but not smooth enough. I think the chart will blink to the beginning x, then move back to where it should be.

**Comment by wuxudong** [comment]
An interesting function is introduced : setDataAndLockIndex.

You can find how to use it in examples->InfiniteScrollLineChartScreen

**Comment by GermanMontejo** [comment]
Thank you @wuxudong !
