### ISSUE TITLE
Data labels are shifted in grouped chart when valueFormatter is used to show specific labels.

### ISSUE THREAD

**Issue by ahmetonol** [wuxudong/react-native-charts-wrapper#393]
With config below, second serie (weight) values are shifted one step to the left (as you see in screenshot). If I use `entry.x` instead of `entry.x.rounded()` in `IndexValueFormatter[.swift].stringForValue` method everything is fine. Why is the `entry.x` value double?

<img width="332" alt="screen shot 2018-09-14 at 08 57 21" src="https://user-images.githubusercontent.com/2670747/45533976-27160500-b802-11e8-980b-8ea3dc890e5f.png">

When I print out `entry.x` in `IndexValueFormatter[.swift].stringForValue` method, I get these outs:
For the height serie, x values are: `0.275, 1.275, 2.275` returned to `0, 1, 2`
For the weight serie, x values are: `0.725, 1.725, 2.725` returned to `1, 2, 3` (These indexes are the main reason of this issue.)

If I remove `valueFormatter` key from the `dataSet` config, it works fine.

```
...
data : {
	dataSets: [
		{
			label: "Avg (Height)"
			values: [
				{y: 33.92514879828818},
				{y: 32.74131093966461},
				{y: 33.333540262047215}
			],
			config: {
				drawValues: true,
				valueFormatter: ["33,9%", "32,7%", "33,3%"],
				...
			}
		},
		{
			label: "Avg (Weight)"
			values: [
				{y: 32.93348343467342},
				{y: 33.871499880880016},
				{y: 33.195016684446564}
			],
			config: {
				drawValues: true,
				valueFormatter: ["32,9%", "39,9%", "33,2%"],
				...
			}			
		}
	], 
	config: {
		barWidth: 0.44
		group: {
			barSpace: 0.01,
			fromX: 0,
			groupSpace: 0.1
		}
	}
},
xAxis: {
	....
	valueFormatter: ['Germany', 'Japan', 'Turkey']
}
...
```

Thanks.

**Comment by wuxudong** [comment]
I think #171  may help

**Comment by ahmetonol** [comment]
> I think #171 may help
Thanks, I'll check it out.

**Comment by ahmetonol** [comment]
Thanks, I'll check it out.

**Comment by ahmetonol** [comment]
Sorry, #171 didn't help. I fixed this by removing `.rounded()` from `entry.x.rounded()` in `IndexValueFormatter[.swift].stringForValue` method.  Will this fix cause any problems in the future?

**Comment by wuxudong** [comment]
The main problem is when you are using **Grouping** Bar Chart, the underline MpAndroidChart/Charts will change x value of your data, this will bring problem for highlighting/IndexValueFormatter. (highlighting need equal x, IndexValueFormatter need integer x).

Solution 1: don't use IndexValueFormatter,  I think `valueFormatter: "#.#'%'"` can work for you.

Solution 2: avoid using **Grouping** Bar Chart when you are using highlighting/IndexValueFormatter like [solution of issue 171](https://github.com/wuxudong/react-native-charts-wrapper/issues/171#issuecomment-355892262).

**Comment by ahmetonol** [comment]
I see. I am going to use Solution 1.
Thanks for your help.
