### ISSUE TITLE
how to set show xAxis maxValue?

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#394]
xAxis: {
                // fontFamily:"HelveticaNeue-Medium",
                // fontWeight:"bold",
                axisMaximum: 288,
                axisMinimum: 0,
                // fontStyle:"italic",
                valueFormatter: time,
                // valueFormatterPattern: 'HH:mm',
                granularityEnabled: true,
                granularity: 1,
                labelCount:8,
                position: 'BOTTOM',
                textColor:processColor('white')
            },
xAxis data is time array of one value per 5 minutes: [00:00, 00:05, ... 24:00]

![image](https://user-images.githubusercontent.com/2498958/45661982-76c23c80-bb32-11e8-94ec-77a5c9f7abad.png)

I just want to set the maxValue is 24：00，how to do ? Anybody help me, thanks

**Comment by wuxudong** [comment]
What is your x value ? not valueFormatter.

**Comment by s349856186** [comment]
> notice the gap between two labels, it is 1 hour and 20 minutes, there is no space for 24:00.
> 
> if you continue zoom in, then you will find 24:00 there.

@wuxudong How to control the gap between two labels? no need to be one hour and 20 minutes

**Comment by wuxudong** [comment]
visibleRange: PropTypes.shape({
      x: PropTypes.shape({
        min: PropTypes.number,
        max: PropTypes.number
      }),
      y: PropTypes.shape({
        left: PropTypes.shape({
          min: PropTypes.number,
          max: PropTypes.number
        }),
        right: PropTypes.shape({
          min: PropTypes.number,
          max: PropTypes.number
        })
      })

**Comment by s349856186** [comment]
xAxis: {
                axisMaximum: 288,
                axisMinimum: 0,
                valueFormatter: time,
                valueFormatterPattern: 'HH:mm',
                granularityEnabled: true,
                granularity: 36,
                labelCount:8,
                position: 'BOTTOM',
                textColor:processColor('white'),
                visibleRange:{
                    x:{
                        min:8,
                        max:8,
                    }
                }
            },
![image](https://user-images.githubusercontent.com/2498958/45799773-3228d380-bce1-11e8-84dd-8c0237c65801.png)

Sorry, I don't quite understand how to use it. Can you make it clear? thank you very much

**Comment by wuxudong** [comment]
you can check example->BarChartScreen.js for help. visibleRange is used in that example.

**Comment by s349856186** [comment]
I have tried it, not work. Can you help me solve？thanks @wuxudong 

![image](https://user-images.githubusercontent.com/2498958/45805920-5b059480-bcf2-11e8-8e43-be4baeab9f0c.png)
![image](https://user-images.githubusercontent.com/2498958/45805990-80929e00-bcf2-11e8-9977-455927703ab5.png)
![image](https://user-images.githubusercontent.com/2498958/45806008-8a1c0600-bcf2-11e8-8678-d99afc5ec881.png)

**Comment by wuxudong** [comment]
Which version?

**Comment by s349856186** [comment]
> Which version?

"react-native-charts-wrapper": "^0.4.1",

**Comment by wuxudong** [comment]
visibleRange is fixed in 0.4.4.

**Comment by s349856186** [comment]
> visibleRange is fixed in 0.4.4.

@wuxudong I upgrade to 0.4.5, but not work too

**Comment by wuxudong** [comment]
You have to set data first, then you can set visibleRange. Or you can set them together in `setState`

It won't work in following code:


	constructor() {
	    super();

	    this.state = {
	      data: {}
	    }
	}
	componentDidMount {
	    this.setState{data: {...}}
	}

	render {
	    <LineChart           
	        data={this.state.data}
	        visibleRange={ {  x: {    min: 2,    max: 2  }}}            
	    />
	}

**Comment by s349856186** [comment]
my data not empty, but not work.
Here is my code structure, so where is the problem? Thank you very much

          this.state({
                        str1: [0],
                        str2: [0],
                        str3: [0],
                        str4: [0],
                       visibleRange: {
                            x: { min: 8, max: 8 }
                        },
              })

 getData(){
             ......
              this.setState({
                        str1: data1,
                        str2: data2,
                        str3: data3,
                        str4: data4,
                       visibleRange: {
                            x: { min: 8, max: 8 }
                        },
              })
          ........
}

refreshPower(str1, str2, str3, str4){
        return {
            data: {
                dataSets:
                    [{
                        values: str1,         
                        .......
                    },{
                        values: str2,         
                        .......
                    },{
                        values: str3,         
                        .......
                    },{
                        values: str4,         
                        .......
                    },
                ],
            },
           xAxis: {
                axisMinimum: 0,
                valueFormatter: time,
                granularityEnabled: true,
                granularity: 1,
                position: 'BOTTOM',
                textColor:processColor('white'),
            },
         ........
}


render() {
              const {str1, str2, str3, str4} = this.state;
              const config = this.refreshPower(str1, str2, str3, str4);
       return (
               <LineChart
                        ref={(chart)=>(this.chart=chart)}
                        data={ config.data }
                        legend={config.legend}
                        marker={config.marker}
                        xAxis={config.xAxis}
                        yAxis={config.yAxis}
                        visibleRange={this.state.visibleRange}
                        drawGridBackground={false}
                        borderColor={processColor('gray')}
                        borderWidth={1}
                        drawBorders={true}           
                        onSelect={this.handleSelect.bind(this)}
                        onChange={(event) => console.log(event.nativeEvent)}
                    />
         )
}

**Comment by wuxudong** [comment]
try remove 

                   visibleRange: {
                        x: { min: 8, max: 8 }
                    },

in the initialization of your state.

**Comment by s349856186** [comment]
@wuxudong Thanks，I remove it, but not ideal

const time = ["0:00","0:05","0:10","0:15","0:20", ....... , "23:50","23:55","24:00"]；

![image](https://user-images.githubusercontent.com/2498958/46057664-68ef6580-c189-11e8-9e5e-cbb2dd777270.png)

**Comment by wuxudong** [comment]
It looks fine, only 8 entries in the chart, why not ideal?

**Comment by s349856186** [comment]
![image](https://user-images.githubusercontent.com/2498958/46057968-0ac38200-c18b-11e8-915e-e0aea8e4038d.png)
I want it start '0:00' and end '24：00‘，how to set

**Comment by wuxudong** [comment]
This work for me.

    data: {  
        dataSets: [{
          values: Array.from(new Array(289), (val, index) => index),
          label: 'Company X',        
        }],
      },

      xAxis: {          
          valueFormatter: ["00:00","00:05","00:10","00:15","00:20","00:25","00:30","00:35","00:40","00:45","00:50","00:55","01:00","01:05","01:10","01:15","01:20","01:25","01:30","01:35","01:40","01:45","01:50","01:55","02:00","02:05","02:10","02:15","02:20","02:25","02:30","02:35","02:40","02:45","02:50","02:55","03:00","03:05","03:10","03:15","03:20","03:25","03:30","03:35","03:40","03:45","03:50","03:55","04:00","04:05","04:10","04:15","04:20","04:25","04:30","04:35","04:40","04:45","04:50","04:55","05:00","05:05","05:10","05:15","05:20","05:25","05:30","05:35","05:40","05:45","05:50","05:55","06:00","06:05","06:10","06:15","06:20","06:25","06:30","06:35","06:40","06:45","06:50","06:55","07:00","07:05","07:10","07:15","07:20","07:25","07:30","07:35","07:40","07:45","07:50","07:55","08:00","08:05","08:10","08:15","08:20","08:25","08:30","08:35","08:40","08:45","08:50","08:55","09:00","09:05","09:10","09:15","09:20","09:25","09:30","09:35","09:40","09:45","09:50","09:55","10:00","10:05","10:10","10:15","10:20","10:25","10:30","10:35","10:40","10:45","10:50","10:55","11:00","11:05","11:10","11:15","11:20","11:25","11:30","11:35","11:40","11:45","11:50","11:55","12:00","12:05","12:10","12:15","12:20","12:25","12:30","12:35","12:40","12:45","12:50","12:55","13:00","13:05","13:10","13:15","13:20","13:25","13:30","13:35","13:40","13:45","13:50","13:55","14:00","14:05","14:10","14:15","14:20","14:25","14:30","14:35","14:40","14:45","14:50","14:55","15:00","15:05","15:10","15:15","15:20","15:25","15:30","15:35","15:40","15:45","15:50","15:55","16:00","16:05","16:10","16:15","16:20","16:25","16:30","16:35","16:40","16:45","16:50","16:55","17:00","17:05","17:10","17:15","17:20","17:25","17:30","17:35","17:40","17:45","17:50","17:55","18:00","18:05","18:10","18:15","18:20","18:25","18:30","18:35","18:40","18:45","18:50","18:55","19:00","19:05","19:10","19:15","19:20","19:25","19:30","19:35","19:40","19:45","19:50","19:55","20:00","20:05","20:10","20:15","20:20","20:25","20:30","20:35","20:40","20:45","20:50","20:55","21:00","21:05","21:10","21:15","21:20","21:25","21:30","21:35","21:40","21:45","21:50","21:55","22:00","22:05","22:10","22:15","22:20","22:25","22:30","22:35","22:40","22:45","22:50","22:55","23:00","23:05","23:10","23:15","23:20","23:25","23:30","23:35","23:40","23:45","23:50","23:55","24:00"],
          granularityEnabled: true,
          granularity : 36,        
          labelCount:9,
      },  

0-24 has 9 labels !! 

and notice that the count is 289 ( 12 * 24 + 1). otherwise data of 24:00 will be lost, then the label will disappear.

![simulator screen shot - iphone 6 - 2018-09-26 at 14 39 08](https://user-images.githubusercontent.com/1391101/46061645-f2a72f00-c199-11e8-8550-137f647c5a77.png)

**Comment by s349856186** [comment]
Sorry, it's my fault, i got it wrong。Thank you for your patience guidance。Can you help me check https://github.com/wuxudong/react-native-charts-wrapper/issues/403 ？
