### ISSUE TITLE
show x value for non numeric value

### ISSUE THREAD

**Issue by mosleim** [wuxudong/react-native-charts-wrapper#395]
I need to show xLabel for every bar, and set the xlabel as a string. but, i don't know how to show. i have try to write some of code, but this not work. 
Copy Paste from [example here](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/StackedBarChartScreen.js).
    
    constructor() {

    super();

    this.state = {
      legend: {
        enabled: true,
        textSize: 14,
        form: "SQUARE",
        formSize: 14,
        xEntrySpace: 10,
        yEntrySpace: 5,
        wordWrapEnabled: true
      },
      data: {
        dataSets: [{
          values: [{y:[1,1,3], marker: ["row1", "row2", "row3"]}, {y:[1, 2, 1], marker:"second"}, {y:[3, 2, 5], marker:["hello", "world","third"], label:"Cell1"}, {y:[3, 5, 1], marker:"fourth"}],
          label: 'Metals Detected Chart',
          config: {
            colors: [processColor('#C0FF8C'), processColor('#FFF78C'), processColor('#FFD08C'),processColor('#FFD08C')],
            stackLabels: ['Pairs', 'Lefts', 'Rights', 'Unconfirmed']
          }
        }],
      },
      highlights: [{x: 1, stackIndex: 2}, {x: 2, stackIndex: 1}],
      xAxis: {
        valueFormatter: ['Q1', 'Q2', 'Q3', 'Q4'],
        label:['ASC1', 'ASC2','ASC3','ASC4'],
        granularityEnabled: true,
        granularity: 1,
        drawLabels: true,
        enable:true,
        centerAxisLabels: true
      }

    };
    }

and the result:

<img width="312" alt="jepretan layar 2018-09-19 pada 06 57 13" src="https://user-images.githubusercontent.com/3499544/45723091-cdcf1c80-bbd9-11e8-8ad1-a7208aa65dba.png">

and my need result:
I need a label for every bar. Look like "ASC1", "ASC2", "ASC3", "ASC4".

**Comment by wuxudong** [comment]
valueFormatter:['ASC1', 'ASC2','ASC3','ASC4']  ?

**Comment by mosleim** [comment]
it's work.
