### ISSUE TITLE
labelCount and labelCountForce not working

### ISSUE THREAD

**Issue by makoy21** [wuxudong/react-native-charts-wrapper#397]
`yAxis={{
            left: {
              fontSize: 12,
              enabled: true,
              valueFormatter: [
                "",
                "0",
                "Label 1",
                "Label 2",
                "Label 3",
                "Label 4",
                "Label 5",
                "Label 6",
                "Label 7",
              ],
              axisMinimum: 0,
              axisMaximum: 9,
              labelCount: 9,
              labelCountForce: true,
            },
            right: {
              enabled: false,
            },
          }}`

<img width="323" alt="scatterchart" src="https://user-images.githubusercontent.com/9860394/45732256-0ab50680-bc0e-11e8-8022-327682830f0d.png">

Expected Output:

<img width="325" alt="scatter chart expected output" src="https://user-images.githubusercontent.com/9860394/45732290-359f5a80-bc0e-11e8-8e35-28ab2212374b.png">

**Comment by wuxudong** [comment]
check #331, 

    granularityEnabled: true,
    granularity : 1,

may help.
