### ISSUE TITLE
请问iOS端怎么集成呢？我不是很懂swift

### ISSUE THREAD

**Issue by lenglengiOS** [wuxudong/react-native-charts-wrapper#4]

**Comment by lenglengiOS** [comment]
而且没有用cocoapods

**Comment by wuxudong** [comment]
照说明文档做一遍？
cocoapods装一个好了，也就一个命令的事情。。

**Comment by wuxudong** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/tree/master/Example 里有个 step by step tutorial
