### ISSUE TITLE
Draw a lines with many colors

### ISSUE THREAD

**Issue by ludovic-coder** [wuxudong/react-native-charts-wrapper#40]
I dont find any implementation of multiple colors for Lines ? Like red before Y: 0 and green after Y:0. Is there a way to do that with that wrapper ?

**Comment by ludovic-coder** [comment]
Use Colors instead of Color one the dataset...

**Comment by ludovic-coder** [comment]
But I don't know how to do that without assign a color to a value.

**Comment by sircrocodile10** [comment]
any solution?
