### ISSUE TITLE
配置不成功

### ISSUE THREAD

**Issue by zhou-ting** [wuxudong/react-native-charts-wrapper#402]
按照https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md这个一步一步配的，就是不管安卓还是ios都编译不成功啊！！疯了。配了3天了。网上的各种教程也不行。跪求作者赐我一个中文版的步骤啊。我怀疑是自己理解错了啊

**Comment by wuxudong** [comment]
错误是什么?

**Comment by zhou-ting** [comment]
The following build commands failed:
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Jobs/AnimatedViewPortJob.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Animation/Animator.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/BarChartRenderer.swift

        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Charts/BarLineChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/BubbleChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/CandleStickChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Data/Implementations/ChartBaseDataSet.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Utils/ChartUtils.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Charts/ChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/HorizontalBarChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Charts/HorizontalBarChartView.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Components/Legend.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/LegendRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/LineChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Renderers/PieChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Charts/PieChartView.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Charts/PieRadarChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartTest/ios/Pods/Charts/Source/Charts/Utils/Platform+Accessibility.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(19 failures)

我是参照了一半http://www.kuajieyuan.com/post/H1xQuT5lQm这个教程，再结合着你的步骤来配置的。但是由于英语水平太有限，迷失在了你link subproject这一步，这一步有use cocoapods(suggested)，有manual setup，我用的是use cocoapods(suggested)，然后这里面没有“xcode中，在你的项目顶层下面创建一个Group盛放node_modules/react-native-charts-wrapper/ios/ReactNativeCharts，最直接有效的方法就是在Finder中看到ReactNativeCharts这个文件夹，将它直接拖到顶层下，如图所示：”（就是上面那个链接教程中的第三步）；报的错应该不值得你帮我看。你能帮我缕缕你的步骤不？感谢！另外。我的RN版本是0.55.4，CocoaPods版本是1.5.3，yarn版本是0.21.3，npm版本是4.1.2，node的版本是7.7.2

**Comment by wuxudong** [comment]
如果 用 cocoapods 的话， 就不需要再 手动创建 Group了。 那个教程比较老了，参考意义不大。

就完全照着 https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md 跑一遍 ？忽略 manual setup的部分。

**Comment by zhou-ting** [comment]
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Jobs/AnimatedViewPortJob.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Animation/Animator.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/BarChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Charts/BarLineChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/BubbleChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/CandleStickChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Data/Implementations/ChartBaseDataSet.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Utils/ChartUtils.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Charts/ChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/HorizontalBarChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Charts/HorizontalBarChartView.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Components/Legend.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/LegendRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/LineChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Renderers/PieChartRenderer.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Charts/PieChartView.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Charts/PieRadarChartViewBase.swift
        CompileSwift normal x86_64 /Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Utils/Platform+Accessibility.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(19 failures)

完全按照  https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md  这个步骤来的了，忽略了 munual setup的部分的。create ios/Podfile这一步我是：先进入ios文件夹，再执行vim Podfile，然后把你文档中的部分粘贴进去，:wq结束，再open Podfile，把里头'demo'改成我自己的项目名称，然后pod install，再打开xx.xcworkspace，创建一个空的swift文件。结果还是编译不通过呢。是我create ios/Podfile这一步有问题吗？

**Comment by wuxudong** [comment]
** BUILD FAILED ** 的具体原因？

**Comment by zhou-ting** [comment]
/Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Components/Legend.swift:318:31: error: type 'NSAttributedString' has no member 'Key'
            let labelAttrs = [NSAttributedString.Key.font: labelFont]
好像是这个

**Comment by wuxudong** [comment]
项目的 swift 版本不对吧。 最新的xcode?
更改下 项目里的swift 版本 到 >= 4.1 ?

**Comment by zhou-ting** [comment]
xcode版本是9.4。更改项目里的swift版本是在Build Settings=>Swift Compiler-Language=>Swift Language Version，选择Swift 4.1吗？我改了，但是还是编译失败：
/Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Jobs/AnimatedViewPortJob.swift:74:46: error: type 'RunLoop' has no member 'Mode'
        _displayLink.add(to: .main, forMode: RunLoop.Mode.common)
                                             ^~~~~~~ ~~~~
ObjectiveC.NSObject:160:15: note: did you mean 'zone'?
    open func zone() -> NSZone!
              ^
ObjectiveC.NSObject:162:21: note: did you mean 'zone'?
    open class func zone() -> NSZone!
                    ^
Foundation.RunLoop:8:15: note: did you mean 'runMode'?
    open func runMode(_ mode: RunLoopMode, beforeDate limitDate: Date) -> Bool
              ^
/Users/zhouting/Desktop/ChartOne/ios/Pods/Charts/Source/Charts/Jobs/AnimatedViewPortJob.swift:81:51: error: type 'RunLoop' has no member 'Mode'
        _displayLink.remove(from: .main, forMode: RunLoop.Mode.common)
                                                  ^~~~~~~ ~~~~
ObjectiveC.NSObject:160:15: note: did you mean 'zone'?
    open func zone() -> NSZone!
              ^
ObjectiveC.NSObject:162:21: note: did you mean 'zone'?
    open class func zone() -> NSZone!
                    ^
Foundation.RunLoop:8:15: note: did you mean 'runMode'?
    open func runMode(_ mode: RunLoopMode, beforeDate limitDate: Date) -> Bool

非常感谢耐心的回复！

**Comment by sonnh58** [comment]
i have same issue Xcode 9.3

**Comment by wuxudong** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/tree/master/Example

这个跑的通么？

**Comment by zhou-ting** [comment]
我是跑不通的，
/Users/zhouting/Desktop/react-native-charts-wrapper/Example/ios/Pods/Charts/Source/Charts/Components/Legend.swift:318:31: error: type 'NSAttributedString' has no member 'Key'
            let labelAttrs = [NSAttributedString.Key.font: labelFont]

**Comment by wuxudong** [comment]
这个还是 swift 版本的问题， 改到 4.1/4.2

**Comment by zhou-ting** [comment]
现在是4.1呢？而且那个地方选项只有Swift 3.3，Swift 4.1，Unspecified

**Comment by wuxudong** [comment]
好奇怪，把pod里面的swift版本也选4.1

**Comment by zhou-ting** [comment]
pod里面的swift版本就是你文档里的create ios/Podfile里面的config.build_settings['SWIFT_VERSION'] = '4.1'吗？这里是4.1啊。今天我又拉了一个新项目，还是编译不过，RN版本是0.55.4
![snip20180921_7](https://user-images.githubusercontent.com/22723026/45865132-0ecc5a00-bdaf-11e8-8ba0-4abd082dd52b.png)

**Comment by wuxudong** [comment]
在xcode里也确认一下这两个的swift 版本？

<img width="1399" alt="screen shot 2018-09-21 at 3 46 47 pm" src="https://user-images.githubusercontent.com/1391101/45867302-b3ea3100-bdb5-11e8-8691-bff83886f5a8.png">
<img width="889" alt="screen shot 2018-09-21 at 3 47 09 pm" src="https://user-images.githubusercontent.com/1391101/45867303-b482c780-bdb5-11e8-8133-f7975365e1a9.png">

**Comment by zhou-ting** [comment]
是4.1呢，
![snip20180921_8](https://user-images.githubusercontent.com/22723026/45867880-037d2c80-bdb7-11e8-82b7-4583a345de2d.png)
![snip20180921_9](https://user-images.githubusercontent.com/22723026/45867883-04ae5980-bdb7-11e8-9801-17a3a611ea8c.png)

**Comment by xiaomingtan** [comment]
@zhou-ting 我有同样的问题，请问你解决了吗

**Comment by imzyf** [comment]
最新版的 chart 好像要 Xcode10，尝试用前一版本

**Comment by xiaomingtan** [comment]
chart 用 3.1.1，成功了

**Comment by xiaomingtan** [comment]
@nthegedus  this is the solution #409
