### ISSUE TITLE
How to hide zero values in StackedBarChart ?

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#403]
https://github.com/wuxudong/react-native-charts-wrapper/issues/174  is BarChart，how to do with StackedBarchart ?
![image](https://user-images.githubusercontent.com/2498958/45915675-9b4c4a80-be8b-11e8-973f-d50065b54b2e.png)

**Comment by s349856186** [comment]
@wuxudong can you help me, thanks

**Comment by s349856186** [comment]
@wuxudong sorry, My technique is poor, I don't know how provide my valueFormatter.

![image](https://user-images.githubusercontent.com/2498958/46129985-c27b9100-c26a-11e8-8978-b7e7943ed8df.png)
![image](https://user-images.githubusercontent.com/2498958/46130006-ceffe980-c26a-11e8-8a17-0f87f507305b.png)
![image](https://user-images.githubusercontent.com/2498958/46130039-de7f3280-c26a-11e8-9ffe-e706eb6a0ed4.png)

@wuxudong Can i control the click on the bar  not just a part?

**Comment by wuxudong** [comment]
Do you mean highlight whole bar?

`highlightFullBarEnabled: PropTypes.bool` can help

**Comment by jenipharachel** [comment]
@s349856186 How did you manage to remove the 0s at the base of the graph that indicate the stacks that dont contain any value? I'm struggling a bit here for removing them. If it's not possible got to find a new library :(

**Comment by jenipharachel** [comment]
> This feature is not supported.
> 
> Maybe you can provide your own valueFormatter.

Hi @wuxudong, If you dont mind, can you explain a bit how this can be done?

**Comment by s349856186** [comment]
@jenipharachel
<BarChart
data={dataSets: [{  config: {drawValues: false,}   }]}  />

This will hide all data even if the value is greater than 0
