### ISSUE TITLE
How to show value data in foriegn currency(By deafult it's Indian Rupee)?

### ISSUE THREAD

**Issue by brahmy** [wuxudong/react-native-charts-wrapper#405]
Question 1-->I have been implementing "React-native-charts-wrapper" .I have got struck with one issue i.e i need to show value data along with difference currency symbols.How can i achieve this?

Ex: expected --> Y-axis value data $4000,$5000 etc.
 But Actual -->Y axis value data 4000,5000 etc.

Question 2-->How can i show X-axis valueFormater data in the bottom by default the data is displaying on the top of the graph.

Please provide solution.Thank you..

**Comment by wuxudong** [comment]
1. valueFormatter: "'$'#",
2.  position: 'BOTTOM'

please check examples first.
