### ISSUE TITLE
Granularity as an array?

### ISSUE THREAD

**Issue by Lastin** [wuxudong/react-native-charts-wrapper#407]
Would it be possible to apply granularity like colors, or valueFormatter?
So that I could have values for Y axis like [-4, 0, 4, 100, 200, 300...] or similar.

Alternatively other solution for showing combined chart where there is a massive gap between bottom values and the top values.

At the moment I'm displaying 2 combined charts, and syncing them with `zoom` prop and `onChange` function. But it's imperfect, as it's all async and chart width may differ, as some data starts at 9th, 12th, 24th day etc. and the chart crops the null values. 
![screenshot_1537861894](https://user-images.githubusercontent.com/5638394/46000419-69f89800-c0a0-11e8-9f2f-1a2cd6f2b99a.png)

**Comment by wuxudong** [comment]
I add a new property 'group' and 'identifier' for linkage chart. 

It will improve performance a lot. 
Check the example in examples-> linkageChart in master branch  for detail.

Currently it has not been published.  Make it a try.

**Comment by Lastin** [comment]
Tested it. Works way better than syncing it over react-native. One issue I faced:
After data changes, the first chart doesn't make second chart move. But the second one still moves the first one.

**Comment by wuxudong** [comment]
I reproduce the bug. 
It can be fixed.

**Comment by wuxudong** [comment]
that bug only exists in android, not iOS.

check out latest master branch .

**Comment by Lastin** [comment]
Confirming it fixes it on Android. Haven't tested with iOS this at all actually :see_no_evil:
