### ISSUE TITLE
Can't compile using xcode 10 and RN 0.57.1

### ISSUE THREAD

**Issue by jmceara** [wuxudong/react-native-charts-wrapper#409]
Hi.

Anyone have success compiling using RN 0.57.1 and iOS?
I'm trying a fresh-new app with XCode 10, Swift 4.2 (already tried with 4.0 and 4.1) and latest version of charts wrapper, no success :(
Also tried with Charts 3.1.1 and 3.2.0, no success.

Android version works without any problem!
Since I'll use firebase, I can't use 'use_frmeworks!' in cocoapods.....so I'm doing manual install (addiding "Charts" and "SwiftyJSON" in Podfile), but no success.....a lot of errors when ocmpiling Charts library :(

If I remove RNChartsWrapper from project, everything works/compile fine! Already checked Bridge file, looks ok. Also create a group and added files (from tutorial).

**Comment by xiaomingtan** [comment]
hi, Do u try to use piechart  on android ? i use it , but it causes my app crash, do u have same problem?
beause my environment same to u

**Comment by wuxudong** [comment]
Now,  v0.4.7 is for swift 4.2 and XCode 10, and v0.4.6 is for swift 4.1 and XCode 9.x

**Comment by wuxudong** [comment]
I tried Example, it works fine.

I can run it from 'react-native run-ios' or from XCode . 

 0.4.88888 should be a writing mistake, or you can try master branch (a few bug fix).

**Comment by jmceara** [comment]
Ok, I've made changes and commited to you (you already merged). Demo compiels fine.

But since I could not find any forum relates to this lib, I'll use this space (since still open) for one more question, if there's ok for you @wuxudong .


I'm trying to build this lib into my existing app that uses, among other libs, Firebase.....so I can't use "use_frameworks!". I'm doing a manual install and I can install Charts and Swifty without problems. I have followed instructions one by one, created bridge file, created a group, add all files (including folders) into this group, etc etc.....but when I try to ocmpile, I'm getting this error:
"Use of unresolved identifier 'BridgeUtils' (RNChartViewBase.swift).

Also, got more errors like this, but for "FontUtils" (RNChartViewBase.swift).

I've added all files in Bridge header....I don't knwo how to fix this. What am I missing?

**Comment by jmceara** [comment]
More info:
Group with files:
![screen shot 2018-10-03 at 21 08 22](https://user-images.githubusercontent.com/3300517/46446123-d46ca080-c750-11e8-9851-7296508fef2a.png)


Error:
![screen shot 2018-10-03 at 21 09 17](https://user-images.githubusercontent.com/3300517/46446137-e8180700-c750-11e8-9dde-c02d9d187a9c.png)

**Comment by wuxudong** [comment]
I make a try, and it success.

here is my step:

1. react-native init demo
2. yarn add react-native-charts-wrapper  (0.4.8 is installed)
3. update App.js just like tutorial
4. open XCode, create a group. add source files to it, notice the folder color. I'm not quite sure what does color difference means. Mine is yellow, yours is blue. 

<img width="1054" alt="screen shot 2018-10-04 at 10 25 56 am" src="https://user-images.githubusercontent.com/1391101/46449686-0406c180-c7c0-11e8-9557-c10da096c871.png">

5. add Podfile and pod install:

```
    target 'demo' do
        pod 'SwiftyJSON', '4.0.0'      
        pod 'Charts', '3.2.0'         
    end
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end 
```
6. Add a bridging file with following content:

```
#import "React/RCTBridge.h"
#import "React/RCTViewManager.h"
#import "React/RCTUIManager.h"
#import "React/UIView+React.h"
#import "React/RCTBridgeModule.h"
#import "React/RCTEventDispatcher.h"
#import "React/RCTEventEmitter.h"
#import "React/RCTFont.h"

```


6. I found there are some errors when compiling js, so I add `yarn add @babel/runtime`

7. XCode compiles success, and runs well.

**Comment by ionush** [comment]
@wuxudong I've run the above example multiple times but still having problems integrating it into a real project. The bridging header sets itself automatically as well

react-native-charts-wrapper 0.4.8, rn 0.56.0, x-code 10, swift 4.

terminal error:
```
Build system information

error: Multiple commands produce '/Users/ionush/app/ios/build/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/RNNBridgeManagerDelegate.h':
1) Target 'ReactNativeNavigation' (project 'ReactNativeNavigation') has copy command from '/Users/ionush/app/node_modules/react-native-navigation/lib/ios/RNNBridgeManagerDelegate.h' to '/Users/ionush/app/ios/build/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/RNNBridgeManagerDelegate.h'
2) Target 'ReactNativeNavigation' (project 'ReactNativeNavigation') has copy command from '/Users/ionush/app/node_modules/react-native-navigation/lib/ios/RNNBridgeManagerDelegate.h' to '/Users/ionush/app/ios/build/Build/Products/Debug-iphonesimulator/include/ReactNativeNavigation/RNNBridgeManagerDelegate.h'



** BUILD FAILED **
```

X-code errors:

```
<unknown>:0: error: module map file '/Users/ionush/Library/Developer/Xcode/DerivedData/app-cbfptdlbzlquabgqqjftrhwuvdzy/Build/Products/Debug-iphonesimulator/Charts/Charts.modulemap' not found
<unknown>:0: error: module map file '/Users/ionush/Library/Developer/Xcode/DerivedData/app-cbfptdlbzlquabgqqjftrhwuvdzy/Build/Products/Debug-iphonesimulator/Charts/Charts.modulemap' not found
2 errors generated.
<unknown>:0: error: failed to emit precompiled header '/Users/ionush/Library/Developer/Xcode/DerivedData/app-cbfptdlbzlquabgqqjftrhwuvdzy/Build/Intermediates.noindex/PrecompiledHeaders/app-Bridging-Header-swift_2B6B0YRKJDRB8-clang_QTCJQ9P43BPF.pch' for bridging header '/Users/ionush/app/ios/RNCharts/app-Bridging-Header.h'
```
and
```

Showing All Messages
Failed to emit precompiled header '/Users/ionush/Library/Developer/Xcode/DerivedData/app-cbfptdlbzlquabgqqjftrhwuvdzy/Build/Intermediates.noindex/PrecompiledHeaders/app-Bridging-Header-swift_2B6B0YRKJDRB8-clang_QTCJQ9P43BPF.pch' for bridging header '/Users/ionush/app/ios/RNCharts/app-Bridging-Header.h'


Showing All Messages
Module map file '/Users/ionush/Library/Developer/Xcode/DerivedData/app-cbfptdlbzlquabgqqjftrhwuvdzy/Build/Products/Debug-iphonesimulator/Charts/Charts.modulemap' not found
```

**Comment by iksent** [comment]
I had an errors, trying to compile project on iOS using [this guide](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md) but then I realised, that I had Xcode < 10.0. So firstly I updated my macOS to the last version `10.13.6`, then updated Xcode to `10.1`. Then I got much more errors like:
```charts wrapper 'commonModes' was obsoleted in Swift 4.2```

Then I deleted my `DerivedData` folder and made changes in Podfile:
```
pod 'Charts', '3.2.0' <----- from 3.1.1 in guide
and
config.build_settings['SWIFT_VERSION'] = '4.2' <------ from 4.1 in guide
```
And it finally got compiled!

**Comment by gifary** [comment]
@iksent can you share your POD file, please? i got same problem

**Comment by rzdev** [comment]
Hi, i've got an error "Type 'NSAttributedString' has no member 'Key'" while compiling, any suggestion what to do?  I've selected Swift 4.1, and done everything the official guide instructed to do.  Thank you

**Comment by neemssoni** [comment]
Upgrade to Charts 0.4.7 version, it will work, it works for me.

**Comment by julianklumpers** [comment]
No matter what i try. Pod install, manual install. i keep getting the swift compiler error.
I'm using React-native version 0.59.5 and Xcode version 10.2

**Comment by wuxudong** [comment]
What error? Can you attach screenshots?

**Comment by derekbar90** [comment]
Had the same issues myself, @julianklumpers try using all the same install steps (use pod method) but when installing react-native-charts-wrapper in your package.json use 

    "react-native-charts-wrapper": "github:wuxudong/react-native-charts-wrapper.git#9711489caaf5b92ade00a2d93752d62a194496d8",

instead of 

"react-native-charts-wrapper": "0.5.2",

rather than the release version (0.5.2) package on NPM. I've found that the NPM release is missing files and so the build will continuously break but the repo contains them.

**Comment by wuxudong** [comment]
0.5.5 is available.

**Comment by mufaawan** [comment]
For me following steps worked. 
1- Delete pods folder
2- cd  ios  && pod update
3- restart xcode
4- clean and rebuild
> Success

**Comment by hpelitebook745G2** [comment]
@mufaawan @wuxudong I still get these errors even with:
react-native-charts-wrapper: 0.5.5
Xcode: 10.2.1
reat-native: 0.59.9

**Comment by 15110011** [comment]
![image](https://user-images.githubusercontent.com/37216098/78111775-5eb9c180-7427-11ea-9ffb-994e514eb50c.png)
I'm facing with this problem, how to solve it?
- react-native-charts-wrapper: 0.5.7
- Xcode: 11
- reat-native: 0.61.2

**Comment by choychris** [comment]
@wuxudong same issue as @15110011 
react-native-charts-wrapper: 0.5.7
Xcode: 11.3
react-native: 0.61.5

1. When I use `react-native run-ios`, no build problem
2. When I use xcode to build/run, the issue happens

I can help looking it up, but I need a little hint to start. Thanks in advance.

**Comment by Obi1Kennoby** [comment]
For me, the error happened when I am trying to build a release version in Xcode

**Comment by abraham1912** [comment]
> ![image](https://user-images.githubusercontent.com/37216098/78111775-5eb9c180-7427-11ea-9ffb-994e514eb50c.png)
> I'm facing with this problem, how to solve it?
> 
>     * react-native-charts-wrapper: 0.5.7
> 
>     * Xcode: 11
> 
>     * reat-native: 0.61.2

https://blog.csdn.net/book_1992/article/details/109058227
