### ISSUE TITLE
你好,请问怎么设置才能使得每一个x的label 和每一个数据对应

### ISSUE THREAD

**Issue by SpadeKingW** [wuxudong/react-native-charts-wrapper#41]
请问怎么设置才能做到以下的这种:
比如设置x轴两个label之间的间距固定(假设为60),然后我会有n个数据那么这个长度就是(n-1)*x,如果这个长度大于屏幕的宽度,那么这个图表就可以左右滑动,跟设置了zoom属性的scaleX属性大于1一样

**Comment by wuxudong** [comment]
granularityEnabled: true,
granularity: 60

**Comment by SpadeKingW** [comment]
<img width="893" alt="default" src="https://cloud.githubusercontent.com/assets/12854467/25511006/c9df0816-2bf6-11e7-846a-909e9213a71b.png">
试过了没啥作用,添加这个属性前后的对比图:
<img width="372" alt="before" src="https://cloud.githubusercontent.com/assets/12854467/25511030/ee4a4e22-2bf6-11e7-89c3-43d9e50cb331.png">

<img width="374" alt="after" src="https://cloud.githubusercontent.com/assets/12854467/25511046/0ca29582-2bf7-11e7-87db-d447e4221e56.png">

**Comment by wuxudong** [comment]
what does 60 means?
60 px/dp? or 60 entries?

**Comment by wuxudong** [comment]
Does it related to [view port](https://github.com/PhilJay/MPAndroidChart/wiki/Modifying-the-Viewport)

**Comment by SpadeKingW** [comment]
<img width="1083" alt="default" src="https://cloud.githubusercontent.com/assets/12854467/25512706/55b89022-2c02-11e7-95d3-ceb0b768c123.png">
I want to config the width of grid

**Comment by wuxudong** [comment]
Sorry, I don't know how to do that. 
and you can check MpAndroidChart first to see if there is any setting can do it for you, then I will add it in react-native.

**Comment by SpadeKingW** [comment]
OK,Thanks anyway.I've done it with setting granularityEnabled:true and zoom={scaleX:(n-1)/x,...}, n is the number of entities and x is the entites u want to show in one screen.
