### ISSUE TITLE
Bubble Chart size does not work?

### ISSUE THREAD

**Issue by GermanMontejo** [wuxudong/react-native-charts-wrapper#411]
hi @wuxudong. I'm trying to alter the size of the bubble marker on a combined chart with a bubble dataset. Even if I added a size parameter, the size is still small and it does not change. I'm trying to get to a size of 50 or more, so it would be visible on my chart with varying zoom levels.

```
// this is the structure of the bubbleData (dataset)
bubbleData: {
          dataSets: [{
            values: this.bubbleMarkerOn,
            label: '',
            config: {
              drawValues: false,
              colors: [processColor('red')]
            }
          }, {
            values: this.bubbleMarkerOff,
            label: '',
            config: {
              drawValues: false,
              colors: [processColor('gray')]
            }
          }]
        }

// in another function that gets called every second, i do this:
const bubbleMarkerOn = this.bubbleMarkerOn.slice();
bubbleMarkerOn.push({x: ctr - 1, y: this.plotPointY, size: 50});
this.bubbleMarkerOn = bubbleMarkerOn;
```

Can you help me figure out the solution for this @wuxudong ?

**Comment by wuxudong** [comment]
I don't think `bubbleMarkerOn.push({x: ctr - 1, y: this.plotPointY, size: 50});` will work directly in react.

Do you forget to call setState again?

**Comment by GermanMontejo** [comment]
Adding an element to bubbleMarkerOn does work, because the bubbleMarkerOn is a local array which contains the copy (slice) of the this.bubbleMarkerOn (instance variable). I was able to bypass this issue by using a scatterData. I tried the same thing in scatterData and just used a CIRCLE scatterShape with a high value for the scatterShapeHoleRadius. I'll just close this issue.
