### ISSUE TITLE
xAxis position not accurate

### ISSUE THREAD

**Issue by mosleim** [wuxudong/react-native-charts-wrapper#413]
hi all,
i use this [example](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/GroupBarChartScreen.js). But, when my data is just 4 or more then 10, xAxis label position to y data is not  accurate. 

how to make automatic  groupSpace and center bar to xLabel(xAxis) on groupbarchart?
 
<img width="375" alt="gambar png" src="https://user-images.githubusercontent.com/3499544/46188016-e396bd00-c310-11e8-8cea-a79f0c1dfb63.png">

**Comment by wuxudong** [comment]
config: {
          barWidth: 0.2,
          group: {
            fromX: 0,
            groupSpace: 0.1,
            barSpace: 0.1,
          },
        }

is used in example, but it may not work for you.

check following equation.

(barSpace + barWidth) * countInGroup + groupSpace = 1

**Comment by mosleim** [comment]
And it's work!
Thank's @wuxudong. :-)

**Comment by Parlegrandpa** [comment]
Hi @mosleim please how did you fix this? cc: @wuxudong
