### ISSUE TITLE
How to keep the charts accurate？

### ISSUE THREAD

**Issue by RPeast** [wuxudong/react-native-charts-wrapper#415]
There is no way for them to interact accurately when I am linking the two charts. Is there a good way to deal with it？Both charts use the same zoom，And I also set the friction coefficient：
```
dragDecelerationEnabled={false}
dragDecelerationFrictionCoef={0}
```
This is the method I use：
```
  if (event.action === 'chartScaled' || event.action === 'chartTranslated') {
            let chart1Zoom = Object.assign({}, this.state.chart1Zoom, { xValue: event.centerX });
            this.setState({ chart1Zoom: chart1Zoom });
        }
```
The chart never kept in sync as my fingers moved quickly from side to side
Can you help me out? Thanks

**Comment by wuxudong** [comment]
related to #407

**Comment by wuxudong** [comment]
I add a new property 'group' and 'identifier' for linkage chart. 

It will improve performance a lot. 
Check the example in examples-> linkageChart in master branch  for detail.

Currently it has not been published.  Make it a try.

**Comment by RPeast** [comment]
Thank you very much! I'll try it now
