### ISSUE TITLE
How to build with Xcode 8.3.2

### ISSUE THREAD

**Issue by fundon** [wuxudong/react-native-charts-wrapper#42]
![screen shot 2017-04-28 at 15 05 40](https://cloud.githubusercontent.com/assets/27926/25517932/3055015e-2c24-11e7-96a1-c41f35b35062.png)

> You should make sure set this file in your target -> Build Settings -> Swift Compiler - General -> Object-C Bridging Header

Not found

**Comment by wuxudong** [comment]
Try  it.
Create a  dummy swift file. then delete it.

**Comment by fundon** [comment]
-
