### ISSUE TITLE
如何设置yAxis使得蜡烛图与Y坐标对应上

### ISSUE THREAD

**Issue by ximolang** [wuxudong/react-native-charts-wrapper#420]
你好，这是我Y坐标轴的设置：
hey，This is setting code about YAxis
```
yAxis: {
        left: {
          enabled: false
        },
        right: {
          enabled: true,
          valueFormatter: '#.00',
          gridColor: processColor('#f3f3f3'),
        }
      },
```
![image](https://user-images.githubusercontent.com/25032899/46596714-12cadc80-cb10-11e8-973c-d2f8e436e870.png)

发现右边绿色线旁边的坐标刻度是可以自动缩放的，具体以怎样的规则缩放不清楚，然后当我往左滑时，数据值变小，右边的刻度值如下图所示，174.5和右边173.4值对不上了，求助！
I found the right yAxis can scale autoly, and when the data number change, Scale also change, the problem is the candle of 174.5 is a wrong yAxis. Help me ,thanks.

![image](https://user-images.githubusercontent.com/25032899/46596850-6806ee00-cb10-11e8-96b3-06e7b1107324.png)

**Comment by wuxudong** [comment]
Can you provide sample data to reproduce the problem?

**Comment by wuxudong** [comment]
It looks like you are using right y axis, try add `axisDependency: 'RIGHT'` in your data config, the default value is left.
