### ISSUE TITLE
Change BarWidth of PieChart

### ISSUE THREAD

**Issue by ninjat003** [wuxudong/react-native-charts-wrapper#423]
How can change default BarWidth of PieChart?

**Comment by wuxudong** [comment]
BarWidth of PieChart?

I don't understand.

**Comment by wuxudong** [comment]
a thinner ring?

you can reduce the size of chart or add extraOffset to it.

**Comment by spacewideweb** [comment]
![download](https://user-images.githubusercontent.com/15638915/46676654-46c20280-cbe1-11e8-97c0-e69241347abc.png)
I wanted to show like this without reducing of overall component size.

**Comment by wuxudong** [comment]
increase holeRadius: PropTypes.number ?

**Comment by spacewideweb** [comment]
How can remove label on PieChart Item? 
![screen shot 2018-10-09 at 4 47 17 pm](https://user-images.githubusercontent.com/15638915/46677479-019ed000-cbe3-11e8-920a-31c250958648.png)

**Comment by wuxudong** [comment]
... Please make a try by yourself.

**Comment by spacewideweb** [comment]
I am trying to remove the labels for 2 hours, but couldn't find the proper props.

**Comment by spacewideweb** [comment]
Thanks for your help

**Comment by wuxudong** [comment]
drawEntryLabels

drawValues
