### ISSUE TITLE
Use of unresolved identifier 'ChartGroupHolder'

### ISSUE THREAD

**Issue by angelos3lex** [wuxudong/react-native-charts-wrapper#424]
After update to xcode 10, and swift 4.2, I get the following error:
Use of unresolved identifier 'ChartGroupHolder'
```
/Users/username/appName/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/RNChartViewBase.swift:511:21: Use of unresolved identifier 'ChartGroupHolder'
```
RN version 0.56

**Comment by wuxudong** [comment]
It is new files added in latest version. 

I think you need to integrate it again, or manually add new files.
