### ISSUE TITLE
Reduce space between bars in BarChart and visible range shows gapping between values of XAxis

### ISSUE THREAD

**Issue by 123afzal** [wuxudong/react-native-charts-wrapper#425]
Issue 1 => I want bars in my BarChart having 0  space between them but I didn't get anything from documentation.
Issue 2=> Secondly when I set visibleRange to more than 10 or 10 it shows gapping on the XAxis data

I want less space between bars and go gapping on Xaxis when I want to show 15 to 20 bars at a time
![inked43672971_1609739835798344_7184159575174545408_n_li](https://user-images.githubusercontent.com/26060386/46733929-ca8ff380-cca2-11e8-995f-6f7f09e7233a.jpg)
![inked43620110_1108449589305652_8389013994668556288_n_li](https://user-images.githubusercontent.com/26060386/46733935-d085d480-cca2-11e8-9de6-a7ff6acfb08c.jpg)

**Comment by 123afzal** [comment]
Here's the code for your review
`              
        this.state = {
            legend: {
                enabled: true,
                textSize: 14,
                form: 'SQUARE',
                formSize: 12,
                formToTextSpace: 6,
                wordWrapEnabled: false,
                maxSizePercent: 0.5,
            },
            data: {
                dataSets: [{
                    values: [{y: 1.00}, {y: 1.00}, {y: 1.00}, {y: 1.00}, {y: 1.00}, {y: 1.05}, {y: 1.45}, {y: 1.50}, {y: 1.50},
                        {y: 1.75}, {y: 1.45}, {y: 1.05}, {y: 2.00}, {y: 2.01}, {y: 2.05}, {y: 2.35}, {y: 2.30}, {y: 2.60},
                        {y: 2.60}, {y: 3.50}, {y: 10.00}, {y: 9.65}, {y: 7.00}, {y: 6.00}, {y: 8.00}, {y: 7.00}, {y: 6.00}],
                    label: 'Years',
                    config: {
                        color: processColor('skyblue '),
                        barShadowColor: processColor('lightgrey'),
                        highlightAlpha: 90,
                        highlightColor: processColor('red'),
                    },
                }],

                config: {
                    barWidth: 0.5,
                },
            },
            // highlights: [{x: 3}, {x: 6}],
            xAxis: {
                valueFormatter: ['1998', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007','1998', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007','1998', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007'],
                granularityEnabled: true,
                granularity : 1,
                enabled: true,
                drawLabels: true,
                drawAxisLine: true,
                drawGridLines: false,
                position:'BOTTOM',
                axisLineWidth: 2,
                axisLineColor: processColor('grey'),
                labelRotationAngle:90
            },

            yAxis: {
                left: {
                    enabled: true,
                    drawLabels: true,
                    drawAxisLine: true,
                    axisLineColor: processColor('grey'),
                    drawGridLines: true,
                    axisLineWidth: 2,
                },
                right: {
                    enabled: false,
                }
            }
        };



 <View style={{height:250, width:350,  transform: [{ rotate: "-90deg" }]}}>
                    <Text style={styles.vertcileLable}>
                        billions
                    </Text>
                    <BarChart
                        style={styles.chart}
                        data={this.state.data}
                        xAxis={this.state.xAxis}
                        yAxis={this.state.yAxis}
                        animation={{durationX: 2000}}
                        legend={this.state.legend}
                        gridBackgroundColor={processColor('#ffffff')}
                        visibleRange={{x: { min: 10, max: 15}}}
                        onChange={(event) => console.log(event.nativeEvent)}
                        labelRotationAngle={45}
                    />
                </View>`

**Comment by 123afzal** [comment]
@wuxudong  I resolved issue 2 but issue, but I am still stuck with issue, Can you plz reply

**Comment by wuxudong** [comment]
I can see in your config:

```
config: {
                barWidth: 0.5,
            },

```

but you are asking 0 space .......

**Comment by 123afzal** [comment]
not 0 but as close as possible.
How I reduce space not 0 ?

**Comment by 123afzal** [comment]
Thanks
