### ISSUE TITLE
How to clear LimitLines

### ISSUE THREAD

**Issue by RPeast** [wuxudong/react-native-charts-wrapper#426]
I had a problem using LimitLines，I looked through the code and found no way to clear LimitLines，At the moment, I can only call axis. RemoveAllLimitLines () in android native. To clear it, but this method seems to be out of date. Is there a better way。

in android Clear and add：
```
 axis.removeAllLimitLines();
 axis.addLimitLine(limitLine);
```

**Comment by wuxudong** [comment]
fixed.

**Comment by shikshik** [comment]
@wuxudong , how it was fixed?
Lines are consists of each render even when I clean the limitLines array.
removeAllLimitLines method is not available for yAxis.

Any ideas how to clear the lines on each render (without breaking the chart component).

Thanks!

**Comment by shikshik** [comment]
Thanks for reopening, is there an alternative option to show some custom line with a changing value to use for a financial chart? I want to show the current market price which is a dynamic value over a custom line and label.

I thought the limit lines is a good solution but it never clears it once you set it.

Thanks!

**Comment by Luomusha** [comment]
+1

**Comment by shikshik** [comment]
@wuxudong , after checking your commits, it seems like you did fix the issue but didn't update the npm project so we get an old version without your fix.

**Comment by vlkosinov** [comment]
@shikshik did you solve this problem?

**Comment by shikshik** [comment]
@vlkosinov , I solved it from a different angle, did a PR (It's updated in my [comment](https://github.com/wuxudong/react-native-charts-wrapper/issues/426#issuecomment-437440080))
