### ISSUE TITLE
How to format bytes in yAxisValue with valueFormatter

### ISSUE THREAD

**Issue by richfisher** [wuxudong/react-native-charts-wrapper#43]
I want to format the labels in yAxis, the values are bytes. 

For example, the value is 3*1024*1024, I want to show it as 3MB in yAxis.

Is it possible, thanks!

**Comment by wuxudong** [comment]
valueFormatter: PropTypes.oneOfType([
    PropTypes.oneOf(['largeValue', 'percent']),
    PropTypes.string,
    PropTypes.arrayOf(PropTypes.string)
  ]),

try largeValue

**Comment by richfisher** [comment]
refer https://github.com/PhilJay/MPAndroidChart/wiki/The-AxisValueFormatter-interface

LargeValueFormatter: Can be used for formatting large values > "1.000". It will turn values like "1.000" into "1k", "1.000.000" will be "1m" (million), "1.000.000.000" will be "1b" (billion) and values like one trillion will be e.g. "1t".

I think I need to convert the data in dataset first, then format the data with "# MB". thanks!
