### ISSUE TITLE
Axis Dependency for 3 or More YAxis Lines in Line Chart 

### ISSUE THREAD

**Issue by GowthamGr** [wuxudong/react-native-charts-wrapper#432]
Hi @wuxudong 

MyOutput:
![screenshot_1540480468](https://user-images.githubusercontent.com/12936293/47511410-c4e7ff80-d897-11e8-94b8-7446f7e62b1a.png)

MyCode:
try{
            fetch('xxxx?fromDate='+from+' 00:00:00&toDate='+to+' 00:00:00', {
                method: 'GET',
                headers: {
                    Accept: 'application/json',
                    'Content-Type': 'application/json',
                    'Authorization': 'JWT '+this.state.tokenvalmp
                },
            }).then((response) => response.json()).then((responseJson)=>{
                console.log("responseJson1111111111111111",responseJson);
                if(responseJson.status=="ok") {
                    var jsonVal=responseJson.pricechartListsData;
                    var jsonDataVal=jsonVal[0].data;
                    var jsonDataVal1=jsonVal[1].data;
                    var jsonDataVal2=jsonVal[2].data;
                    var jsonParseData=[];
                    var jsonParseData1=[];
                    var jsonParseData2=[];
                    var finalArr=[];

                    console.log("jsonDataVal",jsonDataVal);
                    this.setState({
                        xValData:[]
                    })

                    for (var i=0;i<jsonDataVal.length;i++){
                        var splitval=jsonDataVal[i].date;
                        var parts = splitval.trim().split(' ');
                        var date = parts[0].split('-');
                        var time = (parts[1] ? parts[1] : '00:00:00').split(':');
                        var d = new Date(date[0],date[1]-1,date[2],time[0],time[1],time[2]);
                        var timestamp=d.getTime();

                        jsonParseData.push({x:timestamp,y:jsonDataVal[i].value})
                    }

                    for (var i=0;i<jsonDataVal1.length;i++){
                        var splitval=jsonDataVal1[i].date;
                        var parts = splitval.trim().split(' ');
                        var date = parts[0].split('-');
                        var time = (parts[1] ? parts[1] : '00:00:00').split(':');
                        var d = new Date(date[0],date[1]-1,date[2],time[0],time[1],time[2]);
                        var timestamp=d.getTime();

                        jsonParseData1.push({x:timestamp,y:jsonDataVal1[i].value})
                    }

                    for (var i=0;i<jsonDataVal2.length;i++){
                        var splitval=jsonDataVal2[i].date;
                        var parts = splitval.trim().split(' ');
                        var date = parts[0].split('-');
                        var time = (parts[1] ? parts[1] : '00:00:00').split(':');
                        var d = new Date(date[0],date[1]-1,date[2],time[0],time[1],time[2]);
                        var timestamp=d.getTime();

                        jsonParseData2.push({x:timestamp,y:jsonDataVal2[i].value})
                    }

                    //console.log("MP ParseData", jsonParseData);
                    const size = 80;
                    this.setState(
                        update(this.state, {
                            data: {
                                $set: {
                                    lineData: {
                                    dataSets: [{
                                        values: jsonParseData,
                                        label: '',
                                        config: {
                                            lineWidth: 1.15,
                                            drawValues: false,
                                            drawAxisLine: false,
                                            circleRadius: 5,
                                            drawCircles: false,
                                            highlightEnabled: false,
                                            drawHighlightIndicators: false,
                                            color: processColor('red'),
                                            drawFilled: false,
                                            valueTextSize: 10,
                                            axisDependency: 'right',
                                            //fillColor: processColor('red'),
                                            // fillAlpha: 45,
                                            //circleColor: processColor('red')
                                        }
                                    },
                                        {
                                            values: jsonParseData1,
                                            label: '',
                                            config: {
                                                lineWidth: 1.15,
                                                drawValues: false,
                                                drawAxisLine: false,
                                                circleRadius: 5,
                                                drawCircles: false,
                                                highlightEnabled: false,
                                                drawHighlightIndicators: false,
                                                color: processColor('green'),
                                                drawFilled: false,
                                                valueTextSize: 10,
                                                axisDependency: 'right',
                                                //fillColor: processColor('red'),
                                                // fillAlpha: 45,
                                                //circleColor: processColor('red')
                                            }
                                        },
                                        {
                                            values: jsonParseData2,
                                            label: '',
                                            config: {
                                                lineWidth: 1.15,
                                                drawValues: false,
                                                drawAxisLine: false,
                                                circleRadius: 5,
                                                drawCircles: false,
                                                highlightEnabled: false,
                                                drawHighlightIndicators: false,
                                                color: processColor('blue'),
                                                drawFilled: false,
                                                valueTextSize: 10,
                                                axisDependency: 'left',
                                                //fillColor: processColor('red'),
                                                // fillAlpha: 45,
                                                //circleColor: processColor('red')
                                            }
                                        }],
                                }}
                            },
                        })
                    );
                }else{
                }this.setState({
                    isLoading:false,
                });
                
            }).catch((error)=>{
                // alert(error);
                console.error("MP error",error);
            });

        }catch (e) {
            alert(e);
        }

Dependency:
"dependencies": {
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.2",
    "babel-preset-react-native": "^5.0.2",
    "immutability-helper": "^2.7.1",
    "jwt-decode": "^2.2.0",
    "react": "16.4.1",
    "react-native": "^0.56.0",
    "react-native-animatable": "^1.3.0",
    "react-native-charts-wrapper": "^0.4.3",
    "react-native-google-signin": "^1.0.0-rc3",
    "react-native-image-picker": "^0.27.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.11.2"
  },

I need third line should be like other two axis.please guide me.

**Comment by wuxudong** [comment]
I am afraid this is not supported by any chart lib.

It looks confusing for having more than 3 y axis.

I have no idea how it will looks like,  can you show me a demo pic?

**Comment by GowthamGr** [comment]
Expected output

![screenshot from 2018-10-26 10-33-52](https://user-images.githubusercontent.com/12936293/47545633-e6360380-d90a-11e8-9a19-b1ee9c126b04.png)

**Comment by wuxudong** [comment]
Not supported.

Sorry.
