### ISSUE TITLE
Missing labels and columns in xAxis

### ISSUE THREAD

**Issue by datvudang** [wuxudong/react-native-charts-wrapper#433]
Hi @wuxudong ,
I need to show all months, but some labels and columns are missing
I tried all values from 1 to 12 for axisMaximum but did not work.

<img width="377" alt="screen shot 2018-10-26 at 3 31 34 pm" src="https://user-images.githubusercontent.com/15977562/47555790-e77d2580-d936-11e8-8bdd-30c259d71d66.png">

There is my config
```
xAxis: {
        valueFormatter: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        axisMaximum: 8,
        axisMinimum: 0,
        centerAxisLabels: true,
        avoidFirstLastClipping: true,
        position: 'BOTTOM',
      },
```

And
`visibleRange={{ x: { min: 12, max: 12 } }}`

**Comment by wuxudong** [comment]
What about remove 

        
        axisMaximum: 8,
        axisMinimum: 0,

**Comment by datvudang** [comment]
After remove 
```
 axisMaximum: 8,
 axisMinimum: 0,
```

![image](https://user-images.githubusercontent.com/15977562/47625204-3d7be400-db56-11e8-863c-e52ff24ea984.png)

**Comment by andreypaul** [comment]
Same problem.

**Comment by datvudang** [comment]
Nothing happens, still the same error.

**Comment by andreypaul** [comment]
Still the same error too...

**Comment by wuxudong** [comment]
Maybe something like this:

      xAxis: {
        valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Seq', 'Oct', 'Nov', 'Dec'],
        granularityEnabled: true,
        granularity: 1,
        axisMaximum: 12,
        axisMinimum: 0,
        labelCount: 12,
        centerAxisLabels: true
      },

![simulator screen shot - iphone 6 - 2018-10-31 at 09 49 48](https://user-images.githubusercontent.com/1391101/47761160-57522e00-dcf2-11e8-9d0e-b859b32c6e13.png)

**Comment by datvudang** [comment]
That works.
Thanks!
