### ISSUE TITLE
Whether the highest and lowest values of the current screen can be displayed

### ISSUE THREAD

**Issue by RPeast** [wuxudong/react-native-charts-wrapper#434]
How can I capture the highest and lowest values of the current page and draw them in the corresponding position，thanks!

**Comment by wuxudong** [comment]
I don't get what you mean.

**Comment by RPeast** [comment]
Like this,

![image](https://user-images.githubusercontent.com/38761029/47689191-c876e000-dc23-11e8-81a1-de992e3bdc7c.png)

**Comment by wuxudong** [comment]
You can calculate your highest and lowest values of data by yourself, but currently there is no way to get x/y range of current window.

**Comment by wuxudong** [comment]
I think you can use onChange function.

you can find following 

{
action: "chartTranslated"
bottom: -60.39999999999998
centerX: 148.84643866292237
centerY: 302
left: 49.013105329589024
right: 248.67977199625568
scaleX: 3
scaleY: 1
target: 465
top: 664.4
}

in event.nativeEvent

**Comment by RPeast** [comment]
I tried what you said，But I found that I couldn't call the onChange method when I set dragEnabled to false

**Comment by wuxudong** [comment]
I don't understand your meaning.

If user can't drag/zoom chart, then I think you can just find max/min value by iterating your data.

**Comment by RPeast** [comment]
Hi wuxudong,I can carry on the custom to the icon highlighted now, but I don't know how to convey the highlighted to the chart below, can you help me?
![ws](https://user-images.githubusercontent.com/38761029/48334549-00efd280-e696-11e8-9d27-4a016f4960fe.png)

**Comment by gshoanganh** [comment]
can you update data Candlesticks chart?
