### ISSUE TITLE
handleSelect(event) receives null when a second click is made on same bar of any chart in the example.

### ISSUE THREAD

**Issue by asd-ftw** [wuxudong/react-native-charts-wrapper#436]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Actual Behavior - console.log(event.nativeEvent) logs the value at first click but is returning empty {} on second consecutive click on the same element and I receive red screen if i try to access any value using "entry.data"

![error](https://user-images.githubusercontent.com/25449257/47713250-d2b6cf80-dc5f-11e8-909c-5adf831d2af9.png)

### Steps to Reproduce the Problem
run the example of the library successfully and then make 2 consecutive clicks on same element of the chart.

### Specifications

  - Version: react-native 0.55.5 , react-native-charts-wrapper 0.4.5

**Comment by wuxudong** [comment]
A second click is made on same bar means deselect, so return null is the expected behavior.

**Comment by asd-ftw** [comment]
Thanks for confirming but the problem is that it is also not going in the "If" condition of the handleSelect function , which I understand is for the the deselecting purpose , right?
Because what I'm trying to do is sending the data in event.data to the next page and then when i come back to the graph again using back button(react- navigation)  and click on the previously selected element , I get the error that event.data is undefined object as it receives null.
I'm fairly new so please correct me if I'm wrong.
Any help is appreciated.

**Comment by wuxudong** [comment]
Do you mean that user will automatically jump to next page when user click data?

In this case, you will manually deselect it by using `highlights([])` before jump
