### ISSUE TITLE
index of selected value in pie chart as parameter to handleSelect

### ISSUE THREAD

**Issue by prasanth95** [wuxudong/react-native-charts-wrapper#437]
### Steps to Reproduce the Problem
Had an issue with handleSelect since not getting index of selected value in pie chart.

Ex:
data = [120,80,60,120,70]

**Unable to identify which 120 is selected though handleSelect.**

**Comment by wuxudong** [comment]
Try the complete data form just like example did. You can add your own identifier in data.

**Comment by prasanth95** [comment]
@wuxudong Thanks. Got it
