### ISSUE TITLE
The month name is repeated

### ISSUE THREAD

**Issue by andreypaul** [wuxudong/react-native-charts-wrapper#439]
xAxis: {
                valueFormatter: "date",
                valueFormatterPattern: " MMM",
                textColor: processColor("black"),
                textSize: 10,
                granularityEnabled: true,
                granularity: 1,
                drawLabels: true,
                drawGridLines: false,
                avoidFirstLastClipping: false,
                position: "BOTTOM"
            },

<img width="313" alt="2018-10-31 14 52 41" src="https://user-images.githubusercontent.com/17850013/47786456-e5dba500-dd1c-11e8-9d57-dd35bb16310f.png">

The month name is repeated on the x-axis. Must be Jan, Feb, Mar, Apr.... etc.

**Comment by wuxudong** [comment]
check your data

**Comment by andreypaul** [comment]
@wuxudong for example:
<img width="799" alt="2018-10-31 15 57 51" src="https://user-images.githubusercontent.com/17850013/47789511-c7c67280-dd25-11e8-8919-ac4901ef2024.png">

**Comment by wuxudong** [comment]
.........

**Comment by wuxudong** [comment]
X is expected to be Unix timestamp when date valueFormatter is used

**Comment by christopher-18** [comment]
@wuxudong  Any help on this https://github.com/wuxudong/react-native-charts-wrapper/issues/908 would be appreciated.
