### ISSUE TITLE
Do not draw candles in combinedCharts on ios

### ISSUE THREAD

**Issue by sokolenko100** [wuxudong/react-native-charts-wrapper#445]
Hello! I have problem with draw candles in combinedCharts on ios.  I can draw line charts with gradient.

` <CombinedChart
            style={styles.wrapper}
            data={data}
            marker={marker}
            chartDescription={{ text: '' }}
            legend={legend}
            xAxis={xAxis}
            yAxis={yAxis}
            xEntrySpace={false}
            highlightEnabled ={true}
            highlights={this.state.highlights}
            maxVisibleValueCount={116}
            autoScaleMinMaxEnabled={true}
            chartBackgroundColor={processColor('#1A2736')}
            highlightFullBarEnabled={true}
            drawValueAboveBarEnabled ={true}
            drawBarShadowEnabled = {true}
            zoom={zoom}
            scaleYEnabled={false}
            doubleTapToZoomEnabled={false}
          />`

my data --->
`candleData: {
          dataSets: [{
            values: mainDataChartCandle,
            label: '',
            config: {
              highlightColor: this.darkGrayColor,
              shadowColor: this.blackColor,
              shadowWidth: 1,
              shadowColorSameAsCandle: true,
              increasingColor: this.decreasColor,
              increasingPaintStyle: 'FILL',
              decreasingColor: this.increasColor,
              drawValues: false
            }
          }]`

**Comment by Luomusha** [comment]
@sokolenko100 回来吧问题关了。

**Comment by wuxudong** [comment]
It is a bug introduced by Charts 3.2.1,  and it is fixed but not published yet.
