### ISSUE TITLE
Can't run the example code

### ISSUE THREAD

**Issue by Dgs-asohail4** [wuxudong/react-native-charts-wrapper#447]
I have installed the library and linked the library code for android. I have a running application in which i copy pasted the code from /Example.
### Expected Behavior
All charts should be working.
### Actual Behavior
I am getting same error for all the example screens inside /Example

### Screenshots
![screenshot_1542643487](https://user-images.githubusercontent.com/39798653/48719236-d32efe80-ec3e-11e8-802e-cd13f89e2da9.png)

### Specifications

  - Version: 0.5.0
  - Platform: android 
  - Subsystem: Windows

[Edit]:
I think there is some issue with the library at npm because when i copy paste the source code from this repository and link the LineChart etc with the local code in my code base .. everything seems to be working but when i import the from the npm package it breaks.

**Comment by AngelsProjects** [comment]
same issue... any solution for this?

**Comment by Dgs-asohail4** [comment]
The only workaround i found is to download the source code copy the lib folder and use locally, npm package seems to be broken

**Comment by AngelsProjects** [comment]
> The only workaround I found is to download the source code copy the lib folder and use locally, npm package seems to be broken

it still not working and also it that's not the best solution.

**Comment by Dgs-asohail4** [comment]
> > The only workaround I found is to download the source code copy the lib folder and use locally, npm package seems to be broken
> 
> it still not working and also it that's not the best solution.

Yes it not best possible but it seems to be only solution until the package is fixed. It is working for me though

**Comment by nayfusaurus** [comment]
Same issue for me on React-Native 0.57.5 on Android. The issue doesn't happen on iOS.

> The only workaround i found is to download the source code copy the lib folder and use locally, npm package seems to be broken

@Dgs-asohail4 temporary workaround worked for me

**Comment by leo-tavares** [comment]
Please check if you accidentally imported the `import {global} from 'core-js'`

The exempla has version react-native 0.56.0 . This version is broken in windows platform, you need upgrade to 0.57+

**Comment by AngelsProjects** [comment]
> Please check if you accidentally imported the `import {global} from 'core-js'`
> 
> The exempla has version react-native 0.56.0 . This version is broken in windows platform, you need upgrade to 0.57+

So i would have to remove that import to fix this issue??

**Comment by leo-tavares** [comment]
A while ago I had this same problem, after a long time I realized that I accidentally gave a self-import in this `import {global} from 'core-js'`
This solved my problem.

**Comment by Dgs-asohail4** [comment]
i am on v0.57 and i am pretty sure that i have no such import in my project

**Comment by c-goettert** [comment]
I am facing the same error.

**Comment by c-goettert** [comment]
Copying the lib files to the node_modules folder only solves it for me when I am using a remote debugger. When I disable remote debugging, I get the red-screen again. Does anyone have a hint on how to solve this??

**Comment by YisusMB** [comment]
Hi guys actually i install this package and i find some things that maybe help you boys:
1 actually i need to re-install all my dependencies (just npm install) after install this package
2 i have the same problem of @c-goettert and this one is solve that the same way (just delete 'node_modues' folder from 'react-native-charts-wrapper' (/your-project/node_modules/react-native-charts-wrapper/node_modules) and it works 

i dont know why i have this same problem its creepy and im so scared about 'cause this maybe save my project haha

so i hope i helped (sorry for my bad english)
