### ISSUE TITLE
Invariant Violation: Native component for "RNBarChart" does not exist in iOS

### ISSUE THREAD

**Issue by kriptonhaz** [wuxudong/react-native-charts-wrapper#449]
### Expected Behavior
Expecting to run smoothly like in android version

### Actual Behavior
Just like the title said

### Screenshots
[https://imgur.com/a/zlJMsmE](url)

### Steps to Reproduce the Problem
in android is run smoothly, so I tried to show how to reproduce this on iOS version
yarn add react-native-charts-wrapper
add post install in package.json
yarn install
create group under top level app in Xcode (in this case I named to RNCharts)
add files to ... and choose inside folder node_modules/react-native-charts-wrapper/ios/ReactNativeCharts
automatically popup add bridging header appear and choose create bridging header
edit bridging-header.h file based on the doc
add charts and swiftyJSON with pod and after that pod install
update swift language version to 4.1
react-native run-ios 

### Specifications
- Version: 
react-native-charts-wrapper: "^0.5.0",
react-native: "0.55.4"
xcode: 9.4.1

- Platform: Android & IOS

**Comment by devonhuangcodes** [comment]
Having the same problem as well.

**Comment by devonhuangcodes** [comment]
Take a look at what I did at https://github.com/wuxudong/react-native-charts-wrapper/issues/382 and see if that helps at all

**Comment by zry754331875** [comment]
[https://github.com/wuxudong/react-native-charts-wrapper/issues/449#issuecomment-441876282](#382)l also do it.but it doesnt work.

**Comment by zry754331875** [comment]
l try manual setup can fix this problem.
