### ISSUE TITLE
Is valueFormatter not support function ?

### ISSUE THREAD

**Issue by Thyiad** [wuxudong/react-native-charts-wrapper#45]
It defined as :

valueFormatter: PropTypes.oneOfType([
      PropTypes.oneOf(['largeValue', 'percent']),
      PropTypes.string
    ]),

**Comment by wuxudong** [comment]
NO.
only 'largeValue', 'percent', and  [Unicode Technical Standard #35](http://www.unicode.org/reports/tr35/tr35-numbers.html#Number_Format_Patterns)

**Comment by Thyiad** [comment]
tks

**Comment by Thyiad** [comment]
呃。。能请教一下怎么写formatter，以去除后面的小数点吗。。谢谢~~~

**Comment by wuxudong** [comment]
'#'

**Comment by Thyiad** [comment]
谢谢~你是个好人~~
