### ISSUE TITLE
Pie Chart Crashes App

### ISSUE THREAD

**Issue by Gajendra-NL** [wuxudong/react-native-charts-wrapper#450]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

The moment i put values in data and run the app , my app crashes. By crash i mean app builds but closes automatically on my simulator.
It is the same pie example pie chart given.

### Expected Behavior
App should run fine and show the pie chart.

### Actual Behavior
App closes abruptly

### Data and config
import React from 'react'
import { Text, View, StyleSheet, processColor } from 'react-native';
import PropTypes from 'prop-types';
import { PieChart } from 'react-native-charts-wrapper';

class Pie extends React.Component {
  constructor() {
    super();

    this.state = {
      legend: {
        enabled: true,
        textSize: 15,
        form: 'CIRCLE',

        horizontalAlignment: "RIGHT",
        verticalAlignment: "CENTER",
        orientation: "VERTICAL",
        wordWrapEnabled: true
      },
      highlights: [{x:2}],
      description: {
        text: 'This is Pie chart description',
        textSize: 15,
        textColor: processColor('darkgray'),

      },
      data: {
        dataSets: [
          {
            label: 'Users',
            values: [
              {value: 20},
              {value: 20},
              {value: 30},
            ]
          }
        ],
      }
    };
  }

  render () {
    return (
      <View style={styles.container}>
        <Text>Test</Text>
        <PieChart
          legend={this.state.legend}
          data={this.state.data}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF'
  },
  chart: {
    flex: 1
  }
});

export default Pie;

### Specifications
  - Version: 0.5.0
  - Platform: Android
  - Subsystem: 
   "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-charts-wrapper": "^0.5.0"

**Comment by leo-tavares** [comment]
Do other graphics work perfectly? You test in release or debug mode?

I have similar issue in whatever chart, but only in release-mode crash

**Comment by Gajendra-NL** [comment]
I have tried line graph and bar graph. they work fine. I'm testing on debug
only.

**Comment by silvaalvaro** [comment]
Take a look at this https://github.com/wuxudong/react-native-charts-wrapper/pull/448

**Comment by vikrantnegi** [comment]
Crashing on Android for the pie chart. Any solutions? 
@silvaalvaro  The PR doesn't solve the issue.

**Comment by vikrantnegi** [comment]
I've find the solution as mentioned [here](https://github.com/wuxudong/react-native-charts-wrapper/issues/408#issuecomment-428878665).

But now possible solution (in RN):
0) add layout member into you state

wrap char into view:
in `render()`  method add:
```
<View onLayout={_onLayout}>
  {!!this.state.layout && <PieChartNative  .....  /> }
  ...
</View>
```

Add method on the class:

```
  _onLayout = (e) => {
    this.setState({ layout: e.nativeEvent.layout });
  }
```

**Comment by andresmtz98** [comment]
> I've find the solution as mentioned [here](https://github.com/wuxudong/react-native-charts-wrapper/issues/408#issuecomment-428878665).
> 
> But now possible solution (in RN):
> 0) add layout member into you state
> 
> wrap char into view:
> in `render()` method add:
> 
> ```
> <View onLayout={_onLayout}>
>   {!!this.state.layout && <PieChartNative  .....  /> }
>   ...
> </View>
> ```
> Add method on the class:
> 
> ```
>   _onLayout = (e) => {
>     this.setState({ layout: e.nativeEvent.layout });
>   }
> ```

It looks like in version 3.1.1 of native module still happens :/
