### ISSUE TITLE
Ios simulator developer menu could not be opened after react native charts wrapper was integrated

### ISSUE THREAD

**Issue by vitozyf** [wuxudong/react-native-charts-wrapper#451]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
can open the developer menu in the ios emulator
### Actual Behavior
The developer menu cannot be opened in the ios emulator
### Screenshots
![image](https://user-images.githubusercontent.com/26626159/49208267-47f9f980-f3f2-11e8-93fb-b221fbc341b8.png)

### Steps to Reproduce the Problem
After integrating react-native charts-wrapper according to the document steps, the developer menu could not be opened in the ios simulator

### Specifications
  - "react": "16.5.0",
  - "react-native": "0.57.2",
  - "react-native-charts-wrapper": "^0.5.0",
  - Platform: Mac

**Comment by vitozyf** [comment]
If I try to remove libraries other than 'Pods_demo. Framework', I won't be able to run the APP,
The error message is as follows:


![image](https://user-images.githubusercontent.com/26626159/49282606-8c58c880-f4ca-11e8-866a-19011fcff667.png)

**Comment by vitozyf** [comment]
It's true that after I integrated in the project, the developer menu didn't open in the ios emulator. In order to exclude other factors, I created an empty project, running ios can open the developer menu, again after the integration of the library did not open the developer menu.

By the way, I use cocoapods for automatic integration

"react": "16.6.1",
"react-native": "0.57.7",
"react-native-charts-wrapper": "^0.5.0"

"swift": "4.2"
"xcode": "10.1"

I wrote a demo and only integrated this library. Please help me have a look. Thank you very much.
https://github.com/vitozyf/chartDemo

**Comment by vitozyf** [comment]
@wuxudong This problem has been bothering me for a long time. Could you please take a look at it? Thank you very much

**Comment by duyanh2912** [comment]
@vitozyf I've encountered the same problem and managed to fix it by deleting the default React projects in XCode
![screen shot 2018-12-06 at 8 58 31 am](https://user-images.githubusercontent.com/22729135/49556230-736e6e00-f935-11e8-90be-73b4264109df.png)
Then you should choose Remove References
![screen shot 2018-12-06 at 9 00 33 am](https://user-images.githubusercontent.com/22729135/49556260-900aa600-f935-11e8-9d0c-358cf7a3985a.png)
I hope this will help you :)

**Comment by vitozyf** [comment]
> @vitozyf I've encountered the same problem and managed to fix it by deleting the default React projects in XCode
> ![screen shot 2018-12-06 at 8 58 31 am](https://user-images.githubusercontent.com/22729135/49556230-736e6e00-f935-11e8-90be-73b4264109df.png)
> Then you should choose Remove References
> ![screen shot 2018-12-06 at 9 00 33 am](https://user-images.githubusercontent.com/22729135/49556260-900aa600-f935-11e8-9d0c-358cf7a3985a.png)
> I hope this will help you :)

I'm sorry，I made a mistake after I followed the instructions

```
** BUILD FAILED **


The following build commands failed:

        CompileC /Users/zhangyongfeng/Code/RN/ios/build/Build/Intermediates.noindex/RNVectorIcons.build/Debug-iphonesimulator/RNVectorIcons.build/Objects-normal/x86_64/RCTFont+FA5.o /Users/zhangyongfeng/Code/RN/node_modules/react-native-vector-icons/RNVectorIconsManager/RCTFont+FA5.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/ZnlICloud.app
An error was encountered processing the command (domain=IXErrorDomain, code=13):
Failed to get bundle ID from /Users/zhangyongfeng/Code/RN/ios/build/Build/Products/Debug-iphonesimulator/ZnlICloud.app
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ZnlICloud.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ZnlICloud.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:618:11)
    at Object.execFileSync (child_process.js:636:13)
    at Promise.then (/Users/zhangyongfeng/Code/RN/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
```

**Comment by vitozyf** [comment]
> @vitozyf I've encountered the same problem and managed to fix it by deleting the default React projects in XCode
> ![screen shot 2018-12-06 at 8 58 31 am](https://user-images.githubusercontent.com/22729135/49556230-736e6e00-f935-11e8-90be-73b4264109df.png)
> Then you should choose Remove References
> ![screen shot 2018-12-06 at 9 00 33 am](https://user-images.githubusercontent.com/22729135/49556260-900aa600-f935-11e8-9d0c-358cf7a3985a.png)
> I hope this will help you :)

I'm sorry, but I'm surprised. React native run-ios failed to build while running, but it worked in x-code. I don't know why, but the problem has been solved temporarily. Thank you!

**Comment by duyanh2912** [comment]
@vitozyf maybe you could try removing the ios/build folder then run react-native run-ios again haha. I just installed react-native-vector-icons and it works fine with my project.
