### ISSUE TITLE
How to set the width in barChart

### ISSUE THREAD

**Issue by lijie0214** [wuxudong/react-native-charts-wrapper#452]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by vitozyf** [comment]
You can style chat components like {height: 300}

**Comment by vitozyf** [comment]
By the way, can you still open the developer menu of the emulator in debugging after you integrate it into ios?

**Comment by lijie0214** [comment]
> 顺便说一句，在将它集成到ios后，你还可以在调试中打开模拟器的开发人员菜单吗？


i known this,but i want to know how to set the width of each histogram to a fixed value, even if the column is reduced

**Comment by lijie0214** [comment]
and how  to set  the height of the x-axis value

**Comment by vitozyf** [comment]
I looked up the document, as if the author hadn't thrown the property out. It seems that only the outer styles can be set to control width and height

**Comment by vitozyf** [comment]
I would like to ask you, after integrating this component into ios, can you still open the developer menu of the simulator in debugging? I can't open the developer menu in the ios emulator.

**Comment by wuxudong** [comment]
For the whole chart width, You can style chat components like {height: 300}.

If you want to control how many bars can be displayed, you can use zoom or visibleRange. 

if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo. You can find detail in https://github.com/wuxudong/react-native-charts-wrapper/tree/master/installation_guide
