### ISSUE TITLE
配置报错

### ISSUE THREAD

**Issue by sym900728** [wuxudong/react-native-charts-wrapper#453]
在 xcode 10, rn 0.57 的环境下，试过了 0.4.8 和 0.5.0 版本，swift 4.1 和 swift 4.2 版本，配置都是不成功。
一直报这个错误。

![image](https://user-images.githubusercontent.com/4710194/49325938-9ee40800-f585-11e8-86f4-549006425501.png)

希望高手帮我解决一下。

**Comment by ZengMX** [comment]
有解决办法吗，我也是这样的报错，

**Comment by JiyeYu** [comment]
I have the same issue. Did you guys solve this problem? ( I created a new swift file as the manual said)
