### ISSUE TITLE
android Invariant Violation: requireNativeComponent: "RNLineChart" was not found in the UIManager 

### ISSUE THREAD

**Issue by RobertLLM** [wuxudong/react-native-charts-wrapper#457]
Invariant Violation: requireNativeComponent: "RNLineChart" was not found in the UIManager.

This error is located at:
    in RNLineChart (at LineChart.js:25)
    in LineChart (at YGEnvironment_RN/index.js:17)
    in RCTView (at View.js:45)
    in RCTView (at View.js:45)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in RCTView (at View.js:45)
    in AppContainer (at renderApplication.js:33)
getNativeComponentAttributes
    getNativeComponentAttributes.js:29:4
<unknown>
    requireNativeComponent.js:26:33
get
    ReactNativeViewConfigRegistry.js:104:25
createInstance
    ReactNativeRenderer-dev.js:3955:53
completeWork
    ReactNativeRenderer-dev.js:13218:12
completeUnitOfWork
    ReactNativeRenderer-dev.js:15670:10
performUnitOfWork
    ReactNativeRenderer-dev.js:15880:30
workLoop
    ReactNativeRenderer-dev.js:15892:41
renderRoot
    ReactNativeRenderer-dev.js:15996:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:16976:17
performWork
    ReactNativeRenderer-dev.js:16877:24
performSyncWork
    ReactNativeRenderer-dev.js:16838:14
requestWork
    ReactNativeRenderer-dev.js:16703:19
scheduleWork
    ReactNativeRenderer-dev.js:16504:16
scheduleRootUpdate
    ReactNativeRenderer-dev.js:17191:15
updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:17225:28
updateContainer
    ReactNativeRenderer-dev.js:17315:4
render
    ReactNativeRenderer-dev.js:17971:20
renderApplication
    renderApplication.js:59:34
run
    AppRegistry.js:101:10
runApplication
    AppRegistry.js:195:26
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17

**Comment by siddhimandodi** [comment]
I'm also facing the same issue anyone help

**Comment by InxiousRz** [comment]
Im facing the same issue. i already tried npm install and yarn add ... both has no effect ... 

im using expo-cli and my version is :
react-native-cli: 2.0.1
react-native: 0.57.1

and iam running the Example/app/LiveUpdateChartScreen.js

**Comment by triplumix** [comment]
Maybe you missed `react-native link react-native-charts-wrapper`

**Comment by RahulNainwal** [comment]
why this issue is closed without providing any solution for it. I am asking this because i am getting some error.

**Comment by wuxudong** [comment]
It is closed because the question is outdated. 
New version is published, follow the installation tutorial to begin your demo project, 
then open a new issue if you still have problems.
