### ISSUE TITLE
您好,如何给坐标轴设置个单位

### ISSUE THREAD

**Issue by AlexDufresne** [wuxudong/react-native-charts-wrapper#46]

**Comment by wuxudong** [comment]
How to position the unit? Can you draw a picture to clarify it.

**Comment by AlexDufresne** [comment]
I just don't know how to add a  unit for X axis and tY axis, such as speed, time.I know I can add a Text to solve it . 
￼
 @![qq_pic_merged_1493975838882](https://cloud.githubusercontent.com/assets/20389595/25739951/d46211fa-31b6-11e7-9639-3eb86721a45c.jpg)

**Comment by wuxudong** [comment]
It seems axis title is still missing MpAndroidChart.

**Comment by AlexDufresne** [comment]
THX,and I have another question whether cancel label for bottom right of the picture and 'Bar dataSet'. And any have some simple document about it.I just get usages from demo and PropTypes.
Thanks for your help.

**Comment by wuxudong** [comment]
You can check demo picture first in the homepage, you can find no legend in 'ZeroLineChart' .

If you check the example, you will find `legend={{enabled: false}}`

**Comment by AlexDufresne** [comment]
THX!
