### ISSUE TITLE
Zoom min/max limit

### ISSUE THREAD

**Issue by vynogradskyi** [wuxudong/react-native-charts-wrapper#460]
Hi, is there an option to limit zoom to some value? I need to set Combined chart to prevent user to zoom more than to 10 minutes. Is it possible?

**Comment by wuxudong** [comment]
visibleRange may work for you.

**Comment by s349856186** [comment]
@wuxudong 
how to reset zoom? 
zoom={this.state.zoom}  //{scaleX: 1, scaleY: 1, xValue: 2, yValue: 2}
resetZoom=()=>{
        this.setState({
            zoom:{scaleX: 1, scaleY: 1, xValue: 1, yValue: 1},
        });
    }
But only when the first call "resetZoom" valid, invalid enlarged "resetZoom" call again, how to do ?

**Comment by vynogradskyi** [comment]
@wuxudong Thanks! Please close the issue!
