### ISSUE TITLE
yAxis valueFormatter string array not work

### ISSUE THREAD

**Issue by callcter** [wuxudong/react-native-charts-wrapper#461]
react-native: 0.57.1
react-native-charts-wrapper: 0.5.0

this is my config
![](https://s1.ax1x.com/2018/12/24/F6b0hj.png)
and render result
![](https://s1.ax1x.com/2018/12/24/F6bcuV.png)

**Comment by wuxudong** [comment]
Sorry,  valueFormatter string array doesn't work with y axis.

**Comment by FonDorn** [comment]
@wuxudong so how to customize y axis without valueFormatter string array?

**Comment by pavanural** [comment]
@wuxudong so how to customize y axis without valueFormatter string array? Is there any customisable methods or something equivalent? More required feature for me to implement in one of the project? Could you please give the solution soon?

**Comment by Fengweiyuu** [comment]
same problrm with u
