### ISSUE TITLE
how to reset zoom?

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#462]
this.state = {
            zoom: {scaleX: 1, scaleY: 1, xValue: 2, yValue: 2},  
}
zoom={this.state.zoom} //
resetZoom=()=>{
this.setState({
zoom:{scaleX: 1, scaleY: 1, xValue: 1, yValue: 1},
});
}
But only when the first call "resetZoom" valid, invalid enlarged "resetZoom" call again, how to do ?

Is there any example that use this fitScreen/moveViewTo ?

### Specifications

  - Version:"^0.5.0",
  - Platform:ios
  - Subsystem: "^0.54.0",

**Comment by wuxudong** [comment]
scaleX, scaleY in zoom is relative to origin scale, so scaleX: 1, scaleY: 1 means to do nothing.

fitScreen is what you are looking for, and you can find moveViewTo in examples.

**Comment by s349856186** [comment]
ok, Thanks
