### ISSUE TITLE
Swift Compiler Error Group

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#466]
![image](https://user-images.githubusercontent.com/2498958/51151119-70578d80-18a4-11e9-8290-d8333aa88090.png)

### Screenshots
![fb0e2383-55c1-40ba-8b99-b5cc92c08723](https://user-images.githubusercontent.com/2498958/51015477-5453a380-15a7-11e9-847b-d32d8b829371.png)

### Steps to Reproduce the Problem
I update RN 0.51--->0.57.8 ; react-native-charts-wrapper 0.4.8 --->0.5.0

### Specifications
"react-native-charts-wrapper": "^0.5.0",
react: ^16.6.3 => 16.6.3
react-native: ^0.57.8 => 0.57.8

System:
OS: macOS 10.14.1
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 8.9.0 - /usr/local/bin/node
npm: 6.5.0 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
SDKs:
iOS SDK:
Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
iphone x (12.1)
IDEs:
Xcode: 10.1/10B61 
react-native-cli: 2.0.1

**Comment by gifary** [comment]
I got some error like this, how to solve this?

**Comment by s349856186** [comment]
![image](https://user-images.githubusercontent.com/2498958/51151150-9715c400-18a4-11e9-834c-fa37321cdf64.png)

**Comment by JulianKingman** [comment]
I had similar issues, I solved them by removing the package and the RNChart folder in Xcode, and doing a fresh install of the package
