### ISSUE TITLE
TimeSeriesLineChart如何设置列数(x 坐标)

### ISSUE THREAD

**Issue by 2248157705** [wuxudong/react-native-charts-wrapper#468]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Specifications

  - Version:
  - Platform:
  - Subsystem:

demo 上面TimeSeriesLineChart是（6，7）(X，Y)的矩阵，我想修改为（4，4）的矩阵，请问要设置那个参数
如上图当前x轴是4（26，27，28，29，30）列，我想只显示3（27，28，29）列 请问要设置那个参数

**Comment by wuxudong** [comment]
If you want to fix visible window to 4*4，and disable zoom.

 you can use 

```

visibleRange: PropTypes.shape({
      x: PropTypes.shape({
        min: PropTypes.number,
        max: PropTypes.number
      }),
      y: PropTypes.shape({
        left: PropTypes.shape({
          min: PropTypes.number,
          max: PropTypes.number
        }),
        right: PropTypes.shape({
          min: PropTypes.number,
          max: PropTypes.number
        })
      })
    }),

```

**Comment by 2248157705** [comment]
![image](https://user-images.githubusercontent.com/4066040/51233973-5dc57d00-19a6-11e9-8982-3079c4bcf209.png)
there is no use for visibleRange

**Comment by 2248157705** [comment]
![image](https://user-images.githubusercontent.com/4066040/51235515-a54e0800-19aa-11e9-9fc0-bfa408b72070.png)
if xAxis is date like 2018-12-26 how to show it

**Comment by 2248157705** [comment]
thank you

**Comment by 2248157705** [comment]
![image](https://user-images.githubusercontent.com/4066040/51240410-95d4bc00-19b6-11e9-9194-f3c9fca6b41f.png)
the xAxis position is wrong and the last data which is 2018-12-28 did not show thank you very much
