### ISSUE TITLE
Draw vertical Line with Marker

### ISSUE THREAD

**Issue by far1s** [wuxudong/react-native-charts-wrapper#469]
Hi, I'm trying to get a vertical line drawn together with the marker every time I drag inside the chart.

### Desired Behavior
<img width="292" alt="inlmj" src="https://user-images.githubusercontent.com/11456042/51333813-cf70fa00-1a7e-11e9-9aae-044e766e04bc.png">

Is that possible somehow? For me, this is very crucial.

### Specifications

  - Version: 0.5.0
  - Platform: iOS
  - Subsystem: react native v0.57.8

**Comment by wuxudong** [comment]
I am afraid you have to write your custom marker.

**Comment by far1s** [comment]
@wuxudong Can you give a short example? Would be really nice!

**Comment by wuxudong** [comment]
No such short example, I mean there is no such marker as your "Desired Behavior".
you have to write your own one, using native code.

**Comment by lasharela** [comment]
> @wuxudong Can you give a short example? Would be really nice!

Hi, did you find anything for this issue? I have the same problem to solve.

**Comment by harshitaahuja** [comment]
@far1s Did you find anything to start with? I also want to achieve similar behaviour.
