### ISSUE TITLE
Is valueTextColor not support?

### ISSUE THREAD

**Issue by Thyiad** [wuxudong/react-native-charts-wrapper#47]
const chartDataSetConfig = {
  common: {
    valueTextSize:PropTypes.number,
   // ,,,
  },

There is no valueTextColor or valueTextColors。。。

**Comment by Thyiad** [comment]
I found your TODO comment。。

 // TODO more config to add: https://github.com/PhilJay/MPAndroidChart/wiki/The-DataSet-class

**Comment by wuxudong** [comment]
? 
There is config in DataSetConfig
	
	if (BridgeUtils.validate(config, ReadableType.Number, "valueTextSize")) {
            dataSet.setValueTextSize((float) config.getDouble("valueTextSize"));
        }

        if (BridgeUtils.validate(config, ReadableType.Number, "valueTextColor")) {
            dataSet.setValueTextColor(config.getInt("valueTextColor"));
        }

**Comment by Thyiad** [comment]
O, v0.2.8 updated...

**Comment by Thyiad** [comment]
I was still using v0.2.7

**Comment by Thyiad** [comment]
But, is there anyway to config center text like android SpannableString?

**Comment by wuxudong** [comment]
I am afraid not.

**Comment by Thyiad** [comment]
OK~
