### ISSUE TITLE
Horizontal barchart value not setting to whole no. 

### ISSUE THREAD

**Issue by sarry173** [wuxudong/react-native-charts-wrapper#470]
I am not able to change x or y axis value into whole no not in fraction. Please help asap.
![device-2019-01-21-123306](https://user-images.githubusercontent.com/3347527/51457914-3e996780-1d79-11e9-985b-f9c1e5e546ee.png)

**Comment by mitulsavani** [comment]
@sarry173 Hey even I am planning to use horizontal BarChart for my app, would you mind telling me how you got it to working horizontally?

**Comment by sarry173** [comment]
Hi @mitulsavani reffer to bellow link.
https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/HorizontalBarChartScreen.js

if it not work than I can send you my code.

**Comment by wuxudong** [comment]
I think you can apply 

    granularity: PropTypes.number,
    granularityEnabled: PropTypes.bool,


to y axis.

**Comment by tranty9597** [comment]
@wuxudong its not work

**Comment by hungvt00041** [comment]
> 
> 
> Hi @mitulsavani reffer to bellow link.
> https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/HorizontalBarChartScreen.js
> 
> if it not work than I can send you my code.

Hi @sarry173 , can you send me your code about this chart:) thx u
