### ISSUE TITLE
highlights is not function

### ISSUE THREAD

**Issue by gifary** [wuxudong/react-native-charts-wrapper#471]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
clear highlights with  this._chart.highlights([])
### Actual Behavior
 this._chart.highlights([]) is not function

### Data and config
`data: {
                dataSets: [{
                    values: [
                        {value: 45, label: 'Sandwiches',color:'white'},
                        {value: 45, label: 'Salads',color:'white'},
                        {value: 45, label: 'Soup',color:'white'},
                        {value: 45, label: 'Beverages',color:'white'},
                        {value: 45, label: 'Desserts',color:'white'},
                        {value: 45, label: 'Soup',color:'white'},
                        {value: 45, label: 'Beverages',color:'white'},
                        {value: 45, label: 'Desserts',color:'white'}
                    ],
                    label: 'Pie dataset',
                    config: {
                        colors: [
                            processColor('#ff1d00'),
                            processColor('#00c1b2'),
                            processColor('#000fff'),
                            processColor('#2c2c2c'),
                            processColor('#0edb15'),
                            processColor('#bd0b3a'),
                            processColor('#e2c700'),
                            processColor('#ff5549')
                        ],
                        valueTextSize: 1,
                        valueTextColor: processColor('#000'),
                        sliceSpace: 0,
                        selectionShift: 13,
                        xValuePosition: "INSIDE_SLICE",
                        // yValuePosition: "OUTSIDE_SLICE",
                        //valueFormatter: "#.#'%'",
                        valueFormatter:"#",
                        valueLineColor: processColor('#000'),
                        valueLinePart1Length: 0,
                        fontFamily:'Gibson-Regular'
                    }
                }],
            },`
### Steps to Reproduce the Problem
use Piechart
`<PieChart
                                ref={(c) => this._chart = c}
                                chartDescription={this.state.description}
                                style={[{height:300,width:300}]}
                                highlights={this.state.highlights}
                                logEnabled={false}
                                data={this.state.data}
                                legend={this.state.legend}
                                drawEntryLabels={true}
                                rotationEnabled={false}
                                usePercentValues={false}
                                holeRadius={0}
                                entryLabelTextSize={14}
                                maxAngle={360}
                                transparentCircleColor={processColor('#fff')}
                                transparentCircleRadius={processColor('#000')}
                                fontFamily={'Gibson-Regular'}
                                animation={{
                                    durationX: 1000, // Millis
                                    durationY: 1000,
                                    easingX: 'EaseInQuad',
                                    easingY: 'EaseInQuad'
                                }}
                                onSelect={this.handleSelectBig.bind(this)}

                            />`

### Specifications

  - Version: 0.5
  - Platform: android
  - Subsystem:

**Comment by wuxudong** [comment]
highlights & moveViewTo & fitScreen  are implemented by BarLineChartBaseManager, and PieChart is not child of BarLineChartBaseManager.
or we can move fitScreen to ChartBaseManager.

**Comment by wuxudong** [comment]
In MpAndroidChart, fitScreen is implemented by BarLineChartBase, so no support for PieChart.
