### ISSUE TITLE
Missing xAxis labels when zoom in

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#472]
![qq20190130-161535](https://user-images.githubusercontent.com/2498958/51967581-adc63880-24aa-11e9-8aca-c512b8c1ab6b.gif)

### Data and config
const time = ["0:00","0:05","0:10","0:15","0:20","0:25","0:30","0:35","0:40","0:45","0:50","0:55","1:00","1:05","1:10","1:15","1:20","1:25","1:30","1:35","1:40","1:45","1:50","1:55","2:00","2:05","2:10","2:15","2:20","2:25","2:30","2:35","2:40","2:45","2:50","2:55","3:00","3:05","3:10","3:15","3:20","3:25","3:30","3:35","3:40","3:45","3:50","3:55","4:00","4:05","4:10","4:15","4:20","4:25","4:30","4:35","4:40","4:45","4:50","4:55","5:00","5:05","5:10","5:15","5:20","5:25","5:30","5:35","5:40","5:45","5:50","5:55","6:00","6:05","6:10","6:15","6:20","6:25","6:30","6:35","6:40","6:45","6:50","6:55","7:00","7:05","7:10","7:15","7:20","7:25","7:30","7:35","7:40","7:45","7:50","7:55","8:00","8:05","8:10","8:15","8:20","8:25","8:30","8:35","8:40","8:45","8:50","8:55","9:00","9:05","9:10","9:15","9:20","9:25","9:30","9:35","9:40","9:45","9:50","9:55","10:00","10:05","10:10","10:15","10:20","10:25","10:30","10:35","10:40","10:45","10:50","10:55","11:00","11:05","11:10","11:15","11:20","11:25","11:30","11:35","11:40","11:45","11:50","11:55","12:00","12:05","12:10","12:15","12:20","12:25","12:30","12:35","12:40","12:45","12:50","12:55","13:00","13:05","13:10","13:15","13:20","13:25","13:30","13:35","13:40","13:45","13:50","13:55","14:00","14:05","14:10","14:15","14:20","14:25","14:30","14:35","14:40","14:45","14:50","14:55","15:00","15:05","15:10","15:15","15:20","15:25","15:30","15:35","15:40","15:45","15:50","15:55","16:00","16:05","16:10","16:15","16:20","16:25","16:30","16:35","16:40","16:45","16:50","16:55","17:00","17:05","17:10","17:15","17:20","17:25","17:30","17:35","17:40","17:45","17:50","17:55","18:00","18:05","18:10","18:15","18:20","18:25","18:30","18:35","18:40","18:45","18:50","18:55","19:00","19:05","19:10","19:15","19:20","19:25","19:30","19:35","19:40","19:45","19:50","19:55","20:00","20:05","20:10","20:15","20:20","20:25","20:30","20:35","20:40","20:45","20:50","20:55","21:00","21:05","21:10","21:15","21:20","21:25","21:30","21:35","21:40","21:45","21:50","21:55","22:00","22:05","22:10","22:15","22:20","22:25","22:30","22:35","22:40","22:45","22:50","22:55","23:00","23:05","23:10","23:15","23:20","23:25","23:30","23:35","23:40","23:45","23:50","23:55","24:00"];

visibleRange: {x: {min: 9, max: 289},},

xAxis: {
                valueFormatter: time,
                labelCount: 9,    //9,
                labelCountForce:true,
                position: 'BOTTOM',
                textColor:processColor('white'),
            },

                            visibleRange={this.state.visibleRange}
                            drawBorders={true}
                            touchEnabled={true}
                            dragEnabled={true}
                            scaleEnabled={true}
                            scaleXEnabled={true}
                            scaleYEnabled={true}
                            pinchZoom={true}
                            doubleTapToZoomEnabled={true}
### Steps to Reproduce the Problem

If not zoom in, the xAxis labels show normal. It's missing when zoom in the chart, how to do fix it?

### Specifications
"react-native": "^0.57.8",
  "react-native-charts-wrapper": "^0.5.0",
  - Platform: android && ios

**Comment by wuxudong** [comment]
granularity & granularityEnabled ? 
I am not sure if it will help.

**Comment by s349856186** [comment]
@wuxudong It's not work
xAxis: {
granularityEnabled: true,
granularity: 1,
valueFormatter: time,
labelCount: 9, 
labelCountForce:true,
position: 'BOTTOM',
textColor:processColor('white'),
},

**Comment by s349856186** [comment]
@wuxudong can you help me， thanks

**Comment by wuxudong** [comment]
Example data and page required.

**Comment by s349856186** [comment]
@wuxudong 
      You only need to replace the following code in “ react-native-charts-wrapper/Example/app/LineChartScreen.js” to reproduce

       const time = ["0:00","0:05","0:10","0:15","0:20","0:25","0:30","0:35","0:40","0:45","0:50","0:55","1:00","1:05","1:10","1:15","1:20","1:25","1:30","1:35","1:40","1:45","1:50","1:55","2:00","2:05","2:10","2:15","2:20","2:25","2:30","2:35","2:40","2:45","2:50","2:55","3:00","3:05","3:10","3:15","3:20","3:25","3:30","3:35","3:40","3:45","3:50","3:55","4:00","4:05","4:10","4:15","4:20","4:25","4:30","4:35","4:40","4:45","4:50","4:55","5:00","5:05","5:10","5:15","5:20","5:25","5:30","5:35","5:40","5:45","5:50","5:55","6:00","6:05","6:10","6:15","6:20","6:25","6:30","6:35","6:40","6:45","6:50","6:55","7:00","7:05","7:10","7:15","7:20","7:25","7:30","7:35","7:40","7:45","7:50","7:55","8:00","8:05","8:10","8:15","8:20","8:25","8:30","8:35","8:40","8:45","8:50","8:55","9:00","9:05","9:10","9:15","9:20","9:25","9:30","9:35","9:40","9:45","9:50","9:55","10:00","10:05","10:10","10:15","10:20","10:25","10:30","10:35","10:40","10:45","10:50","10:55","11:00","11:05","11:10","11:15","11:20","11:25","11:30","11:35","11:40","11:45","11:50","11:55","12:00","12:05","12:10","12:15","12:20","12:25","12:30","12:35","12:40","12:45","12:50","12:55","13:00","13:05","13:10","13:15","13:20","13:25","13:30","13:35","13:40","13:45","13:50","13:55","14:00","14:05","14:10","14:15","14:20","14:25","14:30","14:35","14:40","14:45","14:50","14:55","15:00","15:05","15:10","15:15","15:20","15:25","15:30","15:35","15:40","15:45","15:50","15:55","16:00","16:05","16:10","16:15","16:20","16:25","16:30","16:35","16:40","16:45","16:50","16:55","17:00","17:05","17:10","17:15","17:20","17:25","17:30","17:35","17:40","17:45","17:50","17:55","18:00","18:05","18:10","18:15","18:20","18:25","18:30","18:35","18:40","18:45","18:50","18:55","19:00","19:05","19:10","19:15","19:20","19:25","19:30","19:35","19:40","19:45","19:50","19:55","20:00","20:05","20:10","20:15","20:20","20:25","20:30","20:35","20:40","20:45","20:50","20:55","21:00","21:05","21:10","21:15","21:20","21:25","21:30","21:35","21:40","21:45","21:50","21:55","22:00","22:05","22:10","22:15","22:20","22:25","22:30","22:35","22:40","22:45","22:50","22:55","23:00","23:05","23:10","23:15","23:20","23:25","23:30","23:35","23:40","23:45","23:50","23:55","24:00"];
const data1 = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,0,0,0,4,57,0,20,43,29,16,0,141,50,111,119,212,77,167,108,137,118,173,141,214,151,216,168,206,286,0,409,216,222,753,221,470,437,373,345,214,228,226,294,581,614,608,596,616,358,932,861,2879,2877,2660,2688,2576,2591,2576,2587,2613,2626,2715,2703,2705,2702,2682,2683,2685,2561,2556,2531,2504,2479,2570,2559,2546,2516,2490,2476,2437,2310,2272,2230,2195,2169,2222,2197,2183,2240,2278,2398,2513,1361,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
const data2 = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25.31,11,36.34,23,28,73.88,33,37,92.94,129.2,124.16,164.76,219.12,398.48,459.53,398,432.32,476.44,472.52,427.74,489.44,1613.8,1403.26,1800.21,1867.52,1783,1826.71,1181.48,1903.6,1954.8,2025.84,2128.24,2182.48,2116.41,2306.66,2285.6,2307.6,2527.28,1685.4,1917.13,2531.11,2647.22,2711.94,3053.07,1385.11,3516.88,3406.6,3305.46,3252.78,3112.68,3065.76,3193.56,3216.52,3177.92,3189.5,3191,3173.71,3200.42,3234.09,3235.07,3167,3182.85,3163.5,3200.44,3191,3199.34,3192.33,3183.5,3197.75,3218.3,3204.88,3205.78,3208.76,3193,3211.77,3173.5,3167.38,3185,3176.5,3146.08,3118.76,3107.08,3072.31,3053.79,3046.91,3035.03,2999.06,2986.44,2951.35,2933.8,2900.2,2851.27,2804.32,2778.12,2758.82,2719.88,2669.24,2670.59,2718.5,2758.14,2882.66,3000.7,1944.06,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
const data3 = [413,414,416,410,412,412,515,524,512,514,511,217,174,165,219,218,574,324,502,315,526,514,512,415,412,411,413,415,413,520,518,515,513,514,509,414,407,752,721,221,223,335,530,547,537,533,525,422,422,420,418,420,417,513,517,519,519,513,416,414,416,415,410,411,412,515,512,511,356,315,216,219,171,216,214,436,420,517,515,513,514,510,416,455,405,411,409,415,410,307,318,318,321,349,250,263,463,438,450,416,447,541,581,549,555,544,457,455,461,471,255,281,257,375,379,365,346,600,489,481,481,482,482,483,489,576,558,555,551,559,859,267,268,202,202,433,419,525,518,518,509,511,503,406,415,404,403,404,401,401,508,507,508,505,511,403,403,400,403,401,399,404,503,503,507,502,503,403,400,401,400,397,400,396,526,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];


xAxis: {
                valueFormatter: time,
                labelCount: 9,
                labelCountForce:true,
                textColor:processColor('black'),
            },

    componentDidMount() {

        this.setState(
            update(this.state, {
                data: {
                    $set: {
                        dataSets: [{
                            values: data1, label: 'A',
                        }, {
                            values: data2, label: 'B',
                        }, {
                            values: data3, label: 'C',
                        }],
                    }
                }
            })
        );
    }

**Comment by wuxudong** [comment]
It works fine after removing

```
 labelCount: 9,
```

labelCount: 9 force that only 9 labels are allowed to appear in x axis.

**Comment by s349856186** [comment]
@wuxudong I need the labelCount=9. Because when I don't zoom in, I need the chart to start from 0:00  to 24:00.
![image](https://user-images.githubusercontent.com/2498958/53774735-a4f1d800-3f2a-11e9-8ef0-f1b15b253236.png)

If I zoom in, there is no way to specify the labelCount to display？
![image](https://user-images.githubusercontent.com/2498958/53774930-6872ac00-3f2b-11e9-83c8-5cc1c1a0a68e.png)
