### ISSUE TITLE
overlap the values on xAxis!

### ISSUE THREAD

**Issue by prav02** [wuxudong/react-native-charts-wrapper#473]
As I am trying to run the following programme, the values on xAxis overlap on each other as the data increases. Is there is any way so that the xAxis values adjust automatically and avoid overlapping on each other? 

### Screenshots
![Uploading Screenshot_20190201_161203_com.chartkit[1].jpg…]()

### Code and config

 <LineChart
            style={styles.chart}
            data={this.state.data}
            chartDescription={{text: ''}}
            legend={this.state.legend}
            marker={this.state.marker}
            // xAxis={this.state.xAxis}
            xAxis= {{
              drawGridLines:false,
              granularityEnabled: false,
              granularity: 1,
              spaceBetweenLabels: 5,
              drawLabels: true,
              position:"BOTTOM",
              textSize:11,
               valueFormatter:'date',
              valueFormatterPattern:"MM-dd HH:mm",
                textColor: processColor('#fff'),
                           
            }}
### Specifications

  - Version:    "react-native-charts-wrapper": "^0.5.0",

  - Platform:
  - Subsystem:

**Comment by prav02** [comment]
labelRotationAngle: -90, in xAxis property solved my problem temporary, but still looking for better soluation.

**Comment by nolife08021** [comment]
I set labelRotationAngle: 50, but it not user-friendly. Any suggestion?
<img width="278" alt="Screenshot 2021-11-12 at 3 35 12 PM" src="https://user-images.githubusercontent.com/49778835/141428924-2b17328b-7d02-4710-8802-7c0f5ad4915c.png">
