### ISSUE TITLE
Conflict with react-native-gesture-handler (thus Expo and React Navigation etc.)

### ISSUE THREAD

**Issue by gsklee** [wuxudong/react-native-charts-wrapper#474]
This library used to work really well for us until we upgraded to React Navigation v3, which depends on `react-native-gesture-handler`. The gesture handler this library is using seems to be conflicting with `react-native-gesture-handler`, and as a result our charts now are no longer working properly since tap/drag events etc. are being intercepted in a wrong fashion.

Since `react-native-gesture-handler` is being used by a few popular and fundamental RN libraries already (Expo and React Navigation to name a few), does Charts Wrapper plan to jump onto the bandwagon as well? Or is it possible to offer better interop with other native gesture handler?

**Comment by wuxudong** [comment]
I update the example to React Navigation v3, no conflict found.

**Comment by gsklee** [comment]
@wuxudong The bug only happened to me on iOS, not on Android, and was for the dragging gesture only.

**Comment by wuxudong** [comment]
Can you attach the detail conflict?

![out](https://user-images.githubusercontent.com/1391101/53846776-33c52a00-3fe9-11e9-83fc-70cc0ed03a84.gif)

In iOS simulator,  it works fine.

**Comment by 3luyka** [comment]
@wuxudong wrap it with `ScrollView`.

**Comment by DerekNien** [comment]
For horizontal BarChart wrapped in a vertical ScrollView, iOS devices may suffer from not being able to scroll vertically cause the drag event is swallowed by the horizontal BarChart while dragging vertically inside the BarChart. Dragging horizontally inside the BarChart is acting normal.

However, the situation only happens on real iOS device (tested on iPad Mini5), iOS simulator (iPhone 11) just works fine. Also Android device works fine (tested on Samsung SM-N960F).

After digging into the [issue](https://github.com/danielgindi/Charts/issues/1847) in [Charts](https://github.com/danielgindi/Charts), I modified the source code and added support for `dragYEnabled` and set `dragYEnabled = false`, and the mentioned problem is solved.
