### ISSUE TITLE
Y-Axis: different values on different platforms

### ISSUE THREAD

**Issue by andreypaul** [wuxudong/react-native-charts-wrapper#477]
### Expected Behavior
Showing y-axis value 0.0 and 0.8 on iOS and Android

### Actual Behavior
Left y-axis shows values .0, and .8 instead of 0.0 and 0.8 (iOS).
On android showing 0.8

### Screenshots

<img width="89" alt="2019-02-13 18 54 22" src="https://user-images.githubusercontent.com/17850013/52724828-20620880-2fc1-11e9-8f18-803604515a02.png">

### Data and config

export const yAxis = {
    left: {
        enabled: false,
        axisMinimum: 0,
        axisMaximum: 3,
    },
    right: {
        textColor: processColor("black"),
        textSize: 8,
        enabled: true,
        drawGridLines: true,
        drawLabels: true,
        labelCount: 5,
        labelCountForce: true,
        gridColor: processColor("#EDF0F0"),
        axisLineColor: processColor("white"),
        axisLineWidth: 0,
        gridLineWidth: 1,
        axisMinimum: 0,
        axisMaximum: 3,
    }
};

### Specifications

  - Version: 0.5.0
  - Platform: iOS

**Comment by wuxudong** [comment]
use valueFormatter?

**Comment by andreypaul** [comment]
I tried to use a valueFormatter to the parameter largeValue but it did not solve my problem

**Comment by wuxudong** [comment]
valueFormatter: '0.#' ?

**Comment by andreypaul** [comment]
Thanks!
