### ISSUE TITLE
Combined chart not focusing to given  yValue in zoom parameter  for ios

### ISSUE THREAD

**Issue by React-Vishnu** [wuxudong/react-native-charts-wrapper#478]
I am using Combined chart (stockchart) from example provides in the react native chart wrapper. all wroks fine in android but in ios chart not focusing to zoom parameter yValue. i have to scroll up to view the plotted data 

### Specifications

  - Version:0.5.0
  - Platform:ios

**Comment by wuxudong** [comment]
Example data and config required.
