### ISSUE TITLE
How to set dynamic color for bar chart? example: value >0 is green, value < 0 is red

### ISSUE THREAD

**Issue by Milkyway94** [wuxudong/react-native-charts-wrapper#479]

**Comment by wuxudong** [comment]
there is colors property in data.config

try

	data: {
        dataSets: [{
          values: [{y: 100}, {y: 105}, {y: 102}, {y: 110}, {y: 114}, {y: 109}, {y: 105}, {y: 99}, {y: 95}],
          label: 'Bar dataSet',
          config: {
            colors: [processColor('red'),processColor('red'),processColor('red'),processColor('green'),processColor('teal'),processColor('teal'),processColor('teal'),processColor('teal'),processColor('green'),]
            
          }
        }]
      }

**Comment by Yandamuri** [comment]
@wuxudong when i set multiple colors, It's throwing following error,

    Failed prop type: Invalid prop `data.dataSets[0].config.color` of type `array` supplied to `BarChart`, expected `number`.

R u sure that `colors` accepts an array of colors? If not, Kindly let us know how to set different color for each bar.

Thank you.

**Comment by ashok-sl** [comment]
@wuxudong How Can I pass dynamic colors array to `config.colors`
