### ISSUE TITLE
how to show all the selected yvalue when we focus on the xvalue?

### ISSUE THREAD

**Issue by eubotas** [wuxudong/react-native-charts-wrapper#48]
when we chose a point in linechart , 'onSelect={this.handleSelect.bind(this)} ' , the selected entry will be the selected point.  In the multi linechart(eg.  3 lines ), when we select one xvalue, we want to get  the all three yvalues .how to realize it?
![Uploading linechart.jpg…]()

**Comment by wuxudong** [comment]
No API for that.

But if you know the dataset and xValue you have selected, it is easy to filter all three yValue you want.

**Comment by wuxudong** [comment]
No API for that.

But if you know the dataset and xValue you have selected, it is easy to filter all three yValue you want.
