### ISSUE TITLE
Diable Zoom in BarChart

### ISSUE THREAD

**Issue by dxhung87** [wuxudong/react-native-charts-wrapper#480]
Hi Wuxudong!
I want disable zoom in BarChart, i find some method set value as 
            " zoomEnabled: false,
            zoomControlEnabled: false,
            doubleTapToZoomEnabled: false"
I set in legend, dataSet but it doesn't work.

Can U help me please! Thanks.

**Comment by nvuhung** [comment]
You can try with: <BarChart scaleEnabled={false} />

**Comment by dxhung87** [comment]
thanks! @nvuhung close issue!
