### ISSUE TITLE
How can we use this in React.js instead of react native?

### ISSUE THREAD

**Issue by babakmoosavi** [wuxudong/react-native-charts-wrapper#481]
How or 

can we use this component in React.js instead of react native?

### Expected Behavior
Using it in react.js source code
### Actual Behavior
it says could not find a declaration for module-native-chart-wrapper

### Screenshots
![bug](https://user-images.githubusercontent.com/45562709/53026088-88ea3300-3462-11e9-9526-8fa88d6fb09a.png)

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wuxudong** [comment]
No, it depends on MpAndroidChart and Charts,  and they are native modules.

There are much more great chart libraries in react than in react-native, like https://github.com/recharts/recharts
