### ISSUE TITLE
Drawvalues does not work on Horizontalbarchart

### ISSUE THREAD

**Issue by tranty9597** [wuxudong/react-native-charts-wrapper#482]
### Expected Behavior
Draw value above bar 
### Actual Behavior
Do not render value on the top of bar
### Screenshots
![screen shot 2019-02-24 at 11 56 43 am](https://user-images.githubusercontent.com/41298303/53295309-4aba8e00-382b-11e9-8913-8b3eabd7d2c8.png)

### Specifications

  - Version: 0.5.0
  - Platform: IOS and ANDROID
  - Subsystem:

**Comment by tranty9597** [comment]
Update: 

with data length <= 12 , chart doesn't draw values above bar

**Comment by wuxudong** [comment]
I don't understand. 
In example->HorizontalBarChartScreen,  drawValueAboveBar works fine even there are only 9 entries in data

**Comment by tranty9597** [comment]
uhm, i just found it, it has some difference thing when i change the domain of data, i show you my screen recording
![ezgif com-crop](https://user-images.githubusercontent.com/41298303/53315585-95eda300-38f6-11e9-8fbc-68a983c3e3a6.gif)

**Comment by wuxudong** [comment]
`change the domain of data`, do you mean replace with new data?

**Comment by tranty9597** [comment]
@wuxudong  yes

**Comment by tranty9597** [comment]
I dont know, if u saw my screen recording. when i change data, the values is not render in some case
![ezgif com-crop](https://user-images.githubusercontent.com/41298303/53320471-5af46b00-3908-11e9-8fd7-e4d8f494efb2.gif)

**Comment by tranty9597** [comment]
![screen shot 2019-02-25 at 2 45 02 pm](https://user-images.githubusercontent.com/41298303/53321782-49ad5d80-390c-11e9-830f-75837b440885.png)
I just try to replace my data by your, but chart still does not render values above bar

**Comment by wuxudong** [comment]
Reproducible example required.

**Comment by wuxudong** [comment]
I am not sure if #71 will help. 
Give it a try.

**Comment by tranty9597** [comment]
Yep, I see. I thank u
