### ISSUE TITLE
Candle Chart - candle data goes black, when I add a dateTime (xAxis)

### ISSUE THREAD

**Issue by irvanster** [wuxudong/react-native-charts-wrapper#485]
### Expected Behavior
Add dateTime on the chart candle, the bottom of the chart (xAxis)

### Actual Behavior
when I add dateTime, the data candle becomes black (no data appears),
### Screenshots

<img width="454" alt="when defining the value of X (candle data becomes black)" title="when defining the value of X (candle data becomes black)" src="https://user-images.githubusercontent.com/22554320/53721433-d2d90d00-3e95-11e9-874f-e7a60e96f96f.png">
<img width="454" alt="ketika tidak mendefinisikan nilai X (chart candle terlihat)" title="ketika tidak mendefinisikan nilai X (chart candle terlihat)" src="https://user-images.githubusercontent.com/22554320/53721434-d371a380-3e95-11e9-880c-94571db1b2d4.png">

### Data and config

```
        <CandleStickChart
            dragEnabled={true}
            pinchZoom={true}
            style={styles.chart}
            logEnabled={false}
            scaleYEnabled={false}
            drawGridBackground={false}
            mode={true}
            marker={{
                enabled: true,
                markerColor: processColor('#2c3e50'),
                textColor: processColor('white'),
            }}
            
            chartDescription={{text: ''}}
            legend={{
                enabled: false,
                textSize: 14,
                form: 'SQUARE',
                wordWrapEnabled: true
            }}
            maxVisibleValueCount={5}
            autoScaleMinMaxEnabled={true}
            zoom={{scaleX: 0, scaleY: 0, xValue:  2000, yValue: 0, axisDependency: 'LEFT'}}
            data={{
                dataSets: [
                  {
                    values: 
                        (function () {
                            data = props.chart.chart
                            chart_data = []
                            if (data.length > 0) {
                                for (i = 0; i < data.length; i++) {
                                    chart_data.push({
                                        x: parseFloat(data[i].dateTime * 1000),
                                        shadowH: parseFloat(data[i].highPrice), // required
                                        shadowL: parseFloat(data[i].lowPrice), // required
                                        open: parseFloat(data[i].openPrice), // required
                                        close: parseFloat(data[i].closePrice), // required
                                    })
                                }
                                return chart_data
                            }
                        }())
                    ,
                    label: `Market`,
                    config: {
                        highlightColor: processColor ('darkgray'),
                        shadowColor: processColor ('black'),
                        shadowWidth: 1,
                        shadowColorSameAsCandle: false,
                        increasingColor: processColor('#008E5F'),
                        increasingPaintStyle: 'FILL',
                        decreasingColor: processColor('#D32E2F'),
                        neutralColor: processColor('#333'),
                    },
                  },
                  
                ]
            }}
            xAxis={{
                enabled: true,
                drawLabels: true,
                drawGridLines: true,
                gridColor: processColor ('#e8e8e8'),
                textColor: processColor ('#777'),
                gridLineWidth: .5,
                valueFormatter: 'date',
                valueFormatterPattern: ("EEE, d MMM yyyy"),
                position: 'BOTTOM',
                labelCount: 4,
            }}
            yAxis={{
                right: {
                  enabled: true,
                  gridColor: processColor ('#e8e8e8'),
                  textColor: processColor ('#777'),
                  drawGridLines: true,
                  gridLineWidth: .5,
                  labelCount: 5,
                  valueFormatter: ('###,###,###'),
                },
                left: {
                  enabled: false,
                },
              }}
              
        />

```
### Steps to Reproduce the Problem

I am starting by entering value values 'X' and xAxis enabled and adding valueFormatter,
the date below appears exactly what I want, but a strange thing happens, when the data is displayed (defining the value of X from the array), the candle data is not visible (only a vertical black line) and that doesn't happen when I don't define the value X, but the date doesn't match...

### Specifications

  - Version: "react-native-charts-wrapper": "0.5.0", "react-native": "0.55.4",
  - Platform: "Android 8.0.0"
  - Subsystem:

**Comment by wuxudong** [comment]
` x: parseFloat(data[i].dateTime * 1000),`

means  x will be something like [1551694429918， 155169450000, ...] , then a big gap exists every neighbor x values.

**Comment by wuxudong** [comment]
#160 may help.

**Comment by KrushnaNaghate** [comment]
> ### Expected Behavior
> Add dateTime on the chart candle, the bottom of the chart (xAxis)
> 
> ### Actual Behavior
> when I add dateTime, the data candle becomes black (no data appears),
> 
> ### Screenshots
> <img alt="when defining the value of X (candle data becomes black)" width="454" src="https://user-images.githubusercontent.com/22554320/53721433-d2d90d00-3e95-11e9-874f-e7a60e96f96f.png">
> 
> <img alt="ketika tidak mendefinisikan nilai X (chart candle terlihat)" width="454" src="https://user-images.githubusercontent.com/22554320/53721434-d371a380-3e95-11e9-880c-94571db1b2d4.png">
> 
> ### Data and config
> ```
>         <CandleStickChart
>             dragEnabled={true}
>             pinchZoom={true}
>             style={styles.chart}
>             logEnabled={false}
>             scaleYEnabled={false}
>             drawGridBackground={false}
>             mode={true}
>             marker={{
>                 enabled: true,
>                 markerColor: processColor('#2c3e50'),
>                 textColor: processColor('white'),
>             }}
>             
>             chartDescription={{text: ''}}
>             legend={{
>                 enabled: false,
>                 textSize: 14,
>                 form: 'SQUARE',
>                 wordWrapEnabled: true
>             }}
>             maxVisibleValueCount={5}
>             autoScaleMinMaxEnabled={true}
>             zoom={{scaleX: 0, scaleY: 0, xValue:  2000, yValue: 0, axisDependency: 'LEFT'}}
>             data={{
>                 dataSets: [
>                   {
>                     values: 
>                         (function () {
>                             data = props.chart.chart
>                             chart_data = []
>                             if (data.length > 0) {
>                                 for (i = 0; i < data.length; i++) {
>                                     chart_data.push({
>                                         x: parseFloat(data[i].dateTime * 1000),
>                                         shadowH: parseFloat(data[i].highPrice), // required
>                                         shadowL: parseFloat(data[i].lowPrice), // required
>                                         open: parseFloat(data[i].openPrice), // required
>                                         close: parseFloat(data[i].closePrice), // required
>                                     })
>                                 }
>                                 return chart_data
>                             }
>                         }())
>                     ,
>                     label: `Market`,
>                     config: {
>                         highlightColor: processColor ('darkgray'),
>                         shadowColor: processColor ('black'),
>                         shadowWidth: 1,
>                         shadowColorSameAsCandle: false,
>                         increasingColor: processColor('#008E5F'),
>                         increasingPaintStyle: 'FILL',
>                         decreasingColor: processColor('#D32E2F'),
>                         neutralColor: processColor('#333'),
>                     },
>                   },
>                   
>                 ]
>             }}
>             xAxis={{
>                 enabled: true,
>                 drawLabels: true,
>                 drawGridLines: true,
>                 gridColor: processColor ('#e8e8e8'),
>                 textColor: processColor ('#777'),
>                 gridLineWidth: .5,
>                 valueFormatter: 'date',
>                 valueFormatterPattern: ("EEE, d MMM yyyy"),
>                 position: 'BOTTOM',
>                 labelCount: 4,
>             }}
>             yAxis={{
>                 right: {
>                   enabled: true,
>                   gridColor: processColor ('#e8e8e8'),
>                   textColor: processColor ('#777'),
>                   drawGridLines: true,
>                   gridLineWidth: .5,
>                   labelCount: 5,
>                   valueFormatter: ('###,###,###'),
>                 },
>                 left: {
>                   enabled: false,
>                 },
>               }}
>               
>         />
> ```
> 
> ### Steps to Reproduce the Problem
> I am starting by entering value values 'X' and xAxis enabled and adding valueFormatter, the date below appears exactly what I want, but a strange thing happens, when the data is displayed (defining the value of X from the array), the candle data is not visible (only a vertical black line) and that doesn't happen when I don't define the value X, but the date doesn't match...
> 
> ### Specifications
> * Version: "react-native-charts-wrapper": "0.5.0", "react-native": "0.55.4",
> * Platform: "Android 8.0.0"
> * Subsystem:

bro you helped me indirectly , by putting this code in issue , as I came across to see how to show time , thanks
