### ISSUE TITLE
BarChart dottedLine support

### ISSUE THREAD

**Issue by 2248157705** [wuxudong/react-native-charts-wrapper#486]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Specifications

  - Version:
  - Platform:
  - Subsystem:

![image](https://user-images.githubusercontent.com/4066040/53779808-97dde480-3f3c-11e9-8084-1f29552a8940.png)

1 is support horizontal dotted Line
2 how to change yAxis textColor
3 can I change legend position for example Bottom right corner
4 how to hidden vertical solid line

thank you very much

**Comment by 2248157705** [comment]
![image](https://user-images.githubusercontent.com/4066040/53780184-23a44080-3f3e-11e9-87d7-b36064a9ff75.png)
i found  
label: '2018年' ,
yAxis: {
        textColor: processColor('#B3BBC5'),
        fontFamily:Common.fontWeight.medium,
        textSize: Common.fontSize.font10,
      }
is not effect

**Comment by 2248157705** [comment]
![image](https://user-images.githubusercontent.com/4066040/53786268-2317a400-3f56-11e9-9b0c-f9295324545a.png)
how did show it

**Comment by wuxudong** [comment]
You can use `valueFormatter:  ["20.5%", "whatever you want", "-61%"]`

**Comment by 2248157705** [comment]
there have two value in every bar for example 200 and +20.5%

**Comment by 2248157705** [comment]
[see props gridDashedLine](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md)
