### ISSUE TITLE
Unable to share project with others

### ISSUE THREAD

**Issue by wongp** [wuxudong/react-native-charts-wrapper#487]
I've followed the instructions [here](https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md) and was able to get the project running locally, but when sharing the project, others are unable to run it because they do not have the Charts ios and SwiftyJSON installed. I installed those libraries manually as well by dragging and dropping the .xcodeproj files into my project.

How can I setup the project in such a way that all of the files are available in the project itself?

Thanks

**Comment by hellpirat** [comment]
Same here, even I can’t run on my own mac after reinstall node_modules and pods.

**Comment by hellpirat** [comment]
Fixed by 
```
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.5.3
```

**Comment by wongp** [comment]
Problem solved.

The folders for ios charts and swifty json were still being referenced locally rather properly checked into the project.

The next problem I ran into was getting my CI update to date to support the latest xcode. Once all that finally fell into place, everything worked.
