### ISSUE TITLE
ios: Swift Compile Errors ("Incorrect argument label...")

### ISSUE THREAD

**Issue by c-goettert** [wuxudong/react-native-charts-wrapper#489]
### Expected Behavior
App compiles
### Actual Behavior
XCode throws compile errors
### Screenshots

![bildschirmfoto 2019-03-08 um 10 23 06](https://user-images.githubusercontent.com/7591624/54020809-f1d5e880-418e-11e9-9320-7f2c7335101f.png)

### My Swift config in XCode:
![bildschirmfoto 2019-03-08 um 10 44 14](https://user-images.githubusercontent.com/7591624/54020898-3c576500-418f-11e9-9de2-a2bf5e8c03cf.png)
![bildschirmfoto 2019-03-08 um 10 44 21](https://user-images.githubusercontent.com/7591624/54020902-3eb9bf00-418f-11e9-80e9-2bcd786ade7a.png)

### Description: 
I followed the Instructions on the setup page. On Android, my project compiles fine but iOS isn't compiling. I don't use cocoapods, so I followed the instructions for manual setup. When I try to compile in XCode, it is giving me 5-Swift errors, e.g.:

`incorrect argument label in call (have 'values:label:', expected 'entries:label:')
Replace 'values' with 'entries'`

I created the RNCharts bridging-header file as stated in the docs. I also set the Swift Version to 4.2.
### Specifications

  - Versions:
React Native: 0.52.0
XCode 10 (Swift Version set to 4.2)
RN-Charts-Wrapper: ^0.5.1
Charts: 3.2.2

  - Platform: iOS

EDIT: 
I could solve this, I had used the latest version of SwiftyJSON, using v4.0.0 fixed the compile errors. Now I am facing [this issue](https://github.com/wuxudong/react-native-charts-wrapper/issues/374).

**Comment by c-goettert** [comment]
Using v4.0.0 of SwiftyJSON fixed these errors.

**Comment by omatrot** [comment]
I'd like to reopen this issue. Using v4.0.0 of SwiftyJSON does not work for me. The errors are exactly the same.

**Comment by IacoCesar** [comment]
same issue

**Comment by fonov** [comment]
i have same issue but update pods help me

```
pod 'SwiftyJSON', '5.0'
pod 'Charts', '3.3.0'
```
