### ISSUE TITLE
Line chart: Circle for first value is missing

### ISSUE THREAD

**Issue by c-goettert** [wuxudong/react-native-charts-wrapper#490]
I recognized that on LineCharts, the first value never has a circle on top of it. This is happening per default, also in the examples. See the following screenshot for reference:

![1](https://user-images.githubusercontent.com/7591624/54137631-45119a80-441e-11e9-9189-fa68f963f338.jpg)

I played around with some settings (zooming, scrolling, styling, etc.) but couldn't find any working setup where the first value would also display a circle. In my scenario the first circle is necessary because some datasets might only contain one single value (which won't be visible otherwise).

This issue seems to be related to the wrapper-project, because in the Example-App of MPAndroidChart it's possible to see one single value in Line-Charts and you see a Circle on top of the first value as well: 

![123](https://user-images.githubusercontent.com/7591624/54138973-d5e97580-4420-11e9-95d8-35a5b4e8faf5.jpg)

Does anyone know why this happens or has a suggestion to fix this for my case?

------------
Update: On Android the circles draw just fine, this seems to be only an issue with iOS.

**Comment by c-goettert** [comment]
Update: This seems to be an issue of Charts library for iOS (see related [issue](https://github.com/danielgindi/Charts/issues/3881)). Hope that this will be fixed in the next release. Closing this issue now.

**Comment by c-goettert** [comment]
Update #2: For anyone suffering from the same problem: It's possible to fix this with a quick hack until this is merged. Presuming you have installed the library manually, you can apply the fix in the Native XCode-Project of the Charts library. You need to adjust the file `BarLineScatterCandleBubbleRenderer.swift`: 
```diff
         public mutating func next() -> Int? {
-            guard value < bounds.max else { return  nil }
-            value += 1
+            guard value <= bounds.max else { return  nil }
+            defer { value += 1 }
             return value
         }
```
This fixed it for me.

**Comment by mogluszka** [comment]
Thank you so much @c-goettert, your solution saved me a lot of time. :)
