### ISSUE TITLE
[Android] The legend spill out the view

### ISSUE THREAD

**Issue by nguyenhathanh510** [wuxudong/react-native-charts-wrapper#492]
How can wrap the lenged on android if I have a long list to show on pie chart
### iOS
<img width="385" alt="Screen Shot 2019-03-18 at 3 03 44 PM" src="https://user-images.githubusercontent.com/18468789/54515628-3895c080-498f-11e9-87d8-80d5fb4c6c57.png">

### Android
<img width="393" alt="Screen Shot 2019-03-18 at 2 08 34 PM" src="https://user-images.githubusercontent.com/18468789/54515620-33d10c80-498f-11e9-83e2-87cd3785fc8b.png">

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.
