### ISSUE TITLE
how to get xAxis label value and fix this view barchart

### ISSUE THREAD

**Issue by kautsarajiw** [wuxudong/react-native-charts-wrapper#493]
Hello, I need help, I have two problems on this chart.

1. how do I get values from xAxis ? the value I mean is the label from xAxis, but I always get an array value not the value of the label, like this : 
![Screen Shot 2019-03-19 at 13 27 14](https://user-images.githubusercontent.com/32380621/54586401-8eca3880-4a4f-11e9-89fd-8dfe4ff85b98.png)

![Screen Shot 2019-03-19 at 13 28 34](https://user-images.githubusercontent.com/32380621/54586335-4d398d80-4a4f-11e9-95e2-7bb05cb54de1.png)

2. if the bar is only one, the display will be like this and the value in that bar will not come out, like this : 
![Screen Shot 2019-03-19 at 13 26 50](https://user-images.githubusercontent.com/32380621/54586501-d51f9780-4a4f-11e9-9de0-2e0d4e95354d.png)

I have searched and tried everything but I did not find what I was looking for, Thank you for helping and thank you for creating this library, I was very helped by this.

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.

**Comment by Skullcan** [comment]
I'm having the same situation of problem number 2.

I have a vertical barchart with only one bar. I want it to be centered. 
![image](https://user-images.githubusercontent.com/10976772/110339169-9b624580-8006-11eb-8729-d7fa04e04c7d.png)

Can I do that?
Thanks.
