### ISSUE TITLE
Failed to build the demo according to installation_guide/README.md

### ISSUE THREAD

**Issue by JiyeYu** [wuxudong/react-native-charts-wrapper#495]
Such error happened when I try to make the basic build according to the installation_guide.

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
The following commands produced analyzer issues:
	Analyze /Users/jiye/workspace/temp/demo/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
	Analyze /Users/jiye/workspace/temp/demo/node_modules/react-native/Libraries/Image/RCTImageCache.m normal x86_64
	Analyze /Users/jiye/workspace/temp/demo/node_modules/react-native/Libraries/Network/RCTNetInfo.m normal x86_64
(3 commands with analyzer issues)

The following build commands failed:
	Ld /Users/jiye/workspace/temp/demo/ios/build/Build/Products/Debug-iphonesimulator/demo.app/PlugIns/demoTests.xctest/demoTests normal x86_64
(1 failure)
```

This error happened at the last step of the guide: react-native run-ios ( same error happened if I ran it by XCode ). Before that, everything seemed to be fine. 

Anyone knows what happened? Version not match?

### Specifications

  - Version: 

```
$ yarn -v
1.13.0

$ react-native -v
react-native-cli: 2.0.1
react-native: 0.58.6

$ pod --version
1.5.3

Xcode 10.1
Swift  4.2.1
react-native-charts-wrapper 0.5.1
```

  - Platform: MacOS Mojave version 10.14.3

### Screenshot

![image](https://user-images.githubusercontent.com/20236152/54910343-7cf50380-4f2f-11e9-8db2-613efa23b797.png)

![image](https://user-images.githubusercontent.com/20236152/54909779-49fe4000-4f2e-11e9-82bf-e8fc1ee9f03d.png)

**Comment by JiyeYu** [comment]
Seems this error happened at the test stage. One solution is disabling the test activity in the build work. (Check this link for disabling the test: http://cleanswifter.com/disable-tests-xcode/ ) However, I hope we can find a better solution for this issue.

**Comment by Nishchit14** [comment]
I am facing the same error, spent all most a day. I have tried Example folder it's working fine but the same implementation fires same above error :D

**Comment by Nishchit14** [comment]
I have also tried disabling test mode but still, I'm facing this error, Have you got any solution? @JiyeYu

**Comment by JiyeYu** [comment]
@Nishchit14 I have no further idea on this issue.. But disabling test works for me.

**Comment by wuxudong** [comment]
@Nishchit14 where does the error occurs?  in built-in Example project or your own demo project?

**Comment by Nishchit14** [comment]
@wuxudong In my own project. 

This is how the library and Frameworks looks
![image](https://user-images.githubusercontent.com/5078921/58401981-dd620780-807c-11e9-8131-371a9bfe6778.png)


And this is Link Binary

![image](https://user-images.githubusercontent.com/5078921/58402020-fa96d600-807c-11e9-9e99-1bc6cc0dabe4.png)

**Comment by wuxudong** [comment]
Your project is not using Cocoapods, and I can't find RNCharts/Charts in your dependencies?

**Comment by Nishchit14** [comment]
It is, let me share  full screenshot,

![image](https://user-images.githubusercontent.com/5078921/58409569-fc1cca00-808d-11e9-8ccf-f5ae4fc22b36.png)


What do you say? This is a pods related error or architecture related? like 64bit.

```
ld: can't map file, errno=22 file '/Users/nd/Library/Developer/Xcode/DerivedData/Project-dojptgftkqhhhscmegyoqdqnpefv/Build/Products/Debug-iphonesimulator' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by wuxudong** [comment]
```
if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo.
```
The pod already imports yoga, react, ...etc,  so there may be troublesome of  importing duplicated libraries in `library and Frameworks` 

Make it a try, or create a new project and run integration again.

**Comment by Nishchit14** [comment]
For the first point, It's after the simulator initialized, right? Here simulator is not opening this error I am getting at build time.

And the second option let me check, I am very new in Xcode, just wanna release the react-native app.

**Comment by wuxudong** [comment]
Several things you can try to figure out the underlying problem.

1.  build the simplest demo by following [tutorial](https://github.com/wuxudong/react-native-charts-wrapper/tree/master/installation_guide#ios)

2. if the demo works well, but your own project is still not working, you can try to remove chart components from your project, then check if it can compile successfully? Sometime compilation error is caused by other settings, not by react-native-charts-wrapper.

3. if compilation failed even if you remove react-native-charts-wrapper in step 2, but the demo project in step 1 works well. Then you can gradually copy your components from your project to demo project.

**Comment by Nishchit14** [comment]
Thank you very much for your instant support @wuxudong 

I have followed step2  then I have clone same project, re-generated `ios` folder and move all libs in Pods. Now build is generating successfully but I couldn't able to log in into app because `cmd + D` is not working in the simulator. I have to debug it to see the error.

Here is my Podfile looks like 

```
platform :ios, '9.0'
use_frameworks!

target 'ETFication' do

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
    pod 'React', path: '../node_modules/react-native/', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
    'CxxBridge',
    'DevSupport',
    ]

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
    
    swift5 = ['Charts', 'SwiftyJSON']
    
    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if swift5.include?(target.name)
            config.build_settings['SWIFT_VERSION'] = '5.0'
          end
        end
      end
    end

end

```

**Comment by wuxudong** [comment]
Check the installation tutorial.

`if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo.`

**Comment by Nishchit14** [comment]
This statement is a bit confusing, other libraries mean all other libraries? If so then I How it would work without a required third-party library? 

And I have two apps in target
1. Demo
2. DemoTest

Am I right with Target? or I am understanding wrong.

and If I remove the `RNGestureHandler` from the library then build will be successful but app showing this error.

![image](https://user-images.githubusercontent.com/5078921/58459273-9ccfc000-8148-11e9-9f7b-701bc8163fd2.png)



![image](https://user-images.githubusercontent.com/5078921/58459249-8de90d80-8148-11e9-970a-f98bd41fe649.png)

**Comment by wuxudong** [comment]
If you are using cocoapod to manage your dependencies, then these lib are already included by  Pods_demo.framework, and for those  libs which are not managed by cocoapod, It is fine to keep them.

**Comment by Nishchit14** [comment]
Bad luck, If I removed those libraries from Library group then the app is crashing on startup.

Here is my Pod looks like, Is it a `Development Pods` issue?
![image](https://user-images.githubusercontent.com/5078921/58477140-7756ac80-8170-11e9-95bf-d7f6c671a590.png)

**Comment by Nishchit14** [comment]
I have linked it manually then it's working fine, Thank you for all the help @wuxudong
