### ISSUE TITLE
How to make an lines and area between or on area?

### ISSUE THREAD

**Issue by hellpirat** [wuxudong/react-native-charts-wrapper#496]
How can I make this chart with this library? I did a chart with three lines.
- values
- from top to zero bottoms (color: green)
- from the end of green value to bottom: (color: white)

But I don't like this solution because there a fillAlpha make my lines are not visible in this area and I can make multiple areas for this. 

### Screenshots
![image](https://user-images.githubusercontent.com/6241354/55001081-e84cdd00-4fe4-11e9-9901-a323ac82ae4c.png)

**Comment by hellpirat** [comment]
LOL, fixed by moving data in dataset under area.

**Comment by 3luyka** [comment]
@hellpirat hey, could you please provide code example?
