### ISSUE TITLE
Does this work on React-Native v0.43.4 or higher??

### ISSUE THREAD

**Issue by riftshock** [wuxudong/react-native-charts-wrapper#50]
**packages versions**
    react : 16.0.0-alpha.6,
    react-native : 0.43.4,
    react-native-charts-wrapper : 0.2.8,

Somehow I can't seem to get it work.. all I see using the examples is a white screen with a red vertical red line on the left side. Or am I doing anything wrong??

**Comment by wuxudong** [comment]
react-native : 0.43.4 works for me.
I think it is a problem of bridge header, check the console log in browser window.

**Comment by Mkalla** [comment]
Same problem here. Indeed it seems to be the bridging header. If I add the files to my project, Xcode doesn't prompt me to create a bridging header. Adding a bridging header manually doesn't work, because my react-native iOS project has no section "Swift compiler - general" under the build settings.

React-native: 0.44.0

Any solution for this?

**Comment by riftshock** [comment]
@Mkalla thanks for the reply and the solution bro..but I'm on android and the bridging configuration only works on IOS version of the app I have the same output for issue #51 but on my android phone. 

Anyway any help will gladly appreciate it ;) thanks a lot man

**Comment by wuxudong** [comment]
turn on Debug JS Remotely, and check the log

**Comment by rafaelviny** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/issues/51

try my solution

**Comment by rl-0x000** [comment]
As per #51 the solution for me was to ensure that the directory 'node_modules/react-native-charts-wrapper/ios/ReactNativeCharts' is added as a Groups (blue) not Files (yellow).

The  easiest way to do this is to use DnD from Finder and drop the 'node_modules/react-native-charts-wrapper/ios/ReactNativeCharts' folder into the top level of your project. This will cause Xcode to prompt you to 'Choose options for adding these files:' and if you select 'Create groups' as per the screenshot below, then click 'Finish' it will do the right thing.

![xcode - create groups](https://cloud.githubusercontent.com/assets/29053346/26566144/31609364-4534-11e7-9f07-5ad8cc32bf72.png)

This will get rid of the warnings from #29:
  Warning: Native component for "RNBarChart" does not exist

and the 'white screen' issue above.

FYI: Project is using the latest react-native as per react-native-git-upgrade:
    https://facebook.github.io/react-native/blog/2016/12/05/easier-upgrades.html
"react": "16.0.0-alpha.6"
"react-native": "0.44.2"

**Comment by dburgmann** [comment]
For me it still does not work. I do not get the prompt nor do I have the Swift-Compiler option to add the bridging header manually. 

Creating a empty swift file and / or adding the files as group did not help.

Using React native 0.44.2

**Comment by kyle-ssg** [comment]
It'd be good if the readme was updated to reflect this. Spent far too long before realising this ^^

**Comment by zack-hx** [comment]
my solution: drag folder node_modules/react-native-charts-wrapper/ReactNativeCharts to top level select "Create Group"
