### ISSUE TITLE
Build fail with XCode10 

### ISSUE THREAD

**Issue by rollback228** [wuxudong/react-native-charts-wrapper#501]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Steps to Reproduce the Problem
I step up manual and get this error

![image](https://user-images.githubusercontent.com/7988087/55399586-acca8980-5575-11e9-92a9-98b0ccb57bdf.png)
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by omatrot** [comment]
There seems to be an inconsitency with the Chart swift package. If you jump to the definition of the BubbleChartDataSet, you'll see that the constructor signature is not the one that this code expects.

**Comment by wuxudong** [comment]
If you are using manual install, you should pick correct version.

v0.5.1 expects Charts v3.2.2

**Comment by rollback228** [comment]
OKay. Thank you.
I build it successful. But i got a crash when using RNPiechart.
It run without problem on android 
![image](https://user-images.githubusercontent.com/7988087/55418215-60467480-559c-11e9-9d66-a7d7df3c37b9.png)

**Comment by P21Marcelo** [comment]
> OKay. Thank you.
> I build it successful. But i got a crash when using RNPiechart.
> It run without problem on android
> ![image](https://user-images.githubusercontent.com/7988087/55418215-60467480-559c-11e9-9d66-a7d7df3c37b9.png)

Im facing the same. even i did follow the step by step guide religiously, the same error is thrown.

**Comment by wuxudong** [comment]
@rollback228 Can you provide a screenshot of your Xcode?

Manual installation involves more work.

Your problem is similar to #307 

and [link](https://www.evernote.com/shard/s304/sh/5d501d94-a8e0-4309-9866-e2026356a29d/130a7aa8b84d73a6) may help.
