### ISSUE TITLE
How to handle the touch events on the Pie chart?

### ISSUE THREAD

**Issue by rajubhusani** [wuxudong/react-native-charts-wrapper#504]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**
Library working without any issue but I would like to implement the touch events on the Pie chart data, once click on the I have to update some views in the screen. Can anyone help me on this?
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wuxudong** [comment]
There is a onSelect callback. Once user click a slice of pie, the callback will be triggered.

**Comment by zoomerland** [comment]
onSelect if click on label outside of slice have no data inside
