### ISSUE TITLE
Example app crashes on startup, using any simulator with Xcode 10.2

### ISSUE THREAD

**Issue by DealPete** [wuxudong/react-native-charts-wrapper#507]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
App working normally

### Actual Behavior
App works fine on my device, but crashes on launch when booted on a simulator. If I use XCode to compile it in debug mode for a simulator, it stops with a SIGABRT signal, and display this message in the console:

objc[21464]: Swift class extensions and categories on Swift classes are not allowed to have +load methods

I also tried to archive it, then export to with an AdHoc distribution and install it on a simulator with "xcrun simctl install (device UUID) Example.app". It installs fine, but crashes with the log messages:

Apr  8 15:52:48 Peters-MacBook-Pro com.apple.CoreSimulator.SimDevice.9B6842B0-4965-485A-B295-8F2B4D20EEB9[21360] (UIKitApplication:com.github.wuxudong.reactnativechartwrapper.Example[0xc1ec][21384][28584]): Program specified by service does not contain any valid architectures for this system.
Apr  8 15:52:48 Peters-MacBook-Pro com.apple.CoreSimulator.SimDevice.9B6842B0-4965-485A-B295-8F2B4D20EEB9[21360] (UIKitApplication:com.github.wuxudong.reactnativechartwrapper.Example[0xc1ec][21384][28584]): Service exited with abnormal code: 78

Running "react-native run-ios" leads to a crash at the same place.

### Steps to Reproduce the Problem

1) Clone the repo
2) cd Example
3) yarn
4) cd ios
5) pod install
6) open Example.xcworkspace in XCode 10.2
7) add glog and DoubleCoversion frameworks to "Link Binary With Libraries" under the React Pod (this appears to be a bug with React, it won't compile otherwise)
8) Either select a simulator from the menu and press play, or archive it and install manually as described above.

### Specifications

  - Version: 0.5.1
  - Platform: macOS Mojave
  - Subsystem: XCode 10.2

**Comment by yjb2020** [comment]
I meet this problem too

**Comment by wuxudong** [comment]
duplicate to #508 
update your react-native version.

**Comment by DealPete** [comment]
thanks, upgrade react-native seems to have solved it.
