### ISSUE TITLE
App crashes on Xcode 10.2 and IOS 12.2

### ISSUE THREAD

**Issue by P21Marcelo** [wuxudong/react-native-charts-wrapper#508]
Error: Swift class extensions and categories on Swift classes are not allowed to have +load methods react-native

### Expected Behavior
it is expected to build normally on Xcode 10.2
### Actual Behavior
when i run the project using Xcode 10.2 and a simulator or device with IOS 12.2 the app crashes. xcode return me the following message: 
 "Swift class extensions and categories on Swift classes are not allowed to have +load methods react-native"
obs: It runs just fine when i use Xcode 10.1 and a simulator with IOS 12.1
maybe its related with swift 5 recent release.

### Specifications
  - Version:v0.5.1
  - Platform:IOS
  - Subsystem: Mac

**Comment by hellpirat** [comment]
+

**Comment by gaykov** [comment]
Try React Native `0.59.3`, it should be fixed there.

**Comment by P21Marcelo** [comment]
> Try React Native `0.59.3`, it should be fixed there.

will give it a try. my actual version of RN is 0.58.6.

**Comment by hellpirat** [comment]
Fixed after upgraded to react-native 0.59.3

**Comment by P21Marcelo** [comment]
Fixed after upgrade to 0.59.4, thanks @gaykov and @hellpirat for helping.

**Comment by fenglu09** [comment]
Same problem. react-native version is 0.48.3.
Is there any other solution besides upgrading RN to 0.59.3?

**Comment by wuxudong** [comment]
Pick up older version?
