### ISSUE TITLE
IOS blank chart

### ISSUE THREAD

**Issue by rafaelviny** [wuxudong/react-native-charts-wrapper#51]
Hello everyone.
I am trying to generate the graphics in IOS and they appear blank. They work perfectly on the android.
All steps were performed.
Infos: Xcode Version 8.3.2
RN 0.43.4
![captura de pantalla 2017-05-14 a la s 20 07 25](https://cloud.githubusercontent.com/assets/3612516/26038549/4a911c14-38e1-11e7-9c8b-69df5a6b3250.png)

Thank you

**Comment by wuxudong** [comment]
Where is added source files?

Have you set the bridging header in General Settings?

**Comment by rafaelviny** [comment]
Hi Wuxudong

in general settings? or Build Settings?


![captura de pantalla 2017-05-15 a la s 07 50 01](https://cloud.githubusercontent.com/assets/3612516/26054532/4d0d6a80-3943-11e7-8892-7a33f4f3b7fd.png)
![captura de pantalla 2017-05-15 a la s 07 49 56](https://cloud.githubusercontent.com/assets/3612516/26054534/4ef10190-3943-11e7-97ad-c244e0625be4.png)
![captura de pantalla 2017-05-15 a la s 07 47 58](https://cloud.githubusercontent.com/assets/3612516/26054541/5899fb98-3943-11e7-8609-5fc8928b5500.png)


in other project use:
![captura de pantalla 2017-05-15 a la s 07 54 50](https://cloud.githubusercontent.com/assets/3612516/26054700/e17bd7ba-3943-11e7-9eb3-8d231c25ab59.png)

**Comment by wuxudong** [comment]
In other people's comments, the added source fold should be yellow color, not blue color.

**Comment by rafaelviny** [comment]
![captura de pantalla 2017-05-15 a la s 08 45 22](https://cloud.githubusercontent.com/assets/3612516/26056286/0e7cf562-394b-11e7-9a83-7e2a5c0247cd.png)

Is this folder correct? After adding is blue, I have no idea how to do otherwise

**Comment by wuxudong** [comment]
I suggest run Example first, then compare it with yours.

**Comment by wuxudong** [comment]
Try add it "under" the "top-level".

**Comment by rafaelviny** [comment]
1 - npm install --save react-native-charts-wrapper
2 - react-native link react-native-charts-wrapper
3 - add directory node_modules/react-native-charts-wrapper/ReactNativeCharts under your project top level. (In Xcode: File -> Add files to "App Name")
4- create a blank Swift class, A screen will appear to create the bridge.
5 - copy to new file APP_NAME-bidge.h
	#import "React/RCTBridge.h"
	#import "React/RCTViewManager.h"
	#import "React/RCTUIManager.h"
	#import "React/UIView+React.h"
	#import "React/RCTBridgeModule.h"
	#import "React/RCTEventDispatcher.h"
	#import "React/RCTEventEmitter.h"

6 - create a Podfile in iOS folder

use_frameworks!

target '**MY_APP_NAME**' do
pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end

7 - using console go to IOS folder and run pod install
8 - **IMPORTANT**
Go to XCODE File > new > Group and change name to ReactNativeChart, repita o processo e crie a mesma estrutura que esta na pasta ReactNativeChart azul na nova pasta ReactNativeChart amarela, e copie todos os arquivos para suas respectivas pastas amarelas
![captura de pantalla 2017-05-16 a la s 09 51 49](https://cloud.githubusercontent.com/assets/3612516/26106768/62f90248-3a1d-11e7-8d72-c86711f28fb0.png)
![captura de pantalla 2017-05-16 a la s 09 52 10](https://cloud.githubusercontent.com/assets/3612516/26106769/632e19f6-3a1d-11e7-9f82-16cdc29c6cd7.png)

**Comment by rafaelviny** [comment]
thx to support @wuxudong, The small tutorial above is my small contribution to those who are having difficulties

**Comment by wuxudong** [comment]
@rafaelviny  thanks for you support, there is some type error in your comment, can you fix it?

`Go to XCODE File > new > Group and change name to ReactNativeChart, repita o processo e crie a mesma estrutura que esta na pasta ReactNativeChart azul na nova pasta ReactNativeChart amarela, e copie todos os arquivos para suas respectivas pastas amarelas`

**Comment by rafaelviny** [comment]
sorry, fixed

**Comment by paul-aigue** [comment]
Hi @wuxudong @rafaelviny When you're at the step "**Add file**", ensure that "**Create Groups**" and "**Copy Items if needed**" options are **checked** as follow : 
![capture d ecran 2017-05-31 a 13 53 07](https://cloud.githubusercontent.com/assets/11890649/26646237/de49aba4-4608-11e7-840f-e67f1b861617.png)

So your files will be added correctly as resources !

**Comment by nemom0901** [comment]
hello everyone
I am trying to  run Example in IOS on rafaelviny's tutorial and they appear blank. 
any other steps that I possibly miss ?
Infos: Xcode Version 8.3.2
RN 0.44.2
Thank you

**Comment by shaun2099** [comment]
Hi Guys,
I just managed to run the example today after few days struggle.
For my env, Xcode = 8.3.2, RN = 0.45.1
There are few tips you should follow since the setup guide is quite some days ago and not fits in latest versions of Xcode and RN
1. You need to follow the Manual install even if you have run pod install by [](https://www.npmjs.com/package/react-native-charts-wrapper), make sure the 2 framework are in place
2. You can create a bridging header file by drag and drop, refer this [](https://github.com/wuxudong/react-native-charts-wrapper/issues/50),
and see my working Xcode config
<img width="1065" alt="screen shot 2017-06-19 at 9 15 39 pm" src="https://user-images.githubusercontent.com/6882091/27287118-450d9cde-5535-11e7-8ee3-503dd24ac4d0.png">
3. some modules in the example are deprecated, if your Xcode has no build error, you can try to only import one char in the index.ios.js

Hope this can help

**Comment by zhangyanlf** [comment]
I want to add multiple graphics in a ScrollView, when trying to add graphics in the ScrollView cannot shows, how to solve this problem?

**Comment by abcde1499** [comment]
Hi @rafaelviny, 
I'm using xcode 8.3.3
After I create a blank Swift class, there's no screen appear for creating the bridging-header file.

Anyone facing the same issue??

**Comment by dgnms** [comment]
Thnx guys @rafaelviny ,  @shaun2099  @wuxudong. For friends who see empty screen, I'll write something. I tried to do it for 1 days. successfull :)
1 - npm install --save react-native-charts-wrapper
2 - react-native link react-native-charts-wrapper
3 - drag and drop "node_modules/react-native-charts-wrapper/ios/ReactNativeCharts" to project under the top level. Ensure that "Create Groups" option is checked.
4 - create empty .swift file on Xcode( File > New > File...)  If the "create bridging header" option does not come,
 create "**MY_APP_NAME**-Bridging-Header.h" file and add:
 #import "React/RCTBridge.h"
#import "React/RCTViewManager.h"
#import "React/RCTUIManager.h"
#import "React/UIView+React.h"
#import "React/RCTBridgeModule.h"
#import "React/RCTEventDispatcher.h"
#import "React/RCTEventEmitter.h"

drag and drop "**MY_APP_NAME**-Bridging-Header.h" file to project under the top level.
5 - create a Podfile in iOS folder ( pod init )

use_frameworks!

target 'MY_APP_NAME' do
pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end

6 - using console go to IOS folder and run ( pod install )
7 - Clean and build your project and ENJOY!!

**Comment by jackmew** [comment]
I follow the step by @dgnms .  But the chart still blank. I compare the all setting in Xcode with Example.  I need to add all ReactNativeChart/xxx to Compile Sources. Finally I success.

<img width="1396" alt="screen shot 2017-08-23 at 10 10 49 pm" src="https://user-images.githubusercontent.com/6193983/29623463-a7cc5a2e-8850-11e7-994b-4ef3a6d2300d.png">

**Comment by insidelabs** [comment]
exact same problem here, but on Android. It only draws a red border around where the chart should be. RN 0.45.1, latest version of react-native-charts-wrapper

**Comment by wuxudong** [comment]
Turn on 'Debug Remotely', and check the log.
