### ISSUE TITLE
ValueFormater for currency in Yaxis

### ISSUE THREAD

**Issue by hungtd97** [wuxudong/react-native-charts-wrapper#510]
### Expected Behavior
I want to format currency value in yaxis like 1,000,000 to 1M. Can I do this with `react-native-charts-wrapper` and how to do this??
### Screenshots
<img width="99" alt="Screenshot 2019-04-09 at 5 19 48 PM" src="https://user-images.githubusercontent.com/41476559/55793080-48b34280-5aec-11e9-9860-4d76b4f6afbf.png">

**Comment by hungtd97** [comment]
Hello @wuxudong. Can you give me some advice?

**Comment by hungtd97** [comment]
> ```
> valueFormatter: PropTypes.oneOfType([
>     PropTypes.oneOf(['largeValue', 'percent', 'date']),
>     PropTypes.string,
>     PropTypes.arrayOf(PropTypes.string)
>   ]),
> ```
> give largeValue a try.

that's awesome.

**Comment by tamacroft** [comment]
how to change mSuffix ? example : results is $14,5 k but i want to change $14,5 K ?

**Comment by hungtd97** [comment]
> how to change mSuffix ? example : result is $14,5 k but i want to change $14,5 K ?

This is how I did: update formatter for IOS in ios/ReactNativeCharts/formatters/LargeValueFormatter.swift,
but in android the formatter located in **MPAndroidChart**, so you need to fork it and make the new version of package by yourself.
