### ISSUE TITLE
Undefined symbol: google::LogMessage::LogMessage(char const*, int, int)

### ISSUE THREAD

**Issue by robinv8** [wuxudong/react-native-charts-wrapper#511]
按照步骤配置ios,并跑本库给出的demo，均报错如下：
![image](https://user-images.githubusercontent.com/12277531/55821991-46bfa280-5b31-11e9-8cdd-e1f9a4417d84.png)

**Comment by PhfManager** [comment]
the same

**Comment by PhfManager** [comment]
mitou

**Comment by IacoCesar** [comment]
same issue

**Comment by IacoCesar** [comment]
any solution?

**Comment by rahul26496** [comment]
any solution?
