### ISSUE TITLE
SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftyJSON')

### ISSUE THREAD

**Issue by serdarosmanonur** [wuxudong/react-native-charts-wrapper#517]
I am getting this error when trying to install this on iOS:

SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'SwiftyJSON')

My XCODE version: Version 10.1 (10B61)

I tried everything in the documentation. I also set the SWIFT_VERSION to 4.2 in build settings of my project, still getting the same error.

**Comment by wuxudong** [comment]
new version is published to support swift 5.0

**Comment by wuxudong** [comment]
The latest version requires xcode 10.2, swift 5
