### ISSUE TITLE
引入cocopod以后，react-native ios 调试菜单出不来，无法进入debug 模式

### ISSUE THREAD

**Issue by 2248157705** [wuxudong/react-native-charts-wrapper#518]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by 2248157705** [comment]
请问 git主有遇到这个问题么？

**Comment by wuxudong** [comment]
if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo.
