### ISSUE TITLE
Bar Chart is not Refreshed after State Update

### ISSUE THREAD

**Issue by co-de** [wuxudong/react-native-charts-wrapper#519]
I created a component that I use for drawing bar charts. I am providing parameters to this chart to draw the y and x axis. When the page first loads, **this chart is drawn successfully**, but when the state is updated the chart is **not re-freshed** and displays the old values. 

```
<BarChartDrawer 
                            yvalues={this.state.myObj.people.map((item)=>{
                                console.log(item.grade);// prints new state values
                                return item.grade;
                            })}
                            xvalues={this.state.myObj.people.map((item)=>{
                                return item.name;
                            })}
/>


```
As you can see, I have defined two properties for my BarChartDrawer component in an effort to make it reusable. The properties' values are directly coming from the state of the parent component. I was thinking that once the state is updated, new values would be drawn by this bar chart component but it just stays the same.

I appreciate the great work so far. Can you help me with this problem?

Cheers

**Comment by wuxudong** [comment]
I think the problem related to your own BarChartDrawer.

**Comment by co-de** [comment]
Actually the drawer is an exact copy of this: https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/BarChartScreen.js

only changes are the below lines:

```
constructor(props) {
    super(props);
```

and

      ```
data: {
        dataSets: [{
          values: this.props.yvalues,//[{y: 100}, {y: 105}, {y: 102}, {y: 110}, {y: 114}, {y: 109}, {y: 105}, {y: 99}, {y: 95}],
          label: 'Bar dataSet',
          config: {
            color: processColor('teal'),
            barShadowColor: processColor('lightgrey'),
            highlightAlpha: 90,
            highlightColor: processColor('red'),
          }
        }],

        config: {
          barWidth: 0.7,
        }
      },
      highlights: [{x: 3}, {x: 6}],
      xAxis: {
        valueFormatter: this.props.xvalues,//['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        granularityEnabled: true,
        granularity : 1,
      }
```

**Comment by wuxudong** [comment]
Reproducible demo is required.

**Comment by co-de** [comment]
I found the problem. It was in my BarChartDrawer component.
