### ISSUE TITLE
Pie chart percent value style config

### ISSUE THREAD

**Issue by junshengpierre** [wuxudong/react-native-charts-wrapper#52]
Hi, may I know if it is possible to set the font size and color of the percent values of the pie chart segments? `entryLabelTextSize` and `entryLabelColor` seem to only affect the label text size and color on both iOS and android.

Thank you.

`entryLabelTextSize`: 12, 
`entryLabelColor` : {processColor('white')}
<img width="359" alt="screen shot 2017-05-15 at 4 56 24 pm" src="https://cloud.githubusercontent.com/assets/14052341/26049967/81896ace-398f-11e7-89a3-c38b90eb405f.png">

**Comment by wuxudong** [comment]
EntryLabelTextSize and entryLabelColor  are special in pie chart.
There are also common config like:
 
       valueTextSize:PropTypes.number,
       valueTextColor:PropTypes.number,

You can take a try.

**Comment by junshengpierre** [comment]
Hi,

I've tried the following:
```
valueTextSize={20}
valueTextColor={processColor('white')}
```
but the result was the same.

**Comment by wuxudong** [comment]
![simulator screen shot 15 may 2017 5 59 29 pm](https://cloud.githubusercontent.com/assets/1391101/26052569/8288036e-3998-11e7-8e07-84b102321977.png)

It works in Example pieChart.

**Comment by junshengpierre** [comment]
Ah. I passed them as props to the PieChart react component instead of the dataSet configs. It absolutely works! Thank you so much for your help!
