### ISSUE TITLE
update Xcode10.2 swift compiler error

### ISSUE THREAD

**Issue by 2248157705** [wuxudong/react-native-charts-wrapper#520]
![image](https://user-images.githubusercontent.com/4066040/56400074-6028c300-6284-11e9-8902-9982ba8b2b9c.png)
help me !

**Comment by 2248157705** [comment]
Clean Build Folder the error lost .
but there is ohter error, 
if i remove the libReact.a in the linked frameworks and libraries I get the error as follow 
![image](https://user-images.githubusercontent.com/4066040/56402351-8c960c80-628f-11e9-928c-8fd023a79ca6.png)
if I get add the libReact.a in the linked frameworks and libraries the release mode ipa will crash
how can i do

**Comment by 2248157705** [comment]
if you can't open development menu in iOS simulator, you can remove other libraries except Pods_demo.framework, and delete other targets except demo.
It  solve my problem

**Comment by neemssoni** [comment]
I am also getting the same error, after upgrading to react-native 0.59.9, cleaning build folder did not help me.
