### ISSUE TITLE
lineChat  value missing

### ISSUE THREAD

**Issue by liuqing520it** [wuxudong/react-native-charts-wrapper#522]
Where did you throw my '0'? and How to keep decimal places?

**Comment by liuqing520it** [comment]
![121212](https://user-images.githubusercontent.com/16216435/56421053-4bbfe700-62d3-11e9-88be-e848d6ad1548.jpg)

**Comment by liuqing520it** [comment]
set valueFormatter: '#0.00' fixed

**Comment by YisusMB** [comment]
Hi @liuqing520it how do yo change the color of the xAxis and yAxis? i try set property yAxis={textColor: processColor('#FFF')} but it dosnt change

**Comment by liuqing520it** [comment]
try like this
yAxis={
       {textColor: processColor('#FFF')}
}
