### ISSUE TITLE
`PieChart` has no propType for native prop `RNPieChart.syncX` of native type `BOOL`

### ISSUE THREAD

**Issue by thuanphamdev** [wuxudong/react-native-charts-wrapper#523]
hi ad,

I run example from https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/PieChartScreen.js

![Simulator Screen Shot - iPhone X - 2019-04-20 at 22 25 17](https://user-images.githubusercontent.com/37131833/56459412-75edd380-63bd-11e9-9a69-fc509f94e862.png)

  - Version: 0.5.2
  - Platform: IOS

Thanks ad!

**Comment by wuxudong** [comment]
currently, syncX is only work with subclass of barlineChart.

**Comment by thuanphamdev** [comment]
hi @wuxudong,

How to run example PieChart without this error above? Thank ad!

**Comment by wuxudong** [comment]
Just remove group, syncx, syncy etc.

**Comment by thuanphamdev** [comment]
hi @wuxudong ,

You can update source fix this bug? Thank @wuxudong!

**Comment by wuxudong** [comment]
？There is no syncX property in https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/PieChartScreen.js .
