### ISSUE TITLE
Windows environment installation, react-native run-android, debug compile, error

### ISSUE THREAD

**Issue by InitialSugar** [wuxudong/react-native-charts-wrapper#524]
* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.github.PhilJay:MPAndroidChart:v3.1.0.
  Searched in the following locations:
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/google/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/google/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/android/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - file:/C:/Users/John/AppData/Local/Android/Sdk/extras/android/m2repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
> Task :app:preDebugBuild FAILED
    - file:/C:/Users/John/.m2/repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - file:/C:/Users/John/.m2/repository/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
    - https://dl.google.com/dl/android/maven2/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - https://dl.google.com/dl/android/maven2/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
    - https://jcenter.bintray.com/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - https://jcenter.bintray.com/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
    - file:/D:/working/react-native/test/node_modules/react-native/android/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.pom
    - file:/D:/working/react-native/test/node_modules/react-native/android/com/github/PhilJay/MPAndroidChart/v3.1.0/MPAndroidChart-v3.1.0.jar
  Required by:
      project :app > project :react-native-charts-wrapper

**Comment by wuxudong** [comment]
jitpack.io is required. Check the install guide.
