### ISSUE TITLE
How to make it work for iOS with other modules that do not support use_frameworks! ?

### ISSUE THREAD

**Issue by ferrannp** [wuxudong/react-native-charts-wrapper#525]
Basically this issue https://github.com/unimodules/react-native-unimodules/issues/29.

Do you know any workaround @wuxudong ?

**Comment by wuxudong** [comment]
Check `manual setup` in the install guide.

**Comment by ferrannp** [comment]
So being trying manual setup but I am getting a native crash just when starting the app with process terminated. Gotta investigate more.

**Comment by ferrannp** [comment]
My bad, was using react-native 0.59.1 and suffered from https://github.com/wuxudong/react-native-charts-wrapper/issues/508. Updating fixed it.
