### ISSUE TITLE
How to make the bar from BarChart to be above the xAxis line?

### ISSUE THREAD

**Issue by ferrannp** [wuxudong/react-native-charts-wrapper#526]
Right now:

![image](https://user-images.githubusercontent.com/774577/56771358-a74c1200-67b6-11e9-985a-cbbd36318ae6.png)

I would like the green part not to be above the white line. I see it's the same in your examples. I'd like it like in the MPAndroidChart examples:

![68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f67726f7570656462617263686172742e706e67](https://user-images.githubusercontent.com/774577/56771405-cc408500-67b6-11e9-8f1a-b98a17eaf6ad.png)

where the axis line is "above" the bars.

I can't really find a prop to change this in the docs.

**Comment by wuxudong** [comment]
There is a drawGridLinesBehindData property in MpAndroidChart, and the default value is true.
