### ISSUE TITLE
How to change yAxis labels color

### ISSUE THREAD

**Issue by YisusMB** [wuxudong/react-native-charts-wrapper#527]
Actually i done the change in the xAxis only doing this 
![image](https://user-images.githubusercontent.com/43631579/56825804-e2366000-681f-11e9-8bdf-a84935191622.png) 

but i try to do the same in the yAxis but it dosnt work any idea how can i change the text color of yAxis?

### Data and config
const xAxis = {
      granularityEnabled: true,
      granularity: 1,
      position: 'BOTTOM',
      valueFormatter: xAxisFormat,
      textColor: processColor('#7FD05D'), // <= this works
    };
    const yAxis = {
      granularityEnabled: true,
      granularity: 10,
      textColor: processColor('#7FD05D'), //<= this dosnt works
    };

### Specifications

  - Version:"react-native-charts-wrapper": "^0.5.2",
  - Platform: android/react-native
  - Subsystem: windows10

**Comment by wuxudong** [comment]
There are left and right y axis. Check config in lib.

**Comment by YisusMB** [comment]
Nice! Thank you! as i see xAxis dosnt catch strings as values right? i guess something like this
values: [{x: '14-Apr', y: 150}]

**Comment by wuxudong** [comment]
Read examples.
