### ISSUE TITLE
柱形图不能指定从左开始按照一定宽度和间隔绘制吗？现在是会默认被居中的中间

### ISSUE THREAD

**Issue by godf4ther** [wuxudong/react-native-charts-wrapper#529]
[柱形图不能指定从左开始按照一定宽度和间隔绘制吗？现在是会默认被居中。我想要图中红框的效果，该怎么设置代码。[
![251556419638_ pic](https://user-images.githubusercontent.com/21051886/56857677-3584eb80-69a3-11e9-893e-39e0e369ceba.jpg)
](url)

**Comment by godf4ther** [comment]
this.state = {
      legend: {
        enabled: false,
      },
      data: {
        dataSets: [{
          values: [{y: 2}, {y: 3}],
          config: {
            highlightEnabled: false,
            drawValues: false,
          },
          label:'',
        }],
      },
      xAxis: {
        enabled:false
      },
      yAxis: {
        left: {
            axisMinimum:0,
            enabled: false,
        },
        right: {
            enabled: false
        },
      },
    };
  }

**Comment by wuxudong** [comment]
try visibleRange?

**Comment by godf4ther** [comment]
版本比较低，没有这个属性。没有其它办法了么？

**Comment by wuxudong** [comment]
axisMaximum?

**Comment by godf4ther** [comment]
thank you very much!
