### ISSUE TITLE
Order of charts when combined

### ISSUE THREAD

**Issue by philippeauriach** [wuxudong/react-native-charts-wrapper#534]
When displaying a Combined chart with bardata and two line datas, line datas are always above the bar datas. It would be nice to have some lind of "index" on each data allowing to ordre them (in my case I would like to have the bar data above the first line and below the second line).

**Comment by wuxudong** [comment]
It is supported in 0.5.4

**Comment by philippeauriach** [comment]
The new feature allow for choosing the order between types of charts, not between charts : 
- we can do BAR < LINE
- we cannot do BAR 1 < LINE 1 < BAR 2

Do you think it would be possible with the different libs behind ? I'm not sure MPAndroidChart and Charts allow this.

**Comment by wuxudong** [comment]
No such api in underlying native library.
