### ISSUE TITLE
In-App Devmenu doesn't work

### ISSUE THREAD

**Issue by kemo0** [wuxudong/react-native-charts-wrapper#535]
Hello

If you setup a new project with 

```
react-native init AwesomeProject
cd AwesomeProject
react-native run-ios
```

and the following instructions:

https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md

the In-App Devmenu (Cmd + D) can no longer be called. The app is also not reloaded during a file change. Is something missing from the tutorial?

`DevSupport` is also included in the podfile (it's from the instruction).

```
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-charts-wrapper": "^0.5.2" 
```

**Comment by wuxudong** [comment]
This is already covered by install tutorial. Check it out.
