### ISSUE TITLE
Value formatter not working!

### ISSUE THREAD

**Issue by aliazizi** [wuxudong/react-native-charts-wrapper#536]
### Expected Behavior
Show right chart for data formatted with config
### Actual Behavior
I'm using `date` formatter with time unit seconds and the chart is empty
### Screenshots
Here is my code
```
<View style={styles.container}>
          <BarChart
            data={{dataSets: [{
              label: "test",
              values: [
                {x: 1557625669, y: 1},
              ],
              config: {
                color: processColor("teal"),
                barShadowColor: processColor("lightgrey"),
                highlightAlpha: 90,
                highlightColor: processColor("red"),
              },
            }]}}
            xAxis={{
              drawLabels: true,
              position: "BOTTOM",
              valueFormatter: "date",
              valueFormatterPattern: "YYYY-MM-dd",
              since: 0,
              timeUnit: "SECONDS",
            }}
            style={styles.volume}
          />
        </View>
```
Note: 1557625669 is unixtimestamp for today
and here is the result
![image](https://user-images.githubusercontent.com/8492767/57576889-5c055500-7480-11e9-806b-ad348ed18f65.png)

when I change 1557625669 to 1 its working for 1970 **but** its repeat days.
![image](https://user-images.githubusercontent.com/8492767/57576895-7a6b5080-7480-11e9-9a76-079c719eef3f.png)

### Steps to Reproduce the Problem
1-Create a new project
2-Add below code to render in component
```
<View style={styles.container}>
          <BarChart
            data={{dataSets: [{
              label: "test",
              values: [
                {x: 1557625669, y: 1},
              ],
              config: {
                color: processColor("teal"),
                barShadowColor: processColor("lightgrey"),
                highlightAlpha: 90,
                highlightColor: processColor("red"),
              },
            }]}}
            xAxis={{
              drawLabels: true,
              position: "BOTTOM",
              valueFormatter: "date",
              valueFormatterPattern: "YYYY-MM-dd",
              since: 0,
              timeUnit: "SECONDS",
            }}
            style={styles.volume}
          />
        </View>
```
3-add these style
```
container: {
    flex: 1,
    backgroundColor: "#F5FCFF",
  },
  volume: {
    flex: 1,
  },
```

### Specifications

  - Version: 0.5.2
  - Platform: react native 0.59.5 and android

**Comment by aliazizi** [comment]
I found this 
https://stackoverflow.com/a/45138307/1827594
that saying long data not supported

So, Can anybody confirm it?

**Comment by wuxudong** [comment]
For iOS/Charts, double is used for x, but in android/MpAndroidChart, float is used for x.
So in android, there will be precision loss when you use MILLISECONDS/SECOND/MINUTES as x value. 
You can use timeUnit:DAYS if your since is 1970, or you can use a different `since` like seconds of 2019

**Comment by aliazizi** [comment]
@wuxudong Thanks I got it, I have a question I have screen with 10 chart in a ScrollView, how to set heght for chart? I add it in style but its do nothing
