### ISSUE TITLE
How do I set the scale value on the x-Axis to appear as a string?

### ISSUE THREAD

**Issue by InitialSugar** [wuxudong/react-native-charts-wrapper#537]
![TIM截图20190514095819](https://user-images.githubusercontent.com/33045757/57665860-4171de00-7630-11e9-9676-50337a6fc688.png)
![TIM截图20190514100134](https://user-images.githubusercontent.com/33045757/57665869-4898ec00-7630-11e9-92df-4f7766fad2e1.png)

I want to set the scale value on the X-axis, as shown in the figure above, for the string.

**Comment by wuxudong** [comment]
There are two approaches.

timestamp & date valueFormatter.
index & custom x labels.
