### ISSUE TITLE
Custom xAxis of Line Chart

### ISSUE THREAD

**Issue by thoth-nexlesoft** [wuxudong/react-native-charts-wrapper#54]
How I custom a array xAxis of Line Chart valueFormatter: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'A6'] (dynamic array). Can you help me? @wuxudong 
![screen shot 2017-05-16 at 7 00 25 pm](https://cloud.githubusercontent.com/assets/25680402/26104920/1b4d024e-3a6a-11e7-83a9-e24bebf37072.png)

**Comment by wuxudong** [comment]
check #15

**Comment by thoth-nexlesoft** [comment]
Thanks @wuxudong.

**Comment by L-Jovi** [comment]
:)
