### ISSUE TITLE
Custom x-axis labels on Line Chart at bottom on graph

### ISSUE THREAD

**Issue by sandeepsinghs** [wuxudong/react-native-charts-wrapper#540]
Hello,

I want to add custom x-axis labes on the line chart at the bottom on graph. 

I am displaying data on monthly based and I want to display month name at the bottom of the graph.

Please Help,
Thank you.

**Comment by wuxudong** [comment]
you can use indexed x value with custom labels.

like `valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep']` in Example->BarChartScreen.

**Comment by sandeepsinghs** [comment]
Thank you @wuxudong ,

Is it possible to show x-asix lables top and bottom both?

**Comment by wuxudong** [comment]
Check the js source code. BOTH_SIDED

**Comment by sandeepsinghs** [comment]
Thank you,

My current scenario is ,I am displaying two line graph on a LineChart which has different labels for each values. But it is displaying only first six labels from the array, rest labels are not displaying. 

So is it possible to display all the labels as first six to top and rest to bottom of graph.

I hope you understand the scenario.
