### ISSUE TITLE
Bubble chart: No chart data available

### ISSUE THREAD

**Issue by mdslab87** [wuxudong/react-native-charts-wrapper#542]
Hi, I have a problem with the bubble chart he always show me:
"No chart data available"

### My Data Screenshots
[dataSet](https://ibb.co/SnQ8vkZ)

### Data and config
Data creation

        let t = {
          values: [],
          label: 'test',
          config: {
            color: '#000'
          }
        }

        for(let i=0; i<deg.length; i++){
          t.values.push({
            x: i,
            y: deg[i].y,
            size: speed[i].y
          })
        }

        let chartData = {
          data: {
            $set: {
              dataSets: [t]
            }
          }
        }

        this.setState({ winds: chartData })

render method:

```
return (
  <View style={{ height: 250 }}>
    <BubbleChart
          style={{ flex: 1 }}
          data={this.state.winds}
          legend={this.state.legend}
          animation={this.state.animation}
          onSelect={this.handleSelect.bind(this)}
          onChange={(event) => console.log(event.nativeEvent)}
    />
  </View>
)
```

### Specifications

  - Version: React Native: 0.59.8, React native charts wrapper: 0.5.5
  - Platform: iOS

**Comment by wuxudong** [comment]
I think it is related to your own code.

**Comment by davidep87** [comment]
Yes the problem was in the chartData object

with a chartData object created in this way the library work well.

```
let chartData = {
   dataSets: [t]
}
```
