### ISSUE TITLE
CandleStick chart not showing properly when time is in milliseconds.

### ISSUE THREAD

**Issue by iAmShakil** [wuxudong/react-native-charts-wrapper#543]
If I set the value as the number of days since 01-01-1970, the candle sticks are showing properly. However, in this way the x axis labels can not be formatted properly to show correct dates.

When I set the x axis values as milliseconds, the candle sticks are coming as thin lines in wrong places.

The following is my xAxis configuration:
    { granularityEnabled: true,
    granularity: 1,
    valueFormatter: "date",
    valueFormatterPattern: 'MM-dd',
    position: "BOTTOM",
    since: 0,
    labelRotationAngle: -45,
    timeUnit: "MILLISECONDS" }

**Comment by wuxudong** [comment]
Duplicate to #160
