### ISSUE TITLE
 Fatal error: Double value cannot be converted to Int because it is either infinite or NaN

### ISSUE THREAD

**Issue by co-de** [wuxudong/react-native-charts-wrapper#545]
I suddenly started getting this error when trying to run my app on ios. It was working before but now it is not. I am attaching the screenshot of xcode displaying the error and the location. Any idea how to fix this?
Actually, that is not entirely true. After editing my podfile I accidentally deleted the packages. I re-installed using the same old podfile and project compiled. But this runtime error started happening.

Edit: Works on Android. 
Edit: I followed all the installation instructions from the ground up using the latest instructions. Still not working. I don't think this is related to installation since it installs and builds successfully but fails at runtime.

<img width="958" alt="Screen Shot 2019-05-29 at 20 11 22" src="https://user-images.githubusercontent.com/13452081/58577560-6761ca00-824f-11e9-9498-46a2fdf128b1.png">

**Comment by co-de** [comment]
I tried many things up to this point and can't seem to solve it. Any help is greatly appreciated, my work is stuck. Thanks.

**Comment by co-de** [comment]
Problem was that the interim NaN values that are passed to the BarChartDrawer can cause problems in iOS but won't cause any problem on Android. I found the problematic area and fixed it by adding additional validation checks for iOS. Closing.

**Comment by YisusMB** [comment]
Hello i have a question, if i want to show a chart without any data this error crashed my app (ios) any idea how to make the same thing that shows in android or anything else?
