### ISSUE TITLE
Initial X position instead of using moveViewToX ?

### ISSUE THREAD

**Issue by ferrannp** [wuxudong/react-native-charts-wrapper#548]
Using `moveViewToX` needs a ref so the component needs to be mounted first and then it will move (will flicker).

Is there any prop to set up the initial X? I have `BarChat` and I want to show it from the end (so user can swipe right to left if the want to go to earlier dates).

Instead of this:

![Screenshot 2019-06-10 at 18 59 23](https://user-images.githubusercontent.com/774577/59212143-e7722300-8bb1-11e9-853a-6ee856c43390.png)

To show this first:

![Screenshot 2019-06-10 at 18 59 30](https://user-images.githubusercontent.com/774577/59212149-e9d47d00-8bb1-11e9-8dcc-1b1cbc5209b5.png)

### Specifications

  - Version: 0.5.2

**Comment by wuxudong** [comment]
Check usage of zoom in Example->CandleStick

**Comment by ferrannp** [comment]
Oh wow, yeah `zoom={{ scaleX: 1, scaleY: 1, xValue: numberOfWeeks, yValue: 0 }}` solved the issue! I didn't know it was the `zoom` prop (I promise I read the docs all the time). Thank you for your support!

I plan to feature your library in Chain React 2019, keep the good work!
