### ISSUE TITLE
Add support for AndroidX

### ISSUE THREAD

**Issue by LucasBrazi06** [wuxudong/react-native-charts-wrapper#555]
### Expected Behavior
Build with AndroidX libs.

### Actual Behavior
Build is broken when using AndroidX

### Screenshots
![image](https://user-images.githubusercontent.com/25266945/59743000-43ead780-926f-11e9-9a4f-db4efd113d48.png)

### Data and config
gradle.properties
  android.useAndroidX=true
  android.enableJetifier=true

### Steps to Reproduce the Problem
Create a react-native project with the CLI
Set-up your lib
Change the gradle,properties
Compile

### Specifications
  - Version: 0.5.5
  - Platform: Win
  - Subsystem: Android

**Comment by wuxudong** [comment]
you can try PR https://github.com/wuxudong/react-native-charts-wrapper/pull/538

**Comment by wuxudong** [comment]
Be aware that react-native-gesture-handler doesn't support androidX currently.

**Comment by LucasBrazi06** [comment]
It seems that it's on going in react-native-gesture-handler  kmagiera/react-native-gesture-handler#645

**Comment by LucasBrazi06** [comment]
When running 'npx jetify' from 'jetifier' version 1.5.0, it converts all the native java files to be compatible with AndroidX.

**Comment by LucasBrazi06** [comment]
After all modules converted, it works.
