### ISSUE TITLE
How to show marker when drag over bar in barchart?

### ISSUE THREAD

**Issue by hoangdoan267** [wuxudong/react-native-charts-wrapper#557]
How to show marker when drag over bar in barchart? My expectation is after choosing a bar and highlight it, drag to the prev/next bar, the prev/next bar will be highlighted.
I try highlightPerDragEnabled={true} but it seems not working.

**Comment by wuxudong** [comment]
I think you have to handle it by yourself. 
The lib doesn't know which bar should be highlighted by itself.

You can use something like `refs.chart.highlight(xx)`
