### ISSUE TITLE
How to draw Ylabels inside the axis ?

### ISSUE THREAD

**Issue by franjorub** [wuxudong/react-native-charts-wrapper#562]
I whant to do something like this on Candle and Line Charts 
![imagen](https://user-images.githubusercontent.com/24401350/60030184-88f87a80-9670-11e9-95c1-dd8cc413569a.png)
The doc says Y: position would be a number, is in percentage ?

**Comment by hadrienbbt** [comment]
Hello,
Have you tried `position: 'INSIDE_CHART'` in the yAxis prop of the chart? It worked for me

**Comment by franjorub** [comment]
@hadrienbbt it worked! thank you
