### ISSUE TITLE
Remove grid and description label of chart.

### ISSUE THREAD

**Issue by thoth-nexlesoft** [wuxudong/react-native-charts-wrapper#57]
![screen shot 2017-05-17 at 5 13 28 pm](https://cloud.githubusercontent.com/assets/25680402/26149545/e1248158-3b24-11e7-8a26-466031e9276a.png)

Hi @wuxudong ,
How I can remove grid and description label of chart.
Thanks.

**Comment by wuxudong** [comment]
chartDescription: PropTypes.shape(descriptionIface),

const descriptionIface = {
  text: PropTypes.string,
  textColor: PropTypes.number,
  textSize: PropTypes.number,

  positionX: PropTypes.number,
  positionY: PropTypes.number,

  fontFamily: PropTypes.string,
  fontStyle: PropTypes.number
};

**Comment by wuxudong** [comment]
You can also check example. you can find most of config there, like remove grid.

**Comment by jsina** [comment]
@wuxudong could you please tell me how could I remove the description label because you didn't tell obviously on comment above about this problem?

**Comment by mehmet-h** [comment]
@jsina you could write chartDescription={{ text: '' }} as a prop to any component you want.

**Comment by jsina** [comment]
@mehmet-h Best

**Comment by douglasjunior** [comment]
I have this problem too, I think that is because some examples are wrong:

https://github.com/wuxudong/react-native-charts-wrapper/blob/3610b475bcf822f46dd4654efc1f6ccbe8655503/Example/app/LineChartScreen.js#L126

**Comment by lequangtuananh** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md#chartbase-props-plus-props-listed-below

**Comment by RahulNainwal** [comment]
You can remove grid by enabled: false in legend.
`legend: {
        enabled: false,
    },`

**Comment by baoho1703** [comment]
I've solved: chartDescription={{ text: '' }}
