### ISSUE TITLE
Charts Wrapper in Expo

### ISSUE THREAD

**Issue by gshoanganh** [wuxudong/react-native-charts-wrapper#571]
I use Expo for my project.
but when i run 'cd ios && pod install'
![image](https://user-images.githubusercontent.com/25890788/60406330-78e81a00-9bdf-11e9-80f3-0bff20b7d9dd.png)
Error:
```
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so: 
project 'path/to/Project.xcodeproj'
```

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.
