### ISSUE TITLE
Can't remove grid lines inside BarChart

### ISSUE THREAD

**Issue by co-de** [wuxudong/react-native-charts-wrapper#575]
Hi, I have been trying to remove the grid lines in my BarChart, only x and y axis should be displayed. I am also trying to make the displayed numbers to be integers not like 0.2, 0.4 as you can see in the attachment. I am using the properties below but they don't seem to work. Am I doing something wrong? Only the ones that say "//works" next to them actually work.

One more thing. Why does the grid lines go out of the chart area from the bottom of the chart?

```
              
              drawGridBackground={false}
              drawBorders={false}
              chartBackgroundColor={processColor('#ffffff')}//works
              gridBackgroundColor={processColor('#fff')}
              drawGridLines={false}
              granularityEnabled={true}
              granularity={1}
              pinchZoom={false}
              doubleTapToZoomEnabled={false}//works
              chartDescription={{ text: '' }}//works
```
![Screenshot_20190709-164925_Gallery](https://user-images.githubusercontent.com/13452081/60894492-75056900-a26b-11e9-897c-e0b3431e98a2.jpg)

**Comment by Connor-Y-Evenset** [comment]
Some of those are axis variables. You will need something like:
```
xAxis={{ drawGridLines: false, ... }}
yAxis={{ 
  left: { drawGridLines: false, ...},
  right: { drawGridLines: false, ...},
}}
```
 You can take a look at the examples in the `Example` folder or check the documentation at https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md

**Comment by jonmnoj** [comment]
Yes you need to set the granularity specifically in the left and right yAxis group like so:

`yAxis: {`
	`left: {
		granularityEnabled: true,
		granularity: 1
	},`
`right: {
		granularityEnabled: true,
		granularity: 1
	}`
`}`

**Comment by co-de** [comment]
@jonmnoj @Connor-Y-Evenset guys, thank for the help. How about the granularity of the value displayed above the bars. "1.00" looks bad. How can I make it "1"?

**Comment by co-de** [comment]
@jonmnoj @Connor-Y-Evenset guys, thanks for the help. How about the granularity of the value displayed above the bars. "1.00" looks bad. How can I make it "1"? @wuxudong
