### ISSUE TITLE
Custom CandleStickChart to BoxChart ?

### ISSUE THREAD

**Issue by gshoanganh** [wuxudong/react-native-charts-wrapper#577]
Is there any way to customize a **CandleStickChart** to **BoxChart**? 
![image](https://user-images.githubusercontent.com/25890788/61284609-827d9e80-a7e9-11e9-9bb3-b46371be8c01.png)

**Comment by wuxudong** [comment]
I can't find BoxChart in mpAndroidChart/Charts
