### ISSUE TITLE
The library dont build on iOS

### ISSUE THREAD

**Issue by franjorub** [wuxudong/react-native-charts-wrapper#579]
A week ago I followed the instructions of the installation guide for ios, and it worked correctly, but today it gives a compilation error, what happens?

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening tiltClient.xcworkspace`

![imagen](https://user-images.githubusercontent.com/24401350/61415227-1d47ad00-a8be-11e9-9e5d-f6b4156181fb.png)

Node 10
xcode version 10.2.1
mac os 10.14.15
"react-native-charts-wrapper": "^0.5.5",

**Comment by wuxudong** [comment]
No detailed error displayed.
