### ISSUE TITLE
Stacked Bar chart marker info

### ISSUE THREAD

**Issue by dimovdaniel** [wuxudong/react-native-charts-wrapper#58]
How to display marker values on each bar element inside the Stacked BarChart, and not the sum of them. (ex. 100 )

**Comment by wuxudong** [comment]
That is a problem. 

I made a small fix. Check the latest version, and Examples -> StackedBarChartScreen.js

**Comment by Gajendra-NL** [comment]
with combined chart, behaviour is different based on platform.
1. If marker is passed in values
on Android, individual bar items can be highlighted and shows the respective marker sent in marker array but on iOS it highlights the entire bar and doesn't show any marker.

2. if marker is not passed in values.
  on iOS it shows sum and highlights the whole bar.
  on android also it shows sum but highlights the individual bar.
