### ISSUE TITLE
It is not working on RN 0.60.X

### ISSUE THREAD

**Issue by ariniastari** [wuxudong/react-native-charts-wrapper#581]
The latest pod generated with RN 0.60 is quite different 

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ms06a' do
  # Pods for ms06a
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pre_install do |installer|
      installer.analysis_result.specifications.each do |s|
          s.swift_version = '5.0' unless s.swift_version
      end
  end

  use_native_modules!
  use_frameworks!
end

target 'ms06a-tvOS' do
  # Pods for ms06a-tvOS

  target 'ms06a-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

The only it could pass the `pod install` is with `use_frameworks!` which resulting on 

```
/Users/user/Projects/ms06a/ios/Pods/Folly/folly/Conv.h:38:10: 'double-conversion/double-conversion.h' file not found
```

removing `use_frameworks!` will leads to another error, so i changed to manual link, and when i change into swift 5 and installing required pods

```
  pod 'SwiftyJSON', '5.0'      
  pod 'Charts', '3.3.0'  
```

resulting on

<img width="272" alt="Screen Shot 2019-07-18 at 20 20 46" src="https://user-images.githubusercontent.com/2470327/61460935-f363b880-a999-11e9-94ea-8cd2d6ca1c1a.png">

can you guys take a look on this problem, i hope it will should worked on 0.60.X version

### Specifications

  - Version: ^0.5.5
  - Platform: iOS
  - Subsystem:

**Comment by wuxudong** [comment]
@ariniastari It looks like you forget to link ReactXX in the manual installation, so these react symbols are not declared.


So many troubles after RN 0.60.X.
refer to https://github.com/facebook/react-native/issues/25349

and there is pull request https://github.com/facebook/react-native/pull/25496 to fix the problem.
The PR is merged, but not released yet.

So I think the simplest way is using rn 0.59.x at this moment, then move to next rn 0.60.x release

**Comment by mboettcher** [comment]
I had the same error message, the solution was that firebase wasn't listed in the podfile anymore. Not sure how that was connected but I removed third-party packages from podfile before the upgrade to rn 0.60 because of the promised auto-linking. but had to re-link all third-party packages later again.

**Comment by tlow92** [comment]
Someone has a solution for 0.61.1? I'm facing the same problem

**Comment by codevoler** [comment]
add RCFont to Bridging Header file. Also add to pod file:
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end`
