### ISSUE TITLE
Combined charts: yellow line crossing chart

### ISSUE THREAD

**Issue by nicollasmatheus** [wuxudong/react-native-charts-wrapper#585]
### Expected Behavior

Nothing must happens if user clicks outside bars 

### Actual Behavior

If user clicks outside bars  a cross yellow line appears 

### Screenshots

<img width="344" alt="Screen Shot 2019-07-29 at 14 41 05" src="https://user-images.githubusercontent.com/39751943/62070214-7396e300-b210-11e9-989e-fd951670d14c.png">

### Data and config

Please check code below:

`
import * as React from 'react';
import {useState, useEffect} from 'react';
import { StyleSheet, processColor } from 'react-native';
import reverse from 'lodash/reverse';
import { CombinedChart } from 'react-native-charts-wrapper';
import colors from '../../../global/colors'
import { translate } from '../../../locales';

import {
  Content,
  BaseTitle,
  Title,
  ContentChart
} from './styles';

const ChartsHistory = (props: any) => {
  const [chartData, setChartData] = useState([]);
  const [chartDataColor, setchartDataColor] = useState([]);
  const [mockChart, setMockChart] = useState(false);

  let consumptions: Array<number> = []

  useEffect(() => {
    if(initializate){
      getChartData(colors)
    }
  })

  const { 
    history,
    initializate,
    getHistoryDetails,
    medium
  } = props

  const data = {
    data: {
      barData: {
        dataSets: [{
          values: chartData,
          label: "",
          config: {
            colors: chartDataColor,
            barSpacePercent: 30,
            valueTextSize: 1,
          },
        }],
        config: {
          barWidth: 0.8,
        }
      },
      lineData: {
        dataSets: [{
          values: [{y: medium, x:0}, {y: medium, x:12}],
          label: "",
          config: {
            drawValues: false,
            colors: [processColor(colors.charts.mediumConsumption)],
            mode: "CUBIC_BEZIER",
            drawCircles: false,
            lineWidth: 1.3,
            dashedLine: {
              lineLength: 7, 
              spaceLength: 7, 
            },
          }
        }],
      },
    },
  }

  const getChartData = ({ charts } : any) => {
    let data: Array<any>  = []
    let mockData: Array<any> = []
    let dataColor: Array<any> = []

      history.map((uc:any, index:any) => {
        let consumo = uc.consumoKWH
        let needMock = index === history.length - 1 && history.length < 13
        
        if(uc.consumoKWH === 0){
          consumo = 5
        }
        
        data = [...data, {
          ...uc,
          y: consumo,
          last: index === history.length - 1
        }]
        consumptions = [...consumptions, consumo]
        dataColor = [
          ...dataColor, uc.faturadoPorMedia ?
          processColor(charts.medium) : uc.faturadoPorMinimo ?
          processColor(charts.minor) : processColor(charts.consumption)
        ]
        
        setMockChart(needMock)
        let roof =  Math.max.apply(null, consumptions)*0.03

        if(needMock){
          setMockChart(true)
          let i = index + 1
          for(i; i < 13; i++){
            mockData = [...mockData, {
              x: i,
              y: roof > 0 ? roof : 15
            }]
            dataColor = [
              ...dataColor, processColor(colors.buttons.disabled)
            ]
          }
        } 
      })
      data = reverse(data)
      data = data.concat(mockData)
      setChartData(data)
      setchartDataColor(dataColor)
  }
  
  return (
    <Content>
      <BaseTitle>
        <Title>{translate(['history', 'subtitle'])}</Title>
      </BaseTitle>
      <ContentChart>
        <CombinedChart style={[styles.chart, { marginBottom: mockChart ? '-5%' : 0}]}
          legend={{
            enabled: false,
          }}
          data={data.data}
          autoScaleMinMaxEnabled={false}
          pinchZoom={false}
          doubleTapToZoomEnabled={false}
          marker={{
            enabled: false
          }}
          xAxis={{
            enabled: false,
          }}
          viewPortOffsets={
            {
              left: 1,
              top: 1,
              right: 1,
              bottom: mockChart ? 5 : 1,
              }
          }
          yAxis={{
            left: {
              enabled: false
            },
            right: {
              enabled: false
            }
          }}
          scaleEnabled={false}
          scaleXEnabled={false}
          scaleYEnabled={false}
          onSelect={getHistoryDetails}
          drawOrder={['BAR','LINE']}
          touchEnabled
          chartDescription={{text: ''}}
        />
      </ContentChart>
    </Content>
  );
}

var styles = StyleSheet.create({
  chart: {
    width: '100%',
    height: 200,
  }
})

export default ChartsHistory;

`

### Specifications

  - Version:

    "react": "16.8.3",
    "react-native": "0.59.5",

  - Platform: React Native

**Comment by rxliuli** [comment]
Is there any solution to the problem that the two bars on either side of the mixed chart are half the width of the normal bars?

![image](https://user-images.githubusercontent.com/24560368/200304260-7a9ebf46-2140-4eff-8ce8-c8d9c9f707c5.png)
