### ISSUE TITLE
Marker Customization

### ISSUE THREAD

**Issue by DiogoAlvess1** [wuxudong/react-native-charts-wrapper#588]
Hello, I need to know how I do marker customization.
For example:
![InkedScreenshot_20190808-154043_LI](https://user-images.githubusercontent.com/50245056/62729561-92595e80-b9f4-11e9-8197-1ff6e4d041a8.jpg)

After the value, I need to add the time this value was taken, the time is in xAxis.
Does anyone know how to format the marker?
I already have both values, the time and the value in question, as in the image is 5.0
I would like it to be for example:
Value: 5.0m 14:20:25

**Comment by rrapiteanu** [comment]
You can add a marker property for each element in the data set.

**Comment by nhatpv-1627** [comment]
@rrapiteanu can you give me an example in code?

**Comment by nhatpv-1627** [comment]
@DiogoAlvess1 How did you add time in maker? Can you show these code for this problem?
