### ISSUE TITLE
Cann't style 'centerText' in PieChart

### ISSUE THREAD

**Issue by k2easy** [wuxudong/react-native-charts-wrapper#59]
could you give me an example like this?
<img width="263" alt="2543b2d4-ebb0-45a8-b7fe-9d16f23b7631" src="https://cloud.githubusercontent.com/assets/20715282/26280568/fce30c36-3e0b-11e7-99c4-0bfece6992c8.png">

**Comment by wuxudong** [comment]
SpannableString is not supported.

**Comment by k2easy** [comment]
perhapse I should use `<View style={{position:absolute,zIndex><Text>`
thanks
