### ISSUE TITLE
Build failure on iOS: Use of unresolved identifier 'BridgeUtils' 'HighlightUtils' 'FontUtils'

### ISSUE THREAD

**Issue by jerome-benoit** [wuxudong/react-native-charts-wrapper#590]
### Expected Behavior

Build success after installation on a demo app. 

### Actual Behavior

Build failure.

### Steps to Reproduce the Problem

* Create a demo RN 0.60.5 app from scratch;
* Follow the step by step *manual* installation guide for iOS (because of the use_framework! bug in RN 0.60.X) with Charts and SwiftyJSON dependencies installed via cocoapods. 
* Build the demo app in Xcode 10.3.    

### Specifications

  - Version: 0.5.5
  - Platform: Mac OS X 10.14.6
  - Subsystem:

**Comment by jerome-benoit** [comment]
Got it working: when you add the swift files from the current package, you have to expand all directories first and select them all. If you don't expand, you only have the directories properly imported, not its content.

**Comment by tlow92** [comment]
Did you add 
`pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
`
to your podfile?
Or did you only add SwiftyJSON and Charts?

**Comment by jerome-benoit** [comment]
> Le 27 sept. 2019 à 09:38, Thilo <notifications@github.com> a écrit :
> 
> Did you add
> pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
> to your podfile?
> Or did you only add SwiftyJSON and Charts?
> 
> 

Only SwiftyJSON and Charts with RN 0.6X.X.

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by wuxudong** [comment]
Now a new version is published, and the tutorial is updated, give it a try.
