### ISSUE TITLE
Add daily value formatter for a month

### ISSUE THREAD

**Issue by salmatarzi** [wuxudong/react-native-charts-wrapper#591]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
I want to have every xAxis grid be a day in a month, starting from 1 and ending at the end of the month

### Actual Behavior
It starts the first value from 0, even though I am stating that the axisMinimum is 1, I want the first value to be formatted as day 1

### Screenshots
![IMG_0014](https://user-images.githubusercontent.com/10965023/63268830-5e542800-c295-11e9-9d5b-4d49b3837263.PNG)

### Data and config

```
xAxis: {
    granularityEnabled: true,
    drawGridLines: true,
    valueFormatter: [
        "1",
        "2",
        "3",
        "4",
        ...,
        "30"
    ],
    granularity: 1,
    axisMinimum: 1,
    axisMaximum: 30,
    textSize: 10,
    textColor: processColor(ME_DARK_GREY_BLUE),
    fontWeight: "100",
    position: "BOTTOM",
    centerAxisLabels: true
}
```

### Specifications

  - Version: 0.5
  - Platform: iOS

**Comment by wuxudong** [comment]
Use complete data format, like {x:1, y:1.5}, you can find it in root README
