### ISSUE TITLE
yAxis Labels not accepting currency values

### ISSUE THREAD

**Issue by p21LucasM** [wuxudong/react-native-charts-wrapper#592]
### Expected Behavior
yAxis Labels accepting currency values in format 
Expect: `R$ 00.000.000`

### Actual Behavior
They are not

### Data and config
`yAxis: {
    left: { valueFormatter: 'R$ #,###' },
    right: { valueFormatter: 'R$ #,###' },
  },`
Result: `R$ 00,000,000`

`yAxis: {
    left: { valueFormatter: 'R$ #.###' },
    right: { valueFormatter: 'R$ #.###' },
  },`
Result: `R$ 00000000`
Don't recognized `.`

### Specifications

  - Version: 0.5.1
  - Platform: both

**Comment by wuxudong** [comment]
Check the grammar of Decimal Format.
Try "'R$ '#,##"?

**Comment by p21LucasM** [comment]
> Check the grammar of Decimal Format.
> Try "'R$ '#,##"?

I've already tried it. I updated the question.

**Comment by p21LucasM** [comment]
I got it now
`yAxis: { left: { valueFormatter: 'R$ #,###' }, right: { valueFormatter: 'R$ #,###' }, },`
i realized that the lib works with the device locale to set it as a `,` or `.`! 
thanks for your support <3
