### ISSUE TITLE
How can I only scale the X-axis data?

### ISSUE THREAD

**Issue by HelloJack0** [wuxudong/react-native-charts-wrapper#594]
- Version:0.5.5
  - Platform:Android&ios
How to control the Y axis to remain the same when zooming in and out？Or control the Y-axis to enlarge the maximum? Thanks

**Comment by HelloJack0** [comment]
@wuxudong can you help me？Thanks

**Comment by FonDorn** [comment]
@HelloJack0 try to use `scaleYEnabled={false}`

**Comment by HelloJack0** [comment]
@FonDorn Thanks for your prompt, it's not work

**Comment by ddavydov** [comment]
I was trying to achieve the same, this worked for me
```
scaleEnabled={false}
scaleXEnabled
scaleYEnabled={false}
```
It works fine on iOS, so only X-axis is scaling, but on android scaling doesn't work at all, which is a problem

**Comment by aditya1711** [comment]
Where you able to find any solution for this? @HelloJack0

**Comment by aditya1711** [comment]
```
scaleYEnabled={false}
scaleXEnabled={true}
```
This works. make sure that you do **not** have `scaleEnabled={true}`. 

Thanks @HelloJack0
