### ISSUE TITLE
Negative Y values on LineChart with areas

### ISSUE THREAD

**Issue by hadrienbbt** [wuxudong/react-native-charts-wrapper#596]
Hello everyone,

What i'm trying to achieve is to display a LineChart with some areas under the graph, regardless if there are negative Y values or not. Can someone help me out with that?

Best regards,
hadrienbbt

### Expected Behavior
The areas are always  under the graph like in second picture, even with negative values

### Actual Behavior
When there are negative values in the dataset it will display the areas only around the zero line

### Screenshots
First picture is what I currently have, second is the same dataset with an offset from the minimum value to remove the negative Y. It represent what I would like to achieve but then the values are wrong.
![IMG_2601](https://user-images.githubusercontent.com/16146115/64183594-6651c180-ce6a-11e9-85b4-da1adce0bb90.jpg)
![IMG_2600](https://user-images.githubusercontent.com/16146115/64183605-6c47a280-ce6a-11e9-9f1f-aa98e51e5b61.jpg)

### Steps to Reproduce the Problem
Provide LineChart component with a dataset of positive and negative y values

### Specifications
  - Version: 0.5.5
  - Platform: iOS 13.1

**Comment by wuxudong** [comment]
There is a `zeroLine` config.
Check the ZeroLineChartScreen.js in Example.

**Comment by hadrienbbt** [comment]
Hello,
I have read the doc, run and played with your example about `zeroLine` but I am not sure this prop will help me accomplishing my task. Whether I set `enabled: true` or `enabled: false` the areas won't behave as I would like to. Only the zero line will appear/disappear. 
Indeed I need to make the areas start from the very bottom of the graph view, not only above nor under the zero line.
I hope I'm being clear enough.
Have a nice day.

**Comment by AdamTorkelsson** [comment]
I have verified the issue above and it seems that the zeroline solution does not work. @wuxudong could you explain how you solved it?

**Comment by wuxudong** [comment]
Close this inactive issue, Reopen it if necessary.
