### ISSUE TITLE
Getting error on build

### ISSUE THREAD

**Issue by Lokesh235** [wuxudong/react-native-charts-wrapper#597]
Environment -
Xcode: 10.3
Swift compiler version: 5
MacOS: 10.14.6
RN version: 0.57.5
react-native-charts-wrapper: 0.5.5
build type: Debug

after completing **manual** step up procedure, getting this error on build:
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 254

Any input would be appreciated. 

<img width="1060" alt="Screen Shot 2019-09-06 at 11 35 08 PM" src="https://user-images.githubusercontent.com/11419486/64450120-12133f80-d0ff-11e9-87eb-5c84aad5d343.png">

**Comment by Lokesh235** [comment]
1 observation - if I remove the swift files and SWiftyJSON & Charts frameworks and trigger the build, it gets successful.

**Comment by wuxudong** [comment]
Give the new version a try.
