### ISSUE TITLE
example npm install error

### ISSUE THREAD

**Issue by lakeoffaith** [wuxudong/react-native-charts-wrapper#6]
cd Example
 npm install 

`npm ERR! addLocal Could not install /home/ijoy/show
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:`

**Comment by wuxudong** [comment]
I haven't test it on linux, and it works on mac.
And the package.json is missing?

**Comment by lakeoffaith** [comment]
i have solved my problem.
i remove the Example folder out to the other directory.so the Package.json can't find react-native-charts-wrapper.
http://package-json-validator.com/  can test your package.json is right or wrong
