### ISSUE TITLE
Hwo to integrate this library in objective-c project

### ISSUE THREAD

**Issue by hanweixing** [wuxudong/react-native-charts-wrapper#60]
In my objective-c project, i did these steps according to this integrate guide, but coming with some errors like "use of undeclared rootView" etc. So how i integrate this library? Thanks in advance.

**Comment by wuxudong** [comment]
This is my first iOS project. Sorry there is not much I can help.

But in my opinion, react-native is friendly to object-c, the swift code is exported by `@obj-c`

**Comment by hanweixing** [comment]
I found a article to integrate this library, and these steps works well to me, anyone can watch this article. Link is [](http://blog.csdn.net/sinat_17775997/article/details/67635156)

**Comment by hanweixing** [comment]
I found a article to integrate this library, and these steps works well to me, anyone can watch this article. Link is [I found a article to integrate this library, and these steps works well to me, anyone can watch this article. Link is](url)

**Comment by hanweixing** [comment]
I found a article to integrate this library, and these steps works well to me, anyone can watch this article. Link is [here](http://blog.csdn.net/sinat_17775997/article/details/67635156)

**Comment by wuxudong** [comment]
Interesting. Btw, pod is preferable than installing dependencies manually
