### ISSUE TITLE
BarChart on press column chart  show value as it is not rounded

### ISSUE THREAD

**Issue by uendar** [wuxudong/react-native-charts-wrapper#602]
I am using BarChar and i have the option that we can press on a column chart and show the value above. The problem is that the value is rounded so for ex if the value is 2.3 when i press it shows 2. What i want is to show exactly how it is 2.3. 

Any idea what we use here ?

**Comment by wuxudong** [comment]
I don't quite understand. Why the value showed is rounded?
Can you attach any screenshots and the config?

**Comment by uendar** [comment]
So if the barchar has values as 23.4 , 99.8 when i press on column it shows 23, 100...

**Comment by wuxudong** [comment]
Check dataFormatter in your config, or you can attach your config here.

**Comment by davidfushao** [comment]
dataSets: [{
                                        ...
                                        config: {
                                          valueFormatter: '0.00'
                                        }
                                      }]

**Comment by nhanhoangDF** [comment]
how can i change borderRadius and add valueFormatter like this picture??

<img width="564" alt="Screen Shot 2023-02-10 at 15 20 54" src="https://user-images.githubusercontent.com/109951984/218040211-d3812631-f0e0-4ed0-82b4-0d826efc3734.png">

**Comment by wuxudong** [comment]
marker borderRadius is not supported yet.
