### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by fabioplaka** [wuxudong/react-native-charts-wrapper#605]
Hello guys
I have an error with this library in react-native in iOS. The error said: **Invariant Violation: requireNativeComponent: "RNBarChart" was not found in the UIManager.**
As is shown in the picture below.
Please help me if anyone have a solution for this error.
Thanks in advance!
![Simulator Screen Shot - iPhone 8 Plus - 2019-09-29 at 21 30 59](https://user-images.githubusercontent.com/32648013/65838233-50b4a800-e301-11e9-8438-0fe6db17ea04.png)

**Comment by wuxudong** [comment]
I think you didn't integrate the lib correctly. 
A new version is published, give it a try.

**Comment by fabioplaka** [comment]
I solve it, I used pods.

**Comment by wang-ories** [comment]
@fabioplaka  can you share your solution plz?

**Comment by neemssoni** [comment]
Please share your solution here

**Comment by wang-ories** [comment]
> Please share your solution here
Hi @neemssoni, I solved the problem just with this link:  https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md
Look at **manual setup**, this is the step that I used and it worked for me. Hope you will find solution.
