### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by ywlifesense** [wuxudong/react-native-charts-wrapper#606]
\react-native-charts-wrapper-master\Example> yarn install
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > @react-native-community/cli@3.0.0-alpha.2" has incorrect peer dependency "react-native@^0.60.0".
warning " > react-navigation-stack@1.9.3" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
[4/4] Building fresh packages...
$ sed -i '' 's/#import <RCTAnimation\/RCTValueAnimatedNode.h>/#import "RCTValueAnimatedNode.h"/' ./node_modules/react-native/Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.h && rm -rf node_modules/react-native-charts-wrapper/Example
系统找不到指定的路径。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by wuxudong** [comment]
Check the latest installation tutorial.

**Comment by jackliuqiang** [comment]
Did you solve it? I had the same problem

**Comment by jackliuqiang** [comment]
> Check the latest installation tutorial.
> There's no 'sed'.

I haven't seen the latest textbook
