### ISSUE TITLE
[Guidance] Can I rotate RadarChart programmatically?

### ISSUE THREAD

**Issue by omatrot** [wuxudong/react-native-charts-wrapper#607]
First of all, thank you for the awesome project.
I've seen in the example that I can rotate the RadarChart by gesture.
Can I do I programmatically on purpose?
I have 7 edges and want 2 edges on top (horizontal) and one on bottom.

**Comment by omatrot** [comment]
Used rotationAngle in props to achieve what I wanted

**Comment by githubofwyh** [comment]
Excuse me, do you know how to disable rotation？
