### ISSUE TITLE
I want to have such bar for working hours. How to get this? 

### ISSUE THREAD

**Issue by Rsl717** [wuxudong/react-native-charts-wrapper#61]
I have the same issue. I want to have such bar for working hours. How to get this? And whether it is possible to put a filter there ? for filtering out monthly/weekly

![](https://cloud.githubusercontent.com/assets/21261181/26141907/89d56f34-3af7-11e7-94a8-261875606e80.PNG)

**Comment by wuxudong** [comment]
What's this, I don't get it.

you can update data to apply filter

**Comment by Rsl717** [comment]
@wuxudong I need the type of such a bar, I tried it myself, but as I could not before I did not use bars, if you have some options to share with me, if it's not difficult for you, I would be glad. The time of arrival or departure or lunch to come from the device through a fingerprint or face recognition, through these data I need to draw such a bar here is an example 

![](https://cloud.githubusercontent.com/assets/21261181/26303130/f84e1a4a-3eff-11e7-9ab9-0ad456ed3b2c.jpg)

**Comment by wuxudong** [comment]
maybe you can use stacked horizontal bar chart.

**Comment by Rsl717** [comment]
OK!
