### ISSUE TITLE
Android Studio sync failed

### ISSUE THREAD

**Issue by zmnv** [wuxudong/react-native-charts-wrapper#616]
There is no `Example` folder in `node_modules`. I see it in github.
I can't sync my project.

### Expected Behavior
Success project syncing.

### Actual Behavior

```
The specified project directory 'path-to-project/node_modules/react-native-charts-wrapper/Example/android' does not exist.
```

### Screenshots
My `node_modules` in project:

<img src="https://user-images.githubusercontent.com/25253501/67772191-b021e700-fa6a-11e9-8825-3310fb1ef8d0.png" width="300" />

CDN folder of your package:

<img src="https://user-images.githubusercontent.com/25253501/67772784-ba90b080-fa6b-11e9-8ac1-c2268ca30dff.png" width="300" />

### Data and config
No matter

### Steps to Reproduce the Problem

```
rm -rf node_modules
```

```
yarn add react-native-charts-wrapper@latest
```

### Specifications

Android Studio 3.5.0
react-native-charts-wrapper 0.5.7

---

Why do Android Studio needs `Example` folder?...

**Comment by 1234yws** [comment]
I encountered the same problem
