### ISSUE TITLE
Can we make Multiline chart with individual series data?

### ISSUE THREAD

**Issue by rikinshah23** [wuxudong/react-native-charts-wrapper#617]
I have 3 arrays, and have different set of values. If I put all 3 in same dataset as below it kinda shows multiline chart but they dont seems to scale Y series for individual chart.
so if value difference between any 2 arrays is big then small values won't be clearly visible on chart like showing as blue and red lines.

              data={{
                dataSets: [
                  {
                    label: 'demo',
                    values: [{y: 1}, {y: 2}, {y: 1}],
                    config: {
                      color: processColor('teal'),

                      highlightAlpha: 90,
                      highlightColor: processColor('red'),
                      axisDependency: 'left',
                    },
                  },
                  {
                    label: 'demo',
                    values: [{y: 70}, {y: 66}, {y: 90}],
                    config: {
                      color: processColor('blue'),

                      highlightAlpha: 90,
                      highlightColor: processColor('yellow'),
                      axisDependency: 'left',
                    },
                  },
                ],
              }}

![image](https://user-images.githubusercontent.com/26806597/67893069-84ab0500-fb1b-11e9-970c-58a36cc7c13a.png)

EXPECTED -
I need to scale Y axis based on their individual series values as shows below.
![image](https://user-images.githubusercontent.com/26806597/67892461-61338a80-fb1a-11e9-87b3-980bf944fd4b.png)

Is it possible with this package ?

**Comment by wuxudong** [comment]
axisDependency can be left/right, so you can have at most two different scale.
