### ISSUE TITLE
onSelect with RadarChart: no x value

### ISSUE THREAD

**Issue by omatrot** [wuxudong/react-native-charts-wrapper#619]
I may have dreamt it but it seemed to me that the event passed to onSelect in RadarChart does not contain the x value axis selected only the y one.

Without an actual x value I can't make a difference between 2 values if there are the same

I'd like to branch to a new graph that gives details, but I can't because I do not know what the user has selected.

**Comment by wuxudong** [comment]
Or you can just add some other attributes as identifiers in your data.

values: [{value: 100, id: 'something'}, {value: 110}, {value: 105}, {value: 115}, {value: 110}]
