### ISSUE TITLE
Is the Swift file placed in that directory, the top level of the project?

### ISSUE THREAD

**Issue by wenjianli92** [wuxudong/react-native-charts-wrapper#620]
![image](https://user-images.githubusercontent.com/29296692/68261655-c687fe00-007b-11ea-9f92-dda7e7f73ab1.png)

What directory should the swift file be placed in after successful creation?

**Comment by wuxudong** [comment]
Anywhere is fine.

**Comment by wenjianli92** [comment]
@wuxudong   Please help me see this problem for me. thanks
[626](https://github.com/wuxudong/react-native-charts-wrapper/issues/626)
