### ISSUE TITLE
Use of unresolved identifier 'RCTFont'

### ISSUE THREAD

**Issue by lizilong007** [wuxudong/react-native-charts-wrapper#621]
### Expected Behavior
![QQ20191106-102954](https://user-images.githubusercontent.com/15603767/68263214-6ba4d580-0080-11ea-96c1-e5730b082f30.png)

### Screenshots
![image](https://user-images.githubusercontent.com/15603767/68263297-9c850a80-0080-11ea-8699-92840a522f83.png)
![image](https://user-images.githubusercontent.com/15603767/68263330-b6265200-0080-11ea-8fb4-bb12d0c96d57.png)

### Specifications

xcode: 10.1
react-native-charts-wrapper: 0.4.8

**Comment by wuxudong** [comment]
check the latest version.

**Comment by lizilong007** [comment]
xcode 10.1 unsupport swift5 ....

**Comment by lizilong007** [comment]
@wuxudong can xcode10.1 run the latest version?

**Comment by wuxudong** [comment]
It is weird that it warns `Use of unresolved identifier 'RCTFont'` even you have already added `#import 'React/RCTFont.h'`. 
Do you add this bridging file in Xcode setting?

**Comment by lizilong007** [comment]
![image](https://user-images.githubusercontent.com/15603767/68293073-2c01dc00-00c8-11ea-8817-66864cf4a0ff.png)

**Comment by lizilong007** [comment]
Is this enough?

**Comment by wuxudong** [comment]
If it still doesn't work. you can add `#import "React/RCTFont.h"` in ios/ReactNativeCharts/RNCharts-Bridging-Header.h

It is fix in latest version, you can add this patch to fix it.

**Comment by lizilong007** [comment]
@wuxudong Thank you very much for your help! 

好人一生平安 ^_^
