### ISSUE TITLE
Build Failed: duplicate symbol '_OBJC_CLASS_$_RNBarChartManager' in ....  Messages : 18 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by tuananh924** [wuxudong/react-native-charts-wrapper#623]
duplicate symbol '_OBJC_CLASS_$_RNBarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNBarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNBarChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNBarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNBarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNBarChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNBubbleChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNBubbleChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNBubbleChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNBubbleChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNBubbleChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNBubbleChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNCandleStickChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNCandleStickChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNCandleStickChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNCandleStickChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNCandleStickChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNCandleStickChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNCombinedChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNCombinedChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNCombinedChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNCombinedChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNCombinedChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNCombinedChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNHorizontalBarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNHorizontalBarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNHorizontalBarChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNHorizontalBarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNHorizontalBarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNHorizontalBarChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNLineChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNLineChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNLineChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNLineChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNLineChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNLineChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNPieChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNPieChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNPieChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNPieChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNPieChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNPieChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNRadarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNRadarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNRadarChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNRadarChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNRadarChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNRadarChartManager.o)
duplicate symbol '_OBJC_CLASS_$_RNScatterChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNScatterChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNScatterChartManager.o)
duplicate symbol '_OBJC_METACLASS_$_RNScatterChartManager' in:
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Intermediates.noindex/rn.build/Release-iphonesimulator/rn.build/Objects-normal/x86_64/RNScatterChartManager.o
    /Users/mac/Library/Developer/Xcode/DerivedData/rn-dpoclczrgzfdxoegudaondusbfvd/Build/Products/Release-iphonesimulator/RNCharts/libRNCharts.a(RNScatterChartManager.o)
ld: 18 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hanifmhd** [comment]
same to me, after implement chart wrapper and firebase
18 duplicate symbols for architecture arm64
<img width="1440" alt="Screen Shot 2019-11-10 at 18 50 41" src="https://user-images.githubusercontent.com/15220788/68543552-0a1b9880-03eb-11ea-9445-9b679e9f09e9.png">

**Comment by tuananh924** [comment]
Problem fixed after following this method: https://github.com/wuxudong/react-native-charts-wrapper/issues/604#issuecomment-548541820
