### ISSUE TITLE
LineChart with marker

### ISSUE THREAD

**Issue by asagcs** [wuxudong/react-native-charts-wrapper#625]
Once I add the following marker, it will report an error
```
<LineChart 
                style={styles.chart}
                data={itValue.data}
                chartDescription={{text: ''}}
                yAxis={itValue.yAxis}
                xAxis={itValue.xAxis}
                borderWidth={1}
                **marker={{
				    enabled: true,
				    markerColor: processColor('white'),
				    textColor: processColor('black'),
				  }}**
                legend={{enabled: false,}}
                doubleTapToZoomEnabled={false}
                highlightPerDragEnabled={false}
            />

```

_Error while updating property 'marker' of a view managed by: RNLineChart

null_

Failed resolution of: Landroidx/core/content/res/ResourcesCompat;

Didn't find class "androidx.core.content.res.ResourcesCompat" on path: DexPathList[[zip file "/data/app/com.zkhuashui.sandmall-1y0KIrmYyIZfg1EwRCrd2w==/base.apk"],nativeLibraryDirectories=[/data/app/com.zkhuashui.sandmall-1y0KIrmYyIZfg1EwRCrd2w==/lib/x86, /data/app/com.zkhuashui.sandmall-1y0KIrmYyIZfg1EwRCrd2w==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
updateViewProp
    ViewManagersPropertyCache.java:95
setProperty
    ViewManagerPropertyUpdater.java:132
updateProps
    ViewManagerPropertyUpdater.java:51
updateProperties
    ViewManager.java:37
createView
    NativeViewHierarchyManager.java:265
execute
    UIViewOperationQueue.java:200
dispatchPendingNonBatchedOperations
    UIViewOperationQueue.java:1109
doFrameGuarded
    UIViewOperationQueue.java:1080
doFrame
    GuardedFrameCallback.java:29
doFrame
    ReactChoreographer.java:166
doFrame
    ChoreographerCompat.java:84
run
    Choreographer.java:964
doCallbacks
    Choreographer.java:790
doFrame
    Choreographer.java:721
run
    Choreographer.java:951
handleCallback
    Handler.java:883
dispatchMessage
    Handler.java:100
loop
    Looper.java:214
main
    ActivityThread.java:7356
invoke
    Method.java
run
    RuntimeInit.java:492
main
    ZygoteInit.java:930

  - Version: rn 0.59.9   react-native-charts-wrapper 0.5.7
  - Platform:  android
  - Subsystem:

**Comment by asagcs** [comment]
If I delete the marker parameter, it will perform well

**Comment by asagcs** [comment]
If I delete the marker parameter, it will perform well

**Comment by asagcs** [comment]
参数
itValue = {
	            xAxis: {
	                valueFormatter: [
	                    '10/17',
	                    '10/18',
	                    '10/19',
	                    '10/20',
	                    '10/21',
	                    '10/22',
	                ],
	                granularityEnabled: true,
	                granularity: 1,
	                drawGridLines: false, 
	                textColor: processColor('#666'),
	                axisLineColor: processColor('#666'),
	                textSize: 12,
	                avoidFirstLastClipping: true,
	                position: 'BOTTOM',
	            },
	            yAxis: {
	                    left:{ 
	                        spaceTop: 5,
	                        granularityEnabled: true,
	                        granularity: 50,
	                        textColor: processColor('#666'),
	                        textSize: 12,
	                        axisMinimum: 0,
	                        axisMaximum: 250,
	                    },
	                    right: {
	                        enabled: false,
	                    },
	                    
	            },
	            marker: {
					enabled: true,
					digits: 2,
					backgroundTint: processColor('teal'),
					markerColor: processColor('red'),
					textColor: processColor('white'),
				},
	            data: {
	                dataSets: [
	                    {
	                        values: this.props.chartValue[0],
	                        label: '舒张压',
	                        config: {
	                            lineWidth: 3,
	                            drawFilled: false,
	                            axisDependency: 'LEFT',
	                            color: processColor('#007bfd'),
	                            mode: 'LINEAR',
	                            drawValues: false,
	                            axisDependency: 'LEFT',
	                            circleRadius: 4,
	                            circleColor: processColor('#007bfd'),
	                            drawCircleHole: false,                            
	                        },
	                    },
	                    {
	                        values: this.props.chartValue[1],
	                        label: '收缩压',
	                        config: {
	                            lineWidth: 3,
	                            drawFilled: false,
	                            axisDependency: 'LEFT',
	                            color: processColor('#ff726b'),
	                            mode: 'LINEAR',
	                            drawValues: false,
	                            axisDependency: 'LEFT',
	                            circleRadius: 4,
	                            circleColor: processColor('#ff726b'),
	                            drawCircleHole: false,
	                        },
	                    },
	                ],
	            },
        	}
		}

**Comment by asagcs** [comment]
参数
itValue = {
xAxis: {
valueFormatter: [
'10/17',
'10/18',
'10/19',
'10/20',
'10/21',
'10/22',
],
granularityEnabled: true,
granularity: 1,
drawGridLines: false,
textColor: processColor('#666'),
axisLineColor: processColor('#666'),
textSize: 12,
avoidFirstLastClipping: true,
position: 'BOTTOM',
},
yAxis: {
left:{
spaceTop: 5,
granularityEnabled: true,
granularity: 50,
textColor: processColor('#666'),
textSize: 12,
axisMinimum: 0,
axisMaximum: 250,
},
right: {
enabled: false,
},

            },
            data: {
                dataSets: [
                    {
                        values: this.props.chartValue[0],
                        label: '舒张压',
                        config: {
                            lineWidth: 3,
                            drawFilled: false,
                            axisDependency: 'LEFT',
                            color: processColor('#007bfd'),
                            mode: 'LINEAR',
                            drawValues: false,
                            axisDependency: 'LEFT',
                            circleRadius: 4,
                            circleColor: processColor('#007bfd'),
                            drawCircleHole: false,                            
                        },
                    },
                    {
                        values: this.props.chartValue[1],
                        label: '收缩压',
                        config: {
                            lineWidth: 3,
                            drawFilled: false,
                            axisDependency: 'LEFT',
                            color: processColor('#ff726b'),
                            mode: 'LINEAR',
                            drawValues: false,
                            axisDependency: 'LEFT',
                            circleRadius: 4,
                            circleColor: processColor('#ff726b'),
                            drawCircleHole: false,
                        },
                    },
                ],
            },
    	}
	}

**Comment by akinncar** [comment]
same here

**Comment by akinncar** [comment]
Does your app have supports for Android X?

**Comment by asagcs** [comment]
That means i need Version 0.60 or above of rn to use this option?
