### ISSUE TITLE
Not supporting React Native 0.59.9 for ios?

### ISSUE THREAD

**Issue by ricechenghk** [wuxudong/react-native-charts-wrapper#629]
I tried this library with React Native 0.59.9. It worked great in Android but build failed in iOS. 

### Expected Behavior
It should work great in both Android & iOS

### Actual Behavior
Build Failed in iOS

### Screenshots
<img width="272" alt="Screenshot 2019-11-14 at 1 12 55 PM" src="https://user-images.githubusercontent.com/6051908/68828574-20726e80-06e1-11ea-8da0-aeb54ca3ccdd.png">

### Steps to Reproduce the Problem
react-native init helloworld --version 0.59.9
yarn add react-native-charts-wrapper
yarn add @babel/runtime
cd helloworld
change podFile, add pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
react-native run-ios

### Specifications

  - Version:
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-charts-wrapper": "^0.5.7"
 
  - Platform: iOS, Xcode11.2
  - Subsystem:

**Comment by lordkiz** [comment]
Go to `Build Settings` in Xcode and add the path to the bridging header in `Objective C Bridging Header` within `Swift Compiler` Section.
![image](https://user-images.githubusercontent.com/18648835/68850693-cf5c7d80-06d4-11ea-8a74-083e73843906.png)

**Comment by lordkiz** [comment]
+1

**Comment by ricechenghk** [comment]
+1

**Comment by jamrockmedz** [comment]
+1

**Comment by SaeedZhiany** [comment]
the versions +0.5.6 have been upgraded to Androidx which means they only can be used with RN V+0.60.0.
for RN projects with version 0.59.10 and lower you must use react-native-charts-wrapper V0.5.5 or lower.

**Comment by codebetterme** [comment]
hi @all,
you could check tutorial below,
- edit package.json:
"react-native-charts-wrapper": "0.5.7"
- edit podfile:
use_frameworks!

target 'crmHybrid' do
  pod 'SwiftyJSON', '5.0'
  pod 'Charts', '3.3.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
