### ISSUE TITLE
I can't create a bridge file

### ISSUE THREAD

**Issue by matheus-hatzlhoffer** [wuxudong/react-native-charts-wrapper#632]
**I am a first year student and I am learning by my own react-native and I am not familiarised with IOS. I was following the installation guide, but the xCode didn't prompt to create bridging header and when I tried to do it manually and xCode didn't prompt to create a bridging header even when I made a swift file. I searched the internet and found this [link](https://stackoverflow.com/questions/31716413/xcode-not-automatically-creating-bridging-header) in stackoverflow that not helped me. Could you help me?**

### Expected Behavior
**Prompt to create bridging header**

### Actual Behavior
**Didn't prompt to create bridging header**

### Screenshots
<img width="1394" alt="Screen Shot 2019-11-17 at 23 48 36" src="https://user-images.githubusercontent.com/48157146/69021698-78d29600-0997-11ea-96c2-2bfd2c1b07af.png">

### Data and config 

- Xcode 11.2.1
- react-native-cli: 2.0.1
- Pod 1.7.5
- Swift 5

### Specifications

  - Platform: IOS

**Comment by CHOIMINSEOK** [comment]
Same here

**Comment by CHOIMINSEOK** [comment]
I resolved it. In my case, when I created swift file, Xcode prompt pop up properly.
Should not remove that swift file. if remove, build fails.
