### ISSUE TITLE
How to set different color for each bar in single bar chart

### ISSUE THREAD

**Issue by Yandamuri** [wuxudong/react-native-charts-wrapper#634]
### Expected Behavior
Need to set different color for each bar in single bar chart

### Actual Behavior
All bars are having single color

### Screenshots
![Screenshot_1574149235](https://user-images.githubusercontent.com/31983789/69126420-2cd63d00-0ace-11ea-81c1-cd1a70653e20.png)

### Code Sample

    dataSets: [{
	  values: singleBarValues,
	  label: datasets[0].label,
          config: {
		color: [processColor('#1ABC9C'),processColor('red'),processColor('green'),]
		drawValues: false,
	  }
     }],

If colors are given as an array as shown above, it's throwing following error,
     ` Failed prop type: Invalid prop `data.dataSets[0].config.color` of type `array` supplied to `BarChart`, expected `number`.`

Thank you.

**Comment by tattivitorino** [comment]
I need this as well!!! anything?????

**Comment by githubofwyh** [comment]
And excuse me, i need this for radar chart. if any one has some solution？appreciate it

**Comment by vuvuive** [comment]
You can usse Group BarChart  : https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/GroupBarChartScreen.js. 
Hope it works

**Comment by ibnukipa** [comment]
while waiting the owner to add this feature, you can try to manipulate with the grouped BarChart.

**Comment by wuxudong** [comment]
```

const chartDataSetConfig = {
  common: {
    color: PropTypes.number,
    colors: PropTypes.arrayOf(PropTypes.number),
    highlightEnabled:PropTypes.bool,
    drawValues: PropTypes.bool,
    valueTextSize:PropTypes.number,

```

You can use colors instead.

**Comment by adityaindiadev** [comment]
Just 'color' to 'colors' in datasets -> config and paas the array of color Ex: [processColor('green'), processColor('blue')], That's it.

Example: 
dataSets: [{
              values: [{y: 50}, {y: 70}],
              label: 'Regularization',
              config: {
                colors: [processColor('green'), processColor('blue')],
                barShadowColor: processColor('lightgrey'),
                highlightAlpha: 90,
                highlightColor: processColor('red'),
              }
            }],
