### ISSUE TITLE
Marker text display like 0,33 instead of 0.33 value.

### ISSUE THREAD

**Issue by DhavalKakadiya** [wuxudong/react-native-charts-wrapper#635]
When I use dataset value as [0.22, 0.33, 0.50, 0.30] for line chart. but when I display a marker on the chart point. In marker text, it displays as 0,22 or 0,33. So, how can I solve it?

**Comment by DhavalKakadiya** [comment]
I've fixed that with customize array like this,  [{y: 0.22, marker: '0.22'}, {y: 0.33, marker: '0.33'}, {y: 0.50, marker: '0.50'}, {y: 0.30, marker: '0.30'}].

**Comment by wuxudong** [comment]
It is locale related.
