### ISSUE TITLE
"0.5.7" is throwing an error pertaining to marker : error while updating property marker of a view managed by rnbarchart

### ISSUE THREAD

**Issue by Yandamuri** [wuxudong/react-native-charts-wrapper#638]
### Expected Behavior
Chart should render as usual
### Actual Behavior
throwing an error: error while updating property marker of a view managed by rnbarchart
### Screenshots
![Screenshot_1574405428](https://user-images.githubusercontent.com/31983789/69405346-6fde1d80-0d25-11ea-8f04-52f478788ce4.png)

### Specifications

  - Version: 0.5.7
  - Platform: android(not sure about ios)
  - Subsystem:

Note: when i revert back to 0.5.1 working fine

**Comment by wuxudong** [comment]
androidx is required.

**Comment by Yandamuri** [comment]
@wuxudong Thank you, I will try to update my react-native version. BTW, Can you have look at this issue which has been open for couple of days?
