### ISSUE TITLE
Android stacked bar chart with lot of data

### ISSUE THREAD

**Issue by dimovdaniel** [wuxudong/react-native-charts-wrapper#64]
Hi. Is it possible to remove the empty space between the bars in the stacked bar char. 
When we have lot of data in the android one, doesn't renders smooth. 

Or can you suggest something else to maki similar graph to this once. 
![Image the chart](http://i.imgur.com/9pj1S2J.png)

Thanks

**Comment by wuxudong** [comment]
![simulator screen shot 26 may 2017 7 13 50 pm](https://cloud.githubusercontent.com/assets/1391101/26492586/7a808422-4247-11e7-8e3a-3035e5ed8459.png)

```
 data: {
        dataSets: [{
          values: [{y:[40, 30, 20], marker: ["row1", "row2", "row3"]}, {y:[10, 20, 10], marker:"second"}, {y:[30, 20, 50], marker:["hello", "world","third"]}, {y:[30, 50, 10], marker:"fourth"}],
          label: 'Stacked Bar dataset',
          config: {
            colors: [processColor('#C0FF8C'), processColor('#FFF78C'), processColor('#FFD08C')],
            stackLabels: ['Engineering', 'Sales', 'Marketing']
          }
        }],
        config: {
          barWidth: 1
        }
      },

```

**Comment by dimovdaniel** [comment]
Thanks, looks great.
