### ISSUE TITLE
How to reverse HorizontalBarChart Data(反转数据)

### ISSUE THREAD

**Issue by ief820** [wuxudong/react-native-charts-wrapper#642]
Hi, wuxudong:

how to reverse data in HorizontalBarChart,  put top data to bottom, bottom data to top,
upsidedown, 

for example:
1
22
333
4444
55555

to:
55555
4444
333
22
1

mpandroid chart reverse  data：
https://github.com/PhilJay/MPAndroidChart/issues/2715
       mChart.getAxisLeft().setInverted(true);
Not  Horozontal  reverse, what I need is vertical  reverse  in HorizontolBarChart

how to reverse data in RN   HorizontalBarChart
xAxis  ,inverted: true  doesn't work

**Comment by wuxudong** [comment]
Not support by MpAndroidChart
