### ISSUE TITLE
This plug-in is packaged according to MPAndroidChart and Charts. Then in the reactNative project, are all method names consistent when calling the plug-in? Do you need not distinguish between ios and Android platforms

### ISSUE THREAD

**Issue by YANGQUNGONGSHE** [wuxudong/react-native-charts-wrapper#643]
This plug-in is packaged according to MPAndroidChart and Charts. Then in the reactNative project, are all method names consistent when calling the plug-in? Do you need not distinguish between ios and Android platforms

**Comment by wuxudong** [comment]
Most features have the same signatures.
Those features which only support a single platform are documented in js file.
