### ISSUE TITLE
Time series not working on Android 

### ISSUE THREAD

**Issue by ezranbayantemur** [wuxudong/react-native-charts-wrapper#649]
I'm trying to show some time series data on app. It's working perfectly on iOS but not on Android.

My example code:
```javascript
...
...
        <LineChart
          data={{
            dataSets: [{
              values: [
                { x: 1576147159, y: 0.88 },
                { x: 1576147162, y: 0.77 },
                { x: 1576147164, y: 105 },
                { x: 1576147166, y: 135 },
                { x: 1576147168, y: 0.88 },
                { x: 1576147170, y: 0.77 },
                { x: 1576147172, y: 105 },
                { x: 1576147175, y: 135 }
              ],
              label: 'Test Date',
            }],
          }}
          
          xAxis={{
            valueFormatter: 'date',
            valueFormatterPattern: "dd-MM-YYYY HH:mm:ss",
            position: 'BOTTOM',
            timeUnit: 'SECONDS',
            since: 0
          }}
        />
...
...
```
And outputs:
**iOS**
![Simulator Screen Shot - iPhone 11 - 2019-12-12 at 15 35 14](https://user-images.githubusercontent.com/42299721/70712674-637e2c80-1cf5-11ea-9e5f-44b6b0377075.png)

**Android**
![screenshot-2019-12-12_15 34 56 417](https://user-images.githubusercontent.com/42299721/70712710-74c73900-1cf5-11ea-8d57-ea178add90c3.png)

On Android it shows all data on the left side of the chart like this;
![Screen Shot 2019-12-12 at 15 39 56](https://user-images.githubusercontent.com/42299721/70712819-af30d600-1cf5-11ea-916d-7e944566add4.png)

Strange thing is if I reduce the x values it starts to show on chart. Like;
```javascript
...
...
              values: [
                { x: 7159, y: 0.88 },
                { x: 7162, y: 0.77 },
                { x: 7164, y: 105 },
                { x: 7166, y: 135 },
                { x: 7168, y: 0.88 },
                { x: 7170, y: 0.77 },
                { x: 7172, y: 105 },
                { x: 7175, y: 135 }
              ]
...
...
```
![screenshot-2019-12-12_15 41 27 224](https://user-images.githubusercontent.com/42299721/70712893-e43d2880-1cf5-11ea-8392-ac78d6459ab8.png)

What is the problem?

```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-charts-wrapper": "^0.5.7"
```

**Comment by ezranbayantemur** [comment]
Can you check it? @wuxudong

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.

**Comment by wuxudong** [comment]
I think it is related to float value range.

Check this comment is AxisIFace.js

// Note: for iOS/Charts, double is used for x, but in MpAndroidChart, float is used for x.
  // so in android, there will be precision loss when you use MILLISECONDS/SECOND/MINUTES as x value.   
  // you can use a different since like seconds of 2019 or use timeUnit DAYS, then x value will be within a valid range.

  valueFormatterPattern: PropTypes.string,
