### ISSUE TITLE
 xAxis: {valueFormatter: [ 'long_name \n long_name' ;  break word not work on android ,but ios is fine

### ISSUE THREAD

**Issue by k2easy** [wuxudong/react-native-charts-wrapper#65]

**Comment by wuxudong** [comment]
The TimeSeriesLineChartScreen.js in examples works well.

```

 values: [
                {x: 1, y: 11000, marker: "a very long \nlong\n long\n long long\n long long long \nmarker at top left"},
                {x: 20, y: 90, marker: "eat eat eat, never\n stop eat"},


```

<img width="464" alt="screen shot 2017-05-29 at 10 47 59 pm" src="https://cloud.githubusercontent.com/assets/1391101/26554184/8228d1ee-44c1-11e7-960f-d71574281f5b.png">

**Comment by muchmeat** [comment]
hi,in BarChart , i  have xAxis valueFormatter like this ,['long_name \n long_name\nlong_name \n long_name','long_name \n long_name\nlong_name \n long_name','long_name \n long_name\nlong_name \n long_name'] . it didn't work on android.here is my formatter function:
 _formatterLabel = (value, num) => {
        let str = "";
        let valLength = value.length;
        let rowNum = Math.ceil(valLength / num); 
        if (rowNum > 1) {
            for (let i = 0; i < rowNum; i++) {
                let temp = "";
                let start = i * num;
                let end = start + num;

                temp = value.substring(start, end) + "\n";
                str += temp;
            }
            return str;
        } else {
            return value;
        }
    };

can you ve me some suggestion @wuxudong @k2easy
