### ISSUE TITLE
Error while updating property 'data' of a view managed by: RNLineChart

### ISSUE THREAD

**Issue by tazik561** [wuxudong/react-native-charts-wrapper#658]
I want to use chart on my react native android application so after googling and some suggestion i finally decide to use of react-native-charts-wrapper .

```
    import React, { useEffect } from "react";
    import { View, StyleSheet, Button,  processColor } from "react-native";
    import { useDispatch, useSelector } from "react-redux";
    import { LineChart } from 'react-native-charts-wrapper';

    import * as lastListFileChartActions from "../../store/actions/lastListFileChart";

    export default LastFileforMonthScreen = ({ navigation }) => {

    const data = useSelector(state => state.chart.chartDataAweekMonth);
    const dispatch = useDispatch();

    console.log('data is: ',data);
    const state = {
        data,
        marker: {
            enabled: true,
            digits: 2,
            backgroundTint: processColor('teal'),
            markerColor: processColor('#F0C0FF8C'),
            textColor: processColor('white'),
        },
        xAxis: {
            granularityEnabled: true,
            granularity: 1,
        },
    }

    useEffect(() => {
        dispatch(lastListFileChartActions.getLastFilesFromSurveyorLong(100));
    }, [dispatch]);

    if (data.length == 0) {
        return null;
    }

    console.log('state: ',state.data)
    return (
        <View style={{ flex: 1 }}>
            <View style={styles.container}>
                <LineChart
                    style={styles.chart}
                    data={state.data}
                    chartDescription={{ text: '' }}
                    legend={state.legend}
                    marker={state.marker}
                    xAxis={state.xAxis}
                    drawGridBackground={false}
                    borderColor={processColor('teal')}
                    borderWidth={1}
                    drawBorders={true}
                    autoScaleMinMaxEnabled={false}
                    touchEnabled={true}
                    dragEnabled={true}
                    scaleEnabled={true}
                    scaleXEnabled={true}
                    scaleYEnabled={true}
                    pinchZoom={true}
                    doubleTapToZoomEnabled={true}
                    highlightPerTapEnabled={true}
                    highlightPerDragEnabled={false}
                    // visibleRange={this.state.visibleRange}
                    dragDecelerationEnabled={true}
                    dragDecelerationFrictionCoef={0.99}
                    // ref="chart"
                    keepPositionOnRotation={false}
                    onSelect={() => { }}
                    onChange={() => { }}
                />
            </View>
        </View>
    );
}
```

This is result of console.log('state: ',state.data):

` state:  {"dataSets": [{"label": "A", "values": [Array]}]}
`
But I got this error :

**Error while updating property 'data' of a view managed by: RNLineChart**

https://i.stack.imgur.com/6ynJG.png

This is values i want to show:

> [{"x": "1398/10/15", "y": 9}, {"x": "1398/10/14", "y": 10}, {"x": "1398/09/17", "y": 1}, {"x": "1398/09/16", "y": 9},...]

I think because i am using string in x key i got this error!! If i right how could i use string ?

**Comment by talha-hameed** [comment]
any solution?

**Comment by jmgayosso** [comment]
HI @tazik561  Did you fix? you can try with `xAxis: {
        enabled: true,
        drawGridLines: false,
        valueFormatter: [
          '2020-01-16',
          '2020-01-17',
          '2020-01-20',
          '2020-01-24',
          '2020-01-30',
]}`

**Comment by crisecheverria** [comment]
In my case says: "Value for x cannot be cast from String to Double"

On iOS is working fine, the issue is with Android.

**Comment by wuxudong** [comment]
Check 

```
values: PropTypes.arrayOf(
        PropTypes.oneOfType([
          PropTypes.shape({
            x: PropTypes.number,
            y: PropTypes.number.isRequired,
            marker: PropTypes.string,
            icon: PropTypes.shape({
              bundle: PropTypes.object,
              width: PropTypes.number,
              height: PropTypes.number
            })
          }),
          PropTypes.number
        ])
      ),

```

x should be number if provided.

**Comment by christopher-18** [comment]
@crisecheverria  @gowthambalashanmugam if you were able to resolve it, can you help me out in this https://github.com/wuxudong/react-native-charts-wrapper/issues/908

**Comment by gowthambalashanmugam** [comment]
By any chance this will help out?
`<LineChart
          scaleEnabled={true}
          scaleXEnabled={true}
          scaleYEnabled={true}
          dragEnabled={true}
          visibleRange={{x: {min: 1, max: 2}}}
          pinchZoom={true}
          doubleTapToZoomEnabled={true}
          highlightPerTapEnabled={true}
          data={this.state.data}
          marker={{
            enabled: true,
            digits: 2,
            markerColor: coreGold,
            textAlign: 'center',
          }}
          width={width - 60}
          legend={{enabled: false}}
          borderColor={processColor('red')}
          chartDescription={{text: ''}}
          height={scaledSize(235)}
          xAxis={{
            textColor: processColor('black'),
            drawLabels: true,
            drawAxisLine: true,
            gridLineWidth: 2,
            gridColor: processColor('#e5e9f0'),
            position: 'BOTTOM',
            valueFormatter: this.state.complianceHistory.x,
            granularityEnabled: true,
            avoidFirstLastClipping: true,
          }}
          yAxis={{
            left: {
              textColor: processColor('black'),
              drawLabels: true,
              drawAxisLine: true,
              drawGridLines: true,
              gridLineWidth: 2,
              valueFormatter: '#%',
              gridColor: processColor('#e5e9f0'),
            },
            right: {
              enabled: false,
            },
          }}
        />`

**Comment by christopher-18** [comment]
> By any chance this will help out? ` <LineChart` scaleEnabled={true} scaleXEnabled={true} scaleYEnabled={true} dragEnabled={true} visibleRange={{x: {min: 1, max: 2}}} pinchZoom={true} doubleTapToZoomEnabled={true} highlightPerTapEnabled={true} data={this.state.data} marker={{ enabled: true, digits: 2, markerColor: coreGold, textAlign: 'center', }} width={width - 60} legend={{enabled: false}} borderColor={processColor('red')} chartDescription={{text: ''}} height={scaledSize(235)} xAxis={{ textColor: processColor('black'), drawLabels: true, drawAxisLine: true, gridLineWidth: 2, gridColor: processColor('#e5e9f0'), position: 'BOTTOM', valueFormatter: this.state.complianceHistory.x, granularityEnabled: true, avoidFirstLastClipping: true, }} yAxis={{ left: { textColor: processColor('black'), drawLabels: true, drawAxisLine: true, drawGridLines: true, gridLineWidth: 2, valueFormatter: '#%', gridColor: processColor('#e5e9f0'), }, right: { enabled: false, }, }} />`

What is your data format? I have converted it to x values to timestamp. And now need to format those values in form of dates.

**Comment by gowthambalashanmugam** [comment]
x: ['Jul-Sep 22', 'Apr-Jun 22', 'Jan-Mar 22', 'Oct-Dec 21', 'Jul-Sep 21', 'Apr-Jun 21']
y: [0.72, 0.61, 0.72, 0.74, 0.79, 0.88]

**Comment by christopher-18** [comment]
> 
I am getting this error on using a string in android . 
Value for x cannot be cast from String to Double

**Comment by christopher-18** [comment]
> In my case says: "Value for x cannot be cast from String to Double"
> 
> On iOS is working fine, the issue is with Android.
> 
> My data looks like
> 
> ```
> [{ "x": "03/Sep 22:11", "y": 72}, { "x": "04/Sep 00:27", "y": 89 }]
> ```
> 
> I disabled xAxis only displaying yAxis.
> 
> EDIT: Fixed converting from String to unix timestamp!

Doing this , works.. but i need to display those timestamp values to some format 'day, date month year'. How to achieve that?

**Comment by christopher-18** [comment]
> responseJson.data.map(e => { complianceHistory.y.push( e.compliance_level ? parseInt(e.compliance_level) / 100 : 0, ); complianceHistory.x.push(e.invoice_date ? e.invoice_date : 0); yObj.push({ y: e.compliance_level ? parseInt(e.compliance_level) / 100 : 0, marker: e.compliance_level ? parseInt(e.compliance_level) + '%' : 0, }); });

What about x value? Since x is of type string.

**Comment by gowthambalashanmugam** [comment]
xAxis={{
            textColor: processColor('black'),
            drawLabels: true,
            drawAxisLine: true,
            gridLineWidth: 2,
            gridColor: processColor('#e5e9f0'),
            position: 'BOTTOM',
            valueFormatter: this.state.complianceHistory.x,
            granularityEnabled: true,
            avoidFirstLastClipping: true,
          }}

**Comment by christopher-18** [comment]
> xAxis={{ textColor: processColor('black'), drawLabels: true, drawAxisLine: true, gridLineWidth: 2, gridColor: processColor('#e5e9f0'), position: 'BOTTOM', valueFormatter: this.state.complianceHistory.x, granularityEnabled: true, avoidFirstLastClipping: true, }}

Can you look into this? https://github.com/wuxudong/react-native-charts-wrapper/issues/908 I don't think we have same format.

**Comment by gowthambalashanmugam** [comment]
![Simulator Screen Shot - iPhone 13 - 2022-10-26 at 10 26 46](https://user-images.githubusercontent.com/5539186/197938744-6c1dd660-799c-4449-8473-6bb90151d258.png)

**Comment by vinhtnk** [comment]
I have same issue. If you have a small dataset, then add more some bigger dataset, chart will crash. Solution is, add bigger dataset first then add smaller dataset after
