### ISSUE TITLE
No chart data although data is supplied

### ISSUE THREAD

**Issue by dburgmann** [wuxudong/react-native-charts-wrapper#66]
I used Linechart as follows:

`<LineChart data={data} style={{height:100, width: 100}} />`

where data looks like its described in the readme:

`let data = {
      data: {
        dataSets: [{
          values: [{y: 100}, {y: 110}, {y: 105}, {y: 115}]
        }]
      }
    }`

however the Linechart elements gets rendered but shows "No chart data available" instead of the actual chart.

**Comment by sunchaosailor** [comment]
Hi! Maybe I make a stupid typo too，because I get the "No chart data available" too. However, I can't recognized my mistake. Can anyone help me ?
