### ISSUE TITLE
How to set format .00 to 0 in yAxis ?

### ISSUE THREAD

**Issue by newKoala** [wuxudong/react-native-charts-wrapper#661]
Excuse me, How to change format .00 to 0 in yAxis ?
![1578652358836@2x](https://user-images.githubusercontent.com/59729995/72147424-1020fc00-33d1-11ea-8421-5ab95f97f011.jpg)

thank you for answer

**Comment by lzweife** [comment]
I also have this situation in iPhone 6s when use LineChart.  yAxis was showed like [.0, .2, .4, .6, .8, 1.0]

**Comment by wuxudong** [comment]
valueFormatter.
