### ISSUE TITLE
How can I customize x axis value in line chart?

### ISSUE THREAD

**Issue by DhavalKakadiya** [wuxudong/react-native-charts-wrapper#663]
I have 43 records for xAxis value and need to display only 7 values on the x-axis. I have used **granularity** property for that, but not display the result which I want.

Thanks in advance for the help!

**Comment by wuxudong** [comment]
try visibleRange  
or maxVisibleValueCount
or  
  axisMaximum: PropTypes.number,
  axisMinimum: PropTypes.number,
