### ISSUE TITLE
Hide xAxis and Description label.

### ISSUE THREAD

**Issue by RajeshKumDev** [wuxudong/react-native-charts-wrapper#669]
How can I hide the xAxis lines and Description Label. Highlighted in Red color.

### Screenshots
![chart](https://user-images.githubusercontent.com/45311174/73657769-fc5b7380-46b8-11ea-9a8f-e8098b23a4a2.png)

### Code
JSON data:

> const CHART_DATA = {
  legend: {
    enabled: false,
  },
  data: {
    dataSets: [
      {
	values: [{y: 100}, {y: 105}, {y: 102}],
	label: 'Report',
	config: {
	  color: processColor(APP_MAIN_BLUE_COLOR),
	},
      },
    ],
    config: {
      barWidth: 0.25,
    },
    chartDescription: {
      textColor: processColor(APP_MAIN_BLUE_COLOR),
      text: 'Hello',
    },
  },
  xAxis: {
    valueFormatter: ['Running Late', 'Arrived on Time', 'Total Visit'],
    position: 'BOTTOM',
    drawGridLines: false,
    drawAxisLine: false,
    labelCount: 3,
    textSize: 6,
    granularityEnabled: true,
    granularity: 1,
  },
  yAxis: {
    limitLines: [{limit: 2}],
    left: {
      drawAxisLine: false,
      drawLabels: false,
    },
    right: {
      drawAxisLine: false,
      drawLabels: false,
    },
  },
};

JSX Code:

        <BarChart
          style={styles.chart}
          data={data.data}
          xAxis={data.xAxis}
          yAxis={data.yAxis}
          animation={{durationX: 0}}
          legend={data.legend}
          visibleRange={{x: {min: 3, max: 3}}}
          drawBarShadow={false}
          drawHighlightArrow={true}
          drawGridBackground={false}
        />

Sorry for poor formatting.

**Comment by RajeshKumDev** [comment]
Hi,

I can solve the above issue using below code:

> const CHART_DATA = {
  legend: {
    enabled: false,
  },
  data: {
    dataSets: [
      {
        values: [{y: 100}, {y: 105}, {y: 102}],
        label: 'Report',
        config: {
          color: processColor(APP_MAIN_BLUE_COLOR),
        },
      },
    ],
    config: {
      barWidth: 0.25,
    },
  },
  xAxis: {
    valueFormatter: ['Running Late', 'Arrived on Time', 'Total Visit'],
    position: 'BOTTOM',
    drawGridLines: false,
    drawAxisLine: false,
    textSize: 6,
    granularityEnabled: true,
    granularity: 1,
    gridColor: processColor('#000'),
  },
  yAxis: {
    zeroLine: {enabled: true},
    limitLines: [{limit: 1}],
    left: {
      drawGridLines: false,
      drawAxisLine: false,
      drawLabels: false,
    },
    right: {
      drawGridLines: false,
      drawAxisLine: false,
      drawLabels: false,
    },
  },
};

JSX code:
> <BarChart
  style={styles.chart}
  data={data.data}
  xAxis={data.xAxis}
  yAxis={data.yAxis}
  animation={{durationX: 0}}
  legend={data.legend}
  visibleRange={{x: {min: 3, max: 3}}}
  drawBarShadow={false}
  chartDescription={{text: ''}}
  drawGridBackground={false}
/>

Thanks.

**Comment by anniewey** [comment]
Has the same `description label` text. Hide it with `chartDescription={{text: ''}}` props. Thanks for sharing.

> Hi,
> 
> I can solve the above issue using below code:
> 
> > const CHART_DATA = {
> > legend: {
> > enabled: false,
> > },
> > data: {
> > dataSets: [
> > {
> > values: [{y: 100}, {y: 105}, {y: 102}],
> > label: 'Report',
> > config: {
> > color: processColor(APP_MAIN_BLUE_COLOR),
> > },
> > },
> > ],
> > config: {
> > barWidth: 0.25,
> > },
> > },
> > xAxis: {
> > valueFormatter: ['Running Late', 'Arrived on Time', 'Total Visit'],
> > position: 'BOTTOM',
> > drawGridLines: false,
> > drawAxisLine: false,
> > textSize: 6,
> > granularityEnabled: true,
> > granularity: 1,
> > gridColor: processColor('#000'),
> > },
> > yAxis: {
> > zeroLine: {enabled: true},
> > limitLines: [{limit: 1}],
> > left: {
> > drawGridLines: false,
> > drawAxisLine: false,
> > drawLabels: false,
> > },
> > right: {
> > drawGridLines: false,
> > drawAxisLine: false,
> > drawLabels: false,
> > },
> > },
> > };
> 
> JSX code:
> 
> > <BarChart
> > style={styles.chart}
> > data={data.data}
> > xAxis={data.xAxis}
> > yAxis={data.yAxis}
> > animation={{durationX: 0}}
> > legend={data.legend}
> > visibleRange={{x: {min: 3, max: 3}}}
> > drawBarShadow={false}
> > chartDescription={{text: ''}}
> > drawGridBackground={false}
> > />
> 
> Thanks.
