### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by bang88** [wuxudong/react-native-charts-wrapper#67]
How to display all  items  even them have a same value ?
Here  have  a snapshot, between 46 and 38 have a item 44 but now its not showing. how can i configure it. 

![snip20170605_50](https://cloud.githubusercontent.com/assets/433259/26770113/3efea2f0-49de-11e7-821d-7f7cf16606f6.png)

Thanks

**Comment by wuxudong** [comment]
Sample data and config is required.
