### ISSUE TITLE
How to change the color of Radar Chart valueFormatter  ?

### ISSUE THREAD

**Issue by naxir** [wuxudong/react-native-charts-wrapper#676]
![Radar](https://user-images.githubusercontent.com/17848552/75419440-a4cac380-5957-11ea-961b-fe013cf3b378.jpg)

I want to change the color of value Formatter as highlighted  with circle 
any help ????

**Comment by naxir** [comment]
@wuxudong @douglasjunior 
I want to change the color of Detect , Protect , Recover , Identity , Respond Recover 
I have tried all CommonDatasetConfig i.e   export interface CommonDatasetConfig {
    color?: Color;
    colors?: Color[];
    highlightEnabled?: boolean;
    drawValues?: boolean;
    valueTextSize?: number;
    valueTextColor?: Color;
    visible?: boolean;
    valueFormatter?: ValueFormatter;
    axisDependency?: AxisDependency;
}
But I am unable to change the color 

![Screenshot 2020-02-29 at 2 01 01 AM](https://user-images.githubusercontent.com/17848552/75587482-61c43980-5a98-11ea-8b04-e7098beb5b7e.png)

Can you please help me about this 
Thanks

**Comment by mdobroggg** [comment]
Hey, I was looking for this as well and found out that this worked for me on HorizonalBarChart. Hope this helps you as well:
javascript```
const chartData = {
    dataSets: [
      {
        values: [1000, 10000, 100000, 1000000],
        label: 'Asset Data',
        config: {
          valueFormatter: ['Transportation $100,000'],
          valueTextColor: processColor('white'),
        },
      },
    ],
  };
```

**Comment by naxir** [comment]
@mdobroggg 
I have also tried valueTextColor but not applying 
my code is
class TestChart extends React.Component {

    constructor() {
        super();
        this.state = {
            data: {},
            legend: {
                enabled: false,
                textSize: 30,
                form: 'CIRCLE',
                wordWrapEnabled: true
            }
        };
    }

    componentDidMount() {
        this.setState(
            update(this.state, {
                data: {
                    $set: {
                        dataSets: [{
                            values: [1.1,1.1,3.38,4.6,3.33],
                            label: 'Identify',
                            config: {
                                valueTextColor:processColor('#146294'),
                                colors: [processColor('white'),processColor('white'),processColor('white'),processColor('white'),processColor('white')],
                                drawFilled: true,
                                fillColor: processColor('#146294'),
                                fillAlpha: 200,
                                lineWidth: 1,
                                drawValues:false,
                            }
                        }, ],
                    }
                },
                xAxis: {
                    $set: {
                        valueFormatter: ['A', 'B', 'C', 'D', 'E']
                    }
                }
            })
        );
    }

    handleSelect(event) {
        let entry = event.nativeEvent
        if (entry == null) {
            this.setState({ ...this.state, selectedEntry: null })
        } else {
            this.setState({ ...this.state, selectedEntry: JSON.stringify(entry) })
        }

        console.log(event.nativeEvent)
    }

    render() {
        return (
            <View style={{ flex: 1, borderColor: '#43464B', borderWidth: Dimension(6), borderRadius: Dimension(10), marginLeft: Dimension(50), marginRight: Dimension(50), marginTop: Dimension(30) }}>
                <View style={{ backgroundColor: '#1E2026', borderColor: '#43464B', borderBottomWidth: Dimension(6), height: Dimension(100), justifyContent: 'center', alignItems: 'center' }}>
                    <Text style={{ fontSize: (18), color: '#949598', alignSelf: 'flex-start', marginLeft: Dimension(24) }}>{this.props.title}</Text>
                </View>
                <RadarChart
                    style={styles.chart}
                    data={this.state.data}
                    xAxis={this.state.xAxis}
                    yAxis={{ drawLabels: true }}
                    legend={this.state.legend}
                    drawWeb={true}
                    webLineWidth={1}
                    webLineWidthInner={1}
                    webAlpha={255}
                    webColor={processColor("white")}
                    webColorInner={processColor("white")}
                    skipWebLineCount={1}
                    onSelect={this.handleSelect.bind(this)}
                    onChange={(event) => console.log(event.nativeEvent)}
                />
            </View>

        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#31343B'
    },
    chart: {
        flex: 1,
    }
});

**Comment by naxir** [comment]
class TestChart extends React.Component {

    constructor() {
        super();
        this.state = {
            data: {},
            legend: {
                enabled: false,
                textSize: 30,
                form: 'CIRCLE',
                wordWrapEnabled: true
            }
        };
    }

    componentDidMount() {
        this.setState(
            update(this.state, {
                data: {
                    $set: {
                        dataSets: [{
                            values: [1.1,1.1,3.38,4.6,3.33],
                            label: 'Identify',
                            config: {
                                valueTextColor:processColor('white'),
                                colors: [processColor('white'),processColor('white'),processColor('white'),processColor('white'),processColor('white')],
                                drawFilled: true,
                                fillColor: processColor('#146294'),
                                fillAlpha: 200,
                                lineWidth: 1,
                                drawValues:false,
                            }
                        }, ],
                    }
                },
                xAxis: {
                    $set: {
                        valueFormatter: ['A', 'B', 'C', 'D', 'E']
                    }
                }
            })
        );
    }

    handleSelect(event) {
        let entry = event.nativeEvent
        if (entry == null) {
            this.setState({ ...this.state, selectedEntry: null })
        } else {
            this.setState({ ...this.state, selectedEntry: JSON.stringify(entry) })
        }

        console.log(event.nativeEvent)
    }

    render() {
        return (
            <View style={{ flex: 1, borderColor: '#43464B', borderWidth: Dimension(6), borderRadius: Dimension(10), marginLeft: Dimension(50), marginRight: Dimension(50), marginTop: Dimension(30) }}>
                <View style={{ backgroundColor: '#1E2026', borderColor: '#43464B', borderBottomWidth: Dimension(6), height: Dimension(100), justifyContent: 'center', alignItems: 'center' }}>
                    <Text style={{ fontSize: (18), color: '#949598', alignSelf: 'flex-start', marginLeft: Dimension(24) }}>{this.props.title}</Text>
                </View>
                <RadarChart
                    style={styles.chart}
                    data={this.state.data}
                    xAxis={this.state.xAxis}
                    yAxis={{ drawLabels: true }}
                    legend={this.state.legend}
                    drawWeb={true}
                    webLineWidth={1}
                    webLineWidthInner={1}
                    webAlpha={255}
                    webColor={processColor("white")}
                    webColorInner={processColor("white")}
                    skipWebLineCount={1}
                    onSelect={this.handleSelect.bind(this)}
                    onChange={(event) => console.log(event.nativeEvent)}
                />
            </View>

        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#31343B'
    },
    chart: {
        flex: 1,
    }
});

@mdobroggg  I have tried but not apply color white

**Comment by naxir** [comment]
@wuxudong  @douglasjunior Any Help ??

**Comment by wuxudong** [comment]
@naxir They are axis labels, not data.

try textColor: processColor('green') in xAxis

**Comment by SamiChab** [comment]
Any help on this guys?

**Comment by SamiChab** [comment]
@naxir `xAxis={{valueFormatter: ['1', '2', '3', '4', '5'], textSize: 15}}`

You can find other props available here: `node_modules/react-native-charts-wrapper/lib/AxisIface.js`
