### ISSUE TITLE
Candlestickchart : Candle is not showing clearly for small difference in data.

### ISSUE THREAD

**Issue by bhoomika911** [wuxudong/react-native-charts-wrapper#679]
Hello Team, thanks for creating awesome library to generate candlestick chart. 

I am facing an issue to show candle stick chart. For my specific data candle is not getting generated inside chart. It is only showing value as per screen shot.

![Screenshot_2020-03-01-10-07-41-926_com bittrade](https://user-images.githubusercontent.com/26411261/75628249-18154500-5ba5-11ea-9cf2-34cefabee40d.png)

My code is as below for this chart:
//*******************************************************//
import React from 'react';
import {
    AppRegistry,
    StyleSheet,
    Text,
    Button,
    View,
    processColor
} from 'react-native';
import update from 'immutability-helper';

import _ from 'lodash';
import { CandleStickChart } from 'react-native-charts-wrapper';

class Exchange extends React.Component {

    constructor() {
        super();

        this.state = {
            legend: {
                enabled: true,
                textSize: 14,
                form: 'CIRCLE',
                wordWrapEnabled: true
            },
            data: {
                dataSets: [{
                    values: [{ shadowH: 101.78, shadowL: 101.77, open: 101.78, close: 101.78 },
                    { shadowH: 101.58, shadowL: 101.57, open: 101.58, close: 101.58 },
                    ],
                    label: 'AAPL',
                    config: {
                        highlightColor: processColor('darkgray'),

                        shadowColor: processColor('black'),
                        shadowWidth: 1,
                        shadowColorSameAsCandle: true,
                        increasingColor: processColor('#71BD6A'),
                        increasingPaintStyle: 'FILL',
                        decreasingColor: processColor('#D14B5A')
                    },
                    xAxis: {},
                    yAxis: {}
                }],
            },
            marker: {
                enabled: true,
                markerColor: processColor('#2c3e50'),
                textColor: processColor('white'),
            },
            zoomXValue: 0
        };

        this.x = 0;
    }

    handleSelect(event) {
        let entry = event.nativeEvent
        if (entry == null) {
            this.setState({ ...this.state, selectedEntry: null })
        } else {
            this.setState({ ...this.state, selectedEntry: JSON.stringify(entry) })
        }

        console.log(event.nativeEvent)
    }

    render() {
        return (

            <View style={{ flex: 1 }}>

                <View style={{ height: 80 }}>
                    <Text> selected entry</Text>
                    <Text> {this.state.selectedEntry}</Text>
                </View>

                <View style={styles.container}>
                    <CandleStickChart
                        style={styles.chart}
                        data={this.state.data}
                        marker={this.state.marker}
                        chartDescription={{ text: 'CandleStick' }}
                        legend={this.state.legend}
                        xAxis={this.state.xAxis}
                        yAxis={this.state.yAxis}
                        maxVisibleValueCount={16}
                        autoScaleMinMaxEnabled={true}
                        // zoom={{scaleX: 2, scaleY: 1, xValue:  400000, yValue: 1}}
                        zoom={{ scaleX: 1, scaleY: 1, xValue: 40, yValue: 916, axisDependency: 'LEFT' }}
                        onSelect={this.handleSelect.bind(this)}
                        ref="chart"
                        onChange={(event) => console.log(event.nativeEvent)}
                    />
                </View>

            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5FCFF'
    },
    chart: {
        flex: 1
    }
});

export default Exchange;
//************************************************//

Anyone can please help here? It is urgent.

**Comment by wuxudong** [comment]
![image](https://user-images.githubusercontent.com/1391101/95058349-fc20e580-0729-11eb-954f-7a9b9fd93401.png)

It looks fine in Example when applying your data.
