### ISSUE TITLE
limitLine wrapper

### ISSUE THREAD

**Issue by fernandessteve** [wuxudong/react-native-charts-wrapper#68]
@wuxudong; hello!
I'm using react-native to set the limit-line from a dynamic value that is passed in the JSX. I tried setting the limitLine with pre-defined values to the y-axis. This did not display the limitLine
`<LineChart
yAxis={{startAtZero:false,drawGridLines:false,position:"INSIDE_CHART", limitLine:115}}
` 
Can this only be done via the native side ONLY or am I missing something in the way limitLine is used.

**Comment by wuxudong** [comment]
you can find limit line usage in example->CandleStickChart

**Comment by fernandessteve** [comment]
Thanks. I tried applying using the limitLine in the CandeStick chart but had no luck. Here is what I tried in the JSX:-
`<LineChart  style={styles.chartM} data={this.getWeekData(false)} description={"Week Wise"} 
                  visibleXRange={[0,30]}
                  maxVisibleValueCount={50} 
                  xAxis={{drawGridLines:false, gridLineWidth:1, position:"BOTTOM", spaceBetweenLabels:0, labelRotationAngle:-30.0, limitLines:[{ limit: 115, lineColor: processColor('red'), lineWidth: 2}]}}
                  yAxisRight={{enable:false}} 
                  yAxis={{startAtZero:false,drawGridLines:false,position:"INSIDE_CHART"}}
                  drawGridBackground={true}
                  backgroundColor={"#f2f2f2"} 
                  legend={{enable:true, position:'ABOVE_CHART_RIGHT', direction:"LEFT_TO_RIGHT"}}
                  gridBackgroundColor={"#f2f2f2"} 
                  scaleEnabled={false}/>`

The below screenshot shows the data on screen. The limitLine was expected to appear at 115, but somehow does not appear even after the limitLine props have been set.
![test_data_2](https://user-images.githubusercontent.com/29043789/27273998-1f9939d6-54ef-11e7-806c-f97c415e3de9.png)

**Comment by andy08691** [comment]
you should put the limit line in yAxis
I did it worked, you can try it 

yAxis={{right: {enabled: false} ,left:{textSize: width*0.03,limitLines:limitArray,axisMaximum:axisMaximum*1.15,axisMinimum:axisMinimum*0.85}}}

**Comment by platonish** [comment]
Is there a way to have dashed limit lines? Similar to the property `GridDashedLine: {lineLength :10, spaceLength: 10}` ?

**Comment by platonish** [comment]
here's what I've tried so far: 
```javascript
limitLines: [
  {
  	limit: 300, 
  	lineColor: processColor('white'), 
  	label:'300', 
  	valueTextColor: processColor('white'), 
  	labelPosition:'LEFT_TOP', 
  	lineDashLengths: [1, 2]
  }
]
```

**Comment by wuxudong** [comment]
dash is supported, don't forget lineDashPhase.

    // limit lines
    limitLines: PropTypes.arrayOf(
      PropTypes.shape({
        limit: PropTypes.number.isRequired,
        label: PropTypes.string,
        lineColor: PropTypes.number,
        lineWidth: PropTypes.number,
        valueTextColor: PropTypes.number,
        valueFont: PropTypes.number,
        labelPosition: PropTypes.string,
        lineDashPhase: PropTypes.number,
        lineDashLengths: PropTypes.arrayOf(PropTypes.number)
      })
    ),
