### ISSUE TITLE
remove values from Yaxis right side 

### ISSUE THREAD

**Issue by prasan2421** [wuxudong/react-native-charts-wrapper#681]
How do we remove the values from right side of yaxis?
![Screenshot_20200304-170001](https://user-images.githubusercontent.com/17663028/75874805-9a6a6700-5e3a-11ea-94f6-26692f096882.png)

My code:

<BarChart
                        style={styles.chart}
                        data={this.state.data}
                        xAxis={this.state.xAxis}
                        yAxis={{
                            left: { enable: true},
                            right: { enable: false},
                        }}
                        // scaleYEnabled: {{ left: YAksis, right: YAksis }}
                        animation={{durationX: 2000}}
                        legend={this.state.legend}
                        gridBackgroundColor={processColor('#ffffff')}
                        visibleRange={{x: { min: 5, max: 5 }}}
                        drawBarShadow={false}
                        drawValueAboveBar={true}
                        drawHighlightArrow={true}
                        onSelect={this.handleSelect.bind(this)}
                        highlights={this.state.highlights}
                        onChange={(event) => console.log(event.nativeEvent)}
                    />

On enable false it still does not work.

**Comment by prasan2421** [comment]
solved

**Comment by blessedcrown** [comment]
can you tell me how you solved that issue? I am having same problem

**Comment by RohanKhedekar21** [comment]
how do you solve

**Comment by Arun-paramasivam** [comment]
For anyone looking here the solution is:
yAxis={{
left: { enabled: true}, //=> enabled is the key not enable
right: { enabled: false},
}}

**Comment by christopher-18** [comment]
@Arun-paramasivam worked for me

**Comment by 2001vishnu** [comment]
worked for me
