### ISSUE TITLE
How can I set a range on the chart

### ISSUE THREAD

**Issue by eyes487** [wuxudong/react-native-charts-wrapper#682]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
@wuxudong 
Expect to be like this picture

![图片](http://fs.eyes487.top:9999/uploads/1583481117626-charts-Wrapper-issue.png)
### Actual Behavior

I implement such a picture through the following code

![图片2](http://fs.eyes487.top:9999/uploads/1583481348591-charts-Wrapper-issue2.png)
### Data and config
xAxis={{
                position: 'BOTTOM',
                valueFormatter: xData,
                granularityEnabled: true,
                drawGridLines: false,
                drawAxisLine: false,
                textSize: 13,
                axisLineColor: chartLineColor,
                axisLineWidth: 1.5,
                centerAxisLabels: false,
                limitLines: [
                    {
                        limit: 3, 
                        lineColor: processColor('#8AC630'), 
                        label:'国际区间', 
                        valueTextColor: processColor('#8AC630'), 
                        valueFont: 13,
                    },
                    {
                        limit: 4, 
                        lineColor: processColor('#8AC630'), 
                        valueTextColor: processColor('#48A7FF'), 
                    }
                  ]
            }}   
### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wuxudong** [comment]
limitLines?
