### ISSUE TITLE
如何自定义Y轴坐标数据

### ISSUE THREAD

**Issue by Fengweiyuu** [wuxudong/react-native-charts-wrapper#683]
**Y轴坐标数据是+-0.00%的格式，我如果设置 valueFormatter: 'percent', Y轴显示百分之整数，设置 valueFormatter: '0.00%', 负数的时候也显示正的，请问这个要怎么设置呢？**

### Specifications

  - Version:  react-native 0.61.5  chart version 0.5.7
  - Platform: iOS
  - Subsystem:

**Comment by Fengweiyuu** [comment]
![image](https://user-images.githubusercontent.com/11786678/76302296-abafe980-62fa-11ea-9ea7-3f75d933b40e.png)

**Comment by Fengweiyuu** [comment]
const leftAxis: yAxis = {
      enabled: true,
      position: "OUTSIDE_CHART",
      axisLineColor: processColor(colors.transparent),
      textColor: processColor('#333333'),
      textSize: fontSizes.f12,
      valueFormatter: '0.00%',
      labelCount: 5,
      labelCountForce: true,
      gridColor: processColor('#e5e5e5'),
      gridDashedLine: {
        lineLength: 2,
        spaceLength: 2
      },
    }

**Comment by wuxudong** [comment]
Try valueFormatter: "0.0%;-0.0%"
