### ISSUE TITLE
Can not compile with Xcode 11

### ISSUE THREAD

**Issue by 15110011** [wuxudong/react-native-charts-wrapper#689]
I have installed and setup like your docs guide. Then I run it with react-native run-ios and it works well, but when I open project with xcode it can not compile 
I have tried to run a demo but it still got same problem
![image](https://user-images.githubusercontent.com/37216098/78319800-21be0e00-7592-11ea-987d-d3ed198639ef.png)
###
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-charts-wrapper": "^0.5.7",
"@babel/runtime": "^7.9.2",

**Comment by amirmcs** [comment]
I got the same error . I am changed the Generail->Deployment Info->Target to 11 worked. It was failing on 9.0
