### ISSUE TITLE
Hide legends

### ISSUE THREAD

**Issue by amirmcs** [wuxudong/react-native-charts-wrapper#691]
Is there a way to hide the bottom legend bar.

<img width="324" alt="Screen Shot 2020-04-07 at 10 58 32 PM" src="https://user-images.githubusercontent.com/49243041/78740019-96db6b80-7923-11ea-9be3-111d36cbd2df.png">

**Comment by salmanitb** [comment]
state={
legend:{
enabled:false
}
}
<PieChart legend={this.state.legend} />
