### ISSUE TITLE
How can I select data from content or table to highlight pie chart

### ISSUE THREAD

**Issue by wasitajeew** [wuxudong/react-native-charts-wrapper#694]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior

How can I select data from content or table to highlight pie chart
I would like to click on the data table to make the chart highlight like select the chart. 
And I have some issue about the overlab label 
<img width="319" alt="Screen Shot 2563-04-10 at 11 36 29" src="https://user-images.githubusercontent.com/17397575/78962824-8859a380-7b1f-11ea-9c01-fc949daaff61.png">
How can I lock the position for the label

### Specifications

  - Version: RN 0.61
  - Platform: both iOS and android
  - Subsystem:

**Comment by wasitajeew** [comment]
The chart highlight was fixed but the over lab label not yet. Do anyone have an idea about this.

**Comment by salmanitb** [comment]
i think u can use posisition absolute..
i have same problem with u..
but i change  label in piechart

**Comment by wuxudong** [comment]
Maybe this will help: https://github.com/huzipiaopiao/MPAndroidChartFix
