### ISSUE TITLE
Android Build fails: "cannot resolve symbol 'chart'"

### ISSUE THREAD

**Issue by 814k31** [wuxudong/react-native-charts-wrapper#698]
https://github.com/wuxudong/react-native-charts-wrapper/blob/9bde6804bffdb6ab5e16a8c65e4603b35a151f8b/android/src/main/java/com/github/wuxudong/rncharts/charts/ChartBaseManager.java#L332

**Comment by 814k31** [comment]
Looks like it was supposed to have been deleted
https://github.com/wuxudong/react-native-charts-wrapper/commit/3ece8e5e8b068cf74fd7630d0b0258a1aee09c49#diff-e9866a2df1aee2769db57dc4b7ac378fL292

**Comment by wuxudong** [comment]
Fixed
