### ISSUE TITLE
Combined Chart Data - lineData overlap barData

### ISSUE THREAD

**Issue by reberthkss** [wuxudong/react-native-charts-wrapper#699]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior

Select bar on click

### Actual Behavior

Select line if i click in the bar below the line.
### Screenshots
![issue1](https://user-images.githubusercontent.com/54030471/80108929-4420c700-8553-11ea-984f-312c38295756.png)
![issue2](https://user-images.githubusercontent.com/54030471/80108931-44b95d80-8553-11ea-928c-7830c9a6eb9e.png)

### Data and config
"react-native-charts-wrapper": "^0.5.7",

### Steps to Reproduce the Problem
Geral: 
> data: {
            barData: getBarData(),
            lineData: getLineData(),
        },
        legend: { enabled: false },
        marker: {
            enabled: true,
            markerColor: processColor(colors.markerBackground),
            textColor: processColor(colors.white),
            textSize: 16,
        },
        animation: { durationX: 2000 },
        gridBackgroundColor: processColor('#ffffff'),
        autoScaleMinMaxEnabled: false,
        touchEnabled: true,
        dragEnabled: true,
        scaleXEnabled: true,
        scaleYEnabled: false,
        pinchZoom: true,
        doubleTapToZoomEnabled: true,
        dragDecelerationEnabled: false,
        keepPositionOnRotation: false,
        zoom: getZoomPropsFromChartProps(),
        chartDescription: { text: "" },
        xAxis: {
            drawLabels: true,
            position: 'BOTTOM',
            granularityEnabled: true,
            granularity: 1,
            valueFormatter: getValueFormatter(),
            valueFormatterPattern: getValueFormatterPattern(),
            drawGridLines: false,
            textSize: 16,
            textColor: processColor(colors.gray54),
            labelRotationAngle: getDirectionLabelRotationAngle(),
        },
        yAxis: {
            right: {
                enabled: false,
                axisMinimum: getYAxisValue('min'),
                axisMaximum: getYAxisValue('max'),
            },
            left: {
                drawAxisLines: false,
                textSize: 16,
                axisMinimum: getYAxisValue('min'),
                axisMaximum: getYAxisValue('max'),
                textColor: processColor(colors.gray54),
            },
        }
    };

getLineData()
>values: [
                { x: index + 1,
                    y: 30,
                    marker: "",
                },
],
        label,
        config: {
            lineWidth: 4,
            color: processColor('#fff'),
            drawCircles: false,
            drawValues: false,
        }

### Specifications

  - Version: 0.5.7
  - Platform: Samsung Gran Prime Duos G531H
  - Subsystem: Android lollipop

**Comment by chipcop106** [comment]
Use drawOrder option for set chart index. Ex: drawOrder={["BAR", "LINE"]}
