### ISSUE TITLE
PieChart Percentage text too crowded

### ISSUE THREAD

**Issue by 1097616819** [wuxudong/react-native-charts-wrapper#702]
![3CB6134A1A669FBB05602FC25EC73790](https://user-images.githubusercontent.com/20593617/81371718-2b0b3f00-912b-11ea-8636-acf98b83c4f7.png)
 How to solve the problem of too crowded text?

     const data: PieData = {
    dataSets: [{
      values: generatePieValues(),
      label: '',
      config: {
        colors: (assetAccounts.length > 0 || debtAccouts.length > 0) ? getConfigColors().map(val      => processColor(val)) : [processColor(colors.background)],
        valueTextSize: 9,
        valueTextColor: processColor(colors.title),
        sliceSpace: 1,
        selectionShift: 15,
        valueFormatter: "#.##'%'",
        valueLineColor: processColor(colors.primary),
        valueLinePart1Length: 0.2,
        valueLinePart2Length: 0.2,
        valueLineWidth: 1,
        valueLinePart1OffsetPercentage: 50,
        valueLineVariableLength: false,
        drawValues: (assetAccounts.length > 0 || debtAccouts.length > 0),
        xValuePosition: 'OUTSIDE_SLICE',
        yValuePosition: 'OUTSIDE_SLICE',
        visible:true
      }
     }]
   }

       <PieChart
          style={styles.chart}
          logEnabled={false}
          chartBackgroundColor={processColor(colors.transparent)}
          chartDescription={description}
          data={data}
          legend={legend}
          entryLabelColor={processColor(colors.content)}
          entryLabelTextSize={9}
          drawEntryLabels={(assetAccounts.length > 0 || debtAccouts.length > 0) }
          rotationEnabled={false}
          rotationAngle={30}
          usePercentValues={true}
          styledCenterText={{}}
          centerTextRadiusPercent={100}
          holeRadius={70}
          holeColor={processColor(colors.transparent)}
          transparentCircleRadius={50}
          transparentCircleColor={processColor(colors.transparent)}
          maxAngle={360}
          animation={{ durationY: 1200 }}
        />

### Specifications

  - Version: "react-native-charts-wrapper": "0.5.7", "react-native": "0.61.5",
  - Platform: android ios
  - Subsystem:

**Comment by wuxudong** [comment]
No solution. Check https://github.com/PhilJay/MPAndroidChart/issues/3233
