### ISSUE TITLE
Example/HorizontalBarChartScreen.js  drawValueAboveBar={true} not work

### ISSUE THREAD

**Issue by k2easy** [wuxudong/react-native-charts-wrapper#71]

**Comment by wuxudong** [comment]
Actually, it is a issue of MpAndroidChart, you can find it here [link](https://github.com/PhilJay/MPAndroidChart/issues/1280)

As a workround, you can add a data entry which y values is 0, or set yAxis: {left:{axisMinimum: 0}}

you can find it in updated HorizontalBarChartScren Example.
