### ISSUE TITLE
can not scroll in horizontal bar chart 

### ISSUE THREAD

**Issue by benduongquang** [wuxudong/react-native-charts-wrapper#713]
I'm tried to put into scroll view but It not avaible.

```
class HorizontalBarChartScreen extends React.Component {
  constructor() {
    super();

    this.state = {
      legend: {
        enabled: true,
        textSize: 12,
        form: 'SQUARE',
        formSize: 10,
        xEntrySpace: 1,
        yEntrySpace: 1,
        formToTextSpace: 1,
        wordWrapEnabled: true,
        maxSizePercent: 0.5,
      },

      data: {
        dataSets: [{
          values: [5, 40, 77, 81, 43],
          label: 'Company A',
          config: {
            drawValues: false,
            colors: [processColor('red')],
          }
        }, {
          values: [40, 5, 50, 23, 79],
          label: 'Company B',
          config: {
            drawValues: false,
            colors: [processColor('blue')],
          }
        }, {
          values: [10, 55, 35, 90, 82],
          label: 'Company C',
          config: {
            drawValues: false,
            colors: [processColor('green')],
          }
        }],
        config: {
          barWidth: 0.2,
          group: {
            fromX: 0,
            groupSpace: 0.1,
            barSpace: 0.1,
          },
        }
      },
      xAxis: {
        valueFormatter: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
        position: 'BOTTOM',
        granularityEnabled: true,
        granularity: 1,
        labelCount: 10,
      },
      yAxis: { left: { axisMinimum: 0 } }
    };
  }

  handleSelect(event) {
    const entry = event.nativeEvent;
    if (entry == null) {
      this.setState({ ...this.state, selectedEntry: null });
    } else {
      this.setState({ ...this.state, selectedEntry: JSON.stringify(entry) });
    }

    console.log(event.nativeEvent);
  }


  render() {
    return (
      <ScrollView style={styles.container}>
        <HorizontalBarChart
          style={styles.chart}
          data={this.state.data}
          xAxis={this.state.xAxis}
          yAxis={this.state.yAxis}
          animation={{ durationX: 2000 }}
          legend={this.state.legend}
          gridBackgroundColor={processColor('#ffffff')}
          drawBarShadow={false}
          drawValueAboveBar
          drawHighlightArrow
          onSelect={this.handleSelect.bind(this)}
          onChange={(event) => console.log(event.nativeEvent)}
        />
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF'
  },
  chart: {
    flex: 1
  }
});

export default HorizontalBarChartScreen;

```

**Comment by benduongquang** [comment]
Sorry is my bad, my simulator is out of Ram

**Comment by wuxudong** [comment]
try visibleRange = {{x: {min: 1, max: 5}}} ?

**Comment by anonewb** [comment]
> try visibleRange = {{x: {min: 1, max: 5}}} ?

I think we can close this issue. Thankyou!

**Comment by SharfMohiuddin** [comment]
Hi there! I'm using visibleRange = {{x: {min: 1, max: 5}}} but the app crashes on IOS. Here is the Implementation :

    <BarChart
                  visibleRange={{ x: { min: 1, max: 5 } }}
                  legend={{
                    textColor: processColor(Colors.BLACK),
                    enabled: true,

                    horizontalAlignment: "RIGHT",
                    verticalAlignment: "TOP",
                    form: "CIRCLE",
                    formSize:
                      Platform.OS == "android" ? normalize(11) : normalize(9),
                    textSize:
                      Platform.OS == "android" ? normalize(12) : normalize(8),
                  }}
                  xAxis={{
                    drawGridLines: false,
                    textColor: processColor(Colors.BLACK),
                    enabled: true,
                    position: "BOTTOM",
                    textSize: 10,
                    labelCount: samStrikers.length,
                    valueFormatter: samStrikers,
                  }}
                  yAxis={{
                    right: { enabled: false },
                    left: {
                      textColor: processColor(Colors.BLACK),
                      axisMinimum: 0,
                      labelCount: 5,
                    },
                  }}
                  style={styles.chartPar}
                  animation={{ durationX: 280 }}
                  touchEnabled={true}
                  data={{
                    dataSets: [
                      {
                        label: "Tendency",

                        values: tendency,

                        config: {
                          barShadowColor: processColor("rgb(251, 185, 0)"),
                          drawValues: false,

                          color: processColor("rgb(251, 185, 0)"),
                          lineWidth: 2.4,
                          barWidth: 0.3,
                        },
                      },

                      {
                        label: "Timing",
                        values: timing,

                        config: {
                          barShadowColor: processColor("rgb(0, 105, 180)"),
                          drawValues: false,
                          color: processColor("rgb(0, 105, 180)"),
                          lineWidth: 2.4,
                        },
                      },
                      {
                        // Consistency
                        label: "Consitency",
                        values: consitency,

                        config: {
                          barShadowColor: processColor(Colors.PRIMARY_GREY),
                          drawValues: false,
                          color: processColor(Colors.PRIMARY_GREY),
                          lineWidth: 2.4,
                        },
                      },
                      {
                        // Overall
                        label: "Overall",

                        values: overall,

                        config: {
                          barShadowColor: processColor(Colors.PRIMARY_GREY),

                          color: processColor(Colors.PRIMARY_GREEN),
                          drawValues: false,
                          lineWidth: 2.4,
                        },
                      },
                    ],
                    config: {
                      // stackLabels: ["Par 3", "Par 4", "Par 5"],
                      drawValues: false,
                      barWidth: 0.13,
                      group: {
                        fromX: -0.5, // required
                        groupSpace: 0.25, // required
                        barSpace: 0.05, // required
                        lineWidth: 2.4,
                      },
                    },
                  }}
                />
