### ISSUE TITLE
The granularity is not working when use the Unix Timestamp

### ISSUE THREAD

**Issue by ibnukipa** [wuxudong/react-native-charts-wrapper#715]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
when the values is Unix Timestamp, be able to use granularity

### Actual Behavior
The granularity is not working when use Unix Timestamp

### Screenshots
![image](https://user-images.githubusercontent.com/12580174/83746033-ae677400-a688-11ea-8d32-b51f70822000.png)
![image2](https://user-images.githubusercontent.com/12580174/83746044-b1fafb00-a688-11ea-9f86-c31380e527fd.png)

### Data and config
![image3](https://user-images.githubusercontent.com/12580174/83746155-e66eb700-a688-11ea-8879-77c1f143db17.png)
![image4](https://user-images.githubusercontent.com/12580174/83746149-e2db3000-a688-11ea-8d86-39cd4ad6e871.png)

### Steps to Reproduce the Problem
![image5](https://user-images.githubusercontent.com/12580174/83746230-01412b80-a689-11ea-9ccc-6a6e8848d10a.png)

### Specifications
  - Version: latest
  - Platform: both
  - Subsystem: MacOS

**Comment by ibnukipa** [comment]
solved. the granularity value must be on unix timestamp value either

**Comment by christopher-18** [comment]
@ibnukipa  I have put my x value in unix timestamp value. But when i trying to display the same on graph the x axis , 
- does not show any timestamp values. 
- need to show x values in the date format 'dd mm'.How to do it? 
More info on this.
https://github.com/wuxudong/react-native-charts-wrapper/issues/908
