### ISSUE TITLE
Android enum to iOS enum parsing fails

### ISSUE THREAD

**Issue by mantas-janulionis** [wuxudong/react-native-charts-wrapper#72]
For android enums that contain multiple words without underscore '_' this library fails to parse.
Please fix androidEnumToIOSEnum function in /ios/ReactNativeCharts/utils/BridgeUtils.swift

**Comment by wuxudong** [comment]
Which enum? can you provide the detail name?

**Comment by mantas-janulionis** [comment]
For example if i set 
`animation={{durationX:1000,easingX:'EaseOutQuad' }}`
it doesn't work uses linear animation on iOS. However by looking at code I found a workaround
`animation={{durationX:1000,easingX:Platform.OS==='ios'?'Ease_Out_Quad':'EaseOutQuad'}}`

The problem is that androidEnumToIOSEnum returns lowercase string and 'EaseOutQuad' becomes 'easeoutquad' whereas only first letter should be made lowecase. Which causes it not passing any switch statement when parsing android easing values

**Comment by wuxudong** [comment]
That is a problem. 
In most case, the enum in MpAndroidChart match the pattern XX_XX_XX, so I  follow the pattern without exception. but it is wrong..

**Comment by wuxudong** [comment]
It is fixed in new version
