### ISSUE TITLE
Error Android BarChart with null and just one object dataSets

### ISSUE THREAD

**Issue by dathuynh2797** [wuxudong/react-native-charts-wrapper#720]
``` javascript
My Config: data: {
        dataSets: [],
        config: {
          barWidth: 0.5,
          group: {
            fromX: 0,
            groupSpace: 0,
            barSpace: 0.1,
          },
        },
      },
      xAxis: {
        valueFormatter: [],
        granularityEnabled: true,
        granularity: 1,
        axisMaximum: 5,
        axisMinimum: 0,,
        position: 'BOTTOM',
      },
      marker: {
        enabled: true,
        markerColor: processColor('yellow'),
        textColor: processColor('#000'),
        markerFontSize: 14,
      },
}
```
#### With ios it work fine, but with android my app was crasked. I try not set dataSets for it and it was run. But with my data handle respone with one object, it's crack aigan. It's need 2 object of dataSets to not cracked. Sorry for my bad English.

![Simulator Screen Shot - iPhone 11 - 2020-06-12 at 17 36 14](https://user-images.githubusercontent.com/56946949/84494596-024f0a00-acd4-11ea-80fb-0a787fc756e7.png)
![Screenshot_1591958122](https://user-images.githubusercontent.com/56946949/84494608-05e29100-acd4-11ea-8fa2-8c472b272aa1.png)

  - Version: React Naitve v0.61.5
  - Platform: MacOS

**Comment by wuxudong** [comment]
At least 2 barDataSets to allow grouping. 
If you have only one dataset, remove the `group` setting.
