### ISSUE TITLE
how to show marker latest data use line chart ?

### ISSUE THREAD

**Issue by otikindriyana** [wuxudong/react-native-charts-wrapper#722]
### Expected Behavior
When first launch automatically show marker latest data on right side

### Actual Behavior
not showed, showed if click 

### Screenshots
https://bit.ly/2Ydtksd

### Specifications
  - Version: react-native-charts-wrapper : 0.5.7
  - Platform: react-native: 0.61.5

**Comment by wuxudong** [comment]
use default highlights. Check the demo in Example->BarChartScreen, it highlights two bars by default.

highlights: [{x: 3}, {x: 6}],

**Comment by otikindriyana** [comment]
@wuxudong 
if values x is unixdate,like:
values: [{"x":1605051960000,"y":903560,"marker":"11-Nov-20: 903,560 IDR"},{"x":1605138360000,"y":913146,"marker":"12-Nov-20: 913,146 IDR"},{"x":1605224760000,"y":906083,"marker":"13-Nov-20: 906,083 IDR"},{"x":1605311160000,"y":908605,"marker":"14-Nov-20: 908,605 IDR"},{"x":1605397560000,"y":908605,"marker":"15-Nov-20: 908,605 IDR"},{"x":1605483960000,"y":908605,"marker":"16-Nov-20: 908,605 IDR"},{"x":1605570360000,"y":908605,"marker":"17-Nov-20: 908,605 IDR"}], label: 'A',

highlights: [{x: 3}] its not work,
how o solve highlights use unixdate ?
