### ISSUE TITLE
Use Custom React Native Component as Marker/Highlight and Legend. Or in general any way to customise Marker with Icons and other stuff.

### ISSUE THREAD

**Issue by aditya1711** [wuxudong/react-native-charts-wrapper#725]

**Comment by aditya1711** [comment]
@wuxudong can you please help or give directions on this?

**Comment by wuxudong** [comment]
Icons are already supported.

PropTypes.shape({
            x: PropTypes.number,
            y: PropTypes.number.isRequired,
            marker: PropTypes.string,
            icon: PropTypes.shape({
              bundle: PropTypes.object,
              width: PropTypes.number,
              height: PropTypes.number
            })
          })

**Comment by anniewey** [comment]
@wuxudong is this only supported in line chart? how to implement this on scatter chart?
