### ISSUE TITLE
how do i customize bar chart width.

### ISSUE THREAD

**Issue by vipinchauhan23** [wuxudong/react-native-charts-wrapper#73]
how do i customize bar chart width in combindChart as i use barWidth in config but doen't work for me.
like---

             barData: {
                $set: {
                  dataSets: [{
                    values: responseData.MarketingCalls,
                    label: 'Marketing Call Weekly - Current',
                    config: {
                      color: processColor('#00BFFE'),
                      barWidth: 20,    // giving barWidth but did't work
                      group: {
                        fromX: 20,
                        groupSpace: 10,
                        barSpace: 10
                      }
                      // barSpacePercent: 40,
                      // barWidth: 50,
                      // groupWidth: 90,
                      // barSpace: 3,
                      // groupSpace: 3,
                      // barShadowColor: processColor('lightgrey'),
                      // highlightAlpha: 90,
                      // highlightColor: processColor('red'),
                    }
                  }],
                }
              },

Please help me out.
thanks

**Comment by MayMayYang** [comment]
`dataSets: [{
          values: data,
          label: '各状态的合同个数',
          config: {
            color: processColor('teal'), //柱子默认显示颜色
            highlightEnabled: true, //柱子是否可点击
            valueTextSize: 12, //柱子上的文字大小
            valueTextColor: processColor('red'), //柱子上的文字颜色
            visible: true, //是否显示柱子
            valueFormatter: 'largeValue'
          }
        }],
        config: {
          barWidth: 0.5, //柱子宽度，不设置则按照宽度及柱子个数平分
        }`

**Comment by nicollasmatheus** [comment]
still not working for me
