### ISSUE TITLE
how to remove space black bottom chart

### ISSUE THREAD

**Issue by phuocantd** [wuxudong/react-native-charts-wrapper#736]
Hi **@wuxudong,** I want to remove space blank bottom chart when value data set have 0, I hope min value yAxis = 0 when have value ~0

![Screen Shot 2020-08-03 at 12 03 21](https://user-images.githubusercontent.com/31690470/89148143-2ff15a80-d583-11ea-8d70-72393f47d798.png)

### Specifications

  - Version: "react-native-charts-wrapper": "^0.5.7",
  - Platform: react-native ^0.60.6

**Comment by Gajendra-NL** [comment]
Hey @phuocantd, were you able to remove this?

**Comment by phuocantd** [comment]
> Hey @phuocantd, were you able to remove this?

@Gajendra-NL Yes, I have found a solution

**Comment by Gajendra-NL** [comment]
How did you do? It will help me. I am also trying to do get rid of the space

**Comment by phuocantd** [comment]
@Gajendra-NL I try props
 yAxis={{
left: {
axisMinimum: 0,
},
right: {
axisMinimum: 0,
},
}}
