### ISSUE TITLE
how to style gradient in barchart

### ISSUE THREAD

**Issue by phuocantd** [wuxudong/react-native-charts-wrapper#737]
Hello @wuxudong, I want to display barchart style gradient like image bellow? Have package support?

![image](https://user-images.githubusercontent.com/31690470/89159725-17d90580-d59a-11ea-8517-faa4520b4da1.png)

### Specifications

  - Version:  "react-native-charts-wrapper": "^0.5.7",
  - Platform: "react-native": "^0.60.6"

**Comment by wuxudong** [comment]
FillGradient only supports line and radar data.
