### ISSUE TITLE
关于 ios pod install 时 拉取git版本的问题

### ISSUE THREAD

**Issue by pausermake** [wuxudong/react-native-charts-wrapper#738]
在 react-native 安装库后
mac 下使用 pod install
会出现资源无法找到的问题
原因是因为 RNCharts.podspec 文件中
  s.source       = { :git => "https://github.com/wuxudong/react-native-charts-wrapper.git", :tag => "#{s.version}" }

这里的 tag=>是 直接获取的package.json中的版本（package.json中的版本号是0.5.7），但是实际的git资源是  v0.5.7

所以这里会造成无法找到git资源。

在库未修正之前临时解决可以修改这个文件为
  s.source       = { :git => "https://github.com/wuxudong/react-native-charts-wrapper.git", :tag => "v#{s.version}" }

**Comment by wuxudong** [comment]
新版本已简化set up
