### ISSUE TITLE
react-native-charts-wrapper\android\src\main\java\com\github\wuxudong\rncharts\charts\ChartBaseManager.java:332

### ISSUE THREAD

**Issue by passats** [wuxudong/react-native-charts-wrapper#740]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Steps to Reproduce the Problem

Example run error.

react-native-charts-wrapper\android\src\main\java\com\github\wuxudong\rncharts\charts\ChartBaseManager.java:332:

chart.setMarker(marker);

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by wuxudong** [comment]
Fixed
