### ISSUE TITLE
How to change gridLineColor in BarChart?

### ISSUE THREAD

**Issue by JungDonggun** [wuxudong/react-native-charts-wrapper#751]
I want to change a gridLine Color 
![KakaoTalk_Photo_2020-09-27-19-10-44](https://user-images.githubusercontent.com/48436555/94362412-12112380-00f6-11eb-90f2-07fe0500bd40.jpeg)

**Comment by wuxudong** [comment]
Take a try of `gridColor`? Check js under lib.
