### ISSUE TITLE
How to place labels outside PieChart?

### ISSUE THREAD

**Issue by rrzhang139** [wuxudong/react-native-charts-wrapper#756]
In Android, how to set thee labels outside of a pie chart with a line pointing to its category? xValuePosition and yValuePosition are for other charts, but is there something like this in pie chart? Thanks!

**Comment by raajnadar** [comment]
+1 even I need something like this

**Comment by nolife08021** [comment]
try this

xValuePosition: "OUTSIDE_SLICE",
yValuePosition: "OUTSIDE_SLICE",
