### ISSUE TITLE
Padding on candlestick chart

### ISSUE THREAD

**Issue by erfinbadrian** [wuxudong/react-native-charts-wrapper#766]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Expected Behavior
I dont know how to adding padding on that area. been looking on documentation but not found any. Help me do this.

### Screenshots
- <img width="420" alt="image" src="https://user-images.githubusercontent.com/70316635/99883389-bbd5e200-2c59-11eb-87fc-163e2b0ee6ba.png">
### Specifications

  - Version: 0.5.7
  - Platform: Ios
  - Subsystem: Mac

**Comment by nathanguigui** [comment]
@erfinbadrian did you find a solution ? 
On android it can be achieved by adding candle with same close value.
This solution does not work properly on iOS for me because it add a blue line for me

**Comment by erfinbadrian** [comment]
@nathanguigui am adding more x to chart to make some padding on right. Hope this helps.
