### ISSUE TITLE
how to hide circle on android

### ISSUE THREAD

**Issue by Liqiankun** [wuxudong/react-native-charts-wrapper#768]
![截屏2020-11-26 15 27 59](https://user-images.githubusercontent.com/11532418/100320509-36a55100-2ffc-11eb-9ac9-b59922005a8c.png)

```js
config: {
        lineWidth: 2,
        drawCircleHole: false,
        drawCircles: false,
        circleRadius: 0,
        drawValues: false,
        valueTextSize: 10,
        color: processColor('#5ea29b')
      }
```
### Specifications

  - Version: ^0.5.7
  - Platform: android

**Comment by Liqiankun** [comment]
@wuxudong Could you give me a hand?

**Comment by alz10** [comment]
Can you try `color: processColor('transparent')`?

**Comment by Liqiankun** [comment]
@alz10 It works. Thanks.
