### ISSUE TITLE
How to make a point data locate at itSelf location? Detail below.

### ISSUE THREAD

**Issue by hanweixing** [wuxudong/react-native-charts-wrapper#77]
When we give a chart a dataSet, the dataSet format is like below:
`componentDidMount() {
        this.setState(
            update(this.state, {
                data: {
                    $set: {
                        dataSets:
                        [{
                         values: [{y: 100}, {y: 110}, {y: 105}, {y: 115}],
                         label: 'Company X', ........`

Look at the values parameter, it just contains y coordination value, and it adjusts the xAxis array in below:
` <LineChart
                    style={styles.chart}
                    data={this.state.data}
                    description={{text: ''}}
                    legend={this.state.legend}
                    marker={this.state.marker}
                    xAxis={["x1", "x2", "x3", "x4"]}
                    drawGridBackground={false}
                    borderColor={processColor('teal')}
                    borderWidth={1}
                    drawBorders={true} ........`
It means x1 to y:100, x2 to y: 110, x3 to y:105, x4 to y: 115.
If `values: [{y: 100}, {y: 105}, {y: 115}]`,   `xAxis={["x1", "x2", "x3", "x4"]`, because the length of values reduce, how values adjust to xAxis ?

I try below
`values: [{x: "x1", y: 100}, {x: "x3", y: 105}, {x: "x4": y: 115}]`,   `xAxis={["x1", "x2", "x3", "x4"]`

but the chart behaves wrongly, and the chart will make {x: "x3", y: "105"} to "x2".

Please help to give an answer. Thanks

**Comment by wuxudong** [comment]
[{y: 100}, {y: 105}, {y: 115}], xAxis={["x1", "x2", "x3", "x4"] will display blank at x4.

if you want blank at x2, you can use null at x2.

**Comment by hanweixing** [comment]
Thank you very much

**Comment by hanweixing** [comment]
@wuxudong Thank you very much
