### ISSUE TITLE
valueFormatter date and timeUnit seconds, issue with valueFormatterPattern and hours (hh)

### ISSUE THREAD

**Issue by ferrannp** [wuxudong/react-native-charts-wrapper#775]
I basically have in `yAxis`:

```js
valueFormatter: 'date',
valueFormatterPattern: 'hh:mm:ss',
timeUnit: 'SECONDS',
```

If my value is 80 seconds  (1 min and 20s) I expect to get `00:01:20` instead I get `01:01:20`. I never get 0 hours. Am I doing something wrong?

And actually if I have 3600 seconds (1 hour) it shows `02:00:00` instead of `01:00:00` so... Why is the hour starting in 1 not 0?

I am actually trying to format it as `duration` no so maybe using `date` won't work? But I see that array of string in `valueFormatter` is not working for `yAxis` ?

**Comment by alesharik** [comment]
According to SimpleDateFormat doc, `h` is `hour in am/pm (1-12)`. You can use `H` for `hour in day (0-23)` or `K` for `Hour in am/pm (0-11) `
