### ISSUE TITLE
How to remove number coma

### ISSUE THREAD

**Issue by kabitacode** [wuxudong/react-native-charts-wrapper#777]
![photo_2020-12-22_10-36-33](https://user-images.githubusercontent.com/30437682/102846073-a8c55600-4441-11eb-9111-dd6e947ccae1.jpg)

i am using in the dataset.
I want to remove the coma at number 8. originally 8.00 to 8 only. how to solve it? 

Thank's you.

**Comment by wuxudong** [comment]
valueFormatter
