### ISSUE TITLE
I want to use LineChart as Gantt chart

### ISSUE THREAD

**Issue by abdulkhaliquem9** [wuxudong/react-native-charts-wrapper#78]
Is there any way to customize yAxis such that it will have string labels instead of default numeric values.
condition1  |--------        --------------------    -------
condition2  |--------------------------                                                         ---------------------
condition3  |                    --------------                 ----------------
                    __________________________________________________________________________________________
                    20Jun   21Jun    22Jun    23Jun                                                                               30Jun
can u please let me know how to customize yAxis.

and How can I disable the scale showing values in RadarChart. where can I find documentation for each component used in every graph such that it has customized values, and can be hide and show on the graph.
please help me.

**Comment by wuxudong** [comment]
Maybe you can try HorizontalBar.

Sorry, no doc for this repo.   
You can find all the customized values in lib/xxx,  
and you can find most of the use case in the Example.

**Comment by abdulkhaliquem9** [comment]
Can I break the bars in HorizontalBar, because the bar has to be drawn over the dates. so for few days it will be visible and for few days it will be hidden. Is this possible.
