### ISSUE TITLE
How to make YAxis starts from zero in LineChart 

### ISSUE THREAD

**Issue by marwakhalil** [wuxudong/react-native-charts-wrapper#79]
Hello, 
First of all thanks for this amazing library, I am using LineChart and i am generating data between 15-30 but the YAxis is auto scaled to start from 15 i put the  autoScaleMinMaxEnabled value to {false} but still starting from 15, what should i do ;
My code looks something like this 
`yAxis: {
        $set: {
          valueFormatter: y,
          granularityEnabled: true,
          granularity: 1,
          axisMaximum: 30,
          axisMinimum: 0,
          labelCount: 30,
          labelCountForce: true,
          zeroLine: {
            enabled: true,
          },
        },
      },
//************
 <LineChart
          style={styles.chart}
          data={this.state.data}
          legend={this.state.legend}
          xAxis={this.state.xAxis}
          yAxis={this.state.yAxis}
          borderColor={processColor('#136ca8')}
          autoScaleMinMaxEnabled={false}
          chartDescription={{ text: '' }}
          borderWidth={1}
          drawBorders
          touchEnabled
          dragEnabled
          scaleEnabled
          scaleXEnabled
          scaleYEnabled
          pinchZoom
          doubleTapToZoomEnabled
          dragDecelerationEnabled
          dragDecelerationFrictionCoef={0.99}
          keepPositionOnRotation={false}
          onSelect={this.handleSelect.bind(this)}
        />
`

**Comment by wuxudong** [comment]
what about 
    axisMinimum: 0,
 
in yAxis config

**Comment by marwakhalil** [comment]
`yAxis: {
        $set: {
          axisMinimum: 0,
        },
      },`


Hi, this is not changing anything in the graph 
![19859097_1773308029360942_810556033_o](https://user-images.githubusercontent.com/15096458/28057319-fe395770-661f-11e7-986a-3d079d347269.png)

**Comment by ramki1979** [comment]
You can try with this
```javascript
yAxis: {
    left: {
        axisMinimum: 0,
        axisMaximum: 30,
        labelCount: 7, // 0 5 10 15 20 25 30
        labelCountForce: true,
       granularity: 5,
       granularityEnabled: true,
    },
    right: {
        axisMinimum: 0,
        axisMaximum: 30,
        labelCount: 7, // 0 5 10 15 20 25 30
        labelCountForce: true,
        granularity: 5,
        granularityEnabled: true,
    }
},
```

**Comment by aaqibkhan658** [comment]
use fromZero

**Comment by zi6xuan** [comment]
> 你可以试试这个
> 
> ```js
> yAxis：{ 
>     left：{ 
>         axisMinimum：0 ，
>         axisMaximum：30 ，
>         labelCount：7 ， //0 5 10 15 20 25 30 
>         labelCountForce：true ，
>         粒度：5 ，
>         particleityEnabled：true ，
>     } ，
>     right：{ 
>         axisMinimum：0 ，
>         axisMaximum：30 , 
>         labelCount : 7 ,  // 0 5 10 15 20 25 30
>         labelCountForce：真，
>         粒度：5 ，
>         粒度启用：真，
>     } 
> } ，
> ```

I found that this setting is completely ignored in blend mode
