### ISSUE TITLE
first and last graph just show half in <Combined /> when include  `CandleChat`

### ISSUE THREAD

**Issue by uinz** [wuxudong/react-native-charts-wrapper#80]
![image](https://user-images.githubusercontent.com/12208108/28002927-f98fd32a-656b-11e7-9cdb-95f1715b5f41.png)

both in iOS and Android

**Comment by wuxudong** [comment]
Maybe you can try different xAxis:

        axisMaximum: 5,
        axisMinimum: 0,
        centerAxisLabels: true

**Comment by wuxudong** [comment]
and There is 

	export const xAxisIface = {
	  ...axisIface,

	  labelRotationAngle: PropTypes.number,
	  avoidFirstLastClipping: PropTypes.bool,
	  position: PropTypes.string,
	};

**Comment by uinz** [comment]
I tried `avoidFirstLastClipping: true`  &
```js
axisMaximum: 5,
axisMinimum: 0,
centerAxisLabels: true
```
but not works, I found that `Example` also has the problem.

Many thanks.

**Comment by jackmew** [comment]
+1

**Comment by darshan-raj** [comment]
I'm facing the same issue for Combined chart containing a stacked chart. Any solution for this?

**Comment by wuxudong** [comment]
I think it is related to [this](https://github.com/danielgindi/Charts/issues/3186)

you can add  axisMinimum &  axisMaximum as a workaround.

```
xAxis: {
        valueFormatter: ['1990', '1991', '1992', '1993', '1994'],
        granularityEnabled: true,
        granularity: 1,
        avoidFirstLastClipping: true,
        axisMinimum:-0.5,
        axisMaximum:4.5,
 },
```

**Comment by silvaalvaro** [comment]
Hi there.

I'm facing a collateral damage from this axisMinimum/axisMaximum dynamic.

Despite the bars being plotted right, xAxis labels does not behaves correctly beneath the first bar (only). There any trick that could help with it's position?

![screen shot 2018-10-23 at 11 46 55](https://user-images.githubusercontent.com/30345229/47369365-e25f7280-d6b9-11e8-977e-92fc6032a8a8.png)

The label "Seg" isn't centered like the other, being shown where the bar starts without axisMinimum/axisMaximum calculation.
