### ISSUE TITLE
Translate date to French in xAxis

### ISSUE THREAD

**Issue by altyx** [wuxudong/react-native-charts-wrapper#806]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**
I read them

### Expected Behavior
When i passed date for xAxis in a combinedChart I want them to be displayed like 01 Mai, 25 Fev. etc (In french)

### Actual Behavior
Actually, i didn't found any option to translate them, so they're displayed in english : 01 May

### Screenshots
![image](https://user-images.githubusercontent.com/5872427/118828087-3efc8b80-b8bd-11eb-8e1e-501d39d651b9.png)
### Data and config

data used : 
X is a date in milliseconds
`{y: 1 x: 1620568980000}`

`            xAxis={{
              valueFormatter: 'date',
              valueFormatterPattern: 'dd MMM',
              position: 'BOTTOM',
              granularity: 1,
              granularityEnabled: true,
            }}
`

### Specifications

  - Version: 0.5.7
  - Platform: android & iOS
  - Subsystem:

**Comment by philipp-kv** [comment]
I also would like to know if providing translation for date formatted labels is possible. Or maybe there is some workaround?
