### ISSUE TITLE
Remove default lines

### ISSUE THREAD

**Issue by kyangy** [wuxudong/react-native-charts-wrapper#817]
Any way to remove the default lines on the x and y axis? These lines don't seem to be coming from the xAxis and yAxis objects as I have drawAxisLines set to false. I don't see any prop on the chart level to remove lines.

<img width="348" alt="Screen Shot 2021-06-28 at 4 00 50 PM" src="https://user-images.githubusercontent.com/9537888/123713867-2ec7bc80-d82a-11eb-8561-7c9450672073.png">

**Comment by robert-go** [comment]
```
xAxis={{
     axisLineColor: processColor('transparent'),
}}
```
Use this as a workaround
It really a bug, I don't see any drawAxisLines in source code

**Comment by kyangy** [comment]
@robert-go Thank you!
