### ISSUE TITLE
problems about view

### ISSUE THREAD

**Issue by nemom0901** [wuxudong/react-native-charts-wrapper#82]
pic1 when open my project
http://imgur.com/a/RrXVF
pic2 after click
http://imgur.com/a/ULSIB

how can I do, when I open the project, it can show me pic2 without click
thank you

**Comment by wuxudong** [comment]
Can you paste your config?

**Comment by nemom0901** [comment]
What do you mean ? 
Is that : 
config: {
                lineWidth: 1,
                drawCubicIntensity: 0.4,
                circleRadius: 5,
                drawHighlightIndicators: false,
                color: processColor('blue'),
                drawFilled: true,
                fillColor: processColor('blue'),
                fillAlpha: 45,
                circleColor: processColor('blue')

**Comment by wuxudong** [comment]
More detail needed. If you have any question about it, please reopen it.
