### ISSUE TITLE
Invariant Violation: requireNativeComponent: “RNLineChart” was not found in the UIManager

### ISSUE THREAD

**Issue by ibrahimyolbir** [wuxudong/react-native-charts-wrapper#821]
Hello, After upgrading to React native 64.2 version, I am getting the error in the picture 

### Screenshots
![Simulator Screen Shot - iPhone 11 - 2021-07-29 at 10 27 01](https://user-images.githubusercontent.com/25623304/127459564-bf0961f6-6edd-4d73-8cd5-0a14b539f0bc.png)

 

### Steps to Reproduce the Problem
I tried following;
❯ reinstall the react-native-chart-wrapper package
❯ pod deintegrate && pod cache clean --all 
❯ pod install

Invariant Violation: requireNativeComponent: “RNLineChart” was not found in the UIManager

### Specifications

  - Version:      "react-native-charts-wrapper": "^0.5.7"
  - Platform: Both android and ios
  - Subsystem:
  
  
  

> ❯ react-native info
info Fetching system and libraries information...
(node:55086) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.27 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/ibrahimyolbir/.rvm/gems/ruby-2.7.1/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by NguyenDinhTrong99** [comment]
u setup with docs? in xcode

**Comment by ibrahimyolbir** [comment]
@NguyenDinhTrong99  actually this was already installed before. The problem was after upgrading to react native. I changed the Podfile file like this in the upgrade

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
target 'DGFonder' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
 
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'})
  post_install do |installer|
    react_native_post_install(installer)
  end
end
```
then I realized that 'RNcharts' is not loading automatically
   and added this **`pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'`** in podffile and the issue solved but this time i get following error


```

Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> 
(Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of 
Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> 
Swift.ContiguousArray<A.Element> in libCharts.a(ChartUtils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
