### ISSUE TITLE
Do you support left and right drag?

### ISSUE THREAD

**Issue by fmshmebaby** [wuxudong/react-native-charts-wrapper#823]
When there are many pieces of data, the x-axis cannot be displayed on one screen, and the user needs to drag left and right to display other data

### Specifications

  - "react-native": "0.64.1",
  - "react-native-charts-wrapper": "^0.5.7",
  - Platform: Android
  - Subsystem:

**Comment by wuxudong** [comment]
Check charts in examples.

**Comment by fmshmebaby** [comment]
您的邮件我已成功收到，谢谢！

**Comment by fmshmebaby** [comment]
您的邮件我已成功收到，谢谢！
