### ISSUE TITLE
Failed to resolve: com.github.PhilJay:MPAndroidChart:v3.1.0

### ISSUE THREAD

**Issue by shreyas1g** [wuxudong/react-native-charts-wrapper#827]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by shreyas1g** [comment]
aready added 

dependencies {

    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
} in the gradle module

and

repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

**Comment by ibnukipa** [comment]
Hey @shreyas1g , did you resolved it?

**Comment by wuxudong** [comment]
Try v0.5.8 , reopen the issue if the problem remains.
