### ISSUE TITLE
执行"npm install --save react-native-charts-wrapper"后，android项目报异常

### ISSUE THREAD

**Issue by jxr202** [wuxudong/react-native-charts-wrapper#83]
npm install --save react-native-charts-wrapper

执行上面的命令后，原项目中的node_modules\react-native\目录下的所有文件被会清空，导致android studio报异常。

异常信息:
Error:(75, 0) Could not read script 'F:\Github\YS_Service_JS\node_modules\react-native\react.gradle' as it does not exist.

如何解决？

**Comment by jxr202** [comment]
我按照如下命令执行，一样会删除一些node_modules下的一些文件，有图有真相。

step:

react-native init ForBeginner
cd ForBeginner
npm install --save react-native-charts-wrapper


![qq 20170711144329](https://user-images.githubusercontent.com/21699430/28054517-b184f380-6647-11e7-8bc8-5cb528616af3.png)

**Comment by wuxudong** [comment]
In package.json, there are some relative devDependencies:

```
"devDependencies": {
    "babel-jest": "21.0.2",
    "babel-preset-react-native": "4.0.0",
    "jest": "21.1.0",
    "react-test-renderer": "15.6.1"
  }

```

it may conflict with yours. and npm pick the newest ones.(4.0.0 vs 1.9.2)

you can update my package.json or upgrade to latest react-native
