### ISSUE TITLE
Hello Everyone, I can`t add "MPAndroidChart" to my Android Studio My version of Android Studio: 7.0.2

### ISSUE THREAD

**Issue by HoangPhuc3112** [wuxudong/react-native-charts-wrapper#832]
Hello Everyone, I can`t add "MPAndroidChart" to my Android Studio
My version of Android Studio: 7.0.2
![image](https://user-images.githubusercontent.com/90994888/134849877-d0c67aba-b44b-45c9-a54a-d7eca0c3ec0c.png)
![image](https://user-images.githubusercontent.com/90994888/134849901-9e873ca5-eb41-4e0c-aec5-1f95b1aa4e35.png)
![image](https://user-images.githubusercontent.com/90994888/134849942-a4c8dcae-dcd4-4b80-96d9-0e783dfeb3c5.png)
![image](https://user-images.githubusercontent.com/90994888/134849951-ea6c3ad7-c45c-4eab-bc63-2f01a01a0787.png)

**Comment by wuxudong** [comment]
Try v0.5.8. Reopen it if problem remains.
