### ISSUE TITLE
How to remove bar text value from Barchat ?

### ISSUE THREAD

**Issue by atologistdipak** [wuxudong/react-native-charts-wrapper#839]
**Do read files under `lib/*` before reporting issues, you can find all the config there, all of them are straightforward.**

### How to remove text value above bar ?
![Simulator Screen Shot - iPhone 11 - 2021-11-24 at 10 46 11](https://user-images.githubusercontent.com/71266588/143179719-6263a5a8-ff65-46d2-bd42-596c2c200d66.png)

**Comment by nijarv** [comment]
barData = {
                    dataSets: [{
                        values: barData Values,
                        label: '',
                        config: {
                            drawValues: false,
                        }
                    }]
                }
