### ISSUE TITLE
Add library dependencies to Maven repository since jCenter is shutting down

### ISSUE THREAD

**Issue by SuhilMohammad-rogers** [wuxudong/react-native-charts-wrapper#845]
Please add the library to Maven repository as jCenter is completely shutting down on february 1st 2022

https://developer.android.com/studio/build/jcenter-migration
https://jeroenmols.com/blog/2021/03/24/migrate-artifacts-mavencentral/

**Comment by SparkleFaerieCoder** [comment]
We are currently unable to release a build on Android using this dependency. Our build pipeline is failing, with an error we're assuming related to this issue. Are there any plans to migrate away from jCenter?

```[stderr] FAILURE: Build failed with an exception.
[stderr] * Where:
[stderr] Initialization script '/root/.gradle/init.gradle' line: 36
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':react-native-charts-wrapper'.
[stderr] > Could not get unknown property 'url' for object of type org.gradle.api.internal.artifacts.repositories.DefaultFlatDirArtifactRepository.```

**Comment by SuhilMohammad-rogers** [comment]
these are some changes i had to do to migrate from jCenter to Maven central i hope it will be of use to you

![image](https://user-images.githubusercontent.com/60407566/151606884-94372bb2-2231-41b0-b7e1-30fd8cec1133.png)

**Comment by SparkleFaerieCoder** [comment]
@SuhilMohammad-rogers We attempted to remove the jcenter dependency, unfortunately, this didn't resolve our issue. I had a question regarding Flipper and fresco, why would these need to change?

**Comment by SuhilMohammad-rogers** [comment]
@SparkleFaerieCoder when i migrated to mavenCentral i found out that flipper version needs to be updated to latest version and fresco also needs to be updated if you use fresco for gif file animation. If you dont have fresco setup in your project then you dont need to worry about that part

**Comment by SparkleFaerieCoder** [comment]
Thanks for the clarification. I'll give it a shot. I appreciate the suggestion 👍

**Comment by jdponomarev** [comment]
hey @SparkleFaerieCoder did you manage to fix it? I'm facing the same issue

**Comment by SparkleFaerieCoder** [comment]
@jdponomarev Sorry! I wasn't able to. We decided to move away from this library since there doesn't seem to be any support/not actively maintained.

**Comment by wuxudong** [comment]
move to expo.
