### ISSUE TITLE
Is possible to give y axis a custom color?

### ISSUE THREAD

**Issue by TheNemus** [wuxudong/react-native-charts-wrapper#850]
I'm using a line-chart with two values series, and I'd like to give users a visual reference about what axis refers to what line.

I tried with the yAxis props but it didn't work (as the 'drawGridBackground') :

```
<LineChart style={styles.chart}
        drawGridBackground={false}
        yAxis={{ 
          left: {
            zeroLine: {enabled: true, lineColor: processColor('green')}
          }}}
        data={{
          dataSets: [{....}]
        }}
      />

```
Am I missing something?

I thought it would be usefull to give each axis the same color of the line that relates to, but I didn't find anything in docs.
 Is this possible?

**Comment by TheNemus** [comment]
found soluton by myself

**Comment by lucasvieceli** [comment]
e qual é
