### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNPieChart" was not found in the UIManager.

### ISSUE THREAD

**Issue by shivika24** [wuxudong/react-native-charts-wrapper#851]
Invariant Violation: requireNativeComponent: "RNPieChart" was not found in the UIManager.

**Comment by kavitha57** [comment]
same here

**Comment by redrose2** [comment]
@shivika24 @kavitha57 please add below line in Podfile
```pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'```

**Comment by wuxudong** [comment]
new version has been updated. Expo and auto link are supported.

**Comment by YoelEigner** [comment]
still having this issue with latest updated :(
