### ISSUE TITLE
Can I set valueLinePart1Length dynamicly for each value?

### ISSUE THREAD

**Issue by zoomerland** [wuxudong/react-native-charts-wrapper#855]
I have same problem as there [link](https://github.com/PhilJay/MPAndroidChart/issues/4776)
But I cant do the same in code beacuse cant find renderer class call.
Mabe I can dynamicly change valueLinePart1Length by value of current slice?

**Comment by wuxudong** [comment]
It is not supported right now.
Pr is welcome.
