### ISSUE TITLE
iOS Chart import issue in CI

### ISSUE THREAD

**Issue by ramki1979** [wuxudong/react-native-charts-wrapper#86]
```
/Users/****/Workspace/ReactNative/ProjectName/node_modules/react-native-charts-wrapper/ios/ReactNativeCharts/scatter/RNScatterChartView.swift:5:8: no such module 'Charts'

import Charts
```

On my system everything is working but getting issue on Bitrise CI. Ran to the same issue using Bitrise CLI tools on my system as well.

I added the Chart & SwiftJSON to my project as Subprojects.
I added these frameworks to Embedded as well as Link Frameworks & Libraries

**Comment by gelove** [comment]
+1

**Comment by rghorbani** [comment]
@ramki1979 When adding libraries make sure not to add them by reference
<img width="321" alt="screen shot 2017-12-12 at 3 17 57 pm" src="https://user-images.githubusercontent.com/5933939/33883121-d290d234-df4f-11e7-8c52-278fef7cf170.png">

**Comment by rghorbani** [comment]
@ramki1979 That's the beauty of Pods, You don't need to worry about these.
