### ISSUE TITLE
Linechart select a column instead of a point

### ISSUE THREAD

**Issue by renanpupin** [wuxudong/react-native-charts-wrapper#87]
It is possible to select the column and show info in a marker instead of selecting a point in line chart?

Example:
http://www.chartjs.org/samples/latest/charts/line/basic.html

**Comment by wuxudong** [comment]
It is not supported by default.
As a workaround, you can manually edit your marker property.

```
{x: 1, y: 11000, marker: "first data 11000 \nsecond data 12000"},

```
