### ISSUE TITLE
react-native-charts-wrapper有没有相关属性设置的文档？

### ISSUE THREAD

**Issue by yhyfms** [wuxudong/react-native-charts-wrapper#88]
BarChartScreen(条形图)
1.x轴每一个label长度过长时，能否倾斜放置，能否放置在条形图的下方；
2.y轴的每一个条形图能否自定义宽度，上方显示的value的数据格式是什么样的，如何设置；
3.y轴的label能否只显示一侧；
4.‘Description Label’字样能否去掉；

希望看到后能及时解决，拜托，谢谢！

**Comment by MayMayYang** [comment]
可以参考下：
`let option = {
      legend: {
        enabled: true,
        textSize: 14,
        form: 'SQUARE',
        formSize: 14,
        xEntrySpace: 10,
        yEntrySpace: 5,
        formToTextSpace: 5,
        wordWrapEnabled: true,
        maxSizePercent: 0.5
      },
      data: {
        dataSets: [{
          values: data,
          label: '各状态的合同个数',
          config: {
            color: processColor('teal'), //柱子默认显示颜色
            highlightEnabled: true, //柱子是否可点击
            valueTextSize: 12, //柱子上的文字大小
            valueTextColor: processColor('red'), //柱子上的文字颜色
            visible: true, //是否显示柱子
            valueFormatter: 'largeValue'
          }
        }],
        config: {
          barWidth: 0.5, //柱子宽度，不设置则按照宽度及柱子个数平分
        }
      },
      xAxis: {
        valueFormatter: ['待生产', '生产中', '生产完成'],
        granularityEnabled: true,
        granularity : 1, //x轴点绘制的粒度
        // axisMinimum: 0, //从第axisMinimum个柱子开始绘制
      },
      yAxis: {
        left: {
          drawLabels: true, //是否绘制左y轴数值
          drawAxisLine: true,
          drawGridLines: false,
          zeroLine: {
            enabled: true,
            lineWidth: 2
          },
          granularity: 1 //左y轴步进值
        },
        right: {
          enabled: true, //是否绘制右y轴数值
          granularity: 1 //右y轴步进值
        }
      }
    }
<BarChart
              style={styles.chart}
              data={option.data}
              xAxis={option.xAxis}
              yAxis={option.yAxis}
              animation={{durationX: 1000}}
              legend={option.legend}
              onSelect={this.handleSelect.bind(this)}
              chartDescription={{
                text: '',
                textColor: processColor('#999'),
                textSize: 12,
                fontFamily: '微软雅黑'
              }}
              marker={{
                enabled: false,
                markerColor: processColor('red'),
                textColor: processColor('green'),
                textSize: 14
              }}
              drawValueAboveBar={true} /*是否绘制柱子y值*/
              drawBarShadow={false} /*是否绘制每根柱子剩余部分*/

              drawGridBackground={false}/*是否绘制柱子背景*/
              gridBackgroundColor={processColor('white')}/*柱子背景色*/

              drawBorders={false}/*图的四边线*/
              borderColor={processColor('#ccc')}/*图的四边线颜色*/
              borderWidth={1}/*图的四边线宽度*/
              chartBackgroundColor={processColor('white')} /*整图的背景色*/
            />`

**Comment by yhyfms** [comment]
非常感谢，@MayMayYang

**Comment by nemom0901** [comment]
＠MayMayYang 
您好
我使用的是line chart
我嘗試套用過您y軸相關屬性 卻得到這個錯誤訊息:undefined is not an object
希望您看到 能教我如何解決？謝謝

另外 請問有沒有相關屬性設置文檔？

**Comment by MayMayYang** [comment]
@nemom0901 
我也没找到相关属性设置文档，用的webstorm，在组件引用地方直接链接查看对应源码
比如第一层：
`{
  name: 'LineChart',
  propTypes: {
    ...BarLineChartBase.propTypes,

    data: lineData,
  }
}`
再链接往下查看扩展属性和data

**Comment by rodrigoxavier** [comment]
You can also take a look in issue #57 .
The documentation is wrong, it say to use a prop inside the "LineChart" for example like this:
`description={{text: 'Dados de Glicemia'}}`

but the right way is:
`chartDescription={{text: 'Dados de Glicemia'}}`

and will change the description like in the image below.
![screen shot 2017-09-27 at 09 34 04](https://user-images.githubusercontent.com/7830920/30913567-0d629c14-a367-11e7-9290-e2c29a69c7de.png)

**Comment by wuxudong** [comment]
Thank for your remind, I have already fixed chartDescription in examples.

**Comment by ericklarac** [comment]
How can I change the description label value on the bar example?

**Comment by ericklarac** [comment]
Ok the solution is to put it like this:

chartDescription={{text: "iWA 2017"}}

**Comment by Lloyd1229** [comment]
当CandleStickChart里面的数据只有少量的时候，怎么设置宽度

**Comment by Lloyd1229** [comment]
How to set the width when there is only a small amount of data in CandleStickChart

**Comment by lijie0214** [comment]
How to set the width  in barChart

**Comment by littlelake** [comment]
https://github.com/wuxudong/react-native-charts-wrapper/blob/master/docs.md
