### ISSUE TITLE
Library doesnt work on expo

### ISSUE THREAD

**Issue by bassamseif** [wuxudong/react-native-charts-wrapper#889]
### Expected Behavior

Using expo, the [example](https://github.com/wuxudong/react-native-charts-wrapper#update-appjs) from readme should initialize correclty

### Actual Behavior

The [example](https://github.com/wuxudong/react-native-charts-wrapper#update-appjs) from readme outputs the error

> "RNLineChart" was not found in the UIManager

### Steps to Reproduce the Problem

Following the [guide](https://github.com/wuxudong/react-native-charts-wrapper#expo) in readme 

> ### expo
> 1. expo init demo
> 2. cd demo
> 3. expo install react-native-charts-wrapper
> 4. eas build 

Change App.js according to the [example from readme](https://github.com/wuxudong/react-native-charts-wrapper#update-appjs)

**Comment by AslamHamdi** [comment]
I'm facing the same problem.  It says "RNLineChart was not found in UI manager".

**Comment by cairoramos7** [comment]
I'm having a similar problem here too

![IMG_285E35855016-1](https://user-images.githubusercontent.com/15651234/192046349-f7af198c-3d94-43f4-9939-c8722087f924.jpeg)

**Comment by wuxudong** [comment]
Try V0.5.10, it works on my iOS simulator by following expo steps in README.

**Comment by hexadecy** [comment]
To reproduce the issue use the Expo Go app for iOS.
```
expo start
Open the app on Expo Go
```

What is working:
```
> yarn global add eas-cli
> eas build -p ios --profile development
login to your expo.dev account
wait in queue for the app to be built
download application-xxx.tar.gz
extract the .tar.gz
drag application to ios simulator
```

**Comment by R-Art-project** [comment]
I have the same problem.

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-25 at 17 50 31](https://user-images.githubusercontent.com/66227758/221384853-1141ead2-b4ca-40ae-80ca-a97126e4dfba.png)
