### ISSUE TITLE
  "position" property issue in LineChart:  xAxis and yAxis works fine in IOS but in Android it throws error :"error while updating property of xAxis"

### ISSUE THREAD

**Issue by abdulkhaliquem9** [wuxudong/react-native-charts-wrapper#89]
here in this code, if I comment "position"  property graph renders without displaying any line in LineChart inAndroid but when i uncomment "position" it throws error.
Note: the "position" property works fine IOS
  xAxis: {  
        drawGridLines: false,
        axisMinimum: 0,
        axisMaximum: (xAxisCount - 1),
        labelCount: xAxisCount,
        valueFormatter: xAxisFormatter,
        labelCountForce: xAxisCount == 7,
        //position: 'bottom',
        centerAxisLabels: false
      },

**Comment by kyle-ssg** [comment]
@abdulkhaliquem9 Can you please write a comment on how you resolved this rather than just closing the issue?

**Comment by abdulkhaliquem9** [comment]
Currently, I changed the to position: 'BOTH_SIDED', the graph is working properly. I think the issue is with case sensitivity; if I am not wrong.

**Comment by kyle-ssg** [comment]
That makes sense, looks like any invalid property names throw up this issue.
