### ISSUE TITLE
Not able to compile code on Xcode 14

### ISSUE THREAD

**Issue by piashcse** [wuxudong/react-native-charts-wrapper#894]
**Please update iOS Charts into 4.1.0**

### Expected Behavior
iOS build should be success full 

### Actual Behavior
`/ MARK: RangeReplaceableCollection
extension ChartDataSet: RangeReplaceableCollection {
    public func append(_ newElement: Element) {
        calcMinMax(entry: newElement)
        entries.append(newElement)
    }`
### Screenshots

<img width="820" alt="Screen Shot 2022-09-16 at 5 09 49 PM" src="https://user-images.githubusercontent.com/13556834/190629223-208e38aa-cdb3-4728-988f-e932c31c2125.png">

### Specifications

  - Version:0.5.9
  - Platform: iOS

**Comment by shahnewaz469** [comment]
Updating Charts to 4.1.0 will rise multiple issues. Because this library is not compatible with Chart v4. It's compatible with v3.

**Comment by Liqiankun** [comment]
Same issue.

**Comment by simrab** [comment]
same issue

**Comment by abdulrafeh857** [comment]
same issue

**Comment by mcarlos137** [comment]
same issue

**Comment by FarmerBZH** [comment]
Same issue.

**Comment by macasfaj** [comment]
This PR fixes the issue 100%

https://github.com/wuxudong/react-native-charts-wrapper/pull/892

**Comment by FarmerBZH** [comment]
> This PR fixes the issue 100%
> 
> #892

Thanks !

**Comment by phamhieu1412** [comment]
> This PR fixes the issue 100%
> 
> #892

not ok please merge soon as for package

**Comment by Blackoverlord24** [comment]
If anyone can't wait for a package, you can make a workaround.
1. Download repo as zip for example.
2. Instal deprecated-react-native-prop-types package (I don't know why this package is needed, but this lib depends on it)
3. Find react-native-charts-wrapper in your node_modules.
4. Remove all data in this folder and replace from downloaded arch.
5. In your Podfile  change pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper' on pod 'react-native-charts-wrapper', :path => '../node_modules/react-native-charts-wrapper'
6. Also change platform :ios version on 13 in the same file.
7. Run pod install and build app.

maybe it's not the best solution but if you have to update the app asap (as I do) you can use this quick fix

**Comment by wuxudong** [comment]
Try v0.5.10, Thx.
