### ISSUE TITLE
Percentage not show in iOS with Xcode14

### ISSUE THREAD

**Issue by Girum** [wuxudong/react-native-charts-wrapper#898]
Hi! I using the PieChart in my app, and using the value formatter, I can show correctly. But after the update to fix the lib in XCode14, the valueFormatter does not work anymore. Did you know how to workaround this (I cant concat with data value, because the values is only float/number).

Image (iOS and Android):
![Screen Shot 2022-09-27 at 09 15 02](https://user-images.githubusercontent.com/1349300/192525316-1178e7d5-2aaf-4398-ba29-8b0766478e2a.png)

**Comment by eden-lecomte** [comment]
I'm also having this issue, the custom `valueFormatter` string is no longer working since updating the library to work in XCode 14. 

Previously the below `valueFormatter` string worked.
```
valueFormatter: "$#,###;-$#,###",
```

<img width="456" alt="Screen Shot 2022-10-05 at 9 28 14 AM" src="https://user-images.githubusercontent.com/16439726/193920076-b2fa9aaf-5d81-419c-9302-7e02c4b6b97c.png">

**Comment by wuxudong** [comment]
It is related to https://github.com/danielgindi/Charts/issues/4690 , still waiting for merging of the fix PR.

**Comment by ismilesky** [comment]
How to solve this problem

**Comment by wuxudong** [comment]
Check v0.5.11

**Comment by mMarcos208** [comment]
BarChart has error yeat.

**Comment by Josee20** [comment]
pieChart has error yet.

Does Anybody knows how to solve this problem?

**Comment by wuxudong** [comment]
@Josee20 Which version are you using?

**Comment by Josee20** [comment]
@wuxudong My XcoderVersion is 14.0.1 and Charts version is 4.1.0
my code is like this 

// 3. Set ChartData
        let pieChartData = PieChartData(dataSet: pieChartDataSet)
        let format = NumberFormatter()
        format.numberStyle = .percent
        format.maximumFractionDigits = 1
        format.multiplier = 1
        format.percentSymbol = "%"

        let formatter = DefaultValueFormatter(formatter: format)
        pieChartData.setValueFormatter(formatter)
        
        mainView.currentMonthSchedulePercentageChart.data = pieChartData
