### ISSUE TITLE
show timestamp values on x axis.

### ISSUE THREAD

**Issue by christopher-18** [wuxudong/react-native-charts-wrapper#908]
I am using LineCharts, and for same set of values of x axis, i don't want multiple values. 
<img width="325" alt="Screenshot 2022-10-25 at 12 51 39" src="https://user-images.githubusercontent.com/23613887/197709191-cfa8266c-4799-47b7-bc08-4edb749a73c9.png">
In this, for oct 10, should come only once. 
In one of the closed issues, i read, we can do so by converting the x axis value to unix timestamp. 
It worked but now i am unable to see labels on x axis. 
<img width="308" alt="Screenshot 2022-10-25 at 12 54 32" src="https://user-images.githubusercontent.com/23613887/197709772-857de02c-1b51-40f3-b0d1-08b1e680e3a0.png">

Following is the data set -> 
```
[{x: 1665187140, y: 78,},
{x: 1665359940, y: 80},
{x: 1665359940, y: 200},
{x: 1665532740, y: 120}
{x: 1666068420, y: 90}
{x: 1666246020, y: 78}]
```

Following is the configuration codesnippet - 

```
  const xAxisFormat = transformedReadingDataArray?.map((val: any) => {
    
      let date = moment.unix(val?.x);
    
      console.log(date.format('dddd, Do MMM YYYY, h:mm:ss A'));
      return date.format('MMM DD');
    });
    
  <LineChart
          xAxis={{
            granularityEnabled: true,
            granularity: 1,
            valueFormatter: xAxisFormat,
            valueFormatterPattern: 'dd MMM',
            // since: 0,
            timeUnit: 'DAYS',
            axisLineWidth: 0,
            textColor: processColor(colors.Grey3),
            textSize: 10,
          }}
data={data}
/>
```

Any help would be appreciated.

**Comment by christopher-18** [comment]
Got it working by converting to the milisec. 
DataSet would look like - 
```
[{x: 1665187140*1000, y: 78,},
{x: 1665359940*1000, y: 80},
{x: 1665359940*1000, y: 200},
{x: 1665532740*1000, y: 120}
{x: 1666068420*1000, y: 90}
{x: 1666246020*1000, y: 78}]
```
and 
```
<LineChart
          xAxis={{
            granularityEnabled: true,
            granularity: 1,
            valueFormatter: 'date',
            valueFormatterPattern: 'dd MMM',
            timeUnit: 'DAYS',
            axisLineWidth: 0,
            textColor: processColor(colors.Grey3),
            textSize: 10,
          }}
data={data}
/>
```

**Comment by DusanSpasojevic98** [comment]
@christopher-18 how did you manage to get different dots colors?
