### ISSUE TITLE
Minimum ios support 12?

### ISSUE THREAD

**Issue by HyopeR** [wuxudong/react-native-charts-wrapper#914]
### Question
After updating the package, in the project with platform ios: 11, **pod install gives the following error.**
But pod install succeeds when set to ios:12.
Does the package now support ios:12 as a minimum?

**Note:** I tried pod install --repo-update. Doesn't work for ios:11.

### Output
```
Specs satisfying the `react-native-charts-wrapper (from `../node_modules/react-native-charts-wrapper`)` 
dependency were found, but they required a higher minimum deployment target.
```

### Specifications

  - Version: 0.5.11
  - Platform: iOS (xcode: Sürüm 13.3.1 (13E500a)

**Comment by wuxudong** [comment]
The latest Charts require iOS 12 as a minimum. Check https://github.com/danielgindi/Charts.
