### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by ignindra** [wuxudong/react-native-charts-wrapper#92]
I'm currently trying to add react-native-charts-wrapper into my android program after following all the steps in the readme. But every single time I run `react-native run-android` command, this happened:

>:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:8: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:16: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:35: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:18: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
C:\sms-mobile-rn\android\app\src\main\java\com\smsmobile\MainApplication.java:34: error: method does not override or implement a method from a supertype
  @Override
  ^
8 errors
:app:compileDebugJavaWithJavac FAILED

>FAILURE: Build failed with an exception.

>* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

>* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

>BUILD FAILED

I'm using:
react-native: 0.45.1
react-native-charts-wrapper: 0.2.10
android build tools: 23.0.1
running on android emulator: Nougat 7.1.1

I already tried to clean the last build using `gradlew clean`, but those errors was still there.
I noticed that those "cannot find symbol" errors started appearing after I added this:
[Adding Maven dependency](https://github.com/wuxudong/react-native-charts-wrapper#2-add-maven-dependency)
Anyone has any idea why this happened?

Thanks

**Comment by felipemartim** [comment]
I had a similar issue, until I realized I was adding the maven repository the wrong way. I was doing this:

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            url "https://jitpack.io"
        }
    }
}
```
when I had to do this:
```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }    // used for MPAndroidChart
    }
}
```

**Comment by ignindra** [comment]
@felipemartim Ah sorry, I haven't logged-in to github for a while. Thanks for your answer, but it still produces the same error.

**Comment by wuxudong** [comment]
I suggest run example first. then compare your project with it.

Close the issue. Please reopen it if you have any question.

**Comment by rjuevesano** [comment]
i have similar issues also.

![image](https://user-images.githubusercontent.com/4033035/60023219-f4ba0200-96c7-11e9-92ff-6439bb60b210.png)

**Comment by gshoanganh** [comment]
I have the same issue.
