### ISSUE TITLE
how to draw line chart on duplicate values ?

### ISSUE THREAD

**Issue by Ranjit8298** [wuxudong/react-native-charts-wrapper#946]
how to draw a line chart on duplicate values ?
please help @all

**Comment by wuxudong** [comment]
@Ranjit8298  This may help.
https://stackoverflow.com/questions/40532564/mpandroidchart-creating-a-closed-chart-circular-line-chart

**Comment by Ranjit8298** [comment]
Thanks Wuxudong/React-Native-Charts-Wrapper

**Comment by Ranjit8298** [comment]
Okay, Thanks
