### ISSUE TITLE
Line Chart is not Showing.

### ISSUE THREAD

**Issue by Ranjit8298** [wuxudong/react-native-charts-wrapper#947]
Hii @wuxudong and @all,
Please help, when we have 1000 data sets the line Chart is not Showing. How can I resolve this issue?
something like that:
[
  {
    "marker": "(-500.0,.00)",
    "x": -500,
    "y": 0
  },
  {
    "marker": "(-497.5,.00)",
    "x": -497.5,
    "y": 0
  },
  {
    "marker": "(-495.0,.00)",
    "x": -495,
    "y": 0
  },
  {
    "marker": "(-492.5,.00)",
    "x": -492.5,
    "y": 0
  },
  {
    "marker": "(-490.0,.00)",
    "x": -490,
    "y": 0
  },
  {
    "marker": "(-487.5,.00)",
    "x": -487.5,
    "y": 0
  },.............................................................1000 data set ]

My Code is : 
<LineChart
              style={{height: 400}}
              chartDescription={{text: ''}}
              legend={{
                enabled: true,
              }}
              marker={{
                enabled: true,
                markerColor: processColor('gray'),
                textColor: processColor('white'),
                digits: 3,
              }}
              drawGridBackground={false}
              drawBorders={true}
              borderWidth={0.5}
              touchEnabled={true}
              dragEnabled={true}
              scaleEnabled={true}
              scaleXEnabled={true}
              scaleYEnabled={false}
              pinchZoom={true}
              doubleTapToZoomEnabled={true}
              dragDecelerationEnabled={true}
              dragDecelerationFrictionCoef={0.99}
              keepPositionOnRotation={true}
              autoScaleMinMaxEnabled={true}
              xAxis={{position: 'BOTTOM'}}
              yAxis={{
                right: {enabled: false},
                left: {
                  enabled: true,
                  axisMaximum: 20,
                  axisMinimum: -30,
                  // position: 'INSIDE_CHART',
                  // valueFormatter: ['-30', '-20', '-10', '0', '10', '20'],
                },
              }}
              data={{
                dataSets: [
                  {
                    label: 'Series 1',
                    config: {
                      color: processColor('red'),
                      circleColor: processColor('red'),
                      drawCircles: true,
                      mode: 'CUBIC_BEZIER',
                      drawCircleHole: false,
                      drawValues: false,
                      circleRadius: 5,
                    },
                    values: [
                      {
                        marker: '(-500.0,.00)',
                        x: -500,
                        y: 0,
                      },
                      {
                        marker: '(-497.5,.00)',
                        x: -497.5,
                        y: 0,
                      },
                      {
                        marker: '(-495.0,.00)',
                        x: -495,
                        y: 0,
                      },
                      {
                        marker: '(-492.5,.00)',
                        x: -492.5,
                        y: 0,
                      },
                      {
                        marker: '(-490.0,.00)',
                        x: -490,
                        y: 0,
                      },
                      {
                        marker: '(-487.5,.00)',
                        x: -487.5,
                        y: 0,
                      },
                      {
                        marker: '(-485.0,.00)',
                        x: -485,
                        y: 0,
                      },
                      {
                        marker: '(-500.0,.00)',
                        x: -500,
                        y: 0,
                      },
                      {
                        marker: '(-497.5,.00)',
                        x: -497.5,
                        y: 0,
                      },
                      {
                        marker: '(-495.0,.00)',
                        x: -495,
                        y: 0,
                      },
                      {
                        marker: '(-492.5,.00)',
                        x: -492.5,
                        y: 0,
                      },
                      {
                        marker: '(-490.0,.00)',
                        x: -490,
                        y: 0,
                      },
                      {
                        marker: '(-487.5,.00)',
                        x: -487.5,
                        y: 0,
                      },
                      {
                        marker: '(-485.0,.00)',
                        x: -485,
                        y: 0,
                      },
                    ],
                  },
                ],
              }}
            />

Thanks

**Comment by 2001vishnu** [comment]
how solved?
