### ISSUE TITLE
Animation won't work on data update

### ISSUE THREAD

**Issue by Kroderia** [wuxudong/react-native-charts-wrapper#95]
The animation works fine the first time data was initialized.
However, if I update the data by `this.setState()`, the chart was updated, but the animation won't work.

**Comment by alexaung** [comment]
I also facing this issue. Temporary solution is that change the key of component.

**Comment by kssujithcj** [comment]
Hi @alexaung,
I am also facing the same issue.
Can you elaborate, your temporary solution?

**Comment by guy-a** [comment]
@kssujithcj Set the key like that
<Chart key={this.state.key} ...

When you update the data, update the key as well
this.setState({key: Math.random()})

This is indeed not perfect but it'll give you some animation.

**Comment by wuxudong** [comment]
In MpAndroidChart, whenever you want to play animation, you should call chart.animateXY/X/Y.
But in RNCW, it is only called once when you set `animation={...}`.

As a workaround, you can change view key as @guy-a did, or just change animation property a little bit.


For example, introduce a useless variable in animation.


```

    this.interval = setInterval(() => {
      if (this.state.values.length >= 60) {
        // https://github.com/PhilJay/MPAndroidChart/issues/2450
        // MpAndroidChart 3.0.2 will crash when data entry list is empty.

        this.setState({values: [0], colorIndex: 0, key: Math.random()});
      } else {
        this.setState({
          values: this.state.values.concat([Math.floor((Math.random() * 100) + 1)]),
          colorIndex: (this.state.colorIndex + 1) % colors.length,
          key: Math.random(),
          animation:{
            durationX: 1500,
            durationY: 1500,
            easingX: 'EaseInCirc',
            random: Math.random()
          }
        });
      }
    }, 2000)
```

```
<LineChart data={config.data} xAxis={config.xAxis} style={styles.container} animation={this.state.animation}/>```
