### ISSUE TITLE
Charts -> DGCharts in 5.0

### ISSUE THREAD

**Issue by mateogianolio** [wuxudong/react-native-charts-wrapper#955]
Hey! Opening this issue just to notify the maintainer.

Charts 5.0 has switched name to DGCharts to prevent conflicts with SwiftUI Charts.

https://github.com/danielgindi/Charts/releases/tag/5.0.0

**Comment by wuxudong** [comment]
Thanks for reminding.

**Comment by longuyen10119** [comment]
it seems simple enough of a fix documented in the link above To fix your projects simply replace ```import Charts``` with import DGCharts

**Comment by hexadecy** [comment]
@longuyen10119 you have to fork `react-native-charts-wrapper` for that.

**Comment by thehale** [comment]
Looks like this was completed in [version 0.6.0](https://github.com/wuxudaong/react-native-charts-wrapper/releases/tag/v0.6.0).
