### ISSUE TITLE
Wrong to convert Swift syntax 

### ISSUE THREAD

**Issue by zhuozp** [wuxudong/react-native-charts-wrapper#99]
Xcode version is 8.3.3, I try it just like your doc. said，But in my workspace, I don't find this: Settings -> Swift Compiler - Version -> User Legacy Swift Language Version, and then I try converting but failed. Hope for your answer. THX!

**Comment by uinz** [comment]
update `Charts` to 3.0.3

```ruby
# Podfile

platform :ios, '9.0'
use_frameworks!

target 'jiucaibang' do
  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', :tag => 'v3.0.3', :git => 'https://github.com/danielgindi/Charts.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
```

**Comment by wuxudong** [comment]
Xcode is 9.x at this moment. Just update it.
In latest examples, Charts is updated to 3.0.3.
